#!/bin/bash
# validate-doc.sh — PostToolUse (Write/Edit)
# 문서 경로 + frontmatter 검증
# Generated by Foreman

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty' 2>/dev/null)

# 절대 경로를 상대 경로로 변환
PROJECT_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
if [[ "$FILE_PATH" == "$PROJECT_ROOT"/* ]]; then
  FILE_PATH="${FILE_PATH#$PROJECT_ROOT/}"
fi

# .md 파일이 docs/ 밖에 생성되면 차단
if [[ "$FILE_PATH" == *.md ]] && \
   [[ "$FILE_PATH" != docs/* ]] && \
   [[ "$FILE_PATH" != README.md ]] && \
   [[ "$FILE_PATH" != CHANGELOG.md ]] && \
   [[ "$FILE_PATH" != CLAUDE.md ]] && \
   [[ "$FILE_PATH" != GEMINI.md ]] && \
   [[ "$FILE_PATH" != AGENTS.md ]] && \
   [[ "$FILE_PATH" != CLAUDE.local.md ]] && \
   [[ "$FILE_PATH" != GEMINI.local.md ]] && \
   [[ "$FILE_PATH" != AGENTS.local.md ]]; then
  echo "ERROR: 문서는 docs/ 폴더에만 생성하세요. 경로: docs/{doc_type}/YYYY-MM-DD-{topic}.md" >&2
  echo "위반 경로: $FILE_PATH" >&2
  exit 2
fi

# docs/ 내 .md 파일이면 frontmatter 검증
if [[ "$FILE_PATH" == docs/*.md ]]; then
  CONTENT=$(echo "$INPUT" | jq -r '.tool_input.content // empty' 2>/dev/null)
  if [ -n "$CONTENT" ] && ! echo "$CONTENT" | head -1 | grep -q "^---"; then
    echo "ERROR: docs/ 내 문서에는 frontmatter가 필수입니다." >&2
    echo "필수 필드: epic_id, doc_type, status, title, date" >&2
    exit 2
  fi
fi

exit 0
