-- Generated by scripts/build_cn_non_tang_tranche1_jds_sql.mjs
-- Purpose: stage CN non-Tang tranche 1 into jds before Supabase hansi_curated_* sync.
-- Safety: poems are inserted only when the same poet slug + title_zh + body_zh is absent.
-- Default ending is ROLLBACK. Change the final ROLLBACK to COMMIT only after reviewing counts.

BEGIN;

WITH input_poets(slug, name_zh, name_ko, life_raw, era_period, country) AS (
  VALUES
    ('liu-bang', '劉邦', '유방', 'BCE 256~BCE 195', '兩漢', 'CN'),
    ('xiang-yu', '項羽', '항우', 'BCE 232~BCE 202', '兩漢', 'CN'),
    ('liu-che', '劉徹', '유철', 'BCE 156~BCE 87', '兩漢', 'CN'),
    ('anonymous-han-yuefu', '無名氏', '무명씨', NULL, '兩漢', 'CN'),
    ('anonymous-gushi-shijiu', '無名氏', '무명씨', NULL, '兩漢', 'CN'),
    ('cao-cao', '曹操', '조조', '155~220', '魏晉南北朝', 'CN'),
    ('cao-pi', '曹丕', '조비', '187~226', '魏晉南北朝', 'CN'),
    ('cao-zhi', '曹植', '조식', '192~232', '魏晉南北朝', 'CN'),
    ('tao-yuanming', '陶淵明', '도연명', '365~427', '魏晉南北朝', 'CN')
)
INSERT INTO poets (slug, name_zh, name_ko, life_raw, era_period, country, poem_count)
SELECT slug, name_zh, name_ko, life_raw, era_period, country, 0
FROM input_poets
ON CONFLICT (slug) DO UPDATE SET
  name_zh = EXCLUDED.name_zh,
  name_ko = EXCLUDED.name_ko,
  life_raw = EXCLUDED.life_raw,
  era_period = EXCLUDED.era_period,
  country = EXCLUDED.country;

WITH input_poems(poet_slug, poem_no, title_zh, title_ko, category, meter, body_zh, translation_ko, commentary_ko, is_notable, status, quality, country) AS (
  VALUES
    ('liu-bang', 1, '大風歌', '대풍가', NULL, NULL, '大風起兮雲飛揚
威加海內兮歸故鄉
安得猛士兮守四方', '큰 바람이 일어 구름이 날아오르니,
위엄은 천하에 더해지고 고향으로 돌아왔네.
어찌하면 용맹한 장사를 얻어
사방을 지키게 할 수 있을까.', '한 고조가 천하를 얻은 뒤에도 나라를 지킬 인재를 걱정한 제왕시다. 짧은 세 구 안에 승리의 호방함과 통치자의 불안이 함께 들어 있다.', TRUE, 'translated', 'cn-tranche1', 'CN'),
    ('xiang-yu', 2, '垓下歌', '해하가', NULL, 7, '力拔山兮氣蓋世
時不利兮騅不逝
騅不逝兮可奈何
虞兮虞兮奈若何', '힘은 산을 뽑고 기개는 세상을 덮었건만,
때가 이롭지 않아 추마도 나아가지 않는구나.
추마가 가지 않으니 어찌해야 하는가.
우희여, 우희여, 그대를 어찌해야 하는가.', '초한 전쟁의 패배 순간을 노래한 비가다. 영웅적 자기 인식과 운명의 좌절, 사랑하는 사람에 대한 절망이 한꺼번에 압축되어 있다.', TRUE, 'translated', 'cn-tranche1', 'CN'),
    ('liu-che', 3, '秋風辭', '추풍사', NULL, NULL, '秋風起兮白雲飛
草木黃落兮雁南歸
蘭有秀兮菊有芳
懷佳人兮不能忘
泛樓船兮濟汾河
橫中流兮揚素波
簫鼓鳴兮發棹歌
歡樂極兮哀情多
少壯幾時兮奈老何', '가을바람 일고 흰 구름 날며,
풀과 나무 누렇게 지고 기러기는 남쪽으로 돌아가네.
난초는 빼어나고 국화는 향기로우니,
아름다운 이를 그리워해 잊을 수 없구나.
누선을 띄워 분하를 건너고,
물 가운데를 가로질러 흰 물결을 일으키네.
피리와 북이 울리고 뱃노래가 일어나지만,
즐거움이 지극할수록 슬픈 정은 많아지네.
젊고 씩씩한 때가 얼마나 되랴, 늙음은 어찌하리.', '한 무제의 제왕적 유람시이면서 동시에 노쇠와 무상감을 노래한다. 화려한 행차 장면 뒤에 인생의 짧음이 강하게 드러난다.', TRUE, 'translated', 'cn-tranche1', 'CN'),
    ('anonymous-han-yuefu', 4, '上邪', '상야', NULL, NULL, '上邪
我欲與君相知
長命無絶衰
山無陵
江水為竭
冬雷震震
夏雨雪
天地合
乃敢與君絶', '하늘이여,
나는 그대와 서로 알고 지내
이 마음이 길이 쇠하지 않기를 바라네.
산에 봉우리가 없어지고,
강물이 다 마르고,
겨울에 우레가 울리고,
여름에 눈이 내리고,
하늘과 땅이 합쳐진 뒤에야
비로소 그대와 끊어지리라.', '한대 악부의 대표적인 사랑 노래다. 불가능한 자연 현상을 나열해 사랑의 단절 또한 불가능하다는 뜻을 강렬하게 드러낸다.', TRUE, 'translated', 'cn-tranche1', 'CN'),
    ('anonymous-gushi-shijiu', 5, '行行重行行', '행행중행행', '五言古詩', 5, '行行重行行
與君生別離
相去萬餘里
各在天一涯
道路阻且長
會面安可知
胡馬依北風
越鳥巢南枝
相去日已遠
衣帶日已緩
浮雲蔽白日
遊子不顧返
思君令人老
歲月忽已晚
棄捐勿復道
努力加餐飯', '가고 또 가니,
그대와 산 채로 이별하게 되었네.
서로 만여 리나 떨어져
각기 하늘 한 끝에 있구나.
길은 막히고 또 멀어
만날 날을 어찌 알 수 있으랴.
북방 말은 북풍을 따르고,
월나라 새는 남쪽 가지에 깃든다네.
서로 떨어진 날은 이미 오래고,
옷 띠는 날로 헐거워지네.
뜬구름이 밝은 해를 가리니,
떠난 이는 돌아볼 줄 모르는구나.
그대를 생각하니 사람은 늙어가고,
세월은 어느덧 저물었네.
버림받은 일은 다시 말하지 말고,
부디 힘써 밥을 더 드시게.', '오언 고시 서정의 원형으로 꼽히는 작품이다. 먼 이별, 몸의 쇠약, 돌아오지 않는 사람에 대한 원망이 절제된 구절 속에 이어진다.', TRUE, 'translated', 'cn-tranche1', 'CN'),
    ('anonymous-gushi-shijiu', 6, '迢迢牽牛星', '초초견우성', '五言古詩', 5, '迢迢牽牛星
皎皎河漢女
纖纖擢素手
札札弄機杼
終日不成章
泣涕零如雨
河漢清且淺
相去復幾許
盈盈一水間
脈脈不得語', '아득한 견우성,
맑고 밝은 은하의 여인.
가느다란 흰 손을 들어
찰찰 베틀을 움직이네.
종일 짜도 무늬 하나 이루지 못하고,
눈물은 비처럼 떨어진다.
은하는 맑고도 얕은데,
서로의 거리가 다시 얼마나 되랴.
가득 찬 한 줄기 물 사이에 두고,
말없이 바라볼 뿐 말하지 못하네.', '견우와 직녀의 설화를 빌려 이별의 거리를 노래한다. 물리적 거리는 얕지만 건널 수 없는 정서적 거리가 핵심이다.', TRUE, 'translated', 'cn-tranche1', 'CN'),
    ('cao-cao', 7, '短歌行', '단가행', NULL, NULL, '對酒當歌
人生幾何
譬如朝露
去日苦多
慨當以慷
憂思難忘
何以解憂
唯有杜康', '술을 마주하고 노래해야 하리,
인생이 그 얼마이던가.
비유하면 아침 이슬 같아,
지나간 날의 괴로움이 많구나.
탄식은 마땅히 씩씩해야 하나,
근심은 잊기 어렵다.
무엇으로 근심을 풀 것인가,
오직 두강의 술뿐이로다.', '건안 풍골의 대표작이다. 짧은 인생의 허무와 인재를 구하는 정치적 갈망이 한 작품 안에 결합되어 있다.', TRUE, 'translated', 'cn-tranche1', 'CN'),
    ('cao-cao', 8, '龜雖壽', '귀수수', NULL, NULL, '神龜雖壽
猶有竟時
騰蛇乘霧
終為土灰
老驥伏櫪
志在千里
烈士暮年
壯心不已', '신령한 거북이 오래 산다 해도
마침내 끝날 때가 있고,
등사는 안개를 타도
끝내 흙과 재가 된다.
늙은 준마가 마구간에 엎드려 있어도
뜻은 천 리에 있고,
열사는 늘그막에도
장한 마음이 그치지 않는다.', '노년의 한계를 인정하면서도 의지를 꺾지 않는 조조의 자기 선언이다. 후대에 노익장의 상징으로 널리 읽혔다.', TRUE, 'translated', 'cn-tranche1', 'CN'),
    ('cao-pi', 9, '燕歌行', '연가행', '七言古詩', 7, '秋風蕭瑟天氣涼
草木搖落露為霜
群燕辭歸鵠南翔
念君客遊思斷腸
慊慊思歸戀故鄉
君何淹留寄他方', '가을바람 쓸쓸하고 날씨는 서늘한데,
풀과 나무 흔들려 지고 이슬은 서리가 되었네.
제비 떼는 돌아가고 고니는 남쪽으로 나는데,
객지에 있는 그대를 생각하니 애가 끊어진다.
간절히 돌아가고 싶어 고향을 그리워하건만,
그대는 어찌 오래 머물러 타향에 기대 있는가.', '현존 초기 칠언시의 중요한 작품으로 평가된다. 계절의 변화와 이별의 정서를 촘촘하게 연결한다.', TRUE, 'translated', 'cn-tranche1', 'CN'),
    ('cao-zhi', 10, '七步詩', '칠보시', '五言古詩', 5, '煮豆燃豆萁
豆在釜中泣
本是同根生
相煎何太急', '콩을 삶으려 콩깍지를 태우니,
콩은 솥 안에서 우는구나.
본래 같은 뿌리에서 태어났는데,
서로 볶아댐이 어찌 이리 급한가.', '형제간 권력 다툼의 비극을 압축한 작품으로 전해진다. 사물 비유가 쉽고 강해 대중적 대표성이 높다.', TRUE, 'translated', 'cn-tranche1', 'CN'),
    ('tao-yuanming', 11, '歸園田居 其一', '귀원전거 1', '五言古詩', 5, '少無適俗韻
性本愛丘山
誤落塵網中
一去三十年
羈鳥戀舊林
池魚思故淵
開荒南野際
守拙歸園田', '젊어서부터 세속에 맞는 운치가 없었고,
성품은 본래 언덕과 산을 사랑했다.
잘못하여 티끌 그물 속에 떨어져,
한번 떠난 지 삼십 년이 되었네.
매인 새는 옛 숲을 그리워하고,
못 속의 물고기는 옛 못을 생각한다.
남쪽 들머리에 황무지를 열고,
졸박함을 지키며 전원으로 돌아가네.', '도연명 전원시의 선언 같은 작품이다. 관직 생활을 그물로 보고 자연으로 돌아가는 선택을 자기 본성의 회복으로 그린다.', TRUE, 'translated', 'cn-tranche1', 'CN'),
    ('tao-yuanming', 12, '飲酒 其五', '음주 5', '五言古詩', 5, '結廬在人境
而無車馬喧
問君何能爾
心遠地自偏
採菊東籬下
悠然見南山
山氣日夕佳
飛鳥相與還
此中有真意
欲辨已忘言', '사람 사는 곳에 초가를 얽었으나,
수레와 말의 시끄러움은 없네.
그대여 어찌 그럴 수 있느냐 묻는다면,
마음이 멀어지니 땅도 절로 외진다 하리.
동쪽 울타리 아래 국화를 따다가,
유연히 남산을 바라본다.
산 기운은 저녁 무렵 더욱 아름답고,
나는 새들도 서로 더불어 돌아오네.
이 가운데 참된 뜻이 있으나,
말하려 하니 이미 말을 잊었네.', '동아시아 전원시의 가장 유명한 장면 중 하나다. 은거는 장소가 아니라 마음의 거리에서 비롯된다는 사유가 담겨 있다.', TRUE, 'translated', 'cn-tranche1', 'CN')
)
INSERT INTO poems (
  poet_id, poem_no, title_zh, title_ko, category, meter, body_zh,
  translation_ko, commentary_ko, is_notable, status, quality, country
)
SELECT
  p.id, ip.poem_no, ip.title_zh, ip.title_ko, ip.category, ip.meter, ip.body_zh,
  ip.translation_ko, ip.commentary_ko, ip.is_notable, ip.status, ip.quality, ip.country
FROM input_poems ip
JOIN poets p ON p.slug = ip.poet_slug
WHERE NOT EXISTS (
  SELECT 1
  FROM poems existing
  WHERE existing.poet_id = p.id
    AND existing.title_zh = ip.title_zh
    AND existing.body_zh = ip.body_zh
);

UPDATE poets p
SET poem_count = sub.cnt
FROM (
  SELECT poet_id, count(*)::integer AS cnt
  FROM poems
  WHERE poet_id IN (SELECT id FROM poets WHERE slug IN ('liu-bang', 'xiang-yu', 'liu-che', 'anonymous-han-yuefu', 'anonymous-gushi-shijiu', 'cao-cao', 'cao-pi', 'cao-zhi', 'tao-yuanming'))
  GROUP BY poet_id
) sub
WHERE p.id = sub.poet_id;

-- Review counts before COMMIT when applying manually:
SELECT era_period, count(*) FROM poets WHERE slug IN ('liu-bang', 'xiang-yu', 'liu-che', 'anonymous-han-yuefu', 'anonymous-gushi-shijiu', 'cao-cao', 'cao-pi', 'cao-zhi', 'tao-yuanming') GROUP BY era_period ORDER BY era_period;
SELECT p.slug, count(pm.id) FROM poets p LEFT JOIN poems pm ON pm.poet_id = p.id WHERE p.slug IN ('liu-bang', 'xiang-yu', 'liu-che', 'anonymous-han-yuefu', 'anonymous-gushi-shijiu', 'cao-cao', 'cao-pi', 'cao-zhi', 'tao-yuanming') GROUP BY p.slug ORDER BY p.slug;

ROLLBACK;
-- COMMIT;
