-- Generated by scripts/build_cn_pre_tang_first_tranche_jds_sql.mjs
-- Purpose: stage CN pre-Tang first tranche into jds before Supabase hansi_curated_* sync.
-- Safety: poems are inserted only when the same poet slug + title_zh + body_zh is absent.
-- Default ending is ROLLBACK. Change the final ROLLBACK to COMMIT only after reviewing counts.

BEGIN;

WITH input_poets(slug, name_zh, name_ko, life_raw, era_period, country) AS (
  VALUES
    ('cn-pretang-4f5a-540d', '佚名', '佚名', NULL, '先秦', 'CN'),
    ('cn-pretang-7121-540d-6c0f-2f-6f22-6a02-5e9c', '無名氏/漢樂府', '無名氏/漢樂府', NULL, '兩漢', 'CN'),
    ('cn-pretang-5289-90a6', '劉邦', '劉邦', NULL, '兩漢', 'CN'),
    ('cn-pretang-6881-9d3b', '梁鴻', '梁鴻', NULL, '兩漢', 'CN'),
    ('cn-pretang-9805-7fbd', '項羽', '項羽', NULL, '兩漢', 'CN'),
    ('cn-pretang-5289-5fb9', '劉徹', '劉徹', NULL, '兩漢', 'CN'),
    ('cn-pretang-5b8b-5b50-4faf', '宋子侯', '宋子侯', NULL, '兩漢', 'CN'),
    ('cn-pretang-8f9b-5ef6-5e74', '辛延年', '辛延年', NULL, '兩漢', 'CN'),
    ('cn-pretang-8607-4f2f-7389-59bb', '蘇伯玉妻', '蘇伯玉妻', NULL, '兩漢', 'CN'),
    ('cn-pretang-5289-7d30-541b', '劉細君', '劉細君', NULL, '兩漢', 'CN'),
    ('cn-pretang-73ed-56fa', '班固', '班固', NULL, '兩漢', 'CN'),
    ('cn-pretang-71d5-523a-738b-65e6', '燕刺王旦', '燕刺王旦', NULL, '兩漢', 'CN')
)
INSERT INTO poets (slug, name_zh, name_ko, life_raw, era_period, country, poem_count)
SELECT slug, name_zh, name_ko, life_raw, era_period, country, 0
FROM input_poets
ON CONFLICT (slug) DO UPDATE SET
  name_zh = EXCLUDED.name_zh,
  name_ko = EXCLUDED.name_ko,
  life_raw = EXCLUDED.life_raw,
  era_period = EXCLUDED.era_period,
  country = EXCLUDED.country;

WITH input_poems(poet_slug, title_zh, title_ko, category, body_zh, translation_ko, commentary_ko, status, quality, country, source_record_id, source_url) AS (
  VALUES
    ('cn-pretang-4f5a-540d', '擊壤歌', NULL, NULL, '日出而作，日入而息；
鑿井而飲，耕田而食。
帝力於我何有哉！', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-PRE-QIN-64ca-58e4-6b4c-2d-4f5a-540d', 'https://zh.wikisource.org/wiki/%E5%8F%A4%E8%A9%A9%E6%BA%90'),
    ('cn-pretang-4f5a-540d', '康衢謠', NULL, NULL, '立我蒸民，莫匪爾極。
不識不知，順帝之則。', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-PRE-QIN-5eb7-8862-8b20-2d-4f5a-540d', 'https://zh.wikisource.org/wiki/%E5%8F%A4%E8%A9%A9%E6%BA%90'),
    ('cn-pretang-4f5a-540d', '伊耆氏蠟辭', NULL, NULL, '土反其宅，水歸其壑。
昆蟲毋作，草木歸其澤。', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-PRE-QIN-4f0a-8006-6c0f-881f-8fad-2d-4f5a-540d', 'https://zh.wikisource.org/wiki/%E5%8F%A4%E8%A9%A9%E6%BA%90'),
    ('cn-pretang-4f5a-540d', '堯戒', NULL, NULL, '戰戰慄慄，日謹一日。
人莫躓於山，而躓於垤。', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-PRE-QIN-582f-6212-2d-4f5a-540d', 'https://zh.wikisource.org/wiki/%E5%8F%A4%E8%A9%A9%E6%BA%90'),
    ('cn-pretang-4f5a-540d', '卿雲歌', NULL, NULL, '卿雲爛兮，糺縵縵兮。
日月光華，旦復旦兮。', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-PRE-QIN-537f-96f2-6b4c-2d-4f5a-540d', 'https://zh.wikisource.org/wiki/%E5%8F%A4%E8%A9%A9%E6%BA%90'),
    ('cn-pretang-4f5a-540d', '八伯歌', NULL, NULL, '明明上天，爛然星陳。
日月光華，弘於一人。', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-PRE-QIN-516b-4f2f-6b4c-2d-4f5a-540d', 'https://zh.wikisource.org/wiki/%E5%8F%A4%E8%A9%A9%E6%BA%90'),
    ('cn-pretang-4f5a-540d', '帝載歌', NULL, NULL, '日月有常，星辰有行。
四時從經，萬姓允誠。
於予論樂，配天之靈。
遷於賢善，莫不咸聽。
鼚乎鼓之，軒乎舞之。
菁華已竭，褰裳去之。', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-PRE-QIN-5e1d-8f09-6b4c-2d-4f5a-540d', 'https://zh.wikisource.org/wiki/%E5%8F%A4%E8%A9%A9%E6%BA%90'),
    ('cn-pretang-4f5a-540d', '南風歌', NULL, NULL, '南風之熏兮，可以解吾民之慍兮！
南風之時兮，可以阜吾民之財兮！', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-PRE-QIN-5357-98a8-6b4c-2d-4f5a-540d', 'https://zh.wikisource.org/wiki/%E5%8F%A4%E8%A9%A9%E6%BA%90'),
    ('cn-pretang-4f5a-540d', '禹玉牒辭', NULL, '七言聯句', '祝融司方發其英，
沐日浴月百寶生。', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-PRE-QIN-79b9-7389-7252-8fad-2d-4f5a-540d', 'https://zh.wikisource.org/wiki/%E5%8F%A4%E8%A9%A9%E6%BA%90'),
    ('cn-pretang-4f5a-540d', '夏後鑄鼎繇', NULL, NULL, '逢逢白雲，一南一北，一西一東。
九鼎既成，遷於三國。', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-PRE-QIN-590f-5f8c-9444-9f0e-7e47-2d-4f5a-540d', 'https://zh.wikisource.org/wiki/%E5%8F%A4%E8%A9%A9%E6%BA%90'),
    ('cn-pretang-4f5a-540d', '商銘', NULL, NULL, '嗛嗛之德，不足就也，不可以矜，而祗取憂也。
嗛嗛之食，不足狃也，不能為膏，而祗離咎也。', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-PRE-QIN-5546-9298-2d-4f5a-540d', 'https://zh.wikisource.org/wiki/%E5%8F%A4%E8%A9%A9%E6%BA%90'),
    ('cn-pretang-4f5a-540d', '麥秀歌', NULL, NULL, '麥秀漸漸兮，禾黍油油，
彼狡童兮，不與我好兮。', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-PRE-QIN-9ea5-79c0-6b4c-2d-4f5a-540d', 'https://zh.wikisource.org/wiki/%E5%8F%A4%E8%A9%A9%E6%BA%90'),
    ('cn-pretang-4f5a-540d', '采薇歌', NULL, NULL, '登彼西山兮，采其薇矣。
以暴易暴兮，不知其非矣。
神農虞夏，忽焉沒兮，吾適安歸矣？
籲嗟徂兮，命之衰矣。', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-PRE-QIN-91c7-8587-6b4c-2d-4f5a-540d', 'https://zh.wikisource.org/wiki/%E5%8F%A4%E8%A9%A9%E6%BA%90'),
    ('cn-pretang-4f5a-540d', '盥盤銘', NULL, NULL, '與其溺於人也，甯溺於淵。
溺于淵猶可遊也，溺於人不可救也。', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-PRE-QIN-76e5-76e4-9298-2d-4f5a-540d', 'https://zh.wikisource.org/wiki/%E5%8F%A4%E8%A9%A9%E6%BA%90'),
    ('cn-pretang-4f5a-540d', '帶銘', NULL, NULL, '火滅修容，慎戒必恭，恭則壽。', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-PRE-QIN-5e36-9298-2d-4f5a-540d', 'https://zh.wikisource.org/wiki/%E5%8F%A4%E8%A9%A9%E6%BA%90'),
    ('cn-pretang-4f5a-540d', '杖銘', NULL, NULL, '惡乎危，於忿懥。
惡乎失道，於嗜欲。
惡乎相忘，于富貴。', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-PRE-QIN-6756-9298-2d-4f5a-540d', 'https://zh.wikisource.org/wiki/%E5%8F%A4%E8%A9%A9%E6%BA%90'),
    ('cn-pretang-4f5a-540d', '衣銘', NULL, NULL, '桑蠶苦，女工難，得新捐故後必寒。', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-PRE-QIN-8863-9298-2d-4f5a-540d', 'https://zh.wikisource.org/wiki/%E5%8F%A4%E8%A9%A9%E6%BA%90'),
    ('cn-pretang-4f5a-540d', '筆銘', NULL, NULL, '豪毛茂茂，陷水可脫，陷文不活。', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-PRE-QIN-7b46-9298-2d-4f5a-540d', 'https://zh.wikisource.org/wiki/%E5%8F%A4%E8%A9%A9%E6%BA%90'),
    ('cn-pretang-4f5a-540d', '矛銘', NULL, NULL, '造矛造矛，少間弗忍，終身之羞。
餘一人所聞。以戒後世子孫。', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-PRE-QIN-77db-9298-2d-4f5a-540d', 'https://zh.wikisource.org/wiki/%E5%8F%A4%E8%A9%A9%E6%BA%90'),
    ('cn-pretang-4f5a-540d', '書車', NULL, NULL, '出畏之，入懼之。', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-PRE-QIN-66f8-8eca-2d-4f5a-540d', 'https://zh.wikisource.org/wiki/%E5%8F%A4%E8%A9%A9%E6%BA%90'),
    ('cn-pretang-4f5a-540d', '書戶', NULL, NULL, '行必履正，無懷僥倖。', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-PRE-QIN-66f8-6236-2d-4f5a-540d', 'https://zh.wikisource.org/wiki/%E5%8F%A4%E8%A9%A9%E6%BA%90'),
    ('cn-pretang-4f5a-540d', '書履', NULL, NULL, '行必履正，無懷僥倖。', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-PRE-QIN-66f8-5c65-2d-4f5a-540d', 'https://zh.wikisource.org/wiki/%E5%8F%A4%E8%A9%A9%E6%BA%90'),
    ('cn-pretang-4f5a-540d', '書硯', NULL, NULL, '石墨相著而黑，邪心讒言，無得汙白。', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-PRE-QIN-66f8-786f-2d-4f5a-540d', 'https://zh.wikisource.org/wiki/%E5%8F%A4%E8%A9%A9%E6%BA%90'),
    ('cn-pretang-4f5a-540d', '書鋒', NULL, NULL, '忍之須臾，乃全汝軀。', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-PRE-QIN-66f8-92d2-2d-4f5a-540d', 'https://zh.wikisource.org/wiki/%E5%8F%A4%E8%A9%A9%E6%BA%90'),
    ('cn-pretang-4f5a-540d', '書杖', NULL, NULL, '輔人無苟，扶人無咎。', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-PRE-QIN-66f8-6756-2d-4f5a-540d', 'https://zh.wikisource.org/wiki/%E5%8F%A4%E8%A9%A9%E6%BA%90'),
    ('cn-pretang-4f5a-540d', '書井', NULL, NULL, '原泉滑滑，連旱則絶。
取事有常，賦斂有節。', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-PRE-QIN-66f8-4e95-2d-4f5a-540d', 'https://zh.wikisource.org/wiki/%E5%8F%A4%E8%A9%A9%E6%BA%90'),
    ('cn-pretang-7121-540d-6c0f-2f-6f22-6a02-5e9c', '上邪', NULL, NULL, '我欲與君相知
長命無絶衰
山無陵
江水為竭
冬雷震震
夏雨雪
天地合
乃敢與君絶', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-HAN-4e0a-90aa-2d-7121-540d-6c0f-2f-6f22-6a02-5e9c', 'https://zh.wikisource.org/wiki/%E4%B8%8A%E9%82%AA'),
    ('cn-pretang-4f5a-540d', '行行重行行', NULL, NULL, '行行重行行 與君生別離
相去萬餘里 各在天一涯
道路阻且長 會面安可知
胡馬依北風 越鳥巢南枝
相去日已遠 衣帶日已緩
浮雲蔽白日 遊子不顧反
思君令人老 歲月忽已晚
棄捐勿復道 努力加餐飯', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-HAN-884c-884c-91cd-884c-884c-2d-4f5a-540d', 'https://zh.wikisource.org/wiki/%E8%A1%8C%E8%A1%8C%E9%87%8D%E8%A1%8C%E8%A1%8C'),
    ('cn-pretang-4f5a-540d', '迢迢牽牛星', NULL, NULL, '迢迢牽牛星 皎皎河漢女
纎纎擢素手 札札弄機杼
終日不成章 泣涕零如雨
河漢清且淺 相去復幾許
盈盈一水間 脈脈不得語', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-HAN-8fe2-8fe2-727d-725b-661f-2d-4f5a-540d', 'https://zh.wikisource.org/wiki/%E8%BF%A2%E8%BF%A2%E7%89%BD%E7%89%9B%E6%98%9F'),
    ('cn-pretang-5289-90a6', '大風歌', NULL, NULL, '大風起兮雲飛揚，威加海內兮歸故鄉。安得猛士兮守四方？', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-HAN-5927-98a8-6b4c-2d-5289-90a6', 'https://zh.wikisource.org/wiki/%E5%A4%A7%E9%A2%A8%E6%AD%8C_(%E5%8A%89%E9%82%A6)'),
    ('cn-pretang-6881-9d3b', '五噫歌', NULL, NULL, '陟彼北芒兮，噫！
顧瞻帝京兮，噫！
宮闕崔巍兮，噫！
民之劬勞兮，噫！
遼遼未央兮，噫！', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-HAN-4e94-566b-6b4c-2d-6881-9d3b', 'https://zh.wikisource.org/wiki/%E4%BA%94%E5%99%AB%E6%AD%8C'),
    ('cn-pretang-9805-7fbd', '垓下歌', NULL, NULL, '力拔山兮氣蓋世，
時不利兮騅不逝。
騅不逝兮可奈何，
虞兮虞兮奈若何。', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-HAN-5793-4e0b-6b4c-2d-9805-7fbd', 'https://zh.wikisource.org/wiki/%E5%9E%93%E4%B8%8B%E6%AD%8C_(%E9%A0%85%E7%BE%BD)'),
    ('cn-pretang-5289-5fb9', '秋風辭', NULL, NULL, '秋風起兮白雲飛，草木黃落兮鴈南歸。
蘭有秀兮菊有芳，攜佳人兮不能忘。
泛樓船兮濟汾河，橫中流兮揚素波。
簫鼓鳴兮發棹歌，歡樂極兮哀情多。
少壯幾時兮奈老何！', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-HAN-79cb-98a8-8fad-2d-5289-5fb9', 'https://zh.wikisource.org/wiki/%E7%A7%8B%E9%A2%A8%E8%BE%AD_(%E5%8A%89%E5%BE%B9)'),
    ('cn-pretang-5289-5fb9', '柏梁詩', NULL, NULL, '日月星辰和四時，（帝）
驂駕駟馬從梁來。（梁王）
郡國士馬羽林材，（大司馬）
總領天下誠難治。（丞相）
和撫四夷不易哉，（大將軍）
刀筆之吏臣執之。（御史大夫）
撞鐘伐鼓聲中詩，（太常）
宗室廣大日益滋。（宗正）
周衛交戟禁不時，（衛尉）
總領從官柏梁台。（光祿勳）
平理請讞決嫌疑，（廷尉）
修飾輿馬待駕來。（太僕）
郡國吏功差次之，（大鴻臚）
乘輿御物主治之。（少府）
陳粟萬石揚以箕，（大司農）
徼道宮下隨討治。（執金吾）
三輔盜賊天下危，（左馮翊）
盜阻南山為民災。（右扶風）
外家公主不可治，（京兆尹）
椒房率更領其材。（詹事）
蠻夷朝賀常會期，（典屬國）
柱欀欂櫨相枝持。（大匠）
枇杷橘栗桃李梅，（太官令）
走狗逐兔張罘罳。（上林令）
齒妃女唇甘如飴，（郭舍人）
迫窘詰屈幾窮哉。（東方朔）', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-HAN-67cf-6881-8a69-2d-5289-5fb9', 'https://zh.wikisource.org/wiki/%E6%9F%8F%E6%A2%81%E8%A9%A9'),
    ('cn-pretang-4f5a-540d', '古詩為焦仲卿妻作', NULL, NULL, '孔雀東南飛 五里一徘徊
十三能織素 十四學裁衣
十五彈箜篌 十六誦詩書
十七為君婦 心中常苦悲
君既為府吏 守節情不移
賤妾留空房 相見常日稀
雞鳴入機織 夜夜不得息
三日斷五匹 大人故嫌遲
非為織作遲 君家婦難為
妾不堪驅使 徒留無所施
便可白公姥 及時相遣歸
府吏得聞之 堂上啟阿母
兒已薄祿相 幸復得此婦
結髮同枕席 黃泉共為友
共事二三年 始爾未為久
女行無偏斜 何意致不厚
阿母謂府吏 何乃太區區
此婦無禮節 舉動自專由
吾意久懷忿 汝豈得自由
東家有賢女 自名秦羅敷
可憐體無比 阿母為汝求
便可速遣之 遣之慎莫留
府吏長跪答 伏惟啟阿母
今若遣此婦 終老不復取
阿母得聞之 捶床便大怒
小子無所畏 何敢助婦語
吾已失恩義 會不相從許
府吏默無聲 再拜還入戶
舉言謂新婦 哽咽不能語
我自不驅卿 逼迫有阿母
卿但暫還家 吾今且報府
不久當歸還 還必相迎取
以此下心意 慎勿違吾語
新婦謂府吏 勿復重紛紜
往昔初陽歲 謝家來貴門
奉事循公姥 進止敢自專
晝夜勤作息 伶俜縈苦辛
謂言無罪過 供養卒大恩
仍更被驅遣 何言復來還
妾有繡腰襦 葳蕤自生光
紅羅復鬥帳 四角垂香囊
箱簾六七十 綠碧青絲繩
物物各自異 種種在其中
人賤物亦鄙 不足迎後人
留待作遣施 於今無會因
時時為安慰 久久莫相忘
雞鳴外欲曙 新婦起嚴妝
著我繡裌裙 事事四五通
足下躡絲履 頭上玳瑁光
腰若流紈素 耳著明月珰
指如削蔥根 口若含朱丹
纖纖作細步 精妙世無雙
上堂拜阿母 母聽去不止
昔作女兒時 生小出野里
本自無教訓 兼愧貴家子
受母錢帛多 不堪母驅使
今日還家去 念母勞家裡
卻與小姑別 淚落連珠子
新婦初來時 小姑始扶床
今日被驅遣 小姑如我長
勤心養公姥 好自相扶將
初七及下九 嬉戲莫相忘
出門登車去 涕落百餘行
府吏馬在前 新婦車在後
隱隱何甸甸 俱會大道口
下馬入車中 低頭共耳語
誓不相隔卿 且暫還家去
吾今且赴府 不久當還歸
誓天不相負
新婦謂府吏 感君區區懷
君既若見錄 不久望君來
君當作盤石 妾當作蒲葦
蒲葦紉如絲 盤石無轉移
我有親父兄 性行暴如雷
恐不任我意 逆以煎我懷
舉手長勞勞 二情同依依
入門上家堂 進退無顏儀
阿母大拊掌 不圖子自歸
十三教汝織 十四能裁衣
十五彈箜篌 十六知禮儀
十七遣汝嫁 謂言無誓違
汝今何罪過 不迎而自歸
蘭芝慚阿母 兒實無罪過
阿母大悲摧
還家十餘日 縣令遣媒來
雲有第三郎 窈窕世無雙
年始十八九 便言多令才
阿母謂阿女 汝可去應之
阿女含淚答 蘭芝初還時
府吏見丁寧 結誓不別離
今日違情義 恐此事非奇
自可斷來信 徐徐更謂之
阿母白媒人
貧賤有此女 始適還家門
不堪吏人婦 豈合令郎君
幸可廣問訊 不得便相許
媒人去數日 尋遣丞請還
說有蘭家女 承籍有宦官
雲有第五郎 嬌逸未有婚
遣丞為媒人 主簿通語言
直說太守家 有此令郎君
既欲結大義 故遣來貴門
阿母謝媒人
女子先有誓 老姥豈敢言
阿兄得聞之 悵然心中煩
舉言謂阿妹 作計何不量
先嫁得府吏 後嫁得郎君
否泰如天地 足以榮汝身
不嫁義郎體 其住欲何雲
蘭芝仰頭答 理實如兄言
謝家事夫婿 中道還兄門
處分適兄意 那得自任專
雖與府吏要 渠會永無緣
登即相許和 便可作婚姻
媒人下床去 諾諾復爾爾
還部白府君
下官奉使命 言談大有緣
府君得聞之 心中大歡喜
視歷復開書
便利此月內 六合正相應
良吉三十日 今已二十七
卿可去成婚
交語速裝束 駱繹如浮雲
青雀白鵠舫 四角龍子幡
婀娜隨風轉 金車玉作輪
躑躅青驄馬 流蘇金鏤鞍
齎錢三百萬 皆用青絲穿
雜彩三百匹 交廣市鮭珍
從人四五百 鬱鬱登郡門
阿母謂阿女
適得府君書 明日來迎汝
何不作衣裳 莫令事不舉
阿女默無聲 手巾掩口啼
淚落便如瀉
移我琉璃榻 出置前窓下
左手持刀尺 右手執綾羅
朝成繡裌裙 晚成單羅衫
晻晻日欲暝 愁思出門啼
府吏聞此變 因求假暫歸
未至二三里 摧藏馬悲哀
新婦識馬聲 躡履相逢迎
悵然遙相望 知是故人來
舉手拍馬鞍 嗟嘆使心傷
自君別我後 人事不可量
果不如先願 又非君所詳
我有親父母 逼迫兼弟兄
以我應他人 君還何所望
府吏謂新婦 賀卿得高遷
盤石方可厚 可以卒千年
蒲葦一時紉 便作旦夕間
卿當日勝貴 吾獨向黃泉
新婦謂府吏 何意出此言
同是被逼迫 君爾妾亦然
黃泉下相見 勿違今日言
執手分道去 各各還家門
生人作死別 恨恨那可論
念與世間辭 千萬不復全
府吏還家去 上堂拜阿母
今日大風寒
寒風摧樹木 嚴霜結庭蘭
兒今日冥冥 令母在後單
故作不良計 勿復怨鬼神
命如南山石 四體康且直
阿母得聞之 零淚應聲落
汝是大家子 仕宦於台閣
慎勿為婦死 貴賤情何薄
東家有賢女 窈窕豔城郭
阿母為汝求 便復在旦夕
府吏再拜還
長嘆空房中 作計乃爾立
轉頭向戶裡 漸見愁煎迫
其日馬牛嘶 新婦入青廬
菴菴黃昏後 寂寂人定初
我命絶今日 魂去屍長留
攬裙脫絲履 舉身赴清池
府吏聞此事 心知長別離
徘徊庭樹下 自掛東南枝
兩家求合葬 合葬華山傍
東西植松柏 左右種梧桐
枝枝相覆蓋 葉葉相交通
中有雙飛鳥 自名為鴛鴦
仰頭相向鳴 夜夜達五更
行人駐足聽 寡婦起徬徨
多謝後世人 戒之慎勿忘', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-HAN-53e4-8a69-70ba-7126-4ef2-537f-59bb-4f5c-2d-4f5a-540d', 'https://zh.wikisource.org/wiki/%E5%8F%A4%E8%A9%A9%E7%82%BA%E7%84%A6%E4%BB%B2%E5%8D%BF%E5%A6%BB%E4%BD%9C'),
    ('cn-pretang-5b8b-5b50-4faf', '董嬌嬈', NULL, NULL, '洛陽城東路 桃李生路傍
花花自相對 葉葉自相當
春風東北起 花葉正低昂
不知誰家子 提籠行采桑
纎手折其枝 花落何飄颺
請謝彼姝子 何為見損傷
高秋八九月 白露變為霜
終年會飄墮 安得久馨香
秋時自零落 春月復芬芳
何時盛年去 懽愛永相忘
吾欲竟此曲 此曲愁人腸
歸來酌美酒 挾瑟上高堂', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-HAN-8463-5b0c-5b08-2d-5b8b-5b50-4faf', 'https://zh.wikisource.org/wiki/%E8%91%A3%E5%AC%8C%E5%AC%88'),
    ('cn-pretang-8f9b-5ef6-5e74', '羽林郎', NULL, NULL, '昔有霍家奴 姓馮名子都
依倚將軍勢 調笑酒家胡
胡姬年十五 春日獨當壚
長裾連理帶 廣袖合歡襦
頭上藍田玉 耳後大秦珠
兩鬟何窈窕 一世良所無
一鬟五百萬 兩鬟千萬餘
不意金吾子 娉婷過我廬
銀鞍何昱爚 翠蓋空歭
就我求清酒 絲繩提玉壺
就我求珍肴 金盤膾鯉魚
貽我青銅鏡 結我紅羅裾
不惜紅羅裂 何論輕賤軀
男兒愛後婦 女子重前夫
人生有新故 貴賤不相踰
多謝金吾子 私愛徒區區', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-HAN-7fbd-6797-90ce-2d-8f9b-5ef6-5e74', 'https://zh.wikisource.org/wiki/%E7%BE%BD%E6%9E%97%E9%83%8E_(%E8%BE%9B%E5%BB%B6%E5%B9%B4)'),
    ('cn-pretang-8607-4f2f-7389-59bb', '盤中詩', NULL, NULL, '山樹高 鳥鳴悲 泉水深 鯉魚肥
空倉雀 常苦飢 吏人婦 會夫希
出門望 見白衣 謂當是 而更非
還入門 中心悲 北上堂 西入階
急機絞 杼聲催 長歎息 當語誰
君有行 妾念之 出有日 還無期
結中帶 長相思 君忘妾 天知之
妾忘君 罪當治 妾有行 宜知之
黃者金 白者玉 高者山 下者谷
姓為蘇 字伯玉 人才多 智謀足
家居長安身在蜀 何惜馬蹄歸不數
羊肉千斤酒百斛 令君馬肥麥與粟
今時人 智不足 與其書 不能讀
當從中央週四角', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-HAN-76e4-4e2d-8a69-2d-8607-4f2f-7389-59bb', 'https://zh.wikisource.org/wiki/%E7%9B%A4%E4%B8%AD%E8%A9%A9'),
    ('cn-pretang-4f5a-540d', '古絶句', NULL, NULL, '其一
藁砧今何在 山上復有山
何當大刀頭 破鏡飛上天
其二
日暮秋雲陰 江水清且深
何用通音信 蓮花瑇瑁簪
其三
菟絲從長風 根莖無斷絶
無情尚不離 有情安可別
其四
南山一桂樹 上有雙鴛鴦
千年長交頸 歡愛不相忘', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-HAN-53e4-7d76-53e5-2d-4f5a-540d', 'https://zh.wikisource.org/wiki/%E5%8F%A4%E7%B5%95%E5%8F%A5'),
    ('cn-pretang-5289-7d30-541b', '悲愁歌', NULL, NULL, '吾家嫁我兮天一方，
遠託異國兮烏孫王。
穹廬為室兮旃為牆，
以肉為食兮酪為漿。
居常土思兮心內傷，
願為黃鵠兮歸故鄉。', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-HAN-60b2-6101-6b4c-2d-5289-7d30-541b', 'https://zh.wikisource.org/wiki/%E6%82%B2%E6%84%81%E6%AD%8C_(%E5%8A%89%E7%B4%B0%E5%90%9B)'),
    ('cn-pretang-7121-540d-6c0f-2f-6f22-6a02-5e9c', '練時日', NULL, NULL, '練時日 侯有望
𤋲膋蕭 延四方
九重開 靈之斿
垂惠恩 鴻祜休
靈之車 結玄雲
駕飛龍 羽旄紛
靈之下 若風馬
左倉龍 右白虎
靈之來 神哉沛
先以雨 般裔裔
靈之至 慶陰陰
相放𢘍 震澹心
靈已坐 五音飭
虞至旦 承靈億
牲繭栗 粢盛香
尊桂酒 賓八鄉
靈安留 吟青黃
遍觀此 眺瑤堂
眾嫭竝 綽奇麗
顏如荼 兆逐靡
被華文 厠霧縠
曳阿錫 佩珠玉
俠嘉夜 茝蘭芳
澹容與 獻嘉觴', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-HAN-7df4-6642-65e5-2d-7121-540d-6c0f-2f-6f22-6a02-5e9c', 'https://zh.wikisource.org/wiki/%E7%B7%B4%E6%99%82%E6%97%A5'),
    ('cn-pretang-7121-540d-6c0f-2f-6f22-6a02-5e9c', '青陽', NULL, NULL, '青陽開動 根荄以遂
膏潤幷愛 跂行畢逮
霆聲發榮 壧處頃聽
枯槀復產 廼成厥命
衆庶熙熙 施及夭胎
羣生啿啿 惟春之祺', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-HAN-9752-967d-2d-7121-540d-6c0f-2f-6f22-6a02-5e9c', 'https://zh.wikisource.org/wiki/%E9%9D%92%E9%99%BD'),
    ('cn-pretang-7121-540d-6c0f-2f-6f22-6a02-5e9c', '西顥', NULL, NULL, '西颢沆砀 秋氣肅殺
含秀垂颖 续舊不废
奸伪不萌 妖孽伏息
隅辟越遠 四貉咸服
既畏兹威 惟慕纯德
附而不骄 正心翊翊', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-HAN-897f-9865-2d-7121-540d-6c0f-2f-6f22-6a02-5e9c', 'https://zh.wikisource.org/wiki/%E8%A5%BF%E9%A1%A5'),
    ('cn-pretang-7121-540d-6c0f-2f-6f22-6a02-5e9c', '玄冥', NULL, NULL, '玄冥陵陰 蛰虫蓋臧
草木零落 抵冬降霜
易乱除邪 革正異俗
兆民反本 抱素懷樸
條理信義 望禮五嶽
籍斂之時 掩收嘉穀', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-HAN-7384-51a5-2d-7121-540d-6c0f-2f-6f22-6a02-5e9c', 'https://zh.wikisource.org/wiki/%E7%8E%84%E5%86%A5'),
    ('cn-pretang-7121-540d-6c0f-2f-6f22-6a02-5e9c', '惟泰元', NULL, NULL, '惟泰元尊 媪神蕃釐
經纬天地 作成四時
精建日月 星辰度理
陰陽五行 周而復始
雲風雷電 降甘露雨
百姓蕃滋 咸循厥绪
继統恭勤 顺皇之德
鸾路龍鳞 罔不肸饰
嘉笾列陳 庶几宴享
灭除凶災 烈腾八荒
鍾鼓竽笙 雲舞翔翔
招摇靈旗 九夷宾將', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-HAN-60df-6cf0-5143-2d-7121-540d-6c0f-2f-6f22-6a02-5e9c', 'https://zh.wikisource.org/wiki/%E6%83%9F%E6%B3%B0%E5%85%83'),
    ('cn-pretang-7121-540d-6c0f-2f-6f22-6a02-5e9c', '天馬', NULL, NULL, '太一況 天馬下
霑赤汗 沫流赭
志俶傥 精權奇
籋浮雲 晻上馳
體容與 迣萬里
今安匹 龍為友
天馬徠 從四極
涉流沙 九夷服
天馬徠 出泉水
虎脊两 化若鬼
天馬徠 歷無草
徑千里 循東道
天馬徠 執徐時
將摇举 谁與期
天馬徠 開遠門
竦予身 逝昆崙
天馬徠 龍之媒
遊阊阖 觀玉台', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-HAN-5929-99ac-2d-7121-540d-6c0f-2f-6f22-6a02-5e9c', 'https://zh.wikisource.org/wiki/%E5%A4%A9%E9%A6%AC'),
    ('cn-pretang-73ed-56fa', '寶鼎詩', NULL, NULL, '嶽脩貢兮川效珍，吐金景兮歊浮雲。
寶鼎見兮色紛縕。煥其炳兮被龍文。
登祖廟兮享聖神。昭靈德兮彌億年。', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-HAN-5bf6-9f0e-8a69-2d-73ed-56fa', 'https://zh.wikisource.org/wiki/%E5%AF%B6%E9%BC%8E%E8%A9%A9'),
    ('cn-pretang-5289-90a6', '鴻鵠歌', NULL, NULL, '鴻鵠高飛
一舉千里
羽翼已就
橫絶四海
橫絶四海
又可奈何
星有繒繳
將安所施', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-HAN-9d3b-9d60-6b4c-2d-5289-90a6', 'https://zh.wikisource.org/wiki/%E9%B4%BB%E9%B5%A0%E6%AD%8C'),
    ('cn-pretang-71d5-523a-738b-65e6', '歌', NULL, NULL, '漢帝臨汾水，周仙去洛濱。
郢中吟白雪，梁上繞飛塵。
響發行雲駐，聲隨子夜新。
願君聽扣角，當自識賢臣。', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-HAN-6b4c-2d-71d5-523a-738b-65e6', 'https://zh.wikisource.org/wiki/%E6%AD%8C'),
    ('cn-pretang-7121-540d-6c0f-2f-6f22-6a02-5e9c', '傷歌行', NULL, NULL, '兔走烏飛不相見，人事依稀速如電。
王母夭桃一度開，玉樓紅粉千回變。
車馳馬走咸陽道，石家舊宅空荒草。
秋雨無情不惜花，芙蓉一一驚香倒。
勸君莫謾栽荆棘，秦皇虛費驅山力。
英風一去更無言，白骨沈埋暮山碧。', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-HAN-50b7-6b4c-884c-2d-7121-540d-6c0f-2f-6f22-6a02-5e9c', 'https://zh.wikisource.org/wiki/%E5%82%B7%E6%AD%8C%E8%A1%8C'),
    ('cn-pretang-7121-540d-6c0f-2f-6f22-6a02-5e9c', '江南', NULL, NULL, '江南春起柂，秋至尚波濤。
問舍才能定，呼舟已復操。
行歌付浩蕩，歸夢得蕭騷。
冉冉欲何補，紛紛為此勞。', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-HAN-6c5f-5357-2d-7121-540d-6c0f-2f-6f22-6a02-5e9c', 'https://zh.wikisource.org/wiki/%E6%B1%9F%E5%8D%97'),
    ('cn-pretang-7121-540d-6c0f-2f-6f22-6a02-5e9c', '薤露歌', NULL, NULL, '蜀琴且勿彈，齊竽且莫吹。
四筵並寂聽，聽我薤露詩。
昨日七尺軀，今日為死屍。
親戚空滿堂，魂氣安所之。
金玉素所愛，棄捐篋笥中。
佩服素所愛，淒涼掛悲風。
妻妾素所愛，洒淚空房櫳。
賓客素所愛，分散各西東。
讎者自相快，親者自相悲。
有耳不復聞，有目不復窺。
譬彼燭上火，一滅無光輝。
譬彼空中雲，散去絶餘姿。
人生無百歲，百歲復如何。
誰能將兩手，挽彼東逝波。
古來英雄士，俱巳歸山阿。
有酒且盡歡，聽我薤露歌。', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-HAN-85a4-9732-6b4c-2d-7121-540d-6c0f-2f-6f22-6a02-5e9c', 'https://zh.wikisource.org/wiki/%E8%96%A4%E9%9C%B2%E6%AD%8C'),
    ('cn-pretang-7121-540d-6c0f-2f-6f22-6a02-5e9c', '君子行', NULL, NULL, '君子愼所履，小人多所疑。
尼甫至聖賢，猶為匡所縻。', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-HAN-541b-5b50-884c-2d-7121-540d-6c0f-2f-6f22-6a02-5e9c', 'https://zh.wikisource.org/wiki/%E5%90%9B%E5%AD%90%E8%A1%8C'),
    ('cn-pretang-5289-5fb9', '李夫人歌', NULL, NULL, '紫皇宮殿重重開，夫人飛入瓊瑤臺。
綠香繡帳何時歇，青雲無光宮水咽。
翩聯桂花墜秋月，孤鸞驚啼商絲發。
紅壁闌珊懸珮璫，歌臺小妓遙相望。
玉蟾滴水雞人唱，露華蘭葉參差光。', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-HAN-674e-592b-4eba-6b4c-2d-5289-5fb9', 'https://zh.wikisource.org/wiki/%E6%9D%8E%E5%A4%AB%E4%BA%BA%E6%AD%8C'),
    ('cn-pretang-7121-540d-6c0f-2f-6f22-6a02-5e9c', '孤兒行', NULL, NULL, '蓬頭皸足誰家兒，滿面塵埃雙淚垂。
爺娘棄我不待老，骨肉無人但兄嫂。
兩身一氣不相知，陌路茫茫向誰道。
清晨采薪日入歸，殘羹冷飯難充饑。
欲言問兄兄不顧，嫂是他人更奚訴。
人生一世為弟兄，同根自合同枯榮。
爺娘在日曾眷戀，願兄回看死人面。', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-HAN-5b64-5152-884c-2d-7121-540d-6c0f-2f-6f22-6a02-5e9c', 'https://zh.wikisource.org/wiki/%E5%AD%A4%E5%85%92%E8%A1%8C'),
    ('cn-pretang-7121-540d-6c0f-2f-6f22-6a02-5e9c', '蒿里曲', NULL, NULL, '澗草萋萋泉汩汩，紫蘭香老棠梨發。
山中無人松柏寒，臥聽狐貍嘯明月。
白楊樹頭風惻惻，寡烏悲啼山月黑。
殯宮冷落清夜長，銀鴨金鳧不堪食。
山花冥冥啼子規，鳥銜紙錢掛花枝。
山中遊人莫相笑，君到此中當自知。', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-HAN-84bf-91cc-66f2-2d-7121-540d-6c0f-2f-6f22-6a02-5e9c', 'https://zh.wikisource.org/wiki/%E8%92%BF%E9%87%8C%E6%9B%B2'),
    ('cn-pretang-7121-540d-6c0f-2f-6f22-6a02-5e9c', '朱明', NULL, NULL, '朱明盛長 旉與萬物
桐生茂豫 靡有所詘
敷蕐就實 既阜既昌
登成甫田 百鬼廸嘗
廣大建祀 肅雍不忘
神若宥之 傳世無疆', NULL, NULL, 'parsed', 'cn-pretang1', 'CN', 'CN-PRETANG-CACHED-HAN-6731-660e-2d-7121-540d-6c0f-2f-6f22-6a02-5e9c', 'https://zh.wikisource.org/wiki/%E6%9C%B1%E6%98%8E')
)
INSERT INTO poems (
  poet_id, poem_no, title_zh, title_ko, category, body_zh,
  translation_ko, commentary_ko, is_notable, status, quality, country
)
SELECT
  p.id,
  COALESCE(existing_poem_count.max_poem_no, 0)
    + row_number() OVER (PARTITION BY p.id ORDER BY ip.title_zh)::integer,
  ip.title_zh, ip.title_ko, ip.category, ip.body_zh,
  ip.translation_ko, ip.commentary_ko, TRUE, ip.status, ip.quality, ip.country
FROM input_poems ip
JOIN poets p ON p.slug = ip.poet_slug
LEFT JOIN LATERAL (
  SELECT max(poem_no) AS max_poem_no
  FROM poems
  WHERE poet_id = p.id
) existing_poem_count ON TRUE
WHERE NOT EXISTS (
  SELECT 1
  FROM poems existing
  WHERE existing.poet_id = p.id
    AND existing.title_zh = ip.title_zh
    AND existing.body_zh = ip.body_zh
);

UPDATE poets p
SET poem_count = sub.cnt
FROM (
  SELECT poet_id, count(*)::integer AS cnt
  FROM poems
  WHERE poet_id IN (SELECT id FROM poets WHERE slug IN ('cn-pretang-4f5a-540d', 'cn-pretang-7121-540d-6c0f-2f-6f22-6a02-5e9c', 'cn-pretang-5289-90a6', 'cn-pretang-6881-9d3b', 'cn-pretang-9805-7fbd', 'cn-pretang-5289-5fb9', 'cn-pretang-5b8b-5b50-4faf', 'cn-pretang-8f9b-5ef6-5e74', 'cn-pretang-8607-4f2f-7389-59bb', 'cn-pretang-5289-7d30-541b', 'cn-pretang-73ed-56fa', 'cn-pretang-71d5-523a-738b-65e6'))
  GROUP BY poet_id
) sub
WHERE p.id = sub.poet_id;

-- Review counts before COMMIT when applying manually:
SELECT era_period, count(*) FROM poets WHERE slug IN ('cn-pretang-4f5a-540d', 'cn-pretang-7121-540d-6c0f-2f-6f22-6a02-5e9c', 'cn-pretang-5289-90a6', 'cn-pretang-6881-9d3b', 'cn-pretang-9805-7fbd', 'cn-pretang-5289-5fb9', 'cn-pretang-5b8b-5b50-4faf', 'cn-pretang-8f9b-5ef6-5e74', 'cn-pretang-8607-4f2f-7389-59bb', 'cn-pretang-5289-7d30-541b', 'cn-pretang-73ed-56fa', 'cn-pretang-71d5-523a-738b-65e6') GROUP BY era_period ORDER BY era_period;
SELECT p.slug, count(pm.id) FROM poets p LEFT JOIN poems pm ON pm.poet_id = p.id WHERE p.slug IN ('cn-pretang-4f5a-540d', 'cn-pretang-7121-540d-6c0f-2f-6f22-6a02-5e9c', 'cn-pretang-5289-90a6', 'cn-pretang-6881-9d3b', 'cn-pretang-9805-7fbd', 'cn-pretang-5289-5fb9', 'cn-pretang-5b8b-5b50-4faf', 'cn-pretang-8f9b-5ef6-5e74', 'cn-pretang-8607-4f2f-7389-59bb', 'cn-pretang-5289-7d30-541b', 'cn-pretang-73ed-56fa', 'cn-pretang-71d5-523a-738b-65e6') GROUP BY p.slug ORDER BY p.slug;

ROLLBACK;
-- COMMIT;
