-- Generated by scripts/build_cn_translation_pipeline_staging.mjs
-- Part: 11/13
-- Purpose: stage CN pre-Tang and Song/Yuan/Ming poems into the JDS translation pipeline.
-- Translator decision: JDS backend=gemini model=gemini-2.5-flash-lite prompt=pipeline/translate/prompts/v5_full.txt.
-- Safety: inserts only missing poet slug + title_zh + body_zh rows. Default ending is ROLLBACK.

BEGIN;

WITH input_poets(slug, name_zh, name_ko, life_raw, era_period, country) AS (
  VALUES
    ('candidate-ming-5f90-71a5', '徐熥', NULL, NULL, '明', 'CN'),
    ('candidate-ming-5f90-4e2d-884c', '徐中行', NULL, NULL, '明', 'CN'),
    ('candidate-ming-6234-9be8', '戴鯨', NULL, NULL, '明', 'CN'),
    ('candidate-yuan-6234-9c32', '戴鰲', NULL, NULL, '元', 'CN'),
    ('candidate-ming-6234-4c80', '戴䲀', NULL, NULL, '明', 'CN'),
    ('candidate-song-5289-93ae', '劉鎮', NULL, NULL, '宋', 'CN'),
    ('candidate-song-5433-60df-4fe1', '吳惟信', NULL, NULL, '宋', 'CN'),
    ('candidate-song-5b8b-81ea-905c', '宋自遜', NULL, NULL, '宋', 'CN'),
    ('candidate-song-9678-904a', '陸遊', NULL, NULL, '宋', 'CN'),
    ('candidate-song-6b50-967d-4fee', '歐陽修', NULL, NULL, '宋', 'CN'),
    ('candidate-song-5468-6587-749e', '周文璞', NULL, NULL, '宋', 'CN'),
    ('candidate-song-84b2-58fd-5bac', '蒲壽宬', NULL, NULL, '宋', 'CN'),
    ('candidate-yuan-5584-4f4f', '善住', NULL, NULL, '元', 'CN'),
    ('candidate-ming-674e-5ef6-8208', '李延興', NULL, NULL, '明', 'CN'),
    ('candidate-ming-85cd-667a', '藍智', NULL, NULL, '明', 'CN'),
    ('candidate-ming-738b-7acb-9053', '王立道', NULL, NULL, '明', 'CN'),
    ('candidate-ming-912d-5b78-9187', '鄭學醇', NULL, NULL, '明', 'CN'),
    ('candidate-ming-76db-9cf4-4e16', '盛鳴世', NULL, NULL, '明', 'CN'),
    ('candidate-song-6641-6c96-4e4b', '晁沖之', NULL, NULL, '宋', 'CN'),
    ('candidate-ming-9b4f-5141-4e2d', '魏允中', NULL, NULL, '明', 'CN'),
    ('candidate-ming-80e1-594e', '胡奎', NULL, NULL, '明', 'CN'),
    ('candidate-song-4ef2-4e26', '仲並', NULL, NULL, '宋', 'CN'),
    ('candidate-song-5289-624d-90b5', '劉才邵', NULL, NULL, '宋', 'CN'),
    ('candidate-song-5b8b-5ea0', '宋庠', NULL, NULL, '宋', 'CN'),
    ('candidate-song-674e-89af', '李覯', NULL, NULL, '宋', 'CN'),
    ('candidate-song-8607-8f4d', '蘇轍', NULL, NULL, '宋', 'CN'),
    ('candidate-song-9112-6d69', '鄒浩', NULL, NULL, '宋', 'CN'),
    ('candidate-song-5f90-5ead-7b60', '徐庭筠', NULL, NULL, '宋', 'CN'),
    ('candidate-song-8881-71ee', '袁燮', NULL, NULL, '宋', 'CN'),
    ('candidate-song-8607-6cc2', '蘇泂', NULL, NULL, '宋', 'CN'),
    ('candidate-ming-674e-5922-967d', '李夢陽', NULL, NULL, '明', 'CN'),
    ('candidate-ming-516c-9f10', '公鼐', NULL, NULL, '明', 'CN'),
    ('candidate-ming-65b9-5b5f-5f0f', '方孟式', NULL, NULL, '明', 'CN'),
    ('candidate-ming-6c5f-6e90', '江源', NULL, NULL, '明', 'CN')
)
INSERT INTO poets (title_id, name_zh, name_ko, life_raw, era_period, poem_count)
SELECT slug, name_zh, name_ko, life_raw, era_period, 0
FROM input_poets
ON CONFLICT (title_id) DO UPDATE SET
  name_zh = EXCLUDED.name_zh,
  name_ko = COALESCE(EXCLUDED.name_ko, poets.name_ko),
  life_raw = COALESCE(EXCLUDED.life_raw, poets.life_raw),
  era_period = EXCLUDED.era_period;

WITH input_poems(poet_slug, volume, title_zh, title_ko, category, meter, body_zh, status, quality, review_memo) AS (
  VALUES
    ('candidate-ming-5f90-71a5', 0, '出塞曲', NULL, '五言古詩', 5, '羽檄交馳急，
橫戈賦逺征。
五更邊地角，
雙淚漢臣纓。
夜月闗山影，
秋風隴水聲。
何時安絶漠，
歸去報承明。
窮冬生朔雪，
寒色滿交河。
絶塞人煙少，
荒城戍角多。
關山同漢月，
部落半羌歌。
欲破匈奴膽，
君王莫許和。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00801","source_record_id":"CN-NT-CAT-00403","alias_record_ids":["CN-NT-CAT-00403"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%87%BA%E5%A1%9E%E6%9B%B2_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '陌上桑', NULL, '五言律詩', 5, '賤妾是羅敷，
條桑向路隅。
捲衣伸玉腕，
掩袂謝金夫。
幹弱揺絲籠，
枝繁罩繡襦。
蠶飢歸去急，
五馬枉踟蹰。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00802","source_record_id":"CN-NT-CAT-00404","alias_record_ids":["CN-NT-CAT-00404"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%99%8C%E4%B8%8A%E6%A1%91_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '巫山高', NULL, '五言律詩', 5, '宮殿傷蕪沒，
峰巒入杳𡨋。
猿聲經峽慘，
山色近湘青。
神女魂何處，
襄王夢已醒。
朝昏見雲雨，
猶自想精靈。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00803","source_record_id":"CN-NT-CAT-00405","alias_record_ids":["CN-NT-CAT-00405"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%B7%AB%E5%B1%B1%E9%AB%98_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '梅花落', NULL, '五言律詩', 5, '繁花生絶塞，
春至幾枝空。
舞雜梁園雪，
飄隨庾嶺風。
妝臺香㸃砌，
官閣影辭叢。
少婦髙樓上，
含悽曲調中。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00804","source_record_id":"CN-NT-CAT-00406","alias_record_ids":["CN-NT-CAT-00406"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%A2%85%E8%8A%B1%E8%90%BD_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '折楊柳', NULL, '五言律詩', 5, '別時曽一折，
羌管不堪聽。
愁鎖眉同翠，
嬌廻眼共青。
征途悲雨雪，
古驛望流星。
却恨飛空絮，
隨波化作萍。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00805","source_record_id":"CN-NT-CAT-00407","alias_record_ids":["CN-NT-CAT-00407"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%8A%98%E6%A5%8A%E6%9F%B3_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '紫騮馬', NULL, '五言律詩', 5, '蹀躞橫行意，
悲鳴戀主身。
金鞭垂漢月，
玉勒控邉塵。
影絶追奔易，
蹄髙轉戰頻。
不辭流汗血，
未可事和親。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00806","source_record_id":"CN-NT-CAT-00408","alias_record_ids":["CN-NT-CAT-00408"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%B4%AB%E9%A8%AE%E9%A6%AC_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '隴頭水', NULL, '五言律詩', 5, '秦川分兩水，
嗚咽不能休。
飲馬氷猶凍，
磨刀血半流。
東西隨隴坂，
逺近入邊州。
萬古聲無盡，
惟添征戍愁。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00807","source_record_id":"CN-NT-CAT-00409","alias_record_ids":["CN-NT-CAT-00409"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%9A%B4%E9%A0%AD%E6%B0%B4_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '關山月', NULL, NULL, NULL, '一片關山月，
悲歡望不同。
穹廬光照海，
沙磧影連空。
輪滿開秦鏡，
斜倚漢弓。
年年三五夜，
魂斷玉樓中。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00808","source_record_id":"CN-NT-CAT-00410","alias_record_ids":["CN-NT-CAT-00410"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%97%9C%E5%B1%B1%E6%9C%88_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '送人赴安西', NULL, '五言律詩', 5, '離亭征馬嘶，
送子赴安西。
後會知何日，
前途方鼓鼙。
天寒白草瘦，
沙濶黃雲低。
所惜同心逺，
能無心慘悽。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00809","source_record_id":"CN-NT-CAT-00411","alias_record_ids":["CN-NT-CAT-00411"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%80%81%E4%BA%BA%E8%B5%B4%E5%AE%89%E8%A5%BF_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '春興', NULL, '五言律詩', 5, '入春纔數日，
春意滿疎林。
苔補堦前色，
禽傳竹外音。
山容開曉霽，
雲氣散輕隂。
虛室無塵想，
泠然物外心。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00810","source_record_id":"CN-NT-CAT-00412","alias_record_ids":["CN-NT-CAT-00412"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%98%A5%E8%88%88_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '王臺驛', NULL, '五言律詩', 5, '古驛枕溪流，
羣山抱驛樓。
灘聲寒午夢，
鶯語動春愁。
芳草王孫路，
桃花漁父舟。
白雲與流水，
相對共悠悠。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00811","source_record_id":"CN-NT-CAT-00413","alias_record_ids":["CN-NT-CAT-00413"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%8E%8B%E8%87%BA%E9%A9%9B_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '舟行', NULL, '五言律詩', 5, '舟行正暮秋，
晚眺思悠悠。
驛路當溪斷，
漁家傍竹幽。
山阿全隠寺，
石罅亂廻舟。
坐聽寒溪水，
潺湲日夜流。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00812","source_record_id":"CN-NT-CAT-00414","alias_record_ids":["CN-NT-CAT-00414"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%88%9F%E8%A1%8C_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '夜坐', NULL, '五言律詩', 5, '空齋寒似水，
獨坐倍淒然。
葉響林間雨，
風聲竹杪泉。
應門雙鶴睡，
照佛一燈懸。
暝色生蘿徑，
飛來絶壑煙。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00813","source_record_id":"CN-NT-CAT-00415","alias_record_ids":["CN-NT-CAT-00415"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%A4%9C%E5%9D%90_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '苦雨', NULL, NULL, NULL, '九夏苦無雨，
冬來何太繁。
翻浪急，
莽莽塞天昏。
野服霑松翠，
空墻繡蘚痕。
山齋幽寂甚，
愁緒豈堪論。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00814","source_record_id":"CN-NT-CAT-00416","alias_record_ids":["CN-NT-CAT-00416"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%8B%A6%E9%9B%A8_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '歲盡', NULL, '五言律詩', 5, '范叔寒如此，
其如復逼年。
文章能作祟，
吾道合迍邅。
吏預催官税，
門多索子錢。
縱然貧到骨，
不敢怨皇天。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00815","source_record_id":"CN-NT-CAT-00417","alias_record_ids":["CN-NT-CAT-00417"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%AD%B2%E7%9B%A1_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '春日閒居', NULL, '五言古詩', 5, '草閣春方暮，
檉隂日未斜。
蝸涎分斷壁，
鶯語共隣家。
曲塢藏脩竹，
輕雲覆落花。
卑棲有至性，
長此臥煙霞。
茒屋依青嶂，
蒲團坐白雲。
新茶燒竹煮，
老栢雜香焚。
壁古苔紋見，
林深鳥語聞。
𡨋心忘早晚，
花外已斜曛。
一室通幽徑，
群峰列翠屏。
空堦半夜雨，
新竹幾行青。
山果猿爭拾，
巖扉鶴自扃。
花間聞剝啄，
客借太𤣥經。
焚香坐翠㣲，
山色入荆扉。
日午鳥啼歇，
門閒人跡稀。
休糧孤鶴瘦，
積雨野蔬肥。
欲識靜中意，
白雲天際飛。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00816","source_record_id":"CN-NT-CAT-00418","alias_record_ids":["CN-NT-CAT-00418"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%98%A5%E6%97%A5%E9%96%92%E5%B1%85_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '風雨', NULL, '五言律詩', 5, '風雨來何驟，
虛堂白晝隂。
木催愁破屋，
巢落不歸禽。
水入花畦亂，
雲埋竹塢深。
殘虹開晚霽，
飛瀑滿遥岑。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00817","source_record_id":"CN-NT-CAT-00419","alias_record_ids":["CN-NT-CAT-00419"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%A2%A8%E9%9B%A8_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-4e2d-884c', 0, '玉女潭', NULL, '七言律詩', 7, '仙臺千尺玉為容，
寒照瓊樓十二重。
石鏡月華流桂樹，
錦屏秋色散芙蓉。
碧霄縹緲春雲度，
絳雪葳蕤白日逢。
更喜洗頭盆尚在，
便應晞髪卧髙峯。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00818","source_record_id":"CN-NT-CAT-00422","alias_record_ids":["CN-NT-CAT-00422"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%8E%89%E5%A5%B3%E6%BD%AD_(%E5%BE%90%E4%B8%AD%E8%A1%8C)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-4e2d-884c', 0, '感舊', NULL, '七言絶句', 7, '自別燕臺白日徂，
華陽碣石總荒蕪。
獨留一片西山月，
猶照當年舊酒壚。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00819","source_record_id":"CN-NT-CAT-00423","alias_record_ids":["CN-NT-CAT-00423"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%84%9F%E8%88%8A_(%E5%BE%90%E4%B8%AD%E8%A1%8C)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-4e2d-884c', 0, '登嶽陽樓', NULL, '七言律詩', 7, '天敞平湖萬里臺，
秋髙鴈色照行杯。
三湘白石波間動，
七澤青山鏡裏開。
風靜仙人吹笛去，
月明神女弄珠來。
徘徊便擬休餐住，
俗吏慚非曼倩才。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00820","source_record_id":"CN-NT-CAT-00424","alias_record_ids":["CN-NT-CAT-00424"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%99%BB%E5%B2%B3%E9%99%BD%E6%A8%93_(%E5%BE%90%E4%B8%AD%E8%A1%8C)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-6234-9be8', 0, '春遊', NULL, '五言古詩', 5, '微風桃李夕，
是處鬭春華。
湖海平三月，
邊城活萬家。
土肥秧得意，
日暖草能芽。
須識東皇意，
歸來一徑斜。
日出東山上，
相從郭外遊。
青青千頃麥，
泛泛一扁舟。
水鳥窺魚倦，
山花倩蝶留。
到來無限意，
猶許續風流。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00821","source_record_id":"CN-NT-CAT-00425","alias_record_ids":["CN-NT-CAT-00425"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%98%A5%E9%81%8A_(%E6%88%B4%E9%AF%A8)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-6234-9be8', 0, '題畫', NULL, '七言絶句', 7, '移家近住釣魚灣，
楚水南邊白石灘。
忽見桐風飄一葉，
半崖秋氣落新寒。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00822","source_record_id":"CN-NT-CAT-00426","alias_record_ids":["CN-NT-CAT-00426"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%A1%8C%E7%95%AB_(%E6%88%B4%E9%AF%A8)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-yuan-6234-9c32', 0, '白蓮池', NULL, '五言絶句', 5, '避暑茅亭下，
清香隔水聞。
白蓮棲白鷺，
獨坐到黃昏。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00823","source_record_id":"CN-NT-CAT-00427","alias_record_ids":["CN-NT-CAT-00427"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%99%BD%E8%93%AE%E6%B1%A0_(%E6%88%B4%E9%B0%B2)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-6234-4c80', 0, '江夜', NULL, '五言律詩', 5, '海甸悲笳切，
愁仍倚柁樓。
沙清懸月白，
崕合湧江流。
客淚魚龍夕，
邊塵鴻雁秋。
如逢采蓮者，
悽惻蕩虛舟。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00824","source_record_id":"CN-NT-CAT-00428","alias_record_ids":["CN-NT-CAT-00428"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%B1%9F%E5%A4%9C_(%E6%88%B4%E4%B2%80)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '北地', NULL, '五言律詩', 5, '北地非吾土，
重逰信可哀。
鴉聲喧白骨，
馬足起黃埃。
野曠衰楊栁，
田荒變草萊。
江南風物好，
一望一徘徊。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00825","source_record_id":"CN-NT-CAT-00429","alias_record_ids":["CN-NT-CAT-00429"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%8C%97%E5%9C%B0_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '贈隱者', NULL, '五言律詩', 5, '東郊稱大隱，
耕鑿古風存。
水竹開三徑，
桃花自一村。
閒心餘白髪，
生事寄青尊。
愛爾幽棲處，
依稀似鹿門。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00826","source_record_id":"CN-NT-CAT-00430","alias_record_ids":["CN-NT-CAT-00430"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%B4%88%E9%9A%B1%E8%80%85_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '贈漁者', NULL, '五言律詩', 5, '不作風塵客，
生涯寄釣綸。
江湖孤棹逺，
煙雨一竿貧。
鼔枻同漁父，
藏名比富春。
武陵溪尚在，
為我問迷津。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00827","source_record_id":"CN-NT-CAT-00431","alias_record_ids":["CN-NT-CAT-00431"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%B4%88%E6%BC%81%E8%80%85_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '夢', NULL, '五言律詩', 5, '夢裏交驩者，
平生識面稀。
贈香疑賈女，
解珮似江妃。
錦水煙波濶，
巫山雲雨㣲。
蘧然驚醒處，
清淚滿羅衣。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00828","source_record_id":"CN-NT-CAT-00432","alias_record_ids":["CN-NT-CAT-00432"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%A4%A2_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5289-93ae', 0, '贈隱者', NULL, '五言律詩', 5, '夫子生東野，
經年不到城。
愛吟無俗趣，
貪畫得閒名。
荒徑侵山影，
虛堂出燕聲。
我慚爲謫吏，
泉石負幽情。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00829","source_record_id":"CN-NT-CAT-00433","alias_record_ids":["CN-NT-CAT-00433"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%B4%88%E9%9A%B1%E8%80%85_(%E5%8A%89%E9%8E%AE)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5433-60df-4fe1', 0, '贈隱者', NULL, '七言律詩', 7, '湖上居家住最幽，
簷牙倒影落滄洲。
詩成梅塢三更月，
酒醒蓮塘半夜秋。
移石爲添燒藥竈，
賣□因起讀書樓。
經年不入煙城去，
長倚欄乾看白鷗。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00830","source_record_id":"CN-NT-CAT-00434","alias_record_ids":["CN-NT-CAT-00434"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%B4%88%E9%9A%B1%E8%80%85_(%E5%90%B3%E6%83%9F%E4%BF%A1)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5b8b-81ea-905c', 0, '贈隱者', NULL, '七言律詩', 7, '或居巖谷或居廛，
未作天仙且地仙。
詩只半聯人寡和，
畫纔數筆世爭傳。
彈琴無譜自成曲，
賣藥資身不較錢。
或問先生今幾歲，
笑言誰解記生年。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00831","source_record_id":"CN-NT-CAT-00435","alias_record_ids":["CN-NT-CAT-00435"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%B4%88%E9%9A%B1%E8%80%85_(%E5%AE%8B%E8%87%AA%E9%81%9C)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-9678-904a', 0, '贈隱者二首', NULL, '五言古詩', 5, '疇昔從君處，
玄都太古壇。
月高旛影直，
霜重佩聲寒。
鶴駕三山近，
壺天萬里寬。
相逢初未省，
但認切雲冠。
力量超終古，
光明破積昏。
獨行寧有待，
妙用本忘言。
神定嬰兒戲，
丹靈豎子奔。
緒餘應不靳，
小出濟元元。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00832","source_record_id":"CN-NT-CAT-00436","alias_record_ids":["CN-NT-CAT-00436"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%B4%88%E9%9A%B1%E8%80%85%E4%BA%8C%E9%A6%96_(%E9%99%B8%E6%B8%B8)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-6b50-967d-4fee', 0, '贈隱者', NULL, '七言律詩', 7, '五嶽嵩當天地中，
聞君仍在最高峯。
山藏六月陰崖雪，
潭養千年蛻骨龍。
物外自應多至樂，
人間何事忽相逢。
飲罷飄然不辭決，
孤雲飛去杳無蹤。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00833","source_record_id":"CN-NT-CAT-00437","alias_record_ids":["CN-NT-CAT-00437"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%B4%88%E9%9A%B1%E8%80%85_(%E6%AD%90%E9%99%BD%E4%BF%AE)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5468-6587-749e', 0, '贈隱者', NULL, NULL, NULL, '袁柳大劉廿八，
長到先生卜肆邊。
便拜逸妻爲嫂氏，
更沽村酒作家筵。
山公馬在何須爾，
林屋丹成亦偶然。
獨此老身無藉頼，
爲他人擲卦爻錢。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00834","source_record_id":"CN-NT-CAT-00438","alias_record_ids":["CN-NT-CAT-00438"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%B4%88%E9%9A%B1%E8%80%85_(%E5%91%A8%E6%96%87%E7%92%9E)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-84b2-58fd-5bac', 0, '贈隱者', NULL, '五言律詩', 5, '自是山林僻，
何心與世踈。
土鐺三合米，
竹牖半床書。
月樹迷歸鶴，
沙泉數過魚。
無人覔巢許，
不必更深居。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00835","source_record_id":"CN-NT-CAT-00439","alias_record_ids":["CN-NT-CAT-00439"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%B4%88%E9%9A%B1%E8%80%85_(%E8%92%B2%E5%A3%BD%E5%AE%AC)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-yuan-5584-4f4f', 0, '贈隱者', NULL, '五言律詩', 5, '生無軒冕志，
老不釋漁竿。
對食慚周粟，
紉衣尚楚蘭。
江城猶雨雪，
花柳政春寒。
窮達皆由命，
初非行路難。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00836","source_record_id":"CN-NT-CAT-00440","alias_record_ids":["CN-NT-CAT-00440"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%B4%88%E9%9A%B1%E8%80%85_(%E5%96%84%E4%BD%8F)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-674e-5ef6-8208', 0, '贈隱者', NULL, '五言絶句', 5, '聽鐘尋野寺，
隔樹扣雲闗。
鶴臥琴窓靜，
樵歸碁局閑。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00837","source_record_id":"CN-NT-CAT-00441","alias_record_ids":["CN-NT-CAT-00441"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%B4%88%E9%9A%B1%E8%80%85_(%E6%9D%8E%E5%BB%B6%E8%88%88)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-85cd-667a', 0, '贈隱者', NULL, '五言律詩', 5, '風雲虵陣將，
山水鹿門居。
報國曾留劒，
歸田始讀書。
鴈秋湖水落，
蟬露栁條疎。
別夢關山逺，
松窻夜月虛。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00838","source_record_id":"CN-NT-CAT-00442","alias_record_ids":["CN-NT-CAT-00442"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%B4%88%E9%9A%B1%E8%80%85_(%E8%97%8D%E6%99%BA)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-738b-7acb-9053', 0, '贈隱者', NULL, '七言律詩', 7, '髙車大蓋意已踈，
鶡冠短褐墻東居。
丹經鋪案晩食後，
黃犢繫門春種餘。
負薪野店與沽酒，
學圃隣翁時乞蔬。
愚公亦近北山住，
為問險路今何如。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00839","source_record_id":"CN-NT-CAT-00443","alias_record_ids":["CN-NT-CAT-00443"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%B4%88%E9%9A%B1%E8%80%85_(%E7%8E%8B%E7%AB%8B%E9%81%93)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-912d-5b78-9187', 0, '贈隱者', NULL, NULL, NULL, '東林富麋鹿，
下有靜者廬。
垂蘿蔭簷隙，
落葉紛前除。
四壁何所有，
一瓢長晏如。
真性匪不足，
分顧自有餘。
黔婁時曳踵，
玄晏恒著書。
何必方外嘉客一水悵盈盈，
吟望寒蟾白。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00840","source_record_id":"CN-NT-CAT-00444","alias_record_ids":["CN-NT-CAT-00444"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%B4%88%E9%9A%B1%E8%80%85_(%E9%84%AD%E5%AD%B8%E9%86%87)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-76db-9cf4-4e16', 0, '贈隱者', NULL, '五言律詩', 5, '只在高霞外，
無人識去踪。
伴猿棲一室，
放鶴下孤峰。
丹灶雲中火，
青天夜半鐘。
平生長往意，
相望不相從。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00841","source_record_id":"CN-NT-CAT-00445","alias_record_ids":["CN-NT-CAT-00445"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%B4%88%E9%9A%B1%E8%80%85_(%E7%9B%9B%E9%B3%B4%E4%B8%96)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '山行', NULL, '五言律詩', 5, '脩竹夾籃輿，
嵐光欲染裾。
小橋流水急，
古路凍雲疎。
村屋乘冬結，
山田隔嵗鋤。
空林聞犬吠，
不異武陵居。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00842","source_record_id":"CN-NT-CAT-00446","alias_record_ids":["CN-NT-CAT-00446"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%B1%B1%E8%A1%8C_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '放船', NULL, '五言律詩', 5, '孤舟廻亂石，
流水響潺湲。
漁網蒹葭外，
人煙竹栢間。
斷雲迷晚渚，
殘照下秋山。
逺寺昏鐘起，
樵歌出谷還。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00843","source_record_id":"CN-NT-CAT-00447","alias_record_ids":["CN-NT-CAT-00447"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%94%BE%E8%88%B9_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-9678-904a', 0, '夜行', NULL, NULL, NULL, '路長憂炬盡，
馬弱畏泥深。
腸斷猿啼樹，
魂驚鬼嘯林。
艱危窮自慣，
寒苦老難禁。
回首金牛道，
加鞭負壯心。
紅藤拄杖扶衰病，
村北村南破夜行。
閑繞長堤逐螢火，
戲臨荒沼問鼃聲。
倦逰但有笭箵興，
久客真諳褦襶情。
安得故人同一醉，
三更城上看河傾。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00844","source_record_id":"CN-NT-CAT-00448","alias_record_ids":["CN-NT-CAT-00448"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%A4%9C%E8%A1%8C_(%E9%99%B8%E6%B8%B8)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-6641-6c96-4e4b', 0, '夜行', NULL, '七言絶句', 7, '老去功名意轉疏，
獨騎瘦馬取長途。
孤村到曉猶燈火，
知有人家夜讀書。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00845","source_record_id":"CN-NT-CAT-00449","alias_record_ids":["CN-NT-CAT-00449"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%A4%9C%E8%A1%8C_(%E6%99%81%E6%B2%96%E4%B9%8B)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-9b4f-5141-4e2d', 0, '去婦詞三首', NULL, '七言古詩', 7, '半遮紅粉蹙雙眉，
一片離心行路知。
憑為語郎休望妾，
妾歸猶似未歸時。
雲雨陽臺舊路迷，
千山明月照人啼。
背風縱作孤飛翼，
索勝金籠裏面棲。
落花飛絮共悠悠，
怕入東風燕子樓。
為看武陵源裏水，
斷腸東去不西流。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00846","source_record_id":"CN-NT-CAT-00450","alias_record_ids":["CN-NT-CAT-00450"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%8E%BB%E5%A9%A6%E8%A9%9E%E4%B8%89%E9%A6%96_(%E9%AD%8F%E5%85%81%E4%B8%AD)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-80e1-594e', 0, '去婦詞三首', NULL, NULL, NULL, '出戶心悄悄，
中情向誰道。
吞聲不敢啼，
又恐傍人笑。
妾有嫁時鏡，
請郎留自照。
鏡裏見新人，
還思舊人貌。
東山生兔絲，
西山生蒺藜。
二物不相偶，
美惡人自知。
妾有堂上姑，
妾有懐中兒。
生兒未及長，
姑老將何依。
妾今別夫去，
裴迴向何處。
他日黃泉相見時，
墓前莫種相思樹。
妾去何足惜，
妾留不自安。
高堂有老姑，
孰知飢與寒。
妾昔念有家，
妾今如風花。
何如千尺松，
而不附女蘿。
哀哀別姑去，
淚下不能語。
姑若念妾時，
看取牀頭女。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00847","source_record_id":"CN-NT-CAT-00451","alias_record_ids":["CN-NT-CAT-00451"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%8E%BB%E5%A9%A6%E8%A9%9E%E4%B8%89%E9%A6%96_(%E8%83%A1%E5%A5%8E)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-9b4f-5141-4e2d', 0, '詠竹', NULL, '五言絶句', 5, '借問數根竹，
㡬時能長成。
憑將截作管，
吹出鳯凰聲。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00848","source_record_id":"CN-NT-CAT-00452","alias_record_ids":["CN-NT-CAT-00452"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A0%E7%AB%B9_(%E9%AD%8F%E5%85%81%E4%B8%AD)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-9b4f-5141-4e2d', 0, '夜行', NULL, '五言絶句', 5, '一片泥滑滑，
縱横荆棘樹。
月暗少人行，
前村不知路。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00849","source_record_id":"CN-NT-CAT-00453","alias_record_ids":["CN-NT-CAT-00453"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%A4%9C%E8%A1%8C_(%E9%AD%8F%E5%85%81%E4%B8%AD)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-4ef2-4e26', 0, '詠竹', NULL, '五言律詩', 5, '自結高人伴，
雅無俗士緣。
驅之傍城市，
勁節非所便。
未論傲霜雪，
試欲藏風煙。
願留舊青眼，
歲晚相周旋。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00850","source_record_id":"CN-NT-CAT-00454","alias_record_ids":["CN-NT-CAT-00454"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A0%E7%AB%B9_(%E4%BB%B2%E5%B9%B6)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5289-624d-90b5', 0, '詠竹', NULL, '七言絶句', 7, '護惜龍孫意正勤，
風漪誰愛織成紋。
林中莫著山王輩，
擬向他時詠五君。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00851","source_record_id":"CN-NT-CAT-00455","alias_record_ids":["CN-NT-CAT-00455"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A0%E7%AB%B9_(%E5%8A%89%E6%89%8D%E9%82%B5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5b8b-5ea0', 0, '詠竹', NULL, '七言絶句', 7, '嵇阮生平憶共遊，
此君高節最凌秋。
兒童少作並門騎，
千畝留封渭水侯。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00852","source_record_id":"CN-NT-CAT-00456","alias_record_ids":["CN-NT-CAT-00456"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A0%E7%AB%B9_(%E5%AE%8B%E5%BA%A0)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-674e-89af', 0, '詠竹', NULL, '五言絶句', 5, '外邊雖節目，
內裏卻空虛。
從來汗流浹，
只為寫經書。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00853","source_record_id":"CN-NT-CAT-00457","alias_record_ids":["CN-NT-CAT-00457"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A0%E7%AB%B9_(%E6%9D%8E%E8%A6%AF)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-8607-8f4d', 0, '詠竹二首', NULL, '五言古詩', 5, '湖濱宜草木，
修竹可三尋。
廛居多野思，
移種近牆陰。
及爾迷未醒，
方予熱正侵。
無嫌不逮本，
地薄肯成林。
南鄰竹甚茂，
門巷不容賓。
懸印君當往，
囊金我患貧。
翠旌稍亂起，
犀角筍初勻。
不惜圖書賣，
端來作主人。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00854","source_record_id":"CN-NT-CAT-00458","alias_record_ids":["CN-NT-CAT-00458"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A0%E7%AB%B9%E4%BA%8C%E9%A6%96_(%E8%98%87%E8%BD%8D)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-9112-6d69', 0, '詠竹', NULL, NULL, NULL, '聲泠泠，
影矗矗。
霜雪難侵，
塵埃莫瀆。
梢雲齊老松，
帶日映寒菊。
籜置頂上高冠，
葉成樽中美祿。
行看威鳳飽相從，
不但子猷情最熟。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00855","source_record_id":"CN-NT-CAT-00459","alias_record_ids":["CN-NT-CAT-00459"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A0%E7%AB%B9_(%E9%84%92%E6%B5%A9)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-5ead-7b60', 0, '詠竹', NULL, '七言律詩', 7, '不論臺閣與山林，
愛爾豈惟千畝陰。
未出土時先有節，
便凌雲去也無心。
葛陂始與龍俱化，
嶰谷聊同鳳一吟。
月朗風清良夜永，
可憐王子獨知音。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00856","source_record_id":"CN-NT-CAT-00460","alias_record_ids":["CN-NT-CAT-00460"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A0%E7%AB%B9_(%E5%BE%90%E5%BA%AD%E7%AD%A0)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-8881-71ee', 0, '詠竹二首', NULL, '五言古詩', 5, '去年種蒼玉，
今歲抽華簪。
初萌節已具，
欲奮力未任。
雷風驅急雨，
滂沱三日霖。
籜龍不許蟄，
倏起騰深林。
遶徑初戢戢，
穿籬俄森森。
吾觀植物性，
漸長歲月深。
此君獨超軼，
生來氣駸駸。
偉哉歲寒種，
有此特達心。
大勇久不作，
進尺退復尋。
對此發幽興，
作詩因自箴。
野性與俗違，
澹然都無營。
窓前水蒼玉，
未能獨忘情。
對之三伏中，
爽氣高秋橫。
數竿亦已好，
況此繁陰成。
中虛洞無物，
節勁老更清。
霜雪自凌厲，
柯葉長敷榮。
物意有相合，
人心原自明。
僻居寡朋儕，
命汝爲友生。
雖無切磋語，
而有清越聲。
入耳久亦佳，
此意不可名。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00857","source_record_id":"CN-NT-CAT-00461","alias_record_ids":["CN-NT-CAT-00461"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A0%E7%AB%B9%E4%BA%8C%E9%A6%96_(%E8%A2%81%E7%87%AE)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-8881-71ee', 0, '詠竹', NULL, '七言絶句', 7, '此君林下靜無塵，
苗裔生來便逸羣。
頭角嶄然圓玉峙，
養成直節要凌雲。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00858","source_record_id":"CN-NT-CAT-00462","alias_record_ids":["CN-NT-CAT-00462"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A0%E7%AB%B9_(%E8%A2%81%E7%87%AE)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '贈張少府', NULL, '五言古詩', 5, '戀越終辭楚，
幽棲似鹿門。
煙霞長作侶，
車馬不聞喧。
世事惟髙枕，
生涯只灌園。
自耽泉石趣，
豈是學桃源。
黒髪棄軒冕，
歸畊南畆田。
不飛雲外舄，
時挂杖頭錢。
野性耽丘壑，
幽居逺市㕓。
中峰髙隱處，
長抱白雲眠。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00859","source_record_id":"CN-NT-CAT-00463","alias_record_ids":["CN-NT-CAT-00463"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%B4%88%E5%BC%B5%E5%B0%91%E5%BA%9C_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '紀事', NULL, '七言律詩', 7, '欃槍夜望射天弧，
邊計年來困輓輸。
萬里君門誰伏闕，
四郊皇店盡徴租。
虎賁宿將多凋謝，
烏合新兵屢譟呼。
時事艱危堪涕淚，
太平能到白頭無。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00860","source_record_id":"CN-NT-CAT-00464","alias_record_ids":["CN-NT-CAT-00464"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%B4%80%E4%BA%8B_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '自題小像', NULL, '七言律詩', 7, '展巻徒為老大悲，
形容將槁鬢將絲。
有時憤世空饒舌，
何處談詩不解頥。
足為無車行路健，
心因多累記書遲。
自知瘦骨宜貧賤，
莫怨人間只相皮。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00861","source_record_id":"CN-NT-CAT-00465","alias_record_ids":["CN-NT-CAT-00465"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%87%AA%E9%A1%8C%E5%B0%8F%E5%83%8F_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '己亥元日', NULL, '七言律詩', 7, '燈燭燒殘見曙光，
傷情多為惜年芳。
無田更切三時望，
有閏翻添一月忙。
已分狂歌惟草澤，
喜占春夢在池塘。
生憎稚子吹蘆管，
落盡梅花樹樹香。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00862","source_record_id":"CN-NT-CAT-00466","alias_record_ids":["CN-NT-CAT-00466"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%B7%B1%E4%BA%A5%E5%85%83%E6%97%A5_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '宮詞', NULL, '七言絶句', 7, '忽聽昭陽歌吹聲，
倚欄無語不勝情。
青青長信宮前草，
盡是鑾輿去後生。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00863","source_record_id":"CN-NT-CAT-00467","alias_record_ids":["CN-NT-CAT-00467"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%AE%AE%E8%A9%9E_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '宮詞二首', NULL, '七言律詩', 7, '翡翠衾寒曉漏遲，
博山香燼夜何其。
起來試揭珠簾看，
月在梨花第一枝。
莫怨鑾輿寵幸稀，
九重天子正宵衣。
雲和一曲閒清晝，
乳燕簾前作對飛。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00864","source_record_id":"CN-NT-CAT-00468","alias_record_ids":["CN-NT-CAT-00468"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%AE%AE%E8%A9%9E%E4%BA%8C%E9%A6%96_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '子夜歌', NULL, '五言古詩', 5, '牽絲嫌榦斷，
求藕恨泥深。
風吹菡萏折，
那得見蓮心。
籬外種都梁，
籬內種黃蘗。
雖是愛他香，
籬心苦難説。
芙蓉面可憐，
巻施心不死。
紅豆落深坑，
到底相思子。
錦帳覆雕牀，
銀鈎宛相向。
何時得見郎，
鈎起合歡帳。
亂却曲中心，
只為音徽誤。
郎來續舊絃，
知移何鴈柱。
採桑飼春繭，
葉稀蠶不飽。
一繭著歡衣，
與歡綿太少。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00865","source_record_id":"CN-NT-CAT-00469","alias_record_ids":["CN-NT-CAT-00469"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%AD%90%E5%A4%9C%E6%AD%8C_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '春歌', NULL, '五言絶句', 5, '羅衾與角枕，
展轉有誰憐。
妾身不如柳，
一日尚三眠。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00866","source_record_id":"CN-NT-CAT-00470","alias_record_ids":["CN-NT-CAT-00470"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%98%A5%E6%AD%8C_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '夏歌', NULL, '五言絶句', 5, '朱夏日何長，
采蓮向南浦。
妾心未剥蓮，
只在房中苦。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00867","source_record_id":"CN-NT-CAT-00471","alias_record_ids":["CN-NT-CAT-00471"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%A4%8F%E6%AD%8C_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '秋歌', NULL, '五言絶句', 5, '秋風吹江湄，
采芳寄相憶。
妾貌如芙蓉，
朝昏幾變色。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00868","source_record_id":"CN-NT-CAT-00472","alias_record_ids":["CN-NT-CAT-00472"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%A7%8B%E6%AD%8C_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '冬歌', NULL, '五言絶句', 5, '寒威動房帷，
悲風起羅薦。
妾恨井中氷，
結時君不見。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00869","source_record_id":"CN-NT-CAT-00473","alias_record_ids":["CN-NT-CAT-00473"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%86%AC%E6%AD%8C_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-8607-6cc2', 0, '春歌', NULL, '五言律詩', 5, '山人昨日到，
野棠連夜開。
啼鵑背山去，
流鶯度水來。
草長留款步，
花殘勸餘盃。
於焉早復暮，
行坐摘青梅。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00870","source_record_id":"CN-NT-CAT-00474","alias_record_ids":["CN-NT-CAT-00474"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%98%A5%E6%AD%8C_(%E8%98%87%E6%B3%82)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '少年行', NULL, '五言絶句', 5, '駿馬千金買，
銀鞍錦障泥。
未諳邊塞苦，
日日玉樓嘶。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00871","source_record_id":"CN-NT-CAT-00476","alias_record_ids":["CN-NT-CAT-00476"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%B0%91%E5%B9%B4%E8%A1%8C_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '怨詞', NULL, '五言絶句', 5, '一從閉深宮，
不復徴歌舞。
房中今夜聲，
是妾當年譜。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00872","source_record_id":"CN-NT-CAT-00477","alias_record_ids":["CN-NT-CAT-00477"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%80%A8%E8%A9%9E_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '昭君怨', NULL, '五言絶句', 5, '掩淚抛長袖，
從今歌舞稀。
肯將邊地月，
來照漢宮衣。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00873","source_record_id":"CN-NT-CAT-00478","alias_record_ids":["CN-NT-CAT-00478"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%98%AD%E5%90%9B%E6%80%A8_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '玉階怨', NULL, '五言絶句', 5, '殘露侵羅袂，
深宮漏正長。
螢光隨月影，
㸃㸃過昭陽。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00874","source_record_id":"CN-NT-CAT-00479","alias_record_ids":["CN-NT-CAT-00479"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%8E%89%E9%9A%8E%E6%80%A8_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '洞房曲', NULL, '五言絶句', 5, '檀郎意憨癡，
留燈照綽約。
郎嫌羅帳深，
儂嫌羅帳薄。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00875","source_record_id":"CN-NT-CAT-00480","alias_record_ids":["CN-NT-CAT-00480"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%B4%9E%E6%88%BF%E6%9B%B2_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '新嫁娘', NULL, '五言絶句', 5, '薄帷鑒明月，
宛轉憐嬌態。
郎來解羅襠，
含羞掩裙帶。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00876","source_record_id":"CN-NT-CAT-00481","alias_record_ids":["CN-NT-CAT-00481"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%96%B0%E5%AB%81%E5%A8%98_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-674e-5922-967d', 0, '夏歌', NULL, '五言律詩', 5, '積潦溢廣澤，
炎雲翳崇臺。
玉階履綦絶，
紫殿生莓苔。
螢流疏竹靜，
風動綌幃開。
佳期悵千里，
竟夕以徘徊。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00877","source_record_id":"CN-NT-CAT-00482","alias_record_ids":["CN-NT-CAT-00482"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%A4%8F%E6%AD%8C_(%E6%9D%8E%E5%A4%A2%E9%99%BD)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-516c-9f10', 0, '秋歌', NULL, '五言絶句', 5, '宵燭無餘光，
熠耀已在堂。
螢光能幾許，
焉照妾中腸。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00878","source_record_id":"CN-NT-CAT-00484","alias_record_ids":["CN-NT-CAT-00484"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%A7%8B%E6%AD%8C_(%E5%85%AC%E9%BC%90)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-65b9-5b5f-5f0f', 0, '秋歌', NULL, '五言律詩', 5, '取次小春天，
無繇花栁妍。
只憐窓下竹，
嫋嫋入雲煙。
贈郎青銅鏡，
持照肝膽清。
勿作地下霜，
見月始分明。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00879","source_record_id":"CN-NT-CAT-00485","alias_record_ids":["CN-NT-CAT-00485"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%A7%8B%E6%AD%8C_(%E6%96%B9%E5%AD%9F%E5%BC%8F)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-6c5f-6e90', 0, '洞房曲', NULL, '七言古詩', 7, '洞房窈窕春融融，
真珠簾幕圍香風。
木難光透芙蓉帳，
琥珀香浮玳瑁鍾。
錦帶蟠胸繡連理，
玉潤冰清兩相倚。
雲鬟斜壓鳳凰釵，
水沉香爇鴛鴦被。
房中琴瑟自和平，
不須楚調和秦箏。
留連歡樂長侵夜，
簾外月高花影橫。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00880","source_record_id":"CN-NT-CAT-00486","alias_record_ids":["CN-NT-CAT-00486"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%B4%9E%E6%88%BF%E6%9B%B2_(%E6%B1%9F%E6%BA%90)","review_status":"auto-extracted","review_reasons":[]}')
)
INSERT INTO poems (
  poet_id, poem_no, volume, title_zh, title_ko, category, meter, body_zh,
  is_notable, status, quality, review_memo
)
SELECT
  p.id,
  COALESCE(existing_poem_count.max_poem_no, 0)
    + row_number() OVER (PARTITION BY p.id ORDER BY ip.title_zh, ip.body_zh)::integer,
  ip.volume::integer, ip.title_zh, ip.title_ko, ip.category, ip.meter::integer, ip.body_zh,
  TRUE, ip.status, ip.quality, ip.review_memo
FROM input_poems ip
JOIN poets p ON p.title_id = ip.poet_slug
LEFT JOIN LATERAL (
  SELECT max(poem_no) AS max_poem_no
  FROM poems
  WHERE poet_id = p.id
) existing_poem_count ON TRUE
WHERE NOT EXISTS (
  SELECT 1
  FROM poems existing
  WHERE existing.poet_id = p.id
    AND existing.title_zh = ip.title_zh
    AND existing.body_zh = ip.body_zh
);

UPDATE poets p
SET poem_count = sub.cnt
FROM (
  SELECT poet_id, count(*)::integer AS cnt
  FROM poems
  WHERE poet_id IN (SELECT id FROM poets WHERE title_id IN ('candidate-ming-5f90-71a5', 'candidate-ming-5f90-4e2d-884c', 'candidate-ming-6234-9be8', 'candidate-yuan-6234-9c32', 'candidate-ming-6234-4c80', 'candidate-song-5289-93ae', 'candidate-song-5433-60df-4fe1', 'candidate-song-5b8b-81ea-905c', 'candidate-song-9678-904a', 'candidate-song-6b50-967d-4fee', 'candidate-song-5468-6587-749e', 'candidate-song-84b2-58fd-5bac', 'candidate-yuan-5584-4f4f', 'candidate-ming-674e-5ef6-8208', 'candidate-ming-85cd-667a', 'candidate-ming-738b-7acb-9053', 'candidate-ming-912d-5b78-9187', 'candidate-ming-76db-9cf4-4e16', 'candidate-song-6641-6c96-4e4b', 'candidate-ming-9b4f-5141-4e2d', 'candidate-ming-80e1-594e', 'candidate-song-4ef2-4e26', 'candidate-song-5289-624d-90b5', 'candidate-song-5b8b-5ea0', 'candidate-song-674e-89af', 'candidate-song-8607-8f4d', 'candidate-song-9112-6d69', 'candidate-song-5f90-5ead-7b60', 'candidate-song-8881-71ee', 'candidate-song-8607-6cc2', 'candidate-ming-674e-5922-967d', 'candidate-ming-516c-9f10', 'candidate-ming-65b9-5b5f-5f0f', 'candidate-ming-6c5f-6e90'))
  GROUP BY poet_id
) sub
WHERE p.id = sub.poet_id;

-- Review counts before COMMIT when applying manually:
SELECT quality, status, count(*) FROM poems WHERE quality IN ('cnnt-auto') GROUP BY quality, status ORDER BY quality, status;
SELECT p.era_period, count(pm.id) FROM poets p JOIN poems pm ON pm.poet_id = p.id WHERE p.title_id IN ('candidate-ming-5f90-71a5', 'candidate-ming-5f90-4e2d-884c', 'candidate-ming-6234-9be8', 'candidate-yuan-6234-9c32', 'candidate-ming-6234-4c80', 'candidate-song-5289-93ae', 'candidate-song-5433-60df-4fe1', 'candidate-song-5b8b-81ea-905c', 'candidate-song-9678-904a', 'candidate-song-6b50-967d-4fee', 'candidate-song-5468-6587-749e', 'candidate-song-84b2-58fd-5bac', 'candidate-yuan-5584-4f4f', 'candidate-ming-674e-5ef6-8208', 'candidate-ming-85cd-667a', 'candidate-ming-738b-7acb-9053', 'candidate-ming-912d-5b78-9187', 'candidate-ming-76db-9cf4-4e16', 'candidate-song-6641-6c96-4e4b', 'candidate-ming-9b4f-5141-4e2d', 'candidate-ming-80e1-594e', 'candidate-song-4ef2-4e26', 'candidate-song-5289-624d-90b5', 'candidate-song-5b8b-5ea0', 'candidate-song-674e-89af', 'candidate-song-8607-8f4d', 'candidate-song-9112-6d69', 'candidate-song-5f90-5ead-7b60', 'candidate-song-8881-71ee', 'candidate-song-8607-6cc2', 'candidate-ming-674e-5922-967d', 'candidate-ming-516c-9f10', 'candidate-ming-65b9-5b5f-5f0f', 'candidate-ming-6c5f-6e90') GROUP BY p.era_period ORDER BY p.era_period;

ROLLBACK;
-- COMMIT;
