-- Generated by scripts/build_cn_translation_pipeline_staging.mjs
-- Part: 7/13
-- Purpose: stage CN pre-Tang and Song/Yuan/Ming poems into the JDS translation pipeline.
-- Translator decision: JDS backend=gemini model=gemini-2.5-flash-lite prompt=pipeline/translate/prompts/v5_full.txt.
-- Safety: inserts only missing poet slug + title_zh + body_zh rows. Default ending is ROLLBACK.

BEGIN;

WITH input_poets(slug, name_zh, name_ko, life_raw, era_period, country) AS (
  VALUES
    ('candidate-song-7a0b-9865', '程顥', NULL, NULL, '宋', 'CN'),
    ('candidate-song-694a-6a38', '楊樸', NULL, NULL, '宋', 'CN'),
    ('candidate-song-8607-8efe', '蘇軾', NULL, NULL, '宋', 'CN'),
    ('candidate-song-738b-6dc7', '王淇', NULL, NULL, '宋', 'CN'),
    ('candidate-song-767d-7389-87fe', '白玉蟾', NULL, NULL, '宋', 'CN'),
    ('candidate-song-5442-5927-81e8', '呂大臨', NULL, NULL, '宋', 'CN'),
    ('candidate-song-694a-842c-91cc', '楊萬里', NULL, NULL, '宋', 'CN'),
    ('candidate-song-6731-6dd1-771f', '朱淑真', NULL, NULL, '宋', 'CN'),
    ('candidate-song-738b-5b89-77f3', '王安石', NULL, NULL, '宋', 'CN'),
    ('candidate-song-8303-6210-5927', '范成大', NULL, NULL, '宋', 'CN'),
    ('candidate-ming-5f90-968e', '徐階', NULL, NULL, '明', 'CN'),
    ('candidate-song-6b66-884d', '武衍', NULL, NULL, '宋', 'CN'),
    ('candidate-ming-6731-4e4b-745c', '朱之瑜', NULL, NULL, '明', 'CN'),
    ('candidate-ming-590f-5b8c-6df3', '夏完淳', NULL, NULL, '明', 'CN'),
    ('candidate-song-5b8b-b7-9673-8944', '宋·陳襄', NULL, NULL, '宋', 'CN'),
    ('candidate-song-9673-8944', '陳襄', NULL, NULL, '宋', 'CN'),
    ('candidate-song-738b-742a', '王琪', NULL, NULL, '宋', 'CN'),
    ('candidate-ming-5289-9438', '劉鐸', NULL, NULL, '明', 'CN'),
    ('candidate-ming-5289-6dd1', '劉淑', NULL, NULL, '明', 'CN'),
    ('candidate-ming-738b-7aef-6dd1', '王端淑', NULL, NULL, '明', 'CN'),
    ('candidate-ming-5468-74ca', '周瓊', NULL, NULL, '明', 'CN'),
    ('candidate-ming-5433-742a', '吳琪', NULL, NULL, '明', 'CN'),
    ('candidate-ming-8881-5f64-82b3', '袁彤芳', NULL, NULL, '明', 'CN'),
    ('candidate-song-9ec3-5ead-5805', '黃庭堅', NULL, NULL, '宋', 'CN'),
    ('candidate-song-7fc1-5377', '翁卷', NULL, NULL, '宋', 'CN'),
    ('candidate-song-8d99-5e2b-79c0', '趙師秀', NULL, NULL, '宋', 'CN'),
    ('candidate-song-5f90-7167', '徐照', NULL, NULL, '宋', 'CN')
)
INSERT INTO poets (title_id, name_zh, name_ko, life_raw, era_period, poem_count)
SELECT slug, name_zh, name_ko, life_raw, era_period, 0
FROM input_poets
ON CONFLICT (title_id) DO UPDATE SET
  name_zh = EXCLUDED.name_zh,
  name_ko = COALESCE(EXCLUDED.name_ko, poets.name_ko),
  life_raw = COALESCE(EXCLUDED.life_raw, poets.life_raw),
  era_period = EXCLUDED.era_period;

WITH input_poems(poet_slug, volume, title_zh, title_ko, category, meter, body_zh, status, quality, review_memo) AS (
  VALUES
    ('candidate-song-7a0b-9865', 0, '秋月', NULL, '七言絶句', 7, '清溪流過碧山頭
空水澄鮮一色秋
隔斷紅塵三十里
白雲紅葉雨悠悠', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00481","source_record_id":"CN-NT-CAT-00050","alias_record_ids":["CN-NT-CAT-00050"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%A7%8B%E6%9C%88_(%E7%A8%8B%E9%A1%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-694a-6a38', 0, '七夕', NULL, '七言絶句', 7, '未會牽牛意若何
須邀織女弄金梭
年年乞與人間巧
不道人間巧幾多', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00482","source_record_id":"CN-NT-CAT-00051","alias_record_ids":["CN-NT-CAT-00051"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E4%B8%83%E5%A4%95_(%E6%A5%8A%E6%A8%B8)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-8607-8efe', 0, '中秋月', NULL, '七言絶句', 7, '暮雲收盡溢清寒，
銀漢無聲轉玉盤。
此生此夜不長好，
明月明年何處看。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00483","source_record_id":"CN-NT-CAT-00052","alias_record_ids":["CN-NT-CAT-00052"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E4%B8%AD%E7%A7%8B%E6%9C%88_(%E8%98%87%E8%BB%BE)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-738b-6dc7', 0, '梅', NULL, '七言絶句', 7, '不受塵埃半點侵
竹籬茅舍自甘心
只因誤識林和靖
惹得詩人說到今', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00484","source_record_id":"CN-NT-CAT-00053","alias_record_ids":["CN-NT-CAT-00053"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%A2%85_(%E7%8E%8B%E6%B7%87)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-767d-7389-87fe', 0, '早春', NULL, '七言絶句', 7, '南枝纔放兩三花
雪裏吟香弄粉些
淡淡著煙濃著月
深深籠水淺籠沙', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00485","source_record_id":"CN-NT-CAT-00054","alias_record_ids":["CN-NT-CAT-00054"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%97%A9%E6%98%A5_(%E7%99%BD%E7%8E%89%E8%9F%BE)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5442-5927-81e8', 0, '禮', NULL, '七言絶句', 7, '禮儀三百復三千，
酬酢天機理必然。
寒即加衣饑即食，
孰爲末後孰爲先。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00486","source_record_id":"CN-NT-CAT-00056","alias_record_ids":["CN-NT-CAT-00056"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%A6%AE%EF%BC%88%E5%91%82%E5%A4%A7%E8%87%A8%EF%BC%89","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-694a-842c-91cc', 0, '野菊', NULL, '七言律詩', 7, '未與騷人當糗糧，
況隨流俗作重陽。
政緣在野有幽色，
肯爲無人减妙香。
已晚相逢半山碧，
便忙也折一枝黃。
花應冷笑東籬族，
猶向陶翁覓寵光。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00487","source_record_id":"CN-NT-CAT-00057","alias_record_ids":["CN-NT-CAT-00057"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%87%8E%E8%8F%8A_(%E6%A5%8A%E8%90%AC%E9%87%8C)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-6731-6dd1-771f', 0, '牡丹', NULL, '七言絶句', 7, '嬌嬈萬態呈殊芳，
花品名中佔得王，
莫把傾城比顏色，
從來家國為伊亡。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00488","source_record_id":"CN-NT-CAT-00058","alias_record_ids":["CN-NT-CAT-00058"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%89%A1%E4%B8%B9_(%E6%9C%B1%E6%B7%91%E7%9C%9F)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-738b-5b89-77f3', 0, '詠風', NULL, '五言古詩', 5, '風從北海起，
至此南海上。
问風來何事，
去復欲何向。
谁遣汝而號，
谁應汝而唱。
汝於何時息，
汝作無乃妄。
風初無一言，
试以问雲將。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00489","source_record_id":"CN-NT-CAT-00059","alias_record_ids":["CN-NT-CAT-00059"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A0%E9%A2%A8_(%E7%8E%8B%E5%AE%89%E7%9F%B3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-8607-8efe', 0, '花影', NULL, '七言絶句', 7, '重重疊疊上瑤臺
幾度呼童掃不開
剛被太陽收拾去
卻教明月送將來', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00490","source_record_id":"CN-NT-CAT-00060","alias_record_ids":["CN-NT-CAT-00060"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%8A%B1%E5%BD%B1_(%E8%98%87%E8%BB%BE)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-8303-6210-5927', 0, '曉起', NULL, NULL, NULL, '簾額繡波蕩漾，
燭盤紅淚闌乾。
夢裏五更風急，
愁邊一半春殘。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00491","source_record_id":"CN-NT-CAT-00061","alias_record_ids":["CN-NT-CAT-00061"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%9B%89%E8%B5%B7(%E8%8C%83%E6%88%90%E5%A4%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-8303-6210-5927', 0, '道中', NULL, '五言律詩', 5, '月冷吟蛩草，
湖平宿鷺沙。
客愁無錦字，
鄉信有燈花。
蹤跡隨風葉，
程途犯鬥槎。
君看枝上鵲，
薄暮亦還家。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00492","source_record_id":"CN-NT-CAT-00062","alias_record_ids":["CN-NT-CAT-00062"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%81%93%E4%B8%AD(%E8%8C%83%E6%88%90%E5%A4%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-738b-5b89-77f3', 0, '暮春', NULL, '七言絶句', 7, '芙蕖的歷抽新葉，
苜蓿闌乾放晚花。
白下門東春已老，
莫嗔楊柳可藏鴉。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00493","source_record_id":"CN-NT-CAT-00063","alias_record_ids":["CN-NT-CAT-00063"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%9A%AE%E6%98%A5(%E7%8E%8B%E5%AE%89%E7%9F%B3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-968e', 0, '秋懷', NULL, '七言律詩', 7, '病夫生事只山林，
竹樹秋來幸鬱森。
花露滴枝晨細細，
洞雲垂地晝陰陰。
時移妙達循環理，
歲晏偏傷伏枕心。
夜漏漸長愁不寐，
更堪江渚拂清砧。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00494","source_record_id":"CN-NT-CAT-00064","alias_record_ids":["CN-NT-CAT-00064"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%A7%8B%E6%87%B7_(%E5%BE%90%E9%9A%8E)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-968e', 0, '中秋對月', NULL, '五言律詩', 5, '對月寡相恤，
停杯深抱愁。
人間別有夜，
天上本無秋。
漸促年華暮，
虛瞻霽色流。
瑁湖何日去，
吟笑逐沙鷗。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00495","source_record_id":"CN-NT-CAT-00065","alias_record_ids":["CN-NT-CAT-00065"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E4%B8%AD%E7%A7%8B%E5%B0%8D%E6%9C%88_(%E5%BE%90%E9%9A%8E)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-6b66-884d', 0, '宮詞', NULL, '七言絶句', 7, '梨花風動玉闌香，
春色沉沉鎖建章。
唯有落紅官不禁，
盡教飛舞出宮牆。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00496","source_record_id":"CN-NT-CAT-00066","alias_record_ids":["CN-NT-CAT-00066"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%AE%AE%E8%A9%9E_(%E6%AD%A6%E8%A1%8D)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-6731-4e4b-745c', 0, '漫興', NULL, '五言律詩', 5, '遠逐徐生跡，
移舟住別峰。
遺書搜孔壁，
仙路隔秦封。
流水去無盡，
故人何日逢？
鄉書經歲達，
離恨轉重重。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00497","source_record_id":"CN-NT-CAT-00067","alias_record_ids":["CN-NT-CAT-00067"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%BC%AB%E8%88%88_(%E6%9C%B1%E4%B9%8B%E7%91%9C)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-590f-5b8c-6df3', 0, '即事', NULL, '五言古詩', 5, '復楚情何極，
亡秦氣未平。
雄風清角勁，
落日大旗明。
縞素酬家國，
戈船決死生！
胡笳千古恨，
一片月臨城。
戰苦難酬國，
仇深敢憶家。
一身存漢臘，
滿目盡胡沙。
落月翻旗影，
清霜冷劍花。
六軍渾散盡，
半夜起悲笳。
一旅同仇誼，
三秋故主懷。
將星沉左輔，
卿月隱中台。
東閣塵賓幕，
西征愧賦才。
月明笳鼓切，
今夜為誰哀。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00498","source_record_id":"CN-NT-CAT-00068","alias_record_ids":["CN-NT-CAT-00068"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%8D%B3%E4%BA%8B_(%E5%A4%8F%E5%AE%8C%E6%B7%B3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-590f-5b8c-6df3', 0, '秋夜感懷', NULL, '五言律詩', 5, '登樓迷北望，
沙草沒寒汀。
月湧長江白，
雲連大海青。
征洪非故國，
橫笛起新亭。
無限悲歌意，
茫茫帝子靈。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00499","source_record_id":"CN-NT-CAT-00069","alias_record_ids":["CN-NT-CAT-00069"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%A7%8B%E5%A4%9C%E6%84%9F%E6%87%B7_(%E5%A4%8F%E5%AE%8C%E6%B7%B3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-590f-5b8c-6df3', 0, '精衛', NULL, '五言古詩', 5, '北風蕩天地，
有鳥鳴空林。
志長羽翼短，
銜石隨浮沈。
崇山日以高，
滄海日以深。
愧非補天匹，
延頸振哀音。
辛苦徒自力，
慷慨誰為心？
滔滔東逝波，
勞勞成古今。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00500","source_record_id":"CN-NT-CAT-00070","alias_record_ids":["CN-NT-CAT-00070"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%B2%BE%E8%A1%9B_(%E5%A4%8F%E5%AE%8C%E6%B7%B3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-590f-5b8c-6df3', 0, '絶句', NULL, '七言絶句', 7, '扁舟明月兩峰間，
千頃蘆花人未還；
縹緲蒼茫不可接，
白雲空翠洞庭山。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00501","source_record_id":"CN-NT-CAT-00071","alias_record_ids":["CN-NT-CAT-00071"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%B5%95%E5%8F%A5_(%E5%A4%8F%E5%AE%8C%E6%B7%B3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-590f-5b8c-6df3', 0, '易水歌', NULL, NULL, NULL, '白日蒼茫落易水，
悲風動地蕭條起。
荊卿入秦功不成，
遺恨驪山暮煙紫。
昔年此地別燕丹，
哀歌變徵風雨闌。
白虹翕翕貫燕市，
黃金台下陰雲寒。
袖中寶刀霜華重，
此事千秋竟成夢。
十三殺人徒爾為，
百二河山儼不動。
嗚呼，
荊卿磊落殊不倫，
漸離慷慨得其真！
長安無限屠刀肆，
猶有吹簫擊築人。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00502","source_record_id":"CN-NT-CAT-00072","alias_record_ids":["CN-NT-CAT-00072"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%98%93%E6%B0%B4%E6%AD%8C_(%E5%A4%8F%E5%AE%8C%E6%B7%B3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-590f-5b8c-6df3', 0, '採蓮曲', NULL, NULL, NULL, '江南兒女好容與，
蓮舟蕩漾隔花語。
為採同心枝，
青蛾素腕知儂許。
長相思，
暮儔侶。
巫山雲，
巴山雨。
沙鷗集，
輕風舉，
乘月歸來歌白紵。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00503","source_record_id":"CN-NT-CAT-00076","alias_record_ids":["CN-NT-CAT-00076"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%8E%A1%E8%93%AE%E6%9B%B2_(%E5%A4%8F%E5%AE%8C%E6%B7%B3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-590f-5b8c-6df3', 0, '觀濤', NULL, NULL, NULL, '大海出沒波滔滔，
魚龍銜日百丈高。
倏忽蒼茫天地合，
咫尺不辨神靈號。
江中小艇不敢渡，
浮雲漠漠隔江樹。
海女霓旌乍有無，
雷鼓填填屏翳怒。
靈冥冥青濛濛，
虛無四面浮芙蓉。
丹楓葉落碧波冷，
一上一下聲淙淙。
須臾風起水勢作，
天門乍開秋不落。
江妃歌舞流佩音，
金河錦湍光灼爍。
登高極望高翠迷，
皓然瀲灩長天低。
涵虛萬頃皆一色，
水面隱隱鮫人啼。
其中深淺不可測，
秋山遠映嵐光白。
龍鱗半掛倒青波，
潑潑鯉魚尾三尺。
嗚呼！
此水乃自滄溟來，
長江如練浮天垓。
雪花片片流不盡，
北風直到天津台。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00504","source_record_id":"CN-NT-CAT-00077","alias_record_ids":["CN-NT-CAT-00077"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%A7%80%E6%BF%A4_(%E5%A4%8F%E5%AE%8C%E6%B7%B3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-590f-5b8c-6df3', 0, '杜鵑行', NULL, '七言古詩', 7, '西川有鳥名杜鵑，
蜀山天子聲相連。
嗚呼三萬六千歲，
君臣舊禮誰能宣。
一身羈旅愁滿眼，
容顏憔悴呼蒼天。
悲鳴未終口流血，
慘淡遊魂竄其穴。
蒼鼠相攫古瓦間，
愁虎啼呼風觱發。
當年高坐深宮中，
左右紅顏共蹀躞。
至今寥落人世殊，
毛長羽短徒區區。
金支翠旗嗟已矣，
望帝魂歸今有無？', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00505","source_record_id":"CN-NT-CAT-00078","alias_record_ids":["CN-NT-CAT-00078"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%9D%9C%E9%B5%91%E8%A1%8C_(%E5%A4%8F%E5%AE%8C%E6%B7%B3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-590f-5b8c-6df3', 0, '野哭', NULL, NULL, NULL, '大河湯湯秦晉來，
荒荒百里見孤骸。
青犢長驅逐鹿塞，
狼煙竟上黃金台。
駟馬騤騤車業業，
日高鵝鸛不成列。
北國遙開雍畤雲，
西風吹落燕山月。
玄黃不辨天地間，
虎豹遼遼蹲九關。
鸞輅淒涼歸便殿，
龍髯奄​​忽墮西山。
庚庚旦旦十七祀，
郊壇翼翼今已矣。
六宮痛哭元妃，
長秋慘淡歸皇嗣。
某時死者曾幾人，
匍匐但稱歸順臣。
旌旄誰是田橫客，
冠蓋無非項伯倫。
唯有先朝一杜宇，
啼入東華門上樹。
望帝望帝何不歸，
千古君臣僅如許！', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00506","source_record_id":"CN-NT-CAT-00079","alias_record_ids":["CN-NT-CAT-00079"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%87%8E%E5%93%AD_(%E5%A4%8F%E5%AE%8C%E6%B7%B3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5b8b-b7-9673-8944', 0, '瀑布', NULL, NULL, NULL, '靈源寂寂何杳寞，
先天後天誰疏鑿。
疑是媧皇功教學法全，
漏泄銀河斜界落。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00507","source_record_id":"CN-NT-CAT-00080","alias_record_ids":["CN-NT-CAT-00080"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%80%91%E5%B8%83%EF%BC%88%E5%AE%8B%C2%B7%E9%99%B3%E8%A5%84%EF%BC%89","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-9673-8944', 0, '偶書', NULL, '七言絶句', 7, '朝居晦息與山鄰，
物理由來有屈伸。
獨把一心經萬事，
逍遙須養穀中神。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00508","source_record_id":"CN-NT-CAT-00081","alias_record_ids":["CN-NT-CAT-00081"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%81%B6%E6%9B%B8_(%E9%99%B3%E8%A5%84)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5b8b-b7-9673-8944', 0, '英宗皇帝挽詞二首', NULL, NULL, NULL, '其一
才武真賢主，
憂勤出至誠。
五年膺大統，
一旦享英名。
鳳駕乘霞遠，
龍樓繼日明。
永言配昭考，
陵寢卜周京。
其二
玉幾言猶在，
雲天去莫攀。
久長期享國，
咫尺忽違顏。
信默歸元子，
遺留暨百蠻。
孤臣方仗節，
無計哭橋山。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00509","source_record_id":"CN-NT-CAT-00082","alias_record_ids":["CN-NT-CAT-00082"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%8B%B1%E5%AE%97%E7%9A%87%E5%B8%9D%E6%8C%BD%E8%A9%9E%E4%BA%8C%E9%A6%96%EF%BC%88%E5%AE%8B%C2%B7%E9%99%B3%E8%A5%84%EF%BC%89","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5b8b-b7-9673-8944', 0, '喜雪', NULL, '五言古詩', 5, '有客何方來，
粲然遊我庭。
推戶出見之，
顏色如瑤英。
問之不吾語，
微風若聞聲。
曰予朔方士，
飲子南方名。
萬里不相識，
修塗一來經。
聞子官大府，
高車塵冥冥。
有言未嘗吐，
低頭斂光精。
西人趨向異，
念予孤蒙行。
我欲友其德，
顧己鴻毛輕。
予起謝不敏，
過辭非予聆。
感子虛白德，
來化純愚誠。
高風激萬世，
凜如伯夷清。
留子永今日，
願言報英瓊。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00510","source_record_id":"CN-NT-CAT-00083","alias_record_ids":["CN-NT-CAT-00083"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%96%9C%E9%9B%AA%EF%BC%88%E5%AE%8B%C2%B7%E9%99%B3%E8%A5%84%EF%BC%89","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5b8b-b7-9673-8944', 0, '英宗皇帝輓詞二首', NULL, NULL, NULL, '其一
才武真賢主，
憂勤出至誠。
五年膺大統，
一旦享英名。
鳳駕乘霞遠，
龍樓繼日明。
永言配昭考，
陵寢卜周京。
其二
玉幾言猶在，
雲天去莫攀。
久長期享國，
咫尺忽違顏。
信默歸元子，
遺留暨百蠻。
孤臣方仗節，
無計哭橋山。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00511","source_record_id":"CN-NT-CAT-00084","alias_record_ids":["CN-NT-CAT-00084"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%8B%B1%E5%AE%97%E7%9A%87%E5%B8%9D%E8%BC%93%E8%A9%9E%E4%BA%8C%E9%A6%96%EF%BC%88%E5%AE%8B%C2%B7%E9%99%B3%E8%A5%84%EF%BC%89","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-738b-742a', 0, '詠史', NULL, '五言律詩', 5, '水調隋宮曲，
當年亦九成。
哀音已亡國，
廢沼尚留名；
儀鳳終陳跡，
鳴蛙隻沸羹。
淒涼不可問，
落日下蕪城。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00512","source_record_id":"CN-NT-CAT-00085","alias_record_ids":["CN-NT-CAT-00085"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A0%E5%8F%B2_(%E7%8E%8B%E7%90%AA)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5289-9438', 0, '絶命詩', NULL, '七言律詩', 7, '大限年來五十三，
翻身跳出是非關。
魂魄先從三島去，
詩書悉付六丁擔。
無棺任憑魚腹葬，
有骨徒教野狗銜。
龍逢比乾歸泉下，
此去相逢面不慚。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00513","source_record_id":"CN-NT-CAT-00086","alias_record_ids":["CN-NT-CAT-00086"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%B5%95%E5%91%BD%E8%A9%A9_(%E5%8A%89%E9%90%B8)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5289-6dd1', 0, '秋怨', NULL, NULL, NULL, '憶前盟，
並肩訂三生。
琵琶幾曲春江夜，
長門今掩月華明。
憶前盟，
枉多情。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00514","source_record_id":"CN-NT-CAT-00087","alias_record_ids":["CN-NT-CAT-00087"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%A7%8B%E6%80%A8_(%E5%8A%89%E6%B7%91)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5289-6dd1', 0, '秋思', NULL, NULL, NULL, '悵秋颸，
雙鯉催歸期。
年年苦盼還衣錦，
漁陽鼙鼓息何時？
悵秋颸，
祇自知。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00515","source_record_id":"CN-NT-CAT-00088","alias_record_ids":["CN-NT-CAT-00088"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%A7%8B%E6%80%9D_(%E5%8A%89%E6%B7%91)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5289-6dd1', 0, '自遣', NULL, '七言律詩', 7, '報國酬親志未諧，
肯將孤憤委陰霾。
心非日月輪堪轉，
命比煙塵鏡裏揩。
戀佛機關龍伏遠，
辭家遇合蝎磨乖。
伸眉試拂青萍劍，
畫割江南搆小齋。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00516","source_record_id":"CN-NT-CAT-00089","alias_record_ids":["CN-NT-CAT-00089"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%87%AA%E9%81%A3_(%E5%8A%89%E6%B7%91)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-738b-7aef-6dd1', 0, '悲憤詩', NULL, '七言古詩', 7, '凌殘漢室滅衣冠，
社稷丘墟民力殫。
勒兵入寇稱可汗，
九州壯士死征鞍。
嬌紅逐馬聞者酸，
乾戈擾攘行路難。
予居陋地不求安，
葉聲颯颯水漫漫。
月催寒影到闌乾，
長吟漢史靜夜看。
思之興廢冷淚彈，
杜鵑啼徹三更殘。
何事男兒無肺肝，
利名切切在魚竿。
椎擊始皇身單弱，
謀雖不成心報韓。
天風借吹羶血乾，
徵賢深谷出幽蘭。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00517","source_record_id":"CN-NT-CAT-00091","alias_record_ids":["CN-NT-CAT-00091"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%82%B2%E6%86%A4%E8%A9%A9_(%E7%8E%8B%E7%AB%AF%E6%B7%91)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5468-74ca', 0, '感興', NULL, '七言律詩', 7, '屠龍未就且浮遊，
江澥飄零豈自由。
華髮似因多難短，
孤衷寧爲晚春愁。
私憐詠絮才偏拙，
雅慕凌雲志欲休。
碧草綠波無限意，
從今莫上最高樓。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00518","source_record_id":"CN-NT-CAT-00092","alias_record_ids":["CN-NT-CAT-00092"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%84%9F%E8%88%88_(%E5%91%A8%E7%93%8A)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5433-742a', 0, '村居', NULL, '七言律詩', 7, '貧家風物厭鉛華，
波影浮來盡落霞。
夢裡青山閒歲月，
鏡中人面想桃花。
秋鐙病後惟餘硯，
春水愁多未浣紗。
枕上片魂誰喚起，
夕陽煙樹幾歸鴉。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00519","source_record_id":"CN-NT-CAT-00093","alias_record_ids":["CN-NT-CAT-00093"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%9D%91%E5%B1%85_(%E5%90%B3%E7%90%AA)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5433-742a', 0, '感懷', NULL, '七言律詩', 7, '鶴煮琴焚事已賒，
不堪回首數年華。
愁來有句留殘葉，
夢去無人問落花。
鳥惜晚香窺檻鏡，
婢憐新病鎖窓紗。
柳枝剩有蘇台曲，
未審春風憶若耶。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00520","source_record_id":"CN-NT-CAT-00094","alias_record_ids":["CN-NT-CAT-00094"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%84%9F%E6%87%B7_(%E5%90%B3%E7%90%AA)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5433-742a', 0, '題畫', NULL, '七言古詩', 7, '江樹迷離鷗自浴，
江雲飄盡春山綠。
渡頭小艇賣魚歸，
月映斜扉滿籬竹。
讀書樓靜倚欄杆，
一望煙霞碧落寒。
奇幛插天藏古寺，
危泉懸壁露岩灘。
玉笙聲斷鶯啼處，
狼藉落花飛不去。
將身欲置畫圖間，
相與神仙覓往還。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00521","source_record_id":"CN-NT-CAT-00095","alias_record_ids":["CN-NT-CAT-00095"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%A1%8C%E7%95%AB_(%E5%90%B3%E7%90%AA)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-8881-5f64-82b3', 0, '九日', NULL, '五言律詩', 5, '玉露泣秋草，
金風彫晚渠。
白衣三徑少，
黃菊一籬疎。
病減登髙興，
愁無寄逺書。
遥知二三子，
相向正愁餘。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00522","source_record_id":"CN-NT-CAT-00096","alias_record_ids":["CN-NT-CAT-00096"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E4%B9%9D%E6%97%A5_(%E8%A2%81%E5%BD%A4%E8%8A%B3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-8881-5f64-82b3', 0, '坐月有懷', NULL, '五言律詩', 5, '月色太無賴，
窺窓一何明。
之子隔千里，
懷君思酒盟。
玉鑪煙篆裊，
銀漢夜縱橫。
坐看雙星隔，
應思長別情。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00523","source_record_id":"CN-NT-CAT-00097","alias_record_ids":["CN-NT-CAT-00097"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%9D%90%E6%9C%88%E6%9C%89%E6%87%B7_(%E8%A2%81%E5%BD%A4%E8%8A%B3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-8881-5f64-82b3', 0, '春日寫懷', NULL, '七言律詩', 7, '風暖月庭春日移，
紅英一夜盡芳枝。
身如遊子隔千里，
心獨思親十二時。
秦樓鳳去玉簫杳，
苕水鱗稀彩筆遲。
曾似呢喃雙燕子，
年年飛向畫梁窺。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00524","source_record_id":"CN-NT-CAT-00098","alias_record_ids":["CN-NT-CAT-00098"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%98%A5%E6%97%A5%E5%AF%AB%E6%87%B7_(%E8%A2%81%E5%BD%A4%E8%8A%B3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-8881-5f64-82b3', 0, '傷春', NULL, '七言律詩', 7, '東風拘束苦相禁，
花落鶯啼葉作陰。
無徑可通青足信，
有信空作白頭吟。
淒淒病骨侵肌瘦，
脈脈閒愁入夢深。
不信只看羅袖上，
斑斑點血遍芳襟。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00525","source_record_id":"CN-NT-CAT-00099","alias_record_ids":["CN-NT-CAT-00099"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%82%B7%E6%98%A5_(%E8%A2%81%E5%BD%A4%E8%8A%B3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-8881-5f64-82b3', 0, '遊山', NULL, '五言絶句', 5, '楓林葉墜紅，
荷沼波翻綠。
回首歸路遙，
雲山萬里曲。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00526","source_record_id":"CN-NT-CAT-00100","alias_record_ids":["CN-NT-CAT-00100"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%81%8A%E5%B1%B1_(%E8%A2%81%E5%BD%A4%E8%8A%B3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-8881-5f64-82b3', 0, '無題', NULL, '七言絶句', 7, '陳宮破鏡還重照，
弄玉瓊簫卻共吹。
何事彩雲飛鶴下，
年年不作一雙歸。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00527","source_record_id":"CN-NT-CAT-00101","alias_record_ids":["CN-NT-CAT-00101"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%84%A1%E9%A1%8C_(%E8%A2%81%E5%BD%A4%E8%8A%B3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-8881-5f64-82b3', 0, '宮詞', NULL, '七言絶句', 7, '楊柳初濃午夢長，
懶持紈扇學宮粧。
美人睡起思無賴，
惟有風吹菡苕香。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00528","source_record_id":"CN-NT-CAT-00102","alias_record_ids":["CN-NT-CAT-00102"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%AE%AE%E8%A9%9E_(%E8%A2%81%E5%BD%A4%E8%8A%B3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-8881-5f64-82b3', 0, '落花', NULL, '七言古詩', 7, '粉褪紅消黯自思，
臨風不敢怨春枝。
一辭並蒂分飛後，
誰惜殷勤未放時。
落紅點點綴蒼苔，
何事音書久不來。
病起最嫌風入幕，
侍兒莫把錦屏開。
羅袂春寒怯曉粧，
繡紅微倦倚雕床。
閒愁空攬一春恨，
羞對呢喃宿畫梁。
蝶夢初醒乍午風，
憑欄極目望飛鴻。
小牕坐久情無奈，
惟有落花滿地紅。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00529","source_record_id":"CN-NT-CAT-00103","alias_record_ids":["CN-NT-CAT-00103"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%90%BD%E8%8A%B1_(%E8%A2%81%E5%BD%A4%E8%8A%B3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-8881-5f64-82b3', 0, '三月三日', NULL, '七言古詩', 7, '韶光九十春將半，
遙憶金閭思欲迷。
一水似添千里隔，
滿庭飛絮亂鶯啼。
桃花落盡柳煙濃，
病裏愁閒午夜鐘。
別後滿懷離索恨，
一起收拾錦箋中。
禁煙三日清明雨，
寒食幾番花信風。
遙憶故人應寂寞，
小欄斜倚怨飛紅。
楊枝飛絮草煙萋，
黃鳥間關只亂啼。
夢裏不知身是蝶，
時時飛過大江西。
多情常是因花瘦，
獨坐閒吟晝掩扉。
好句似從天外得，
春心時在夢中歸。
木蘭花發最繁枝，
錦字何繇寄我思。
一自武陵人別後，
至今只有夢相期。
彩筆漫題幽曲怨，
錦箋難寄辟寒香。
故人為我應憔悴，
我為思君泣夢長。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00530","source_record_id":"CN-NT-CAT-00104","alias_record_ids":["CN-NT-CAT-00104"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E4%B8%89%E6%9C%88%E4%B8%89%E6%97%A5_(%E8%A2%81%E5%BD%A4%E8%8A%B3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-9ec3-5ead-5805', 0, '秋思', NULL, '七言律詩', 7, '椎牛作社酒新篘，
扶老將兒嬉隴頭。
木落人家見雞犬，
曉寒溪口在汀洲。
無功可佩水蒼玉，
卒歲空思狐白裘。
身到楚傖非屈宋，
顧慙疏懶作悲秋。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00531","source_record_id":"CN-NT-CAT-00106","alias_record_ids":["CN-NT-CAT-00106"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%A7%8B%E6%80%9D_(%E9%BB%83%E5%BA%AD%E5%A0%85)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-7fc1-5377', 0, '春雪', NULL, '五言律詩', 5, '疑是梨花發，
滿園驚乍看。
不能爲臘瑞，
空自作春寒。
遠遁營巢鵲，
深埋吐葉蘭。
從教豔陽曬，
流去作波瀾。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00532","source_record_id":"CN-NT-CAT-00107","alias_record_ids":["CN-NT-CAT-00107"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%98%A5%E9%9B%AA_(%E7%BF%81%E5%8D%B7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-7fc1-5377', 0, '即事', NULL, '五言律詩', 5, '省飲不成醉，
牢愁將奈何。
晚煙雲半雜，
春雪雨相和。
巷濕人行少，
空寒雁叫多。
憑欄思無極，
懷古謾悲歌。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00533","source_record_id":"CN-NT-CAT-00108","alias_record_ids":["CN-NT-CAT-00108"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%8D%B3%E4%BA%8B_(%E7%BF%81%E5%8D%B7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-7fc1-5377', 0, '喜蔣德瞻還里', NULL, NULL, NULL, '爲官三載餘，
所得是清虛。
學就金丹法，
修成玉檢書。
乍歸人客西巖集作朋舊。
久出竹林疎。
怪我吟髭白，
相歡原作還，
據西巖集改。
相見初。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00534","source_record_id":"CN-NT-CAT-00109","alias_record_ids":["CN-NT-CAT-00109"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%96%9C%E8%94%A3%E5%BE%B7%E7%9E%BB%E9%82%84%E9%87%8C_(%E7%BF%81%E5%8D%B7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-7fc1-5377', 0, '句', NULL, NULL, NULL, '留客看花賦詩坐。
獨自卷簾樓上望。
梅花處處妍。
官歷春猶淺。
空把月中枝。
以上宋李龏《梅花衲》
分石同僧坐，
看松見鶴來（遊寺）。
宋張端義《貴耳集》', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00535","source_record_id":"CN-NT-CAT-00111","alias_record_ids":["CN-NT-CAT-00111"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%8F%A5_(%E7%BF%81%E5%8D%B7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-7fc1-5377', 0, '題竹', NULL, '五言律詩', 5, '偶種得成陰，
翛翛過別林。
月寒雙鴿睡，
風靜一蟬吟。
映地添苔碧，
臨池覺水深。
貧居來客少，
頼爾慰人心。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00536","source_record_id":"CN-NT-CAT-00112","alias_record_ids":["CN-NT-CAT-00112"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%A1%8C%E7%AB%B9_(%E7%BF%81%E5%8D%B7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-7fc1-5377', 0, '能仁寺', NULL, NULL, NULL, '芙蓉峰入天，
寺與此峰連。
得見是冬月，
要來從昔年。
寒潭盛西巖集作摇。
古木帶厨煙。
偶值高僧出，
禪牀坐默然。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00537","source_record_id":"CN-NT-CAT-00114","alias_record_ids":["CN-NT-CAT-00114"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%83%BD%E4%BB%81%E5%AF%BA_(%E7%BF%81%E5%8D%B7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-7fc1-5377', 0, '宿寺', NULL, NULL, NULL, '一宿此禪宮，
身同落西巖集作薙。
深窓難得月，
老屋易生風。
燈冷紗光淡，
香殘印篆空。
獨憐吟思苦，
妨却夢西東。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00538","source_record_id":"CN-NT-CAT-00115","alias_record_ids":["CN-NT-CAT-00115"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%AE%BF%E5%AF%BA_(%E7%BF%81%E5%8D%B7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-7fc1-5377', 0, '贈九華李丹士', NULL, '五言律詩', 5, '行遍東南地，
曾看江水源。
袖藏勾漏藥，
身是老君孫。
去住雲相似，
枯榮事不論。
九華峰最碧，
相對舊柴門。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00539","source_record_id":"CN-NT-CAT-00116","alias_record_ids":["CN-NT-CAT-00116"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%B4%88%E4%B9%9D%E8%8F%AF%E6%9D%8E%E4%B8%B9%E5%A3%AB_(%E7%BF%81%E5%8D%B7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-7fc1-5377', 0, '夢回', NULL, '五言律詩', 5, '一枕莊生夢，
囘來日未衙。
自煎砂井水，
更煮嶽僧茶。
宿雨消花氣，
驚雷長荻芽。
故山滄海角，
遥念在春華。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00540","source_record_id":"CN-NT-CAT-00118","alias_record_ids":["CN-NT-CAT-00118"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%A4%A2%E5%9B%9E_(%E7%BF%81%E5%8D%B7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-7fc1-5377', 0, '閩中秋思', NULL, '五言律詩', 5, '客愁無定迹，
幾處冒風埃。
逢得家鄉便，
憑將信息囘。
海煙蠻樹濕，
秋雨瘴花開。
舊日越王國，
吾今身再來。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00541","source_record_id":"CN-NT-CAT-00120","alias_record_ids":["CN-NT-CAT-00120"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%96%A9%E4%B8%AD%E7%A7%8B%E6%80%9D_(%E7%BF%81%E5%8D%B7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-7fc1-5377', 0, '山中', NULL, '七言律詩', 7, '山中凡事幸相宜，
第一紅塵免上衣。
尋藥每同丹客去，
拾薪多趁牧兒歸。
鳴泉潄石寒蒲潔，
宿霧蒸泥早蕨肥。
不奈鄰峰學禪伴，
時時來此叩巖扉。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00542","source_record_id":"CN-NT-CAT-00122","alias_record_ids":["CN-NT-CAT-00122"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%B1%B1%E4%B8%AD_(%E7%BF%81%E5%8D%B7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-7fc1-5377', 0, '尋僧', NULL, NULL, NULL, '秋凈日暉暉，
間行風滿衣。
尋僧雖不遇，
折得菊花歸以上《西巖集》。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00543","source_record_id":"CN-NT-CAT-00123","alias_record_ids":["CN-NT-CAT-00123"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%B0%8B%E5%83%A7_(%E7%BF%81%E5%8D%B7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-7fc1-5377', 0, '西風', NULL, NULL, NULL, '一處西風一處愁，
又逢鳴雁在西巖集作宿。
芙蓉不分秋蕭索，
鬭拆繁紅滿樹頭。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00544","source_record_id":"CN-NT-CAT-00124","alias_record_ids":["CN-NT-CAT-00124"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%A5%BF%E9%A2%A8_(%E7%BF%81%E5%8D%B7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-7fc1-5377', 0, '秋懷', NULL, '七言絶句', 7, '不管秋天陰復晴，
秋懷何處不淒清。
江城幾夜無佳月，
亦有新詩對雨成。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00545","source_record_id":"CN-NT-CAT-00125","alias_record_ids":["CN-NT-CAT-00125"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%A7%8B%E6%87%B7_(%E7%BF%81%E5%8D%B7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-7fc1-5377', 0, '野望', NULL, '七言絶句', 7, '一天秋色冷晴灣，
無數峰巒遠近間。
閑上山來看野水，
忽於水底見青山。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00546","source_record_id":"CN-NT-CAT-00126","alias_record_ids":["CN-NT-CAT-00126"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%87%8E%E6%9C%9B_(%E7%BF%81%E5%8D%B7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-8d99-5e2b-79c0', 0, '秋色', NULL, '五言律詩', 5, '幽人愛秋色，
祗為屬吟情。
一片葉初落，
數聯詩已清。
瘦便藤杖細，
凉覺葛衣輕。
門外蕭蕭徑，
今年菊自生。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00547","source_record_id":"CN-NT-CAT-00129","alias_record_ids":["CN-NT-CAT-00129"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%A7%8B%E8%89%B2_(%E8%B6%99%E5%B8%AB%E7%A7%80)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-8d99-5e2b-79c0', 0, '信州草衣寺', NULL, '五言律詩', 5, '芙蕖四五枝，
寂寞在空池。
難見草衣士，
空看宴坐碑。
香煙思盛日，
詩句記遊時。
欲問苔中鶴，
長松自不知。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00548","source_record_id":"CN-NT-CAT-00130","alias_record_ids":["CN-NT-CAT-00130"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E4%BF%A1%E5%B7%9E%E8%8D%89%E8%A1%A3%E5%AF%BA_(%E8%B6%99%E5%B8%AB%E7%A7%80)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-8d99-5e2b-79c0', 0, '大龍湫', NULL, '五言律詩', 5, '一派落虛空，
如何畫得同。
髙風吹作雨，
低日射成虹。
西域書曽說，
先朝路始通。
或言龍已去，
幽處別為宮。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00549","source_record_id":"CN-NT-CAT-00131","alias_record_ids":["CN-NT-CAT-00131"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%A4%A7%E9%BE%8D%E6%B9%AB_(%E8%B6%99%E5%B8%AB%E7%A7%80)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-7fc1-5377', 0, '送薛子舒赴華亭船官', NULL, NULL, NULL, '君到西巖集作至。
雲間日，
應分二陸名。
縣圖山色少西巖集作好。
井味海潮並。
剡局三年印，
春風半月程。
野人因買鶴，
曾向西巖集作到。
此中行。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00550","source_record_id":"CN-NT-CAT-00132","alias_record_ids":["CN-NT-CAT-00132"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%80%81%E8%96%9B%E5%AD%90%E8%88%92%E8%B5%B4%E8%8F%AF%E4%BA%AD%E8%88%B9%E5%AE%98_(%E7%BF%81%E5%8D%B7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-8d99-5e2b-79c0', 0, '春晚即事', NULL, '五言律詩', 5, '一身來作吏，
白日算徒勞。
塵土侵衣重，
年光如鬢牢。
春深禽語改，
溪落岸沙髙。
柳下垂鈎者，
吾今媿爾曹。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00551","source_record_id":"CN-NT-CAT-00133","alias_record_ids":["CN-NT-CAT-00133"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%98%A5%E6%99%9A%E5%8D%B3%E4%BA%8B_(%E8%B6%99%E5%B8%AB%E7%A7%80)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-8d99-5e2b-79c0', 0, '病起', NULL, '七言律詩', 7, '身如瘦鶴已伶俜，
一卧兼旬更有零。
朝客偶知親送藥，
野僧相保密持經。
力微尚覺衣裳重，
才退難邀筆硯靈。
惟有愛花心未已，
遍分黃菊插空瓶。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00552","source_record_id":"CN-NT-CAT-00134","alias_record_ids":["CN-NT-CAT-00134"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%97%85%E8%B5%B7_(%E8%B6%99%E5%B8%AB%E7%A7%80)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-8d99-5e2b-79c0', 0, '池上', NULL, '七言絶句', 7, '朝來行樂向秋池，
池上秋深病不知。
一樹木犀供夜雨，
清香移在菊花枝。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00553","source_record_id":"CN-NT-CAT-00135","alias_record_ids":["CN-NT-CAT-00135"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%B1%A0%E4%B8%8A_(%E8%B6%99%E5%B8%AB%E7%A7%80)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '自君之出矣', NULL, NULL, NULL, '自君之出矣，
心意明本、顧本作魂。
遠相隨。
拆破唐人絹，
經經是雙絲。
自君之出矣，
玉鑑明本、顧本作琴。
生塵垢。
蓮子種成荷，
曷時可成藕。
自君之出矣，
懶粧眉黛濃。
愁心如屋漏，
點點不移床明本、顧本作蹤。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00554","source_record_id":"CN-NT-CAT-00136","alias_record_ids":["CN-NT-CAT-00136"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%87%AA%E5%90%9B%E4%B9%8B%E5%87%BA%E7%9F%A3_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '江南曲', NULL, '七言絶句', 7, '絡緯催寒斷夢頭，
不眠雙淚枕邊流。
屏風莫展江南畫，
寸地能生千里愁。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00555","source_record_id":"CN-NT-CAT-00138","alias_record_ids":["CN-NT-CAT-00138"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%B1%9F%E5%8D%97%E6%9B%B2_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '采蓮曲', NULL, '七言律詩', 7, '行遍塘邊不肯歸，
鴛鴦打起看雙飛。
荷花近岸難攀折，
蒲葦叢深露濕衣。
羅蓋初收晚日陰，
野鳬飛起小魚沉。
蓮蓬摘下留空柄，
把向船前探水深。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00556","source_record_id":"CN-NT-CAT-00139","alias_record_ids":["CN-NT-CAT-00139"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%87%87%E8%93%AE%E6%9B%B2_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '妾薄命', NULL, '五言律詩', 5, '初與君相知，
便欲腸肺傾。
只擬君肺腸，
與妾相似生。
徘徊幾言笑，
始悟非真情。
妾情不可收，
悔思淚盈盈。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00557","source_record_id":"CN-NT-CAT-00140","alias_record_ids":["CN-NT-CAT-00140"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%A6%BE%E8%96%84%E5%91%BD_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '舟中', NULL, '五言律詩', 5, '秋氣清如水，
推篷夜不眠。
蘆花新有鴈，
莎葉尚鳴蟬。
心向征途老，
詩憑物景全。
漁童看月上，
吹笛柁樓前。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00558","source_record_id":"CN-NT-CAT-00141","alias_record_ids":["CN-NT-CAT-00141"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%88%9F%E4%B8%AD_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '途中', NULL, '五言律詩', 5, '隻影微陽外，
青山自鬰盤。
未經千里遠，
欲寄一書難。
堠碣苔侵字，
魚塘水過欄。
西風吹樹葉，
不問客衣單。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00559","source_record_id":"CN-NT-CAT-00142","alias_record_ids":["CN-NT-CAT-00142"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%80%94%E4%B8%AD_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '山中', NULL, '五言律詩', 5, '世事已無營，
翛然物外形。
野蔬僧飯潔，
山葛道衣輕。
掃葉燒茶鼎，
標題記藥瓶。
敲門舊賓客，
稚子會相迎。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00560","source_record_id":"CN-NT-CAT-00143","alias_record_ids":["CN-NT-CAT-00143"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%B1%B1%E4%B8%AD_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}')
)
INSERT INTO poems (
  poet_id, poem_no, volume, title_zh, title_ko, category, meter, body_zh,
  is_notable, status, quality, review_memo
)
SELECT
  p.id,
  COALESCE(existing_poem_count.max_poem_no, 0)
    + row_number() OVER (PARTITION BY p.id ORDER BY ip.title_zh, ip.body_zh)::integer,
  ip.volume::integer, ip.title_zh, ip.title_ko, ip.category, ip.meter::integer, ip.body_zh,
  TRUE, ip.status, ip.quality, ip.review_memo
FROM input_poems ip
JOIN poets p ON p.title_id = ip.poet_slug
LEFT JOIN LATERAL (
  SELECT max(poem_no) AS max_poem_no
  FROM poems
  WHERE poet_id = p.id
) existing_poem_count ON TRUE
WHERE NOT EXISTS (
  SELECT 1
  FROM poems existing
  WHERE existing.poet_id = p.id
    AND existing.title_zh = ip.title_zh
    AND existing.body_zh = ip.body_zh
);

UPDATE poets p
SET poem_count = sub.cnt
FROM (
  SELECT poet_id, count(*)::integer AS cnt
  FROM poems
  WHERE poet_id IN (SELECT id FROM poets WHERE title_id IN ('candidate-song-7a0b-9865', 'candidate-song-694a-6a38', 'candidate-song-8607-8efe', 'candidate-song-738b-6dc7', 'candidate-song-767d-7389-87fe', 'candidate-song-5442-5927-81e8', 'candidate-song-694a-842c-91cc', 'candidate-song-6731-6dd1-771f', 'candidate-song-738b-5b89-77f3', 'candidate-song-8303-6210-5927', 'candidate-ming-5f90-968e', 'candidate-song-6b66-884d', 'candidate-ming-6731-4e4b-745c', 'candidate-ming-590f-5b8c-6df3', 'candidate-song-5b8b-b7-9673-8944', 'candidate-song-9673-8944', 'candidate-song-738b-742a', 'candidate-ming-5289-9438', 'candidate-ming-5289-6dd1', 'candidate-ming-738b-7aef-6dd1', 'candidate-ming-5468-74ca', 'candidate-ming-5433-742a', 'candidate-ming-8881-5f64-82b3', 'candidate-song-9ec3-5ead-5805', 'candidate-song-7fc1-5377', 'candidate-song-8d99-5e2b-79c0', 'candidate-song-5f90-7167'))
  GROUP BY poet_id
) sub
WHERE p.id = sub.poet_id;

-- Review counts before COMMIT when applying manually:
SELECT quality, status, count(*) FROM poems WHERE quality IN ('cnnt-auto') GROUP BY quality, status ORDER BY quality, status;
SELECT p.era_period, count(pm.id) FROM poets p JOIN poems pm ON pm.poet_id = p.id WHERE p.title_id IN ('candidate-song-7a0b-9865', 'candidate-song-694a-6a38', 'candidate-song-8607-8efe', 'candidate-song-738b-6dc7', 'candidate-song-767d-7389-87fe', 'candidate-song-5442-5927-81e8', 'candidate-song-694a-842c-91cc', 'candidate-song-6731-6dd1-771f', 'candidate-song-738b-5b89-77f3', 'candidate-song-8303-6210-5927', 'candidate-ming-5f90-968e', 'candidate-song-6b66-884d', 'candidate-ming-6731-4e4b-745c', 'candidate-ming-590f-5b8c-6df3', 'candidate-song-5b8b-b7-9673-8944', 'candidate-song-9673-8944', 'candidate-song-738b-742a', 'candidate-ming-5289-9438', 'candidate-ming-5289-6dd1', 'candidate-ming-738b-7aef-6dd1', 'candidate-ming-5468-74ca', 'candidate-ming-5433-742a', 'candidate-ming-8881-5f64-82b3', 'candidate-song-9ec3-5ead-5805', 'candidate-song-7fc1-5377', 'candidate-song-8d99-5e2b-79c0', 'candidate-song-5f90-7167') GROUP BY p.era_period ORDER BY p.era_period;

ROLLBACK;
-- COMMIT;
