-- Generated by scripts/build_cn_translation_pipeline_staging.mjs
-- Part: 12/13
-- Purpose: stage CN pre-Tang and Song/Yuan/Ming poems into the JDS translation pipeline.
-- Translator decision: JDS backend=gemini model=gemini-2.5-flash-lite prompt=pipeline/translate/prompts/v5_full.txt.
-- Safety: inserts only missing poet slug + title_zh + body_zh rows. Default ending is ROLLBACK.

BEGIN;

WITH input_poets(slug, name_zh, name_ko, life_raw, era_period, country) AS (
  VALUES
    ('candidate-ming-5f35-55ac', '張喬', NULL, NULL, '明', 'CN'),
    ('candidate-ming-5f35-74a8', '張璨', NULL, NULL, '明', 'CN'),
    ('candidate-ming-5f90-5eb8', '徐庸', NULL, NULL, '明', 'CN'),
    ('candidate-ming-9ad8-555f', '高啟', NULL, NULL, '明', 'CN'),
    ('candidate-ming-5510-82b3-7b2c', '唐芳第', NULL, NULL, '明', 'CN'),
    ('candidate-ming-5f90-71a5', '徐熥', NULL, NULL, '明', 'CN'),
    ('candidate-song-9678-904a', '陸遊', NULL, NULL, '宋', 'CN'),
    ('candidate-song-5b54-5e73-4ef2', '孔平仲', NULL, NULL, '宋', 'CN'),
    ('candidate-song-912d-525b-4e2d', '鄭剛中', NULL, NULL, '宋', 'CN'),
    ('candidate-song-65bd-6a1e', '施樞', NULL, NULL, '宋', 'CN'),
    ('candidate-song-5f6d-6c5d-792a', '彭汝礪', NULL, NULL, '宋', 'CN'),
    ('candidate-ming-674e-6771-967d', '李東陽', NULL, NULL, '明', 'CN'),
    ('candidate-ming-5510-4e4b-6df3', '唐之淳', NULL, NULL, '明', 'CN'),
    ('candidate-ming-9ec3-5c0a-7d20', '黃尊素', NULL, NULL, '明', 'CN'),
    ('candidate-ming-5c48-5927-5747', '屈大均', NULL, NULL, '明', 'CN'),
    ('candidate-yuan-6d2a-7131-7956', '洪焱祖', NULL, NULL, '元', 'CN'),
    ('candidate-yuan-5b8b-8927', '宋褧', NULL, NULL, '元', 'CN'),
    ('candidate-song-6c6a-5143-91cf', '汪元量', NULL, NULL, '宋', 'CN'),
    ('candidate-ming-4faf-606a', '侯恪', NULL, NULL, '明', 'CN'),
    ('candidate-ming-4f55-543e-9a36', '何吾騶', NULL, NULL, '明', 'CN'),
    ('candidate-ming-694a-8d77-5143', '楊起元', NULL, NULL, '明', 'CN'),
    ('candidate-ming-90b1-96f2-9704', '邱雲霄', NULL, NULL, '明', 'CN'),
    ('candidate-ming-590f-539f-5409', '夏原吉', NULL, NULL, '明', 'CN'),
    ('candidate-ming-6bb7-594e', '殷奎', NULL, NULL, '明', 'CN'),
    ('candidate-ming-6eab-7d14', '溫純', NULL, NULL, '明', 'CN'),
    ('candidate-song-6b50-967d-4fee', '歐陽修', NULL, NULL, '宋', 'CN'),
    ('candidate-song-8d99-4f76', '趙佶', NULL, NULL, '宋', 'CN'),
    ('candidate-song-4f5a-540d', '佚名', NULL, NULL, '宋', 'CN'),
    ('candidate-yuan-99ae-5b50-632f', '馮子振', NULL, NULL, '元', 'CN'),
    ('candidate-yuan-8d99-5dd6', '趙巖', NULL, NULL, '元', 'CN'),
    ('candidate-yuan-5f35-821c-54a8', '張舜咨', NULL, NULL, '元', 'CN'),
    ('candidate-yuan-5289-5d69', '劉嵩', NULL, NULL, '元', 'CN'),
    ('candidate-yuan-85a9-9054-9053', '薩達道', NULL, NULL, '元', 'CN'),
    ('candidate-yuan-9322-9078', '錢選', NULL, NULL, '元', 'CN'),
    ('candidate-ming-5289-7199-795a', '劉熙祚', NULL, NULL, '明', 'CN'),
    ('candidate-ming-7d76-547d-8a69', '絶命詩', NULL, NULL, '明', 'CN')
)
INSERT INTO poets (title_id, name_zh, name_ko, life_raw, era_period, poem_count)
SELECT slug, name_zh, name_ko, life_raw, era_period, 0
FROM input_poets
ON CONFLICT (title_id) DO UPDATE SET
  name_zh = EXCLUDED.name_zh,
  name_ko = COALESCE(EXCLUDED.name_ko, poets.name_ko),
  life_raw = COALESCE(EXCLUDED.life_raw, poets.life_raw),
  era_period = EXCLUDED.era_period;

WITH input_poems(poet_slug, volume, title_zh, title_ko, category, meter, body_zh, status, quality, review_memo) AS (
  VALUES
    ('candidate-ming-5f35-55ac', 0, '洞房曲', NULL, '七言絶句', 7, '芙蓉雙臉玉微紅，
恰在金屏翠幕中。
蝶翅舞餘春粉熱，
闌乾十二鎖香風。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00881","source_record_id":"CN-NT-CAT-00487","alias_record_ids":["CN-NT-CAT-00487"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%B4%9E%E6%88%BF%E6%9B%B2_(%E5%BC%B5%E5%96%AC)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f35-74a8', 0, '洞房曲', NULL, '七言古詩', 7, '鴉雛夜宿迷濛栁，
鬥帳燒燈蠟光透。
銀罌注酒芙蓉香，
金絲檀槽為君奏。
歌喉窱窱鶯兒語，
象口吹香凝碧縷。
盤龍繡帯結同心，
牽惹巫雲隨峽雨。
歌聲未䦨香未滅，
曲屛生香暈眼纈。
小玉催鋪蜀錦衾，
紗窓影轉桐花月。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00882","source_record_id":"CN-NT-CAT-00488","alias_record_ids":["CN-NT-CAT-00488"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%B4%9E%E6%88%BF%E6%9B%B2_(%E5%BC%B5%E7%92%A8)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-5eb8', 0, '洞房曲', NULL, '七言古詩', 7, '珍珠簾逗銀蟾光，
葳蕤綉帳垂蘭堂。
阿儂不似青樓娼，
也學搊箏來奉郎。
絃聲未和頻促柱，
更啟櫻唇歌白苧。
瓊筵酒薦鯉魚尾，
洞房夜燒燈燄紫。
翠被疊床春薿薿，
骨醉錦鴛嬌不起。
花梢香露撲窓紗，
一任井闌啼曙鴉。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00883","source_record_id":"CN-NT-CAT-00489","alias_record_ids":["CN-NT-CAT-00489"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%B4%9E%E6%88%BF%E6%9B%B2_(%E5%BE%90%E5%BA%B8)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-9ad8-555f', 0, '洞房曲', NULL, '七言絶句', 7, '洞房香吐合昏花，
月轉勾闌啼乳鴉。
今宵有酒留君醉，
不信娼家勝妾家。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00884","source_record_id":"CN-NT-CAT-00490","alias_record_ids":["CN-NT-CAT-00490"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%B4%9E%E6%88%BF%E6%9B%B2_(%E9%AB%98%E5%95%9F)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5510-82b3-7b2c', 0, '洞房曲', NULL, '七言古詩', 7, '軟金屈戌開鴛鴦，
花符細字呼徐娘。
綠雲半墮蓮花妝，
雅鬟十五攜履箱。
琵琶百囀春漏長，
嬌歌欲遞遲龍香。
臨筵催賜青雀觴，
海棠滴露低紅芳。
流蘇壓鉤金鏘鏘，
銅球宛轉添都梁。
殢人緩緩收鳴璫，
花枝故惱東風狂。
銀屏疊疊遮瑣窓，
長夜遼遼天未央。
橫嬌妒寵誰能望，
春光不到翾風房。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00885","source_record_id":"CN-NT-CAT-00491","alias_record_ids":["CN-NT-CAT-00491"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%B4%9E%E6%88%BF%E6%9B%B2_(%E5%94%90%E8%8A%B3%E7%AC%AC)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '聞鴈', NULL, '五言絶句', 5, '忽起蘆花渚，
哀聲入亂雲。
空閨多戍婦，
莫遣夜深聞。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00886","source_record_id":"CN-NT-CAT-00492","alias_record_ids":["CN-NT-CAT-00492"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%81%9E%E9%B4%88_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '自遣', NULL, '五言絶句', 5, '遯跡在空山，
生涯寄塲圃。
柴門到者稀，
滿地梨花雨。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00887","source_record_id":"CN-NT-CAT-00493","alias_record_ids":["CN-NT-CAT-00493"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%87%AA%E9%81%A3_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '山館', NULL, '五言絶句', 5, '地僻稀來往，
空山日正長。
晩凉新睡覺，
古木自斜陽。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00888","source_record_id":"CN-NT-CAT-00494","alias_record_ids":["CN-NT-CAT-00494"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%B1%B1%E9%A4%A8_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '山中', NULL, '五言絶句', 5, '散歩入空林，
斜陽滿山麓。
四顧寂無人，
蟬聲出修竹。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00889","source_record_id":"CN-NT-CAT-00495","alias_record_ids":["CN-NT-CAT-00495"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%B1%B1%E4%B8%AD_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '薄暮', NULL, '五言絶句', 5, '匹馬黃沙路，
蕭蕭欲斷魂。
天涯多少恨，
況乃近黃昏。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00890","source_record_id":"CN-NT-CAT-00496","alias_record_ids":["CN-NT-CAT-00496"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%96%84%E6%9A%AE_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '馬上', NULL, '五言絶句', 5, '去國八千里，
堪嗟行路難。
馬頭天欲盡，
猶不見長安。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00891","source_record_id":"CN-NT-CAT-00497","alias_record_ids":["CN-NT-CAT-00497"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%A6%AC%E4%B8%8A_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '警急', NULL, '五言絶句', 5, '聞説臨洮府，
今年沒敵塵。
願圗恢復䇿，
不必議和親。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00892","source_record_id":"CN-NT-CAT-00498","alias_record_ids":["CN-NT-CAT-00498"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%AD%A6%E6%80%A5_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-9678-904a', 0, '馬上', NULL, NULL, NULL, '客遊多感慨，
老病少歡欣。
去去穿村市，
翻翻吹帽裙。
天低落平野，
雁遠入寒雲。
漸覺江城近，
秋笳馬上聞。
燈前薄飰陳鹽虀，
帶睡強出行江隄。
五更落月移樹影，
十月清霜侵馬蹄。
荒陂嗈嗈已度雁，
小市喔喔初鳴雞。
可憐萬里覓歸夢，
未到故山先自迷。
殘年流轉似萍根，
馬上傷春易斷魂。
烘暖花無經日蕊，
漲深水過去年痕。
迷行每問樵夫路，
投宿時敲竹寺門。
不信太平元有象，
牛羊點點散煙村。
春殘馬上意倀倀，
縱轡微吟過數坊。
緑樹成帷連藥市，
清流如帶繞毬場。
城荒鼓角增悲壯，
苑廢雲煙尚莽蒼。
堪笑年來向詩懶，
還家古錦只空囊。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00893","source_record_id":"CN-NT-CAT-00499","alias_record_ids":["CN-NT-CAT-00499"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%A6%AC%E4%B8%8A_(%E9%99%B8%E6%B8%B8)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5b54-5e73-4ef2', 0, '馬上', NULL, NULL, NULL, '秋山剝棗熟，
野水漚麻香。
鳥倦投空木，
蟬悲送夕陽。
去程猶未幾，
歸興一何長。
應爲西齋睡，
疏慵不忘。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00894","source_record_id":"CN-NT-CAT-00500","alias_record_ids":["CN-NT-CAT-00500"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%A6%AC%E4%B8%8A_(%E5%AD%94%E5%B9%B3%E4%BB%B2)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '逢俠者', NULL, '五言絶句', 5, '了不知名姓，
偶遇長安市。
片語忽相投，
懽然結生死。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00895","source_record_id":"CN-NT-CAT-00501","alias_record_ids":["CN-NT-CAT-00501"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%80%A2%E4%BF%A0%E8%80%85_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-912d-525b-4e2d', 0, '馬上', NULL, NULL, NULL, '蚤酒衝寒不滿，
日髙猶踐馬蹄霜。
鳥依密樹旁邊語，
梅在遠林幽處香。
西去流移還未復，
東來書訊且都忘。
征途一任如天遠，
不過歸時杏子黃。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00896","source_record_id":"CN-NT-CAT-00502","alias_record_ids":["CN-NT-CAT-00502"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%A6%AC%E4%B8%8A_(%E9%84%AD%E5%89%9B%E4%B8%AD)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-65bd-6a1e', 0, '馬上', NULL, '七言律詩', 7, '只爲溪山有宿盟，
兩旬兩度此經行。
馬嘶險逕霜蹄滑，
鷗舞平沙雪羽輕。
豪氣不從塵外減，
新詩偏向道間成。
梅花似有相迎意，
野水籬邊數蘂明。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00897","source_record_id":"CN-NT-CAT-00503","alias_record_ids":["CN-NT-CAT-00503"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%A6%AC%E4%B8%8A_(%E6%96%BD%E6%A8%9E)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f6d-6c5d-792a', 0, '馬上', NULL, '五言律詩', 5, '馬上值寒食，
途中非故鄉。
山川勞跋涉，
風雨助悲凉。
碧樹鳥相語，
幽林花自芳。
不辭趨道路，
多愧負春光。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00898","source_record_id":"CN-NT-CAT-00504","alias_record_ids":["CN-NT-CAT-00504"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%A6%AC%E4%B8%8A_(%E5%BD%AD%E6%B1%9D%E7%A4%AA)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-674e-6771-967d', 0, '馬上', NULL, '七言律詩', 7, '玉珂朝㪚紫宸班，
馬上詩成按轡還。
近侍有名聊作伴，
史才無用合教閒。
狂過相府慵通刺，
貧住京華亦愛山。
淺薄未酬升鬥在，
漫將心事付朱顔。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00899","source_record_id":"CN-NT-CAT-00505","alias_record_ids":["CN-NT-CAT-00505"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%A6%AC%E4%B8%8A_(%E6%9D%8E%E6%9D%B1%E9%99%BD)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5510-4e4b-6df3', 0, '馬上', NULL, '七言律詩', 7, '谷深風急帽簷斜，
滿眼寒雲滿面沙。
騎馬過山看不盡，
更多芳樹沒人家。
五月營門栁始華，
新新草色舊人家。
鄉山萬里誰相伴，
惟有囊中日鑄茶。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00900","source_record_id":"CN-NT-CAT-00506","alias_record_ids":["CN-NT-CAT-00506"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%A6%AC%E4%B8%8A_(%E5%94%90%E4%B9%8B%E6%B7%B3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-9ec3-5c0a-7d20', 0, '馬上', NULL, '七言絶句', 7, '層氷積雪逗村家，
半去春光栁未芽。
一日鳴驄南陌上，
黃鸝已鬧杏頭花。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00901","source_record_id":"CN-NT-CAT-00507","alias_record_ids":["CN-NT-CAT-00507"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%A6%AC%E4%B8%8A_(%E9%BB%83%E5%B0%8A%E7%B4%A0)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5c48-5927-5747', 0, '馬上', NULL, '五言律詩', 5, '馬上聽橫吹，
征夫心最悲。
邊雲多慘淡，
隴水易流離。
翠嶂盤陵邑，
渾河繞嶽祠。
時艱思用武，
未忍採華芝。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00902","source_record_id":"CN-NT-CAT-00508","alias_record_ids":["CN-NT-CAT-00508"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%A6%AC%E4%B8%8A_(%E5%B1%88%E5%A4%A7%E5%9D%87)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '對雨', NULL, '五言絶句', 5, '寒窻一夜雨，
山色幾重青。
㑹得靜中意，
焚香看道經。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00903","source_record_id":"CN-NT-CAT-00509","alias_record_ids":["CN-NT-CAT-00509"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%B0%8D%E9%9B%A8_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '客中寒食', NULL, '五言絶句', 5, '去歳燕山道，
今朝劍水濵。
如何兩寒食，
俱作異鄉人。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00904","source_record_id":"CN-NT-CAT-00510","alias_record_ids":["CN-NT-CAT-00510"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%AE%A2%E4%B8%AD%E5%AF%92%E9%A3%9F_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '題畫', NULL, '五言古詩', 5, '日落溪水寒，
林疎秋色老。
柴門閉白雲，
滿樹丹楓老。
森森灌木隂，
渺渺澄江靜。
一棹獨垂綸，
中流釣山影。
振衣危峰巔，
扶桑日初起。
柳色破青煙，
桃花帶流水。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00905","source_record_id":"CN-NT-CAT-00511","alias_record_ids":["CN-NT-CAT-00511"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%A1%8C%E7%95%AB_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '記夢', NULL, '五言絶句', 5, '夢與雙親別，
牽衣兩淚垂。
不知成永隔，
猶道暫相離。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00906","source_record_id":"CN-NT-CAT-00512","alias_record_ids":["CN-NT-CAT-00512"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%A8%98%E5%A4%A2_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '漂母祠', NULL, '五言絶句', 5, '落落千金報，
悠悠國士心。
從今慚漂母，
不敢過淮隂。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00907","source_record_id":"CN-NT-CAT-00513","alias_record_ids":["CN-NT-CAT-00513"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%BC%82%E6%AF%8D%E7%A5%A0_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '迴文詩', NULL, '五言絶句', 5, '緑波迴斷港，
青嶂蔭孤村。
谷蘿開亂莽，
汀浪浸疎園。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00908","source_record_id":"CN-NT-CAT-00514","alias_record_ids":["CN-NT-CAT-00514"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%BF%B4%E6%96%87%E8%A9%A9_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '江上送客', NULL, '七言絶句', 7, '片㠶遥向洞庭遊，
湖水茫茫一色秋。
別後思君腸欲斷，
不堪重倚夕陽樓。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00909","source_record_id":"CN-NT-CAT-00515","alias_record_ids":["CN-NT-CAT-00515"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%B1%9F%E4%B8%8A%E9%80%81%E5%AE%A2_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '蘇小小墓', NULL, '七言絶句', 7, '疎林落葉亂孤村，
芳草萋萋滿墓門。
惆悵美人今不見，
寒鴉棲盡又黃昏。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00910","source_record_id":"CN-NT-CAT-00516","alias_record_ids":["CN-NT-CAT-00516"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%98%87%E5%B0%8F%E5%B0%8F%E5%A2%93_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '彭城懷古', NULL, '七言絶句', 7, '雲龍山下鳥爭啼，
戲馬臺前日欲西。
莫謂楚宮今寂寞，
五陵芳草正萋萋。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00911","source_record_id":"CN-NT-CAT-00517","alias_record_ids":["CN-NT-CAT-00517"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%BD%AD%E5%9F%8E%E6%87%B7%E5%8F%A4_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '聽角思歸', NULL, '七言絶句', 7, '白草黃榆不見春，
十年遼海困征塵。
夜來正有還鄉夢，
殘角一聲愁殺人。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00912","source_record_id":"CN-NT-CAT-00518","alias_record_ids":["CN-NT-CAT-00518"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%81%BD%E8%A7%92%E6%80%9D%E6%AD%B8_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '感舊', NULL, '七言絶句', 7, '一別心知萬里遥，
孤燈空對可憐宵。
因思十五年前事，
月色簫聲共寂寥。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00913","source_record_id":"CN-NT-CAT-00519","alias_record_ids":["CN-NT-CAT-00519"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%84%9F%E8%88%8A_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '軍城早秋', NULL, '七言絶句', 7, '落日荒城起暮笳，
蕭條秋色滿黃沙。
一聲塞鴈西風裡，
十萬征人盡憶家。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00914","source_record_id":"CN-NT-CAT-00520","alias_record_ids":["CN-NT-CAT-00520"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%BB%8D%E5%9F%8E%E6%97%A9%E7%A7%8B_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '秋夜聞笛', NULL, '七言絶句', 7, '殘月微微玉漏深，
一聲長笛起秋陰。
天涯多少懷歸客，
獨對西風思不禁。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00915","source_record_id":"CN-NT-CAT-00521","alias_record_ids":["CN-NT-CAT-00521"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%A7%8B%E5%A4%9C%E8%81%9E%E7%AC%9B_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '宮怨', NULL, NULL, NULL, '金鎖重封院宇深鑾，
輿消息總沉沉。
君王何處看歌舞負，
却長門夜夜心。
遥聞玉輦過昭陽歌，
吹聲中欲斷腸。
一閉深宮經十載夢，
魂無自識君王。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00916","source_record_id":"CN-NT-CAT-00522","alias_record_ids":["CN-NT-CAT-00522"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%AE%AE%E6%80%A8_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-yuan-6d2a-7131-7956', 0, '彭城懷古二首', NULL, '五言古詩', 5, '霸業重瞳子，
雄才大耳兒。
河山猶表裏，
今古幾興衰。
彭祖終遺墓，
蘇公僅有碑。
伊誰居里閈，
寒餓得聞思。
戶口十餘萬，
承平亦富哉。
人煙今寂寞，
洪勢自喧豗。
可有名駒子，
空餘戲馬臺。
登臨興不盡，
挽纜故相催。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00917","source_record_id":"CN-NT-CAT-00523","alias_record_ids":["CN-NT-CAT-00523"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%BD%AD%E5%9F%8E%E6%87%B7%E5%8F%A4%E4%BA%8C%E9%A6%96_(%E6%B4%AA%E7%84%B1%E7%A5%96)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '送人出塞', NULL, '七言絶句', 7, '黃塵漠漠暗征衣，
楊柳青青折漸稀。
試問玉門關外路，
幾人西去幾人歸。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00918","source_record_id":"CN-NT-CAT-00524","alias_record_ids":["CN-NT-CAT-00524"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%80%81%E4%BA%BA%E5%87%BA%E5%A1%9E_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '長門怨', NULL, '七言絶句', 7, '芳草何時輦路通，
長門花鳥自春風。
總縁薄命難承寵，
不是相如賦未工。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00919","source_record_id":"CN-NT-CAT-00525","alias_record_ids":["CN-NT-CAT-00525"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%95%B7%E9%96%80%E6%80%A8_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '金谷園', NULL, '七言絶句', 7, '聞説佳人此墜樓，
青山長在水長流。
明珠已與珊瑚碎，
尚有香魂夜出遊。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00920","source_record_id":"CN-NT-CAT-00526","alias_record_ids":["CN-NT-CAT-00526"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%87%91%E8%B0%B7%E5%9C%92_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '青塚', NULL, '七言絶句', 7, '誤殺婵娟是畫圖，
千年孤塜長蘼蕪。
春風似亦憐芳質，
不遣窮陰草色枯。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00921","source_record_id":"CN-NT-CAT-00527","alias_record_ids":["CN-NT-CAT-00527"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%9D%92%E5%A1%9A_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '楊白花', NULL, '七言絶句', 7, '楊花如雪葉如絲，
無奈東風一夜吹。
飄落不知何處所，
年年腸斷暮春時。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00922","source_record_id":"CN-NT-CAT-00528","alias_record_ids":["CN-NT-CAT-00528"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%A5%8A%E7%99%BD%E8%8A%B1_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '宮人斜', NULL, '七言絶句', 7, '春雨春風粉黛銷，
誰憐黃土葬妖嬌。
墓門幸與諸陵近，
夜夜香魂不寂寥。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00923","source_record_id":"CN-NT-CAT-00529","alias_record_ids":["CN-NT-CAT-00529"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%AE%AB%E4%BA%BA%E6%96%9C_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '馬嵬驛', NULL, '七言絶句', 7, '蛾眉宛轉倍堪憐，
永別君恩赴九泉。
千載馬嵬山下路，
傷心最是佛堂前。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00924","source_record_id":"CN-NT-CAT-00530","alias_record_ids":["CN-NT-CAT-00530"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%A6%AC%E5%B5%AC%E9%A9%9B_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '隴西行', NULL, '七言律詩', 7, '一別家山萬里長，
多年白骨委沙塲。
遊魂已逐邊塵散，
空有髙臺築望鄉。
仗劍封侯事已非，
閨中少婦葬征衣。
玉門關內多邊馬，
縱有遊魂不敢歸。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00925","source_record_id":"CN-NT-CAT-00531","alias_record_ids":["CN-NT-CAT-00531"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%9A%B4%E8%A5%BF%E8%A1%8C_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '楚宮怨', NULL, '七言絶句', 7, '黃土埋香翠黛銷，
楚妃魂逐楚雲飄。
愁多自殞如花貌，
豈為君王愛細腰。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00926","source_record_id":"CN-NT-CAT-00532","alias_record_ids":["CN-NT-CAT-00532"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%A5%9A%E5%AE%AE%E6%80%A8_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '吳宮怨', NULL, '七言絶句', 7, '髙臺日日翠華臨，
何事顰眉更捧心。
本是苧蘿山下女，
吳中恩淺越中深。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00927","source_record_id":"CN-NT-CAT-00533","alias_record_ids":["CN-NT-CAT-00533"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%90%B3%E5%AE%AE%E6%80%A8_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '漢宮怨', NULL, '七言絶句', 7, '寵幸當年不省憂，
六宮那許近宸旒。
一從廢入長門裡，
始解宮中失寵愁。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00928","source_record_id":"CN-NT-CAT-00534","alias_record_ids":["CN-NT-CAT-00534"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%BC%A2%E5%AE%AE%E6%80%A8_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-yuan-5b8b-8927', 0, '漢宮怨', NULL, NULL, NULL, '趙飛燕，
漢春如一日。
色映豹尾竿，
膏香髮鬈漆。
掃粉浴蘭雲帳底，
三十六宮寒似水。
天教痴妬擅浮榮，
緑篋緘傳還啄矢。
唯餘擁背人，
暖夢黃金殿。
西風長信深，
塵埋舊紈扇。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00929","source_record_id":"CN-NT-CAT-00535","alias_record_ids":["CN-NT-CAT-00535"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%BC%A2%E5%AE%AE%E6%80%A8_(%E5%AE%8B%E8%A4%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-6c6a-5143-91cf', 0, '巴陵', NULL, NULL, NULL, '重到巴陵秋正清，
嶽陽城下繫孤舲。
江湖萬里水雲闊，
天地一凉河漢明。
月出洞庭魚婢舞，
氣蒸雁奴腥。
篙工又鼓瀟湘柁，
漁笛漁榔上下鳴。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00930","source_record_id":"CN-NT-CAT-00536","alias_record_ids":["CN-NT-CAT-00536"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%B7%B4%E9%99%B5_(%E6%B1%AA%E5%85%83%E9%87%8F)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-4faf-606a', 0, '巴陵', NULL, '五言律詩', 5, '一夜巴陵雨，
湖光接洞庭。
天圍夔子國，
波入楚王亭。
嵗逺山樓廢，
春深草木馨。
惟餘羣鴈北，
蕭瑟不能聴。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00931","source_record_id":"CN-NT-CAT-00537","alias_record_ids":["CN-NT-CAT-00537"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%B7%B4%E9%99%B5_(%E4%BE%AF%E6%81%AA)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '竹枝詞', NULL, '七言古詩', 7, '美人門對錢塘江，
水透蘇堤月透窻。
莫怨裴航仙夢晚，
種來玉杵未成雙。
妾住西湖舊狹邪，
孤山深處是郎家。
郎若重來須細認，
湖邉新種碧桃花。
楊柳堤邉去採蓮，
柳枝低拂采蓮舩。
分付兒童休浪折，
留待郎來作馬鞭。
忽聽樓頭鼓亂敲，
模糊月色上花梢。
郎今去住無消息，
暗擲金錢卜一爻。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00932","source_record_id":"CN-NT-CAT-00538","alias_record_ids":["CN-NT-CAT-00538"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%AB%B9%E6%9E%9D%E8%A9%9E_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '月夜', NULL, '七言絶句', 7, '鶯花三月出燕關，
千里家鄉幾日還。
今夜月明天似水，
夢魂先到武夷山。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00933","source_record_id":"CN-NT-CAT-00539","alias_record_ids":["CN-NT-CAT-00539"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%9C%88%E5%A4%9C_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '感事', NULL, '七言絶句', 7, '莫嘆吾家似磬懸，
資生猶有賣文錢。
不知萬落千村裡，
多少人家絶火煙。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00934","source_record_id":"CN-NT-CAT-00540","alias_record_ids":["CN-NT-CAT-00540"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%84%9F%E4%BA%8B_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '秋夜即事', NULL, '七言絶句', 7, '秋宵殘雨上窻紗，
一㸃流螢照暮花。
覔得輕羅穿竹徑，
已隨風葉過隣家。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00935","source_record_id":"CN-NT-CAT-00541","alias_record_ids":["CN-NT-CAT-00541"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%A7%8B%E5%A4%9C%E5%8D%B3%E4%BA%8B_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '夜雨', NULL, '七言絶句', 7, '客路逢秋夢易醒，
空江煙雨晚㝠㝠。
數聲夜半孤篷外，
不似髙齋竹裡聽。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00936","source_record_id":"CN-NT-CAT-00542","alias_record_ids":["CN-NT-CAT-00542"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%A4%9C%E9%9B%A8_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '詠燕', NULL, '七言絶句', 7, '燕子嬌飛羽翼齊，
呢喃時向小窻西。
只因舊壘營初定，
縱有雕梁不敢棲。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00937","source_record_id":"CN-NT-CAT-00543","alias_record_ids":["CN-NT-CAT-00543"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%92%8F%E7%87%95_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '渡江', NULL, '七言絶句', 7, '一葉扁舟逐浪飛，
罡風吹浪上征衣。
他時縱有南歸夢，
夢見濤聲不敢歸。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00938","source_record_id":"CN-NT-CAT-00544","alias_record_ids":["CN-NT-CAT-00544"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%B8%A1%E6%B1%9F_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '寄弟', NULL, '七言絶句', 7, '春風送客飜愁客，
客路逢春不當春。
寄語鶯聲休便老，
天涯猶有未歸人。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00939","source_record_id":"CN-NT-CAT-00545","alias_record_ids":["CN-NT-CAT-00545"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%AF%84%E5%BC%9F_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '對鏡', NULL, '七言絶句', 7, '前路虛名未可期，
曉來臨鏡不勝悲。
無情最是雙青鬢，
豈待名成始有絲。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00940","source_record_id":"CN-NT-CAT-00546","alias_record_ids":["CN-NT-CAT-00546"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%B0%8D%E9%8F%A1_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-4f55-543e-9a36', 0, '寄弟', NULL, '七言絶句', 7, '短檠燈影夜躊躇，
此日初封寄弟書。
北望長安千萬里，
江天回首雁群疏。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00941","source_record_id":"CN-NT-CAT-00547","alias_record_ids":["CN-NT-CAT-00547"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%AF%84%E5%BC%9F_(%E4%BD%95%E5%90%BE%E9%A8%B6)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-694a-8d77-5143', 0, '寄弟', NULL, NULL, NULL, '我年四十一，
亦知四十非。
雙親家萬里，
夢寐常依依。
尚幸我弟賢，
夙夜侍庭幃。
我無補袞功，
只以竊祿違。
自從七月來，
三命清切司。
首展經筵書，
再篡曹工題。
復令知制誥，
代草明光扉。
備員立螭蚴，
何異立仗騎。
天子本聖明，
忠臣要防微。
秦隴旱爲雪，
東南潦饑。
委非親民職，
內計誠無奇。
肉食每自愧，
幾欲抽簪歸。
尚抱獻納心，
終欲有所施。
不然望舊山，
歸來慰嚴慈。
春初種松竹，
想已含綠滋。
未種應爲種，
勿過青春時。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00942","source_record_id":"CN-NT-CAT-00548","alias_record_ids":["CN-NT-CAT-00548"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%AF%84%E5%BC%9F_(%E6%A5%8A%E8%B5%B7%E5%85%83)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-90b1-96f2-9704', 0, '寄弟', NULL, '五言絶句', 5, '昔別鶯花早，
重經梅栁春。
髙雲斷去鴈，
芳草未歸人。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00943","source_record_id":"CN-NT-CAT-00549","alias_record_ids":["CN-NT-CAT-00549"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%AF%84%E5%BC%9F_(%E9%82%B1%E9%9B%B2%E9%9C%84)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-590f-539f-5409', 0, '寄弟', NULL, '七言律詩', 7, '一身為客寓神京，
兩弟隨親在楚城。
魚鴈常時傳別字，
塤箎何日奏和聲。
願勤燈火寒窻業，
勿負箕裘先世名。
嵗晚歸來姜被煖，
載歌棠棣話心情。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00944","source_record_id":"CN-NT-CAT-00550","alias_record_ids":["CN-NT-CAT-00550"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%AF%84%E5%BC%9F_(%E5%A4%8F%E5%8E%9F%E5%90%89)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-6bb7-594e', 0, '寄弟', NULL, '七言律詩', 7, '故園二仲近何如，
半載平安未得書。
堂下紫荆長㡬許，
墻隂翠竹勝當初。
時常官府供徭役，
旦日庭幃問起居。
媿我飄蓬歸已緩，
不知歸計尚全踈。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00945","source_record_id":"CN-NT-CAT-00551","alias_record_ids":["CN-NT-CAT-00551"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%AF%84%E5%BC%9F_(%E6%AE%B7%E5%A5%8E)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-6eab-7d14', 0, '寄弟', NULL, '五言律詩', 5, '吾仲幾傳書，
飛騰興欲舒。
看雲愁見鴈，
彈鋏嘆無魚。
經學三冬足，
鵬摶萬里餘。
雪霜亦雨露，
努力愛居諸。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00946","source_record_id":"CN-NT-CAT-00552","alias_record_ids":["CN-NT-CAT-00552"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%AF%84%E5%BC%9F_(%E6%BA%AB%E7%B4%94)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-6b50-967d-4fee', 0, '猛虎', NULL, NULL, NULL, '猛虎白日行，
心閑貌揚揚。
當路擇人肉，
豬不形相。
頭垂尾不掉，
百獸自然降。
暗禍發所忽，
有機埋路傍。
徐行自踏之，
機飜矢穿腸。
怒吼震林丘，
瓦落兒墮床。
已死不敢近，
目睛射餘光。
虎恃其外，
爪牙利鉤鋩。
人形雖羸弱，
乃中藏。
恃外可摧折，
藏中難測量。
英心多決烈，
自信不猜防。
老狐足姦計，
穴垣墻。
窮冬聽冰渡，
思慮豈不長。
引身入扱中，
將死猶跳踉。
狐姦固堪笑，
虎猛誠可傷。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00947","source_record_id":"CN-NT-CAT-00554","alias_record_ids":["CN-NT-CAT-00554"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%8C%9B%E8%99%8E_(%E6%AD%90%E9%99%BD%E4%BF%AE)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-8d99-4f76', 0, '五絶二首', NULL, NULL, NULL, '國破山河在
人非殿宇空
中興何日是搔首賦《車攻》
國破山河在
宮庭荆棘春
衣冠今左𥙛
忍作北朝臣', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00948","source_record_id":"CN-NT-CAT-00555","alias_record_ids":["CN-NT-CAT-00555"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E4%BA%94%E7%B5%95%E4%BA%8C%E9%A6%96_(%E8%B6%99%E4%BD%B6)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-4f5a-540d', 0, '題葵花蛺蝶圖卷', NULL, '七言絶句', 7, '白露才過催八月，
紫房紅葉共淒涼。
黃花冷淡無人看，
獨自傾心向夕陽。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00949","source_record_id":"CN-NT-CAT-00556","alias_record_ids":["CN-NT-CAT-00556"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%A1%8C%E8%91%B5%E8%8A%B1%E8%9B%BA%E8%9D%B6%E5%9C%96%E5%8D%B7_(%E4%BD%9A%E5%90%8D)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-yuan-99ae-5b50-632f', 0, '題葵花蛺蝶圖卷', NULL, '七言絶句', 7, '繪墨清新德壽宮，
戎葵生意暢西風。
金輝留照傾心矚，
秋在黃裳正色中。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00950","source_record_id":"CN-NT-CAT-00557","alias_record_ids":["CN-NT-CAT-00557"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%A1%8C%E8%91%B5%E8%8A%B1%E8%9B%BA%E8%9D%B6%E5%9C%96%E5%8D%B7_(%E9%A6%AE%E5%AD%90%E6%8C%AF)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-yuan-8d99-5dd6', 0, '題葵花蛺蝶圖卷', NULL, '七言絶句', 7, '香凝御墨曉涼催，
不與凡華一樣開。
日落中原何處在，
傾心誰與酹金杯。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00951","source_record_id":"CN-NT-CAT-00558","alias_record_ids":["CN-NT-CAT-00558"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%A1%8C%E8%91%B5%E8%8A%B1%E8%9B%BA%E8%9D%B6%E5%9C%96%E5%8D%B7_(%E8%B6%99%E5%B7%96)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-yuan-5f35-821c-54a8', 0, '題蒼鷹竹梧圖', NULL, '七言絶句', 7, '華嶽峰高萬里秋，
飛揚初下樹梢頭；
凡鷹戀肉真堪恥，
絛鏇拘拘守臂鞲。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00952","source_record_id":"CN-NT-CAT-00559","alias_record_ids":["CN-NT-CAT-00559"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%A1%8C%E8%92%BC%E9%B7%B9%E7%AB%B9%E6%A2%A7%E5%9C%96_(%E5%BC%B5%E8%88%9C%E5%92%A8)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-yuan-5289-5d69', 0, '題蒼鷹竹梧圖', NULL, '七言絶句', 7, '雄姿挺挺出籠時，
萬里雲霄雲翼遲。
落日無心擊凡鳥，
乘風飛上最高枝。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00953","source_record_id":"CN-NT-CAT-00560","alias_record_ids":["CN-NT-CAT-00560"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%A1%8C%E8%92%BC%E9%B7%B9%E7%AB%B9%E6%A2%A7%E5%9C%96_(%E5%8A%89%E5%B5%A9)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-yuan-85a9-9054-9053', 0, '題蒼鷹竹梧圖', NULL, NULL, NULL, '碧梧翠竹暫為巢，
影落斜陽止處高。
回首楚天秋萬里，
山野雉竟何逃？', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00954","source_record_id":"CN-NT-CAT-00561","alias_record_ids":["CN-NT-CAT-00561"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%A1%8C%E8%92%BC%E9%B7%B9%E7%AB%B9%E6%A2%A7%E5%9C%96_(%E8%96%A9%E9%81%94%E9%81%93)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-yuan-9322-9078', 0, '題白蓮圖卷', NULL, '七言絶句', 7, '嫋嫋瑤池白玉花，
往來青鳥靜無譁。
幽人不飲閑携杖，
但憶清香伴月華。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00955","source_record_id":"CN-NT-CAT-00562","alias_record_ids":["CN-NT-CAT-00562"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%A1%8C%E7%99%BD%E8%93%AE%E5%9C%96%E5%8D%B7_(%E9%8C%A2%E9%81%B8)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-yuan-99ae-5b50-632f', 0, '題白蓮圖卷', NULL, '七言絶句', 7, '水晶宮館舊豪華，
曾結芬陀利上花。
記得匡廬分淨設，
東林無數吉祥葩。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00956","source_record_id":"CN-NT-CAT-00563","alias_record_ids":["CN-NT-CAT-00563"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%A1%8C%E7%99%BD%E8%93%AE%E5%9C%96%E5%8D%B7_(%E9%A6%AE%E5%AD%90%E6%8C%AF)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-yuan-8d99-5dd6', 0, '題白蓮圖卷', NULL, '七言絶句', 7, '湖邊雪壓畫船寬，
太華峰高玉井寒。
席捲碧筩呼夜月，
龍宮飛出白瑤盤。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00957","source_record_id":"CN-NT-CAT-00564","alias_record_ids":["CN-NT-CAT-00564"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%A1%8C%E7%99%BD%E8%93%AE%E5%9C%96%E5%8D%B7_(%E8%B6%99%E5%B7%96)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5289-7199-795a', 0, '絶命詩·其一', NULL, '七言律詩', 7, '倥傯軍旅已逾年，
家室迢遙久別顏。
南北骷髏已作壘，
湖湘宮殿倏成煙。
鵑血不成無塚骨，
烏啼偏集有狐田。
死生遲速皆前定，
堅此丹心映楚天。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00958","source_record_id":"CN-NT-CAT-00566","alias_record_ids":["CN-NT-CAT-00566"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%B5%95%E5%91%BD%E8%A9%A9%C2%B7%E5%85%B6%E4%B8%80_(%E5%8A%89%E7%86%99%E7%A5%9A)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-7d76-547d-8a69', 0, '絶命辭·其二', NULL, '七言律詩', 7, '故園隔別已經年，
今顏非復舊時顏。
山川草木俱含淚，
貔虎旌旗盡作煙。
老婦漫勞成蝶夢，
兒孫切莫種書田。
萇弘化碧非豪事，
留此孤忠向九天。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00959","source_record_id":"CN-NT-CAT-00567","alias_record_ids":["CN-NT-CAT-00567"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%B5%95%E5%91%BD%E8%BE%AD%C2%B7%E5%85%B6%E4%BA%8C_(%E7%B5%95%E5%91%BD%E8%A9%A9)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5289-7199-795a', 0, '絶命詩·其三', NULL, '七言絶句', 7, '人逾五十不為夭，
一世功名今日了。
精忠血噴九霄空，
萬古乾坤終不老。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00960","source_record_id":"CN-NT-CAT-00568","alias_record_ids":["CN-NT-CAT-00568"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%B5%95%E5%91%BD%E8%A9%A9%C2%B7%E5%85%B6%E4%B8%89_(%E5%8A%89%E7%86%99%E7%A5%9A)","review_status":"auto-extracted","review_reasons":[]}')
)
INSERT INTO poems (
  poet_id, poem_no, volume, title_zh, title_ko, category, meter, body_zh,
  is_notable, status, quality, review_memo
)
SELECT
  p.id,
  COALESCE(existing_poem_count.max_poem_no, 0)
    + row_number() OVER (PARTITION BY p.id ORDER BY ip.title_zh, ip.body_zh)::integer,
  ip.volume::integer, ip.title_zh, ip.title_ko, ip.category, ip.meter::integer, ip.body_zh,
  TRUE, ip.status, ip.quality, ip.review_memo
FROM input_poems ip
JOIN poets p ON p.title_id = ip.poet_slug
LEFT JOIN LATERAL (
  SELECT max(poem_no) AS max_poem_no
  FROM poems
  WHERE poet_id = p.id
) existing_poem_count ON TRUE
WHERE NOT EXISTS (
  SELECT 1
  FROM poems existing
  WHERE existing.poet_id = p.id
    AND existing.title_zh = ip.title_zh
    AND existing.body_zh = ip.body_zh
);

UPDATE poets p
SET poem_count = sub.cnt
FROM (
  SELECT poet_id, count(*)::integer AS cnt
  FROM poems
  WHERE poet_id IN (SELECT id FROM poets WHERE title_id IN ('candidate-ming-5f35-55ac', 'candidate-ming-5f35-74a8', 'candidate-ming-5f90-5eb8', 'candidate-ming-9ad8-555f', 'candidate-ming-5510-82b3-7b2c', 'candidate-ming-5f90-71a5', 'candidate-song-9678-904a', 'candidate-song-5b54-5e73-4ef2', 'candidate-song-912d-525b-4e2d', 'candidate-song-65bd-6a1e', 'candidate-song-5f6d-6c5d-792a', 'candidate-ming-674e-6771-967d', 'candidate-ming-5510-4e4b-6df3', 'candidate-ming-9ec3-5c0a-7d20', 'candidate-ming-5c48-5927-5747', 'candidate-yuan-6d2a-7131-7956', 'candidate-yuan-5b8b-8927', 'candidate-song-6c6a-5143-91cf', 'candidate-ming-4faf-606a', 'candidate-ming-4f55-543e-9a36', 'candidate-ming-694a-8d77-5143', 'candidate-ming-90b1-96f2-9704', 'candidate-ming-590f-539f-5409', 'candidate-ming-6bb7-594e', 'candidate-ming-6eab-7d14', 'candidate-song-6b50-967d-4fee', 'candidate-song-8d99-4f76', 'candidate-song-4f5a-540d', 'candidate-yuan-99ae-5b50-632f', 'candidate-yuan-8d99-5dd6', 'candidate-yuan-5f35-821c-54a8', 'candidate-yuan-5289-5d69', 'candidate-yuan-85a9-9054-9053', 'candidate-yuan-9322-9078', 'candidate-ming-5289-7199-795a', 'candidate-ming-7d76-547d-8a69'))
  GROUP BY poet_id
) sub
WHERE p.id = sub.poet_id;

-- Review counts before COMMIT when applying manually:
SELECT quality, status, count(*) FROM poems WHERE quality IN ('cnnt-auto') GROUP BY quality, status ORDER BY quality, status;
SELECT p.era_period, count(pm.id) FROM poets p JOIN poems pm ON pm.poet_id = p.id WHERE p.title_id IN ('candidate-ming-5f35-55ac', 'candidate-ming-5f35-74a8', 'candidate-ming-5f90-5eb8', 'candidate-ming-9ad8-555f', 'candidate-ming-5510-82b3-7b2c', 'candidate-ming-5f90-71a5', 'candidate-song-9678-904a', 'candidate-song-5b54-5e73-4ef2', 'candidate-song-912d-525b-4e2d', 'candidate-song-65bd-6a1e', 'candidate-song-5f6d-6c5d-792a', 'candidate-ming-674e-6771-967d', 'candidate-ming-5510-4e4b-6df3', 'candidate-ming-9ec3-5c0a-7d20', 'candidate-ming-5c48-5927-5747', 'candidate-yuan-6d2a-7131-7956', 'candidate-yuan-5b8b-8927', 'candidate-song-6c6a-5143-91cf', 'candidate-ming-4faf-606a', 'candidate-ming-4f55-543e-9a36', 'candidate-ming-694a-8d77-5143', 'candidate-ming-90b1-96f2-9704', 'candidate-ming-590f-539f-5409', 'candidate-ming-6bb7-594e', 'candidate-ming-6eab-7d14', 'candidate-song-6b50-967d-4fee', 'candidate-song-8d99-4f76', 'candidate-song-4f5a-540d', 'candidate-yuan-99ae-5b50-632f', 'candidate-yuan-8d99-5dd6', 'candidate-yuan-5f35-821c-54a8', 'candidate-yuan-5289-5d69', 'candidate-yuan-85a9-9054-9053', 'candidate-yuan-9322-9078', 'candidate-ming-5289-7199-795a', 'candidate-ming-7d76-547d-8a69') GROUP BY p.era_period ORDER BY p.era_period;

ROLLBACK;
-- COMMIT;
