-- Generated by scripts/build_cn_translation_pipeline_staging.mjs
-- Part: 4/13
-- Purpose: stage CN pre-Tang and Song/Yuan/Ming poems into the JDS translation pipeline.
-- Translator decision: JDS backend=gemini model=gemini-2.5-flash-lite prompt=pipeline/translate/prompts/v5_full.txt.
-- Safety: inserts only missing poet slug + title_zh + body_zh rows. Default ending is ROLLBACK.

BEGIN;

WITH input_poets(slug, name_zh, name_ko, life_raw, era_period, country) AS (
  VALUES
    ('cnpreqin-3fcc3c660d5a7a4d', '佚名/詩經', NULL, NULL, '先秦', 'CN')
)
INSERT INTO poets (title_id, name_zh, name_ko, life_raw, era_period, poem_count)
SELECT slug, name_zh, name_ko, life_raw, era_period, 0
FROM input_poets
ON CONFLICT (title_id) DO UPDATE SET
  name_zh = EXCLUDED.name_zh,
  name_ko = COALESCE(EXCLUDED.name_ko, poets.name_ko),
  life_raw = COALESCE(EXCLUDED.life_raw, poets.life_raw),
  era_period = EXCLUDED.era_period;

WITH input_poems(poet_slug, volume, title_zh, title_ko, category, meter, body_zh, status, quality, review_memo) AS (
  VALUES
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '隰有萇楚', NULL, NULL, NULL, '隰有萇楚，猗儺其枝。夭之沃沃，樂子之無知。
隰有萇楚，猗儺其華。夭之沃沃，樂子之無家。
隰有萇楚，猗儺其實。夭之沃沃，樂子之無室。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00241","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-34-38-2d-96b0-6709-8407-695a-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-96b0-6709-8407-695a","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-34-38-2d-96b0-6709-8407-695a-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-96b0-6709-8407-695a"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%9A%B0%E6%9C%89%E8%90%87%E6%A5%9A","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '匪風', NULL, NULL, NULL, '匪風發兮，匪車偈兮。顧瞻周道，中心怛兮。
匪風飄兮，匪車嘌兮。顧瞻周道，中心弔兮。
誰能亨魚，溉之釜鬵。誰將西歸，懷之好音。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00242","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-34-39-2d-532a-98a8-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-532a-98a8","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-34-39-2d-532a-98a8-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-532a-98a8"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%8C%AA%E9%A2%A8","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '蜉蝣', NULL, NULL, NULL, '蜉蝣之羽，衣裳楚楚。心之憂矣，於我歸處。
蜉蝣之翼，采采衣服。心之憂矣，於我歸息。
蜉蝣掘閱，麻衣如雪。心之憂矣，於我歸說。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00243","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-35-30-2d-8709-8763-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-8709-8763","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-35-30-2d-8709-8763-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-8709-8763"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E8%9C%89%E8%9D%A3","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '候人', NULL, NULL, NULL, '彼候人兮，何戈與祋。彼其之子，三百赤芾。
維鵜在梁，不濡其翼。彼其之子，不稱其服。
維鵜在梁，不濡其咮。彼其之子，不遂其媾。
薈兮蔚兮，南山朝隮。婉兮孌兮，季女斯飢。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00244","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-35-31-2d-5019-4eba-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5019-4eba","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-35-31-2d-5019-4eba-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5019-4eba"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%80%99%E4%BA%BA","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '鳲鳩', NULL, NULL, NULL, '鳲鳩在桑 其子七兮 淑人君子 其儀一兮 其儀一兮 心如結兮
鳲鳩在桑 其子在梅 淑人君子 其帶伊絲 其帶伊絲 其弁伊騏
鳲鳩在桑 其子在棘 淑人君子 其儀不忒 其儀不忒 正是四國
鳲鳩在桑 其子在榛 淑人君子 正是國人 正是國人 胡不萬年', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00245","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-35-32-2d-9cf2-9ce9-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9cf2-9ce9","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-35-32-2d-9cf2-9ce9-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9cf2-9ce9"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%B3%B2%E9%B3%A9","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '下泉', NULL, NULL, NULL, '洌彼下泉，浸彼苞稂。愾我寤嘆，念彼周京。
洌彼下泉，浸彼苞蕭。愾我寤嘆，念彼京周。
洌彼下泉，浸彼苞蓍。愾我寤嘆，念彼京師。
芃芃黍苗，陰雨膏之。四國有王，郇伯勞之。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00246","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-35-33-2d-4e0b-6cc9-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-4e0b-6cc9","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-35-33-2d-4e0b-6cc9-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-4e0b-6cc9"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E4%B8%8B%E6%B3%89","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '七月', NULL, NULL, NULL, '七月流火，九月授衣。一之日觱發，二之日栗烈。
無衣無褐，何以卒歲？三之日于耜，四之日舉趾。同我婦子，饁彼南畝。田畯至喜。
七月流火，九月授衣。春日載陽，有鳴倉庚。
女執懿筐，遵彼微行，爰求柔桑。春日遲遲。采蘩祁祁。女心傷悲，殆及公子同歸。
七月流火，八月萑葦。蠶月條桑，取彼斧斨。
以伐遠揚，猗彼女桑。七月鳴鵙，八月載績，載玄載黃。我朱孔陽，為公子裳。
四月秀葽，五月鳴蜩，八月其穫，十月隕蘀。
一之日于貉，取彼狐貍，為公子裘。二之日其同，載纘武功，言私其豵，獻豜于公。
五月斯螽動股，六月莎雞振羽，七月在野，八月在宇，
九月在戶，十月蟋蟀入我牀下。穹窒熏鼠，塞向墐戶。嗟我婦子，曰為改歲。入此室處。
六月食鬱及薁，七月亨葵及菽，八月剝棗，十月穫稻。
為此春酒，以介眉壽。七月食瓜，八月斷壺，九月叔苴，采荼薪樗，食我農夫。
九月築場圃，十月納禾稼。黍稷重穋，禾麻菽麥。
嗟我農夫，我稼既同，上入執宮功。晝爾于茅，宵爾索綯。亟其乘屋，其始播百穀。
二之日鑿冰沖沖，三之日納于凌陰，四之日其蚤，獻羔祭韭。
九月肅霜，十月滌場。朋酒斯饗，曰殺羔羊。躋彼公堂，稱彼兕觥。萬壽無疆。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00247","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-35-34-2d-4e03-6708-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-4e03-6708","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-35-34-2d-4e03-6708-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-4e03-6708"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E4%B8%83%E6%9C%88","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '鴟鴞', NULL, NULL, NULL, '鴟鴞鴟鴞，既取我子，無毀我室！恩斯勤斯，鬻子之閔斯。
迨天之未陰雨，徹彼桑土。綢繆牖戶。今女下民，或敢侮予。
予手拮據，予所捋荼。予所蓄租，予口卒瘏。曰予未有室家。
予羽譙譙，予尾翛翛。予室翹翹，風雨所漂搖。予維音嘵嘵。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00248","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-35-35-2d-9d1f-9d1e-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9d1f-9d1e","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-35-35-2d-9d1f-9d1e-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9d1f-9d1e"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%B4%9F%E9%B4%9E","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '東山', NULL, NULL, NULL, '我徂東山，慆慆不歸。我來自東，零雨其濛。我東曰歸，我心西悲。
制彼裳衣，勿士行枚。蜎蜎者蠋，烝在桑野。敦彼獨宿，亦在車下。
我徂東山，慆慆不歸。我來自東，零雨其濛。果臝之實，亦施于宇。
伊威在室，蠨蛸在戶。町畽鹿場，熠燿宵行。不可畏也，伊可懷也。
我徂東山，慆慆不歸。我來自東，零雨其濛。鸛鳴于垤，婦歎于室。
洒埽穹窒，我征聿至。有敦瓜苦，烝在栗薪。自我不見，于今三年。
我徂東山，慆慆不歸。我來自東，零雨其濛。倉庚于飛，熠燿其羽。
之子于歸，皇駁其馬。親結其縭，九十其儀。其新孔嘉，其舊如之何？', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00249","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-35-36-2d-6771-5c71-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6771-5c71","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-35-36-2d-6771-5c71-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6771-5c71"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%9D%B1%E5%B1%B1","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '破斧', NULL, NULL, NULL, '既破我斧，又缺我斨。周公東征，四國是皇。哀我人斯，亦孔之將。
既破我斧，又缺我錡。周公東征，四國是吪。哀我人斯，亦孔之嘉。
既破我斧，又缺我銶。周公東征，四國是遒。哀我人斯，亦孔之休。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00250","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-35-37-2d-7834-65a7-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7834-65a7","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-35-37-2d-7834-65a7-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7834-65a7"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E7%A0%B4%E6%96%A7","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '伐柯', NULL, NULL, NULL, '伐柯如何？匪斧不克。取妻如何？匪媒不得。
伐柯伐柯，其則不遠。我覯之子？籩豆有踐。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00251","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-35-38-2d-4f10-67ef-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-4f10-67ef","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-35-38-2d-4f10-67ef-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-4f10-67ef"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E4%BC%90%E6%9F%AF","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '九罭', NULL, NULL, NULL, '九罭之魚，鱒魴。我覯之子，袞衣繡裳。
鴻飛遵渚，公歸無所。於女信處。
鴻飛遵陸，公歸不復。於女信宿。
是以有袞衣兮，無以我公歸兮，無使我心悲兮。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00252","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-35-39-2d-4e5d-7f6d-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-4e5d-7f6d","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-35-39-2d-4e5d-7f6d-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-4e5d-7f6d"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E4%B9%9D%E7%BD%AD","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '狼跋', NULL, NULL, NULL, '狼跋其胡，載疐其尾。公孫碩膚，赤舄几几。
狼疐其尾，載跋其胡。公孫碩膚，德音不瑕。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00253","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-36-30-2d-72fc-8dcb-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-72fc-8dcb","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-36-30-2d-72fc-8dcb-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-72fc-8dcb"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E7%8B%BC%E8%B7%8B","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '鹿鳴', NULL, NULL, NULL, '呦呦鹿鳴，食野之苹。我有嘉賓，鼓瑟吹笙。
吹笙鼓簧，承筐是將。人之好我，示我周行。
呦呦鹿鳴，食野之蒿。我有嘉賓，德音孔昭。
視民不恌，君子是則是傚。我有旨酒，嘉賓式燕以敖。
呦呦鹿鳴，食野之芩。我有嘉賓，鼓瑟鼓琴。
鼓瑟鼓琴，和樂且湛。我有旨酒，以燕樂嘉賓之心。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00254","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-36-31-2d-9e7f-9cf4-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9e7f-9cf4","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-36-31-2d-9e7f-9cf4-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9e7f-9cf4"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%B9%BF%E9%B3%B4","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '四牡', NULL, NULL, NULL, '四牡騑騑，周道倭遲。豈不懷歸？王事靡盬，我心傷悲。
四牡騑騑，嘽嘽駱馬。豈不懷歸？王事靡盬，不遑啟處。
翩翩者鵻，載飛載下，集于苞栩。王事靡盬，不遑將父。
翩翩者鵻，載飛載止，集于苞杞。王事靡盬，不遑將母。
駕彼四駱，載驟駸駸。豈不懷歸？是用作歌，將母來諗。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00255","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-36-32-2d-56db-7261-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-56db-7261","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-36-32-2d-56db-7261-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-56db-7261"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%9B%9B%E7%89%A1","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '皇皇者華', NULL, NULL, NULL, '皇皇者華，于彼原隰。駪駪征夫，每懷靡及。
我馬維駒，六轡如濡。載馳載驅，周爰咨諏。
我馬維騏，六轡如絲。載馳載驅，周爰咨謀。
我馬維駱，六轡沃若。載馳載驅，周爰咨度。
我馬維駰，六轡既均。載馳載驅，周爰咨詢。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00256","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-36-33-2d-7687-7687-8005-83ef-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7687-7687-8005-83ef","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-36-33-2d-7687-7687-8005-83ef-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7687-7687-8005-83ef"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E7%9A%87%E7%9A%87%E8%80%85%E8%8F%AF","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '常棣', NULL, NULL, NULL, '常棣之華，鄂不韡韡。凡今之人，莫如兄弟。
死喪之威，兄弟孔懷。原隰裒矣，兄弟求矣。
脊令在原，兄弟急難。每有良朋，況也永歎。
兄弟鬩于牆，外禦其務。每有良朋，蒸也無戎。
喪亂既平，既安且寧。雖有兄弟，不如友生。
儐爾籩豆，飲酒之飫。兄弟既具，和樂且孺。
妻子好合，如鼓瑟琴。兄弟既翕，和樂且湛。
宜爾室家，樂爾妻孥。是究是圖，亶其然乎。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00257","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-36-34-2d-5e38-68e3-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5e38-68e3","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-36-34-2d-5e38-68e3-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5e38-68e3"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%B8%B8%E6%A3%A3","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '伐木', NULL, NULL, NULL, '伐木丁丁，鳥鳴嚶嚶。出自幽谷，遷于喬木。嚶其鳴矣，求其友聲。
相彼鳥矣，猶求友聲。矧伊人矣，不求友生。神之聽之，終和且平。
伐木許許，釃酒有藇。既有肥羜，以速諸父。寧適不來？微我弗顧。
於粲洒埽，陳饋八簋。既有肥牡，以速諸舅。寧適不來？微我有咎。
伐木于阪，釃酒有衍，籩豆有踐，兄弟無遠。民之失德，乾餱以愆。
有酒湑我，無酒酤我。坎坎鼓我，蹲蹲舞我。迨我暇矣！飲此湑矣！', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00258","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-36-35-2d-4f10-6728-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-4f10-6728","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-36-35-2d-4f10-6728-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-4f10-6728"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E4%BC%90%E6%9C%A8","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '天保', NULL, NULL, NULL, '天保定爾，亦孔之固。俾爾單厚，何福不除？俾爾多益，以莫不庶。
天保定爾，俾爾戩穀。罄無不宜，受天百祿。降爾遐福，維日不足。
天保定爾，以莫不興！如山如阜，如岡如陵。如川之方至，以莫不增。
吉蠲為饎，是用孝享。禴祠烝嘗，于公先王。君曰卜爾，萬壽無疆！
神之弔矣，詒爾多福。民之質矣，日用飲食。羣黎百姓，徧為爾德。
如月之恆，如日之升。如南山之壽，不騫不崩。如松柏之茂，無不爾或承。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00259","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-36-36-2d-5929-4fdd-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5929-4fdd","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-36-36-2d-5929-4fdd-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5929-4fdd"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%A4%A9%E4%BF%9D","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '采薇', NULL, NULL, NULL, '采薇采薇，薇亦作止。曰歸曰歸，歲亦莫止。
靡室靡家，玁狁之故。不遑啟居，玁狁之故。
采薇采薇，薇亦柔止。曰歸曰歸，心亦憂止。
憂心烈烈，載飢載渴。我戍未定，靡使歸聘。
采薇采薇，薇亦剛止。曰歸曰歸，歲亦陽止。
王事靡盬。不遑啟處。憂心孔疚，我行不來。
彼爾維何？維常之華。彼路斯何？君子之車。
戎車既駕，四牡業業。豈敢定居？一月三捷。
駕彼四牡，四牡騤騤。君子所依，小人所腓。
四牡翼翼，象弭魚服。豈不日戒，玁狁孔棘！
昔我往矣，楊柳依依。今我來思，雨雪霏霏。
行道遲遲，載渴載飢。我心傷悲，莫知我哀！', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00260","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-36-37-2d-91c7-8587-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-91c7-8587","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-36-37-2d-91c7-8587-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-91c7-8587"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%87%87%E8%96%87","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '出車', NULL, NULL, NULL, '我出我車，于彼牧矣。自天子所，謂我來矣。
召彼僕夫，謂之載矣。王事多難，維其棘矣。
我出我車，于彼郊矣。設此旐矣，建彼旄矣。
彼旟旐斯，胡不斾斾？憂心悄悄，僕夫況瘁。
王命南仲，往城于方。出車彭彭，旂旐央央。
天子命我，城彼朔方。赫赫南仲，玁狁于襄。
昔我往矣，黍稷方華。今我來思，雨雪載塗。
王事多難，不遑啟居。豈不懷歸？畏此簡書。
喓喓草蟲，趯趯阜螽。未見君子，憂心忡忡。
既見君子，我心則降。赫赫南仲，薄伐西戎。
春日遲遲，卉木萋萋。倉庚喈喈，采蘩祁祁。
執訊獲醜，薄言還歸。赫赫南仲，玁狁于夷。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00261","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-36-38-2d-51fa-8eca-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-51fa-8eca","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-36-38-2d-51fa-8eca-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-51fa-8eca"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%87%BA%E8%BB%8A","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '魚麗', NULL, NULL, NULL, '魚麗于罶，鱨鯊。君子有酒，旨且多。
魚麗于罶，魴鱧。君子有酒，多且旨。
魚麗于罶，鰋鯉。君子有酒，旨且有。
物其多矣，維其嘉矣。
物其旨矣，維其偕矣。
物其有矣，維其時矣。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00262","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-37-30-2d-9b5a-9e97-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9b5a-9e97","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-37-30-2d-9b5a-9e97-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9b5a-9e97"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%AD%9A%E9%BA%97","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '白華', NULL, NULL, NULL, '白華菅兮，白茅束兮。之子之遠，俾我獨兮。
英英白雲，露彼菅茅。天步艱難，之子不猶。
滮池北流，浸彼稻田。嘯歌傷懷，念彼碩人。
樵彼桑薪，卬烘于煁。維彼碩人，實勞我心。
鼓鍾于宮，聲聞于外。念子懆懆，視我邁邁。
有鶖在梁，有鶴在林。維彼碩人，實勞我心。
鴛鴦在梁，戢其左翼。之子無良，二三其德。
有扁斯石，履之卑兮。之子之遠，俾我疧兮。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00263","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-33-35-2d-767d-83ef-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-767d-83ef","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-33-35-2d-767d-83ef-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-767d-83ef"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E7%99%BD%E8%8F%AF","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '南有嘉魚', NULL, NULL, NULL, '南有嘉魚，烝然罩罩。君子有酒，嘉賓式燕以樂。
南有嘉魚，烝然汕汕。君子有酒，嘉賓式燕以衎。
南有樛木，甘瓠纍之。君子有酒，嘉賓式燕綏之。
翩翩者鵻，烝然來思。君子有酒，嘉賓式燕又思。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00264","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-37-34-2d-5357-6709-5609-9b5a-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5357-6709-5609-9b5a","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-37-34-2d-5357-6709-5609-9b5a-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5357-6709-5609-9b5a"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%8D%97%E6%9C%89%E5%98%89%E9%AD%9A","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '南山有臺', NULL, NULL, NULL, '南山有臺，北山有萊。樂只君子，邦家之基。樂只君子，萬壽無期。
南山有桑，北山有楊。樂只君子，邦家之光。樂只君子，萬壽無疆。
南山有杞，北山有李。樂只君子，民之父母。樂只君子，德音不已。
南山有栲，北山有杻。樂只君子，遐不眉壽。樂只君子，德音是茂。
南山有枸，北山有楰。樂只君子，遐不黃耇。樂只君子，保艾爾後。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00265","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-37-35-2d-5357-5c71-6709-81fa-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5357-5c71-6709-81fa","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-37-35-2d-5357-5c71-6709-81fa-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5357-5c71-6709-81fa"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%8D%97%E5%B1%B1%E6%9C%89%E8%87%BA","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '蓼蕭', NULL, NULL, NULL, '蓼彼蕭斯，零露湑兮。既見君子，我心寫兮。燕笑語兮，是以有譽處兮。
蓼彼蕭斯，零露瀼瀼。既見君子，為龍為光。其德不爽，壽考不忘。
蓼彼蕭斯，零露泥泥。既見君子，孔燕豈弟。宜兄宜弟，令德壽豈。
蓼彼蕭斯，零露濃濃。既見君子，鞗革忡忡。和鸞雝雝，萬福攸同。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00266","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-37-39-2d-84fc-856d-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-84fc-856d","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-37-39-2d-84fc-856d-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-84fc-856d"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E8%93%BC%E8%95%AD","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '湛露', NULL, NULL, NULL, '湛湛露斯，匪陽不晞。厭厭夜飲，不醉無歸。
湛湛露斯，在彼豐草。厭厭夜飲，在宗載考。
湛湛露斯，在彼杞棘。顯允君子，莫不令德。
其桐其椅，其實離離。豈弟君子，莫不令儀。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00267","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-38-30-2d-6e5b-9732-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6e5b-9732","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-38-30-2d-6e5b-9732-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6e5b-9732"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%B9%9B%E9%9C%B2","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '彤弓', NULL, NULL, NULL, '彤弓弨兮，受言藏之。我有嘉賓，中心貺之。鐘鼓既設，一朝饗之。
彤弓弨兮，受言載之。我有嘉賓，中心喜之。鐘鼓既設，一朝右之。
彤弓弨兮，受言櫜之。我有嘉賓，中心好之。鐘鼓既設，一朝醻之。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00268","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-38-31-2d-5f64-5f13-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5f64-5f13","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-38-31-2d-5f64-5f13-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5f64-5f13"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%BD%A4%E5%BC%93","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '菁菁者莪', NULL, NULL, NULL, '菁菁者莪，在彼中阿，既見君子，樂且有儀。
菁菁者莪，在彼中沚，既見君子，我心則喜。
菁菁者莪，在彼中陵，既見君子，錫我百朋。
汎汎楊舟，載沈載浮，既見君子，我心則休。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00269","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-38-32-2d-83c1-83c1-8005-83aa-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-83c1-83c1-8005-83aa","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-38-32-2d-83c1-83c1-8005-83aa-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-83c1-83c1-8005-83aa"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E8%8F%81%E8%8F%81%E8%80%85%E8%8E%AA","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '蓼莪', NULL, NULL, NULL, '蓼蓼者莪，匪莪伊蒿。
哀哀父母，生我劬勞。
蓼蓼者莪，匪莪伊蔚。
哀哀父母，生我勞瘁。
缾之罄矣，維罍之恥。
鮮民之生，不如死之久矣。
無父何怙？無母何恃？
出則銜恤，入則靡至。
父兮生我，母兮鞠我，拊我、畜我、長我、育我、
顧我、復我、出入腹我。欲報之德，昊天罔極。
南山烈烈，飄風發發。
民莫不穀，我獨何害？
南山律律，飄風弗弗。
民莫不穀，我獨不卒！', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00270","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-30-38-2d-84fc-83aa-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-84fc-83aa","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-30-38-2d-84fc-83aa-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-84fc-83aa"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E8%93%BC%E8%8E%AA","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '六月', NULL, NULL, NULL, '六月棲棲，戎車既飭。四牡騤騤，載是常服。
玁狁孔熾，我是用急。王于出征，以匡王國。
比物四驪，閑之維則。維此六月，既成我服。
我服既成，于三十里。王于出征，以佐天子。
四牡脩廣，其大有顒。薄伐玁狁，以奏膚公。
有嚴有翼，共武之服。共武之服，以定王國。
玁狁匪茹，整居焦穫。侵鎬及方，至于涇陽。
織文鳥章，白斾央央。元戎十乘，以先啟行。
戎車既安，如輊如軒。四牡既佶，既佶且閑。
薄伐玁狁，至于大原。文武吉甫，萬邦為憲。
吉甫燕喜，既多受祉。來歸自鎬，我行永久。
飲御諸友，炰鱉膾鯉。侯誰在矣？張仲孝友。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00271","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-38-33-2d-516d-6708-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-516d-6708","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-38-33-2d-516d-6708-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-516d-6708"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%85%AD%E6%9C%88","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '采芑', NULL, NULL, NULL, '薄言采芑，于彼新田，于此菑畝。
方叔涖止，其車三千，師乾之試。
方叔率止，乘其四騏，四騏翼翼。
路車有奭，簟茀魚服，鉤膺鞗革。
薄言采芑，于彼新田，于此中鄉。
方叔涖止，其車三千，旂旐央央。
方叔率止，約軧錯衡，八鸞瑲瑲。
服其命服，朱芾斯皇，有瑲蔥珩。
鴥彼飛隼，其飛戾天，亦集爰止。
方叔涖止，其車三千，師乾之試。
方叔率止，鉦人伐鼓，陳師鞠旅。
顯允方叔，伐鼓淵淵，振旅闐闐。
蠢爾蠻荊，大邦為讎。
方叔元老，克壯其猶。
方叔率止，執訊獲醜。
戎車嘽嘽，嘽嘽焞焞，如霆如雷。
顯允方叔，征伐玁狁，蠻荊來威。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00272","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-38-34-2d-91c7-8291-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-91c7-8291","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-38-34-2d-91c7-8291-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-91c7-8291"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%87%87%E8%8A%91","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '車攻', NULL, NULL, NULL, '我車既攻，我馬既同。四牡龐龐，駕言徂東。
田車既好，四牡孔阜。東有甫草，駕言行狩。
之子于苗，選徒嚻嚻。建旐設旄，搏獸于敖。
駕彼四牡，四牡奕奕。赤芾金舄，會同有繹。
決拾既佽，弓矢既調。射夫既同，助我舉柴。
四黃既駕，兩驂不猗。不失其馳，舍矢如破。
蕭蕭馬鳴，悠悠斾旌。徒御不驚，大庖不盈。
之子于征，有聞無聲。允矣君子，展也大成。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00273","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-38-35-2d-8eca-653b-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-8eca-653b","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-38-35-2d-8eca-653b-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-8eca-653b"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E8%BB%8A%E6%94%BB","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '吉日', NULL, NULL, NULL, '吉日維戊，既伯既禱。田車既好，四牡孔阜。升彼大阜，從其羣醜。
吉日庚午，既差我馬。獸之所同，麀鹿麌麌。漆沮之從，天子之所。
瞻彼中原，其祁孔有。儦儦俟俟，或羣或友。悉率左右，以燕天子。
既張我弓，既挾我矢。發彼小豝，殪此大兕。以御賓客，且以酌醴。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00274","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-38-36-2d-5409-65e5-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5409-65e5","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-38-36-2d-5409-65e5-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5409-65e5"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%90%89%E6%97%A5","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '鴻鴈', NULL, NULL, NULL, '鴻鴈于飛，肅肅其羽。之子于征，劬勞于野。爰及矜人，哀此鰥寡。
鴻鴈于飛，集于中澤。之子于垣，百堵皆作。雖則劬勞，其究安宅。
鴻鴈于飛，哀鳴嗸嗸。維此哲人，謂我劬勞。維彼愚人，謂我宣驕。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00275","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-38-37-2d-9d3b-9d08-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9d3b-9d08","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-38-37-2d-9d3b-9d08-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9d3b-9d08"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%B4%BB%E9%B4%88","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '庭燎', NULL, NULL, NULL, '夜如何其？夜未央。庭燎之光，君子至止，鸞聲將將。
夜如何其？夜未艾。庭燎晣晣，君子至止，鸞聲噦噦。
夜如何其？夜鄉晨。庭燎有煇，君子至止，言觀其旂。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00276","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-38-38-2d-5ead-71ce-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5ead-71ce","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-38-38-2d-5ead-71ce-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5ead-71ce"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%BA%AD%E7%87%8E","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '沔水', NULL, NULL, NULL, '沔彼流水，朝宗于海。鴥彼飛隼，載飛載止。
嗟我兄弟，邦人諸友。莫肯念亂，誰無父母？
沔彼流水，其流湯湯。鴥彼飛隼，載飛載揚。
念彼不蹟，載起載行。心之憂矣，不可弭忘。
鴥彼飛隼，率彼中陵。
民之訛言，寧莫之懲？我友敬矣，讒言其興。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00277","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-38-39-2d-6c94-6c34-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6c94-6c34","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-38-39-2d-6c94-6c34-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6c94-6c34"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%B2%94%E6%B0%B4","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '鶴鳴', NULL, NULL, NULL, '鶴鳴于九皐，聲聞于野。魚潛在淵，或在于渚。
樂彼之園，爰有樹檀，其下維蘀。他山之石，可以為錯。
鶴鳴于九皐，聲聞于天。魚在于渚，或潛在淵。
樂彼之園，爰有樹檀，其下維穀。他山之石，可以攻玉。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00278","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-39-30-2d-9db4-9cf4-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9db4-9cf4","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-39-30-2d-9db4-9cf4-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9db4-9cf4"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%B6%B4%E9%B3%B4","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '祈父', NULL, NULL, NULL, '祈父！予王之爪牙，胡轉予于恤？靡所止居。
祈父！予王之爪士，胡轉予于恤？靡所厎止。
祈父！亶不聦，胡轉予于恤？有母之尸饔。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00279","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-39-31-2d-7948-7236-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7948-7236","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-39-31-2d-7948-7236-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7948-7236"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E7%A5%88%E7%88%B6","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '白駒', NULL, NULL, NULL, '皎皎白駒，食我場苗。縶之維之，以永今朝。所謂伊人，於焉逍遙。
皎皎白駒，食我場藿。縶之維之，以永今夕。所謂伊人，於焉嘉客。
皎皎白駒，賁然來思。爾公爾侯，逸豫無期。慎爾優遊，勉爾遁思。
皎皎白駒，在彼空谷，生芻一束。其人如玉，毋金玉爾音，而有遐心。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00280","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-39-32-2d-767d-99d2-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-767d-99d2","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-39-32-2d-767d-99d2-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-767d-99d2"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E7%99%BD%E9%A7%92","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '我行其野', NULL, NULL, NULL, '我行其野，蔽芾其樗。昏姻之故，言就爾居。爾不我畜，復我邦家。
我行其野，言采其蓫。昏姻之故，言就爾宿。爾不我畜，言歸斯復。
我行其野，言采其葍。不思舊姻，求爾新特。成不以富，亦祗以異。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00281","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-39-34-2d-6211-884c-5176-91ce-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6211-884c-5176-91ce","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-39-34-2d-6211-884c-5176-91ce-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6211-884c-5176-91ce"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%88%91%E8%A1%8C%E5%85%B6%E9%87%8E","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '斯乾', NULL, NULL, NULL, '秩秩斯乾，幽幽南山。如竹苞矣，如松茂矣。
兄及弟矣，式相好矣，無相猶矣。
似續妣祖，築室百堵。
西南其戶，爰居爰處，爰笑爰語。
約之閣閣，椓之橐橐。
風雨攸除，鳥鼠攸去，君子攸芋。
如跂斯翼，如矢斯棘。
如鳥斯革，如翬斯飛。君子攸躋。
殖殖其庭，有覺其楹。
噲噲其正，噦噦其冥。君子攸寧。
下莞上簟，乃安斯寢。乃寢乃興，乃占我夢。
吉夢維何？維熊維羆，維虺維蛇。
大人占之，維熊維羆，男子之祥。
維虺維蛇，女子之祥。
乃生男子，載寢之牀。載衣之裳，載弄之璋。
其泣喤喤，朱芾斯皇，室家君王。
乃生女子，載寢之地。載衣之裼，載弄之瓦。
無非無儀，唯酒食是議，無父母詒罹。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00282","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-39-35-2d-65af-4e7e-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-65af-5e72","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-39-35-2d-65af-4e7e-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-65af-5e72"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%96%AF%E5%B9%B2","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '無羊', NULL, NULL, NULL, '誰謂爾無羊？三百維羣。誰謂爾無牛？九十其犉。
爾羊來思，其角濈濈，爾牛來思，其耳濕濕。
或降于阿，或飲于池。或寢或訛，爾牧來思。
何蓑何笠，或負其餱。三十維物，爾牲則具。
爾牧來思，以薪以蒸。以雌以雄，爾羊來思。
矜矜兢兢，不騫不崩。麾之以肱，畢來既升。
牧人乃夢，衆維魚矣。旐維旟矣，大人占之。
衆維魚矣，實維豐年。旐維旟矣，室家溱溱。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00283","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-39-36-2d-7121-7f8a-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7121-7f8a","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-39-36-2d-7121-7f8a-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7121-7f8a"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E7%84%A1%E7%BE%8A","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '大東', NULL, NULL, NULL, '有饛簋飧，有捄棘匕。周道如砥，其直如矢。
君子所履，小人所視。睠言顧之，澘焉出涕。
小東大東，杼柚其空。糾糾葛屨，可以履霜。
佻佻公子，行彼周行。既往既來，使我心疚。
有洌氿泉，無浸穫薪。契契寤歎，哀我憚人。
薪是穫薪，尚可載也。哀我憚人，亦可息也。
東人之子，職勞不來。西人之子，粲粲衣服。
舟人之子，熊羆是裘。私人之子，百僚是試。
或以其酒，不以其漿。鞙鞙佩璲，不以其長。
維天有漢，監亦有光。跂彼織女，終日七襄。
雖則七襄，不成報章。睆彼牽牛，不以服箱。
東有啟明，西有長庚。有捄天畢，載施之行。
維南有箕，不可以簸揚。維北有鬥，不可以挹酒漿。
維南有箕，載翕其舌。維北有鬥，西柄之揭。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00284","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-30-39-2d-5927-6771-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5927-6771","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-30-39-2d-5927-6771-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5927-6771"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%A4%A7%E6%9D%B1","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '四月', NULL, NULL, NULL, '四月維夏，六月徂暑。先祖匪人？胡寧忍予？
秋日淒淒，百卉具腓。亂離瘼矣，爰其適歸？
冬日烈烈，飄風發發。民莫不穀，我獨何害？
山有嘉卉，侯栗侯梅。廢為殘賊，莫知其尤。
相彼泉水，載清載濁。我日構禍，曷雲能穀？
滔滔江漢，南國之紀。盡瘁以仕，寧莫我有。
匪鶉匪鳶，翰飛戾天。匪鱣匪鮪，濳逃于淵。
山有蕨薇，隰有杞桋。君子作歌，維以告哀。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00285","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-31-30-2d-56db-6708-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-56db-6708","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-31-30-2d-56db-6708-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-56db-6708"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%9B%9B%E6%9C%88","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '北山', NULL, NULL, NULL, '陟彼北山，言采其杞。偕偕士子，朝夕從事。王事靡盬，憂我父母。
溥天之下，莫非王土。率土之濱，莫非王臣。大夫不均，我從事獨賢。
四牡彭彭，王事傍傍。嘉我未老，鮮我方將。旅力方剛，經營四方。
或燕燕居息，或盡瘁事國；或息偃在牀，或不已于行。
或不知叫號，或慘慘劬勞；或棲遲偃仰，或王事鞅掌。
或湛樂飲酒，或慘慘畏咎；或出入風議，或靡事不為。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00286","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-31-31-2d-5317-5c71-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5317-5c71","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-31-31-2d-5317-5c71-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5317-5c71"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%8C%97%E5%B1%B1","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '無將大車', NULL, NULL, NULL, '無將大車，祇自塵兮。無思百憂，祇自疷兮。
無將大車，維塵冥冥。無思百憂，不出于熲。
無將大車，維塵雍兮。無思百憂，祇自重兮。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00287","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-31-32-2d-7121-5c07-5927-8eca-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7121-5c07-5927-8eca","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-31-32-2d-7121-5c07-5927-8eca-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7121-5c07-5927-8eca"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E7%84%A1%E5%B0%87%E5%A4%A7%E8%BB%8A","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '小明', NULL, NULL, NULL, '明明上天，照臨下土。我征徂西，至于艽野。二月初吉，載離寒暑。
心之憂矣，其毒大苦。念彼共人，涕零如雨。豈不懷歸？畏此罪罟。
昔我往矣，日月方除。曷雲其還？歲聿雲莫。念我獨兮，我事孔庶。
心之憂矣，憚我不暇。念彼共人，睠睠懷顧。豈不懷歸？畏此譴怒。
昔我往矣，日月方奧。曷雲其還，政事愈蹙。歲聿雲莫，采蕭穫菽。
心之憂矣，自詒伊戚。念彼共人，興言出宿。豈不懷歸？畏此反覆。
嗟爾君子，無恆安處。靖共爾位，正直是與。神之聽之，式穀以女。
嗟爾君子，無恆安息。靖共爾位，好是正直。神之聽之，介爾景福。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00288","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-31-33-2d-5c0f-660e-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5c0f-660e","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-31-33-2d-5c0f-660e-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5c0f-660e"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%B0%8F%E6%98%8E","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '鼓鍾', NULL, NULL, NULL, '鼓鍾將將，淮水湯湯。憂心且傷。淑人君子，懷允不忘。
鼓鍾喈喈，淮水湝湝。憂心且悲。淑人君子，其德不回。
鼓鍾伐鼛，淮有三洲。憂心且妯。淑人君子，其德不猶。
鼓鍾欽欽，鼓瑟鼓琴。笙磬同音。以雅以南，以籥不僭。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00289","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-31-34-2d-9f13-937e-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9f13-937e","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-31-34-2d-9f13-937e-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9f13-937e"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%BC%93%E9%8D%BE","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '楚茨', NULL, NULL, NULL, '楚楚者茨，言抽其棘。自昔何為？我蓺黍稷。
我黍與與，我稷翼翼。我倉既盈，我庾維億。
以為酒食，以享以祀。以妥以侑，以介景福。
濟濟蹌蹌，絜爾牛羊，以往烝嘗。
或剝或亨，或肆或將，祝祭于祊。
祀事孔明，先祖是皇，神保是饗。
孝孫有慶，報以介福，萬壽無疆。
執爨踖踖，為俎孔碩，或燔或炙。
君婦莫莫，為豆孔庶，為賓為客。
獻醻交錯，禮儀卒度，笑語卒獲。
神保是格，報以介福，萬壽攸酢。
我孔熯矣，式禮莫愆。工祝致告，徂賚孝孫。
苾芬孝祀，神嗜飲食。卜爾百福，如幾如式。
既齊既稷，既匡既勑。永錫爾極，時萬時億。
禮儀既備，鍾鼓既戒。孝孫徂位，工祝致告。
神具醉止，皇尸載起。鼓鍾送尸，神保聿歸。
諸宰君婦，廢徹不遲。諸父兄弟，備言燕私。
樂具入奏，以綏後祿。爾殽既將，莫怨具慶。
既醉既飽，小大稽首。神嗜飲食，使君壽考。
孔惠孔時，維其盡之。子子孫孫，勿替引之。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00290","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-31-35-2d-695a-8328-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-695a-8328","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-31-35-2d-695a-8328-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-695a-8328"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%A5%9A%E8%8C%A8","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '信南山', NULL, NULL, NULL, '信彼南山，維禹甸之。畇畇原隰，曾孫田之。我疆我理，南東其畝。
上天同雲，雨雪雰雰。益之以霢霂，既優既渥。既霑既足，生我百穀。
疆埸翼翼，黍稷彧彧。曾孫之穡，以為酒食。畀我尸賓，壽考萬年。
中田有廬，疆埸有瓜。是剝是菹，獻之皇祖。曾孫壽考，受天之祜。
祭以清酒，從以騂牡，享于祖考。執其鸞刀，以啟其毛，取其血膋。
是烝是享，苾苾芬芬。祀事孔明，先祖是皇。報以介福，萬壽無疆。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00291","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-31-36-2d-4fe1-5357-5c71-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-4fe1-5357-5c71","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-31-36-2d-4fe1-5357-5c71-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-4fe1-5357-5c71"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E4%BF%A1%E5%8D%97%E5%B1%B1","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '大田', NULL, NULL, NULL, '大田多稼，既種既戒。既備乃事，以我覃耜。
俶載南畝，播厥百穀。既庭且碩，曾孫是若。
既方既皁，既堅既好，不稂不莠。
去其螟螣，及其蟊賊，無害我田穉。
田祖有神，秉畀炎火。
有渰萋萋，興雨祁祁，雨我公田，遂及我私。
彼有不穫穉，此有不斂穧。彼有遺秉，此有滯穗。伊寡婦之利。
曾孫來止，以其婦子，饁彼南畝。田畯至喜。
來方禋祀，以其騂黑。與其黍稷，以享以祀，以介景福。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00292","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-31-38-2d-5927-7530-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5927-7530","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-31-38-2d-5927-7530-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5927-7530"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%A4%A7%E7%94%B0","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '瞻彼洛矣', NULL, NULL, NULL, '瞻彼洛矣，維水泱泱。君子至止，福祿如茨。韎韐有奭，以作六師。
瞻彼洛矣，維水泱泱。君子至止，鞸琫有珌。君子萬年，保其家室。
瞻彼洛矣，維水泱泱。君子至止，福祿既同。君子萬年，保其家邦。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00293","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-31-39-2d-77bb-5f7c-6d1b-77e3-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-77bb-5f7c-6d1b-77e3","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-31-39-2d-77bb-5f7c-6d1b-77e3-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-77bb-5f7c-6d1b-77e3"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E7%9E%BB%E5%BD%BC%E6%B4%9B%E7%9F%A3","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '裳裳者華', NULL, NULL, NULL, '裳裳者華，其葉湑兮。我覯之子，我心寫兮。我心寫兮，是以有譽處兮。
裳裳者華，芸其黃矣。我覯之子，維其有章矣。維其有章矣，是以有慶矣。
裳裳者華，或黃或白。我覯之子，乘其四駱。乘其四駱，六轡沃若。
左之左之，君子宜之。右之右之，君子有之。維其有之，是以似之。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00294","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-32-30-2d-88f3-88f3-8005-83ef-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-88f3-88f3-8005-83ef","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-32-30-2d-88f3-88f3-8005-83ef-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-88f3-88f3-8005-83ef"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E8%A3%B3%E8%A3%B3%E8%80%85%E8%8F%AF","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '桑扈', NULL, NULL, NULL, '交交桑扈，有鶯其羽。君子樂胥，受天之祜。
交交桑扈，有鶯其領。君子樂胥，萬邦之屏。
之屏之翰，百辟為憲。不戢不難，受福不那。
兕觥其觩，旨酒思柔。彼交匪敖，萬福來求。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00295","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-32-31-2d-6851-6248-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6851-6248","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-32-31-2d-6851-6248-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6851-6248"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%A1%91%E6%89%88","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '鴛鴦', NULL, NULL, NULL, '鴛鴦于飛，畢之羅之。君子萬年，福祿宜之。
鴛鴦在梁，戢其左翼。君子萬年，宜其遐福。
乘馬在廏，摧之秣之。君子萬年，福祿艾之。
乘馬在廏，秣之摧之。君子萬年，福祿綏之。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00296","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-32-32-2d-9d1b-9d26-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9d1b-9d26","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-32-32-2d-9d1b-9d26-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9d1b-9d26"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%B4%9B%E9%B4%A6","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '頍弁', NULL, NULL, NULL, '有頍者弁，實維伊何？爾酒既旨，爾殽既嘉。
豈伊異人？兄弟匪他。蔦與女蘿，施于松柏。
未見君子，憂心弈弈；既見君子，庶幾說懌。
有頍者弁，實維何期？爾酒既旨，爾殽既時。
豈伊異人？兄弟具來。蔦與女蘿，施于松上。
未見君子，憂心怲怲；既見君子，庶幾有臧。
有頍者弁，實維在首？爾酒既旨，爾殽既阜。
豈伊異人？兄弟甥舅。如彼雨雪，先集維霰。
死喪無日，無幾相見，樂酒今夕，君子維宴。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00297","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-32-33-2d-980d-5f01-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-980d-5f01","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-32-33-2d-980d-5f01-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-980d-5f01"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%A0%8D%E5%BC%81","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '車舝', NULL, NULL, NULL, '閒關車之舝兮，思孌季女逝兮。匪飢匪渴，德音來括。雖無好友，式燕且喜。
依彼平林，有集維鷮。辰彼碩女，令德來教。式燕且譽，好爾無射。
雖無旨酒，式飲庶幾。雖無嘉殽，式食庶幾。雖無德與女，式歌且舞。
陟彼高岡，析其柞薪。析其柞薪，其葉湑兮。鮮我覯爾，我心寫兮。
高山仰止，景行行止。四牡騑騑，六轡如琴。覯爾新昏，以慰我心。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00298","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-32-34-2d-8eca-821d-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-8eca-821d","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-32-34-2d-8eca-821d-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-8eca-821d"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E8%BB%8A%E8%88%9D","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '青蠅', NULL, NULL, NULL, '營營青蠅，止於樊。豈弟君子，無信讒言。
營營青蠅，止于棘。讒人罔極，交亂四國。
營營青蠅，止于榛。讒人罔極，構我二人。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00299","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-32-35-2d-9752-8805-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9752-8805","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-32-35-2d-9752-8805-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9752-8805"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%9D%92%E8%A0%85","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '賓之初筵', NULL, NULL, NULL, '賓之初筵，左右秩秩，籩豆有楚，殽核維旅。
酒既和旨，飲酒孔偕，鐘鼓既設，舉醻逸逸。
大侯既抗，弓矢斯張，射夫既同，獻爾發功。
發彼有的，以祈爾爵。
籥舞笙鼓，樂既和奏，烝衎烈祖，以洽百禮。
百禮既至，有壬有林，錫爾純嘏，子孫其湛。
其湛曰樂，各奏爾能，賓載手仇，室人入又。
酌彼康爵，以奏爾時。
賓之初筵，溫溫其恭，其未醉止，威儀反反。
曰既醉止，威儀幡幡，舍其坐遷，屢舞僊僊。
其未醉止，威儀抑抑，曰既醉止，威儀怭怭。
是曰既醉，不知其秩。
賓既醉止，載號載呶，亂我籩豆，屢舞僛僛。
是曰既醉，不知其郵，側弁之俄，屢舞傞傞。
既醉而出，並受其福，醉而不出，是謂伐德。
飲酒孔嘉，維其令儀。
凡此飲酒，或醉或否，既立之監，或佐之史。
彼醉不臧，不醉反恥。式勿從謂，無俾大怠。
匪言勿言，匪由勿語，由醉之言，俾出童羖。
三爵不識，矧敢多又。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00300","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-32-36-2d-8cd3-4e4b-521d-7b75-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-8cd3-4e4b-521d-7b75","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-32-36-2d-8cd3-4e4b-521d-7b75-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-8cd3-4e4b-521d-7b75"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E8%B3%93%E4%B9%8B%E5%88%9D%E7%AD%B5","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '魚藻', NULL, NULL, NULL, '魚在在藻，有頒其首。王在在鎬，豈樂飲酒。
魚在在藻，有莘其尾。王在在鎬，飲酒樂豈。
魚在在藻，依于其蒲。王在在鎬，有那其居。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00301","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-32-37-2d-9b5a-85fb-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9b5a-85fb","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-32-37-2d-9b5a-85fb-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9b5a-85fb"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%AD%9A%E8%97%BB","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '采菽', NULL, NULL, NULL, '采菽采菽，筐之筥之。君子來朝，何錫予之？
雖無予之，路車乘馬。又何予之？玄袞及黼。
觱沸檻泉，言采其芹。君子來朝，言觀其旂。
其旂淠淠，鸞聲嘒嘒。載驂載駟，君子所屆。
赤芾在股，邪幅在下。彼交匪紓，天子所予。
樂只君子，天子命之。樂只君子，福祿申之。
維柞之枝，其葉蓬蓬。樂只君子，殿天子之邦。
樂只君子，萬福攸同。平平左右，亦是率從。
汎汎楊舟，紼纚維之。樂只君子，天子葵之。
樂只君子，福祿膍之。優哉遊哉，亦是戾矣。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00302","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-32-38-2d-91c7-83fd-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-91c7-83fd","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-32-38-2d-91c7-83fd-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-91c7-83fd"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%87%87%E8%8F%BD","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '角弓', NULL, NULL, NULL, '騂騂角弓，翩其反矣。兄弟昏姻，無胥遠矣。
爾之遠矣，民胥然矣。爾之教矣，民胥傚矣。
此令兄弟，綽綽有裕。不令兄弟，交相為瘉。
民之無良，相怨一方。受爵不讓，至于已斯亡。
老馬反為駒，不顧其後。如食宜饇，如酌孔取。
毋教猱升木，如塗塗附。君子有徽猷，小人與屬。
雨雪瀌瀌，見晛曰消。莫肯下遺，式居婁驕。
雨雪浮浮，見晛曰流。如蠻如髦，我是用憂。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00303","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-32-39-2d-89d2-5f13-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-89d2-5f13","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-32-39-2d-89d2-5f13-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-89d2-5f13"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E8%A7%92%E5%BC%93","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '菀柳', NULL, NULL, NULL, '有菀者柳，不尚息焉？上帝甚蹈，無自暱焉。俾予靖之，後予極焉。
有菀者柳，不尚愒焉？上帝甚蹈，無自瘵焉。俾予靖之，後予邁焉。
有鳥高飛，亦傅于天。彼人之心，于何其臻？曷予靖之？居以凶矜。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00304","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-33-30-2d-83c0-67f3-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-83c0-67f3","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-33-30-2d-83c0-67f3-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-83c0-67f3"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E8%8F%80%E6%9F%B3","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '都人士', NULL, NULL, NULL, '彼都人士，狐裘黃黃。其容不改，出言有章。行歸于周，萬民所望。
彼都人士，臺笠緇撮。彼君子女，綢直如髮。我不見兮，我心不說。
彼都人士，充耳琇實。彼君子女，謂之尹吉。我不見兮，我心苑結。
彼都人士，垂帶而厲。彼君子女，卷髮如蠆。我不見兮，言從之邁。
匪伊垂之，帶則有餘。匪伊卷之，髮則有旟。我不見兮，雲何盱矣。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00305","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-33-31-2d-90fd-4eba-58eb-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-90fd-4eba-58eb","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-33-31-2d-90fd-4eba-58eb-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-90fd-4eba-58eb"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%83%BD%E4%BA%BA%E5%A3%AB","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '采綠', NULL, NULL, NULL, '終朝采綠，不盈一匊。予髮曲局，薄言歸沐。
終朝采藍，不盈一襜。五日為期，六日不詹。
之子于狩，言韔其弓。之子于釣，言綸之繩。
其釣維何？維魴及鱮。維魴及鱮，薄言觀者。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00306","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-33-32-2d-91c7-7da0-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-91c7-7da0","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-33-32-2d-91c7-7da0-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-91c7-7da0"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%87%87%E7%B6%A0","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '黍苗', NULL, NULL, NULL, '芃芃黍苗，陰雨膏之。悠悠南行，召伯勞之。
我任我輦，我車我牛。我行既集，蓋雲歸哉。
我徒我御，我師我旅。我行既集，蓋雲歸處。
肅肅謝功，召伯營之。烈烈征師，召伯成之。
原隰既平，泉流既清。召伯有成，王心則寧。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00307","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-33-33-2d-9ecd-82d7-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9ecd-82d7","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-33-33-2d-9ecd-82d7-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9ecd-82d7"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%BB%8D%E8%8B%97","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '隰桑', NULL, NULL, NULL, '隰桑有阿，其葉有難。既見君子，其樂如何？
隰桑有阿，其葉有沃。既見君子，雲何不樂？
隰桑有阿，其葉有幽。既見君子，德音孔膠。
心乎愛矣，遐不謂矣？中心藏之，何日忘之？', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00308","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-33-34-2d-96b0-6851-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-96b0-6851","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-33-34-2d-96b0-6851-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-96b0-6851"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%9A%B0%E6%A1%91","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '緜蠻', NULL, NULL, NULL, '緜蠻黃鳥，止于丘阿。道之雲遠，我勞如何！
飲之食之，教之誨之。命彼後車，謂之載之。
緜蠻黃鳥，止于丘隅。豈敢憚行？畏不能趨。
飲之食之，教之誨之。命彼後車，謂之載之。
緜蠻黃鳥，止于丘側。豈敢憚行，畏不能極。
飲之食之，教之誨之。命彼後車，謂之載之。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00309","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-33-36-2d-7ddc-883b-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7ddc-883b","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-33-36-2d-7ddc-883b-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7ddc-883b"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E7%B7%9C%E8%A0%BB","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '瓠葉', NULL, NULL, NULL, '幡幡瓠葉，采之亨之。君子有酒，酌言嘗之。
有兔斯首，炮之燔之。君子有酒，酌言獻之。
有兔斯首，燔之炙之。君子有酒，酌言酢之。
有兔斯首，燔之炮之。君子有酒，酌言醻之。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00310","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-33-37-2d-74e0-8449-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-74e0-8449","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-33-37-2d-74e0-8449-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-74e0-8449"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E7%93%A0%E8%91%89","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '漸漸之石', NULL, NULL, NULL, '漸漸之石，維其高矣。山川悠遠，維其勞矣。武人東征，不皇朝矣。
漸漸之石，維其卒矣。山川悠遠，曷其沒矣。武人東征，不皇出矣。
有豕白蹢，烝涉波矣。月離于畢，俾滂沱矣。武人東征，不皇他矣。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00311","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-33-38-2d-6f38-6f38-4e4b-77f3-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6f38-6f38-4e4b-77f3","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-33-38-2d-6f38-6f38-4e4b-77f3-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6f38-6f38-4e4b-77f3"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%BC%B8%E6%BC%B8%E4%B9%8B%E7%9F%B3","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '苕之華', NULL, NULL, NULL, '苕之華，芸其黃矣。心之憂矣，維其傷矣。
苕之華，其葉青青。知我如此，不如無生。
牂羊墳首，三星在罶。人可以食，鮮可以飽。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00312","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-33-39-2d-82d5-4e4b-83ef-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-82d5-4e4b-83ef","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-33-39-2d-82d5-4e4b-83ef-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-82d5-4e4b-83ef"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E8%8B%95%E4%B9%8B%E8%8F%AF","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '何草不黃', NULL, NULL, NULL, '何草不黃？何日不行？何人不將？經營四方。
何草不玄？何人不矜？哀我征夫，獨為匪民。
匪兕匪虎，率彼曠野。哀我征夫，朝夕不暇。
有芃者狐，率彼幽草。有棧之車，行彼周道。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00313","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-34-30-2d-4f55-8349-4e0d-9ec3-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-4f55-8349-4e0d-9ec3","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-34-30-2d-4f55-8349-4e0d-9ec3-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-4f55-8349-4e0d-9ec3"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E4%BD%95%E8%8D%89%E4%B8%8D%E9%BB%83","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '文王', NULL, NULL, NULL, '文王在上，於昭于天。周雖舊邦，其命維新。
有周不顯，帝命不時。文王陟降，在帝左右。
亹亹文王，令聞不已。陳錫哉周，侯文王孫子。
文王孫子，本支百世。凡周之士，不顯亦世。
世之不顯，厥猶翼翼。思皇多士，生此王國。
王國克生，維周之楨。濟濟多士，文王以寧。
穆穆文王，於緝熙敬止。假哉天命，有商孫子。
商之孫子，其麗不億。上帝既命，侯于周服。
侯服于周，天命靡常。殷士膚敏，祼將于京。
厥作祼將，常服黼冔。王之藎臣，無念爾祖。
無念爾祖，聿脩厥德。永言配命，自求多福。
殷之未喪師，克配上帝。宜鑒于殷，駿命不易。
命之不易，無遏爾躬。宣昭義問，有虞殷自天。
上天之載，無聲無臭。儀刑文王，萬邦作孚。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00314","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-34-31-2d-6587-738b-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6587-738b","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-34-31-2d-6587-738b-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6587-738b"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%96%87%E7%8E%8B","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '大明', NULL, NULL, NULL, '明明在下，赫赫在上。天難忱斯，不易維王。天位殷適，使不挾四方。
摯仲氏任，自彼殷商，來嫁于周。曰嬪于京，乃及王季，維德之行。大任有身，生此文王。
維此文王，小心翼翼。昭事上帝，聿懷多福。厥德不回，以受方國。
天監在下，有命既集。文王初載，天作之合。在洽之陽，在渭之涘。文王嘉止，大邦有子。
大邦有子，俔天之妹。文定厥祥，親迎于渭。造舟為梁，不顯其光。
有命自天，命此文王。于周于京，纘女維莘。長子維行，篤生武王。保右命爾，燮伐大商。
殷商之旅，其會如林。矢于牧野，維予侯興。上帝臨女，無貳爾心。
牧野洋洋，檀車煌煌，駟騵彭彭。維師尚父，時維鷹揚。涼彼武王，肆伐大商。會朝清明。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00315","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-34-32-2d-5927-660e-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5927-660e","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-34-32-2d-5927-660e-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5927-660e"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%A4%A7%E6%98%8E","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '緜', NULL, NULL, NULL, '緜緜瓜瓞，民之初生，自土沮漆。古公亶父，陶復陶宂，未有家室。
古公亶父，來朝走馬。率西水滸，至于岐下。爰及姜女，聿來胥宇。
周原膴膴，堇荼如飴。爰始爰謀，爰契我龜。曰止曰時，築室于茲。
廼慰廼止，廼左廼右。廼疆廼理，廼宣廼畝。自西徂東，周爰執事。
乃召司空，乃召司徒。俾立室家，其繩則直。縮版以載，作廟翼翼。
捄之陾陾，度之薨薨。築之登登，削屢馮馮。百堵皆興，鼛鼓弗勝。
廼立皐門，皐門有伉。廼立應門，應門將將。廼立冢土，戎醜攸行。
肆不殄厥慍，亦不隕厥問。柞棫拔矣，行道兌矣。混夷駾矣，維其喙矣。
虞芮質厥成，文王蹶厥生。予曰有疏附，予曰有先後。予曰有奔奏，予曰有禦侮。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00316","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-34-33-2d-7ddc-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7ddc","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-34-33-2d-7ddc-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7ddc"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E7%B7%9C","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '棫樸', NULL, NULL, NULL, '芃芃棫樸，薪之槱之。濟濟辟王，左右趣之。
濟濟辟王，左右奉璋。奉璋峨峨，髦士攸宜。
淠彼涇舟，烝徒楫之。周王于邁，六師及之。
倬彼雲漢，為章于天。周王壽考，遐不作人。
追琢其章，金玉其相。勉勉我王，綱紀四方。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00317","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-34-34-2d-68eb-6a38-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-68eb-6a38","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-34-34-2d-68eb-6a38-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-68eb-6a38"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%A3%AB%E6%A8%B8","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '旱麓', NULL, NULL, NULL, '瞻彼旱麓，榛楛濟濟。豈弟君子，乾祿豈弟。
瑟彼玉瓚，黃流在中。豈弟君子，福祿攸降。
鳶飛戾天，魚躍于淵。豈弟君子，遐不作人。
清酒既載，騂牡既備。以享以祀，以介景福。
瑟彼柞棫，民所燎矣。豈弟君子，神所勞矣。
莫莫葛藟，施于條枚。豈弟君子，求福不回。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00318","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-34-35-2d-65f1-9e93-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-65f1-9e93","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-34-35-2d-65f1-9e93-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-65f1-9e93"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%97%B1%E9%BA%93","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '思齊', NULL, NULL, NULL, '思齊大任，文王之母，思媚周姜。京室之婦，大姒嗣徽音，則百斯男。
惠于宗公，神罔時怨，神罔時恫。刑于寡妻，至于兄弟，以御于家邦。
雝雝在宮，肅肅在廟。不顯亦臨，無射亦保。
肆戎疾不殄，烈假不瑕。不聞亦式，不諫亦入。
肆成人有德，小子有造。古之人無斁，譽髦斯士。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00319","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-34-36-2d-601d-9f4a-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-601d-9f4a","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-34-36-2d-601d-9f4a-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-601d-9f4a"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%80%9D%E9%BD%8A","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '皇矣', NULL, NULL, NULL, '皇矣上帝，臨下有赫。監觀四方，求民之莫。
維此二國，其政不獲。維彼四國，爰究爰度。
上帝耆之，憎其式廓。乃眷西顧，此維與宅。
作之屏之，其菑其翳。脩之平之，其灌其栵。
啟之辟之，其檉其椐。攘之剔之，其檿其柘。
帝遷明德，串夷載路，天立厥配，受命既固。
帝省其山，柞棫斯拔，松柏斯兌。
帝作邦作對。自大伯王季。
維此王季，因心則友。則友其兄，則篤其慶。
載錫之光。受祿無喪，奄有四方。
維此王季，帝度其心。貊其德音，其德克明。
克明克類，克長克君。王此大邦，克順克比。
比于文王，其德靡悔，既受帝祉，施于孫子。
帝謂文王：無然畔援，無然歆羨，誕先登于岸。
密人不恭，敢距大邦，侵阮徂共。
王赫斯怒，爰整其旅，以按徂旅，以篤于周祜，以對于天下。
依其在京，侵自阮疆，陟我高岡。
無矢我陵，我陵我阿，無飲我泉，我泉我池。
度其鮮原，居岐之陽，在渭之將，萬邦之方，下民之王。
帝謂文王：予懷明德。不大聲以色，不長夏以革，不識不知，順帝之則。
帝謂文王：詢爾仇方。同爾兄弟，以爾鉤援，與爾臨衝，以伐崇墉。
臨衝閑閑，崇墉言言。執訊連連，攸馘安安。是類是禡，是致是附。四方以無侮。
臨衝茀茀，崇墉仡仡。是伐是肆，是絶是忽。四方以無拂。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00320","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-34-37-2d-7687-77e3-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7687-77e3","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-34-37-2d-7687-77e3-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7687-77e3"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E7%9A%87%E7%9F%A3","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}')
)
INSERT INTO poems (
  poet_id, poem_no, volume, title_zh, title_ko, category, meter, body_zh,
  is_notable, status, quality, review_memo
)
SELECT
  p.id,
  COALESCE(existing_poem_count.max_poem_no, 0)
    + row_number() OVER (PARTITION BY p.id ORDER BY ip.title_zh, ip.body_zh)::integer,
  ip.volume::integer, ip.title_zh, ip.title_ko, ip.category, ip.meter::integer, ip.body_zh,
  TRUE, ip.status, ip.quality, ip.review_memo
FROM input_poems ip
JOIN poets p ON p.title_id = ip.poet_slug
LEFT JOIN LATERAL (
  SELECT max(poem_no) AS max_poem_no
  FROM poems
  WHERE poet_id = p.id
) existing_poem_count ON TRUE
WHERE NOT EXISTS (
  SELECT 1
  FROM poems existing
  WHERE existing.poet_id = p.id
    AND existing.title_zh = ip.title_zh
    AND existing.body_zh = ip.body_zh
);

UPDATE poets p
SET poem_count = sub.cnt
FROM (
  SELECT poet_id, count(*)::integer AS cnt
  FROM poems
  WHERE poet_id IN (SELECT id FROM poets WHERE title_id IN ('cnpreqin-3fcc3c660d5a7a4d'))
  GROUP BY poet_id
) sub
WHERE p.id = sub.poet_id;

-- Review counts before COMMIT when applying manually:
SELECT quality, status, count(*) FROM poems WHERE quality IN ('cnpt-shijing') GROUP BY quality, status ORDER BY quality, status;
SELECT p.era_period, count(pm.id) FROM poets p JOIN poems pm ON pm.poet_id = p.id WHERE p.title_id IN ('cnpreqin-3fcc3c660d5a7a4d') GROUP BY p.era_period ORDER BY p.era_period;

ROLLBACK;
-- COMMIT;
