-- Generated by scripts/build_cn_translation_pipeline_staging.mjs
-- Part: 10/13
-- Purpose: stage CN pre-Tang and Song/Yuan/Ming poems into the JDS translation pipeline.
-- Translator decision: JDS backend=gemini model=gemini-2.5-flash-lite prompt=pipeline/translate/prompts/v5_full.txt.
-- Safety: inserts only missing poet slug + title_zh + body_zh rows. Default ending is ROLLBACK.

BEGIN;

WITH input_poets(slug, name_zh, name_ko, life_raw, era_period, country) AS (
  VALUES
    ('candidate-ming-5f90-71a5', '徐熥', NULL, NULL, '明', 'CN'),
    ('candidate-ming-738b-4e16-8c9e', '王世貞', NULL, NULL, '明', 'CN'),
    ('candidate-ming-738b-7acb-9053', '王立道', NULL, NULL, '明', 'CN'),
    ('candidate-ming-674e-5922-967d', '李夢陽', NULL, NULL, '明', 'CN'),
    ('candidate-ming-6c6a-5ee3-6d0b', '汪廣洋', NULL, NULL, '明', 'CN'),
    ('candidate-ming-80e1-61c9-9e9f', '胡應麟', NULL, NULL, '明', 'CN'),
    ('candidate-ming-5f6d-5b6b-8cbd', '彭孫貽', NULL, NULL, '明', 'CN'),
    ('candidate-song-5289-5b50-7fec', '劉子翬', NULL, NULL, '宋', 'CN')
)
INSERT INTO poets (title_id, name_zh, name_ko, life_raw, era_period, poem_count)
SELECT slug, name_zh, name_ko, life_raw, era_period, 0
FROM input_poets
ON CONFLICT (title_id) DO UPDATE SET
  name_zh = EXCLUDED.name_zh,
  name_ko = COALESCE(EXCLUDED.name_ko, poets.name_ko),
  life_raw = COALESCE(EXCLUDED.life_raw, poets.life_raw),
  era_period = EXCLUDED.era_period;

WITH input_poems(poet_slug, volume, title_zh, title_ko, category, meter, body_zh, status, quality, review_memo) AS (
  VALUES
    ('candidate-ming-5f90-71a5', 0, '飲馬長城窟行', NULL, '五言古詩', 5, '飲馬長城窟，
水深沒馬腹。
朝發祈連山，
暮宿太原谷。
男兒事格鬬，
安能諱殺戮。
昨日新戰敗，
死者什五六。
殘血吹腥風，
屍骸路相續。
身死自不悲，
所痛在骨肉。
嗟哉杞梁妻，
哀哀城下哭。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00721","source_record_id":"CN-NT-CAT-00319","alias_record_ids":["CN-NT-CAT-00319"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%A3%B2%E9%A6%AC%E9%95%B7%E5%9F%8E%E7%AA%9F%E8%A1%8C_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '銅雀妓', NULL, '五言律詩', 5, '日暮西陵望，
但見蒿與萊。
悲風起四野，
歌舞有餘哀。
漳河流不返，
繐帳空塵埃。
荒臺久寂寞，
雄圖安在哉。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00722","source_record_id":"CN-NT-CAT-00320","alias_record_ids":["CN-NT-CAT-00320"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%8A%85%E9%9B%80%E5%A6%93_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '羽林郎', NULL, '五言古詩', 5, '昔有羽林郎，
持㦸出未央。
揮鞭過酒肆，
招搖都市傍。
酒家女二八，
顔色耀春芳。
黃金為條脱，
白玉為耳璫。
越羅裁中裙，
齊紈製下裳。
服飾既璀璨，
膏沐尤馨香。
不意冶逰子，
停驂登我堂。
銀鞍耀紅日，
韎韐何輝煌。
提壺索美酒，
岸幘據胡床。
金刀膾鮮鯉，
烈火炮羔羊。
酒盡出門去，
嬋媛結𠂻腸。
已去復再返，
解贈紫羅囊。
君心一何苦，
君情一何長。
婦人貴逺別，
持此非所當。
還君紫羅囊，
妾非青樓倡。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00723","source_record_id":"CN-NT-CAT-00321","alias_record_ids":["CN-NT-CAT-00321"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%BE%BD%E6%9E%97%E9%83%8E_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '車遙遙', NULL, '五言古詩', 5, '車輪何遙遙，
出門不顧返。
輪豈不能廻，
君心自難輓。
聽此轔轔聲，
一聲一以逺。
看此兩行轍，
能令歡愛斷。
如何馭者手，
不肯須㬰緩。
敢望君心回，
但願車輪爛。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00724","source_record_id":"CN-NT-CAT-00322","alias_record_ids":["CN-NT-CAT-00322"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%BB%8A%E9%81%99%E9%81%99_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '門有車馬客行', NULL, '五言古詩', 5, '門有車馬客，
來從故鄉陌。
乍見雖可懽，
道舊反不懌。
試問舊親賔，
存亡異疇昔。
別時諸兒童，
于今皆半百。
今時諸壯夫，
多非故相識。
舊人居新墳，
新人居舊宅。
里社既荒凉，
市朝多變易。
纍纍丘壠間，
鬱鬱生松栢。
離別纔幾時，
光隂如此廹。
靜言思故鄉，
含情淚沾臆。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00725","source_record_id":"CN-NT-CAT-00323","alias_record_ids":["CN-NT-CAT-00323"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%96%80%E6%9C%89%E8%BB%8A%E9%A6%AC%E5%AE%A2%E8%A1%8C_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '白馬篇', NULL, '五言古詩', 5, '誰家冶逰子，
捐軀事戎行。
白馬黃金羈，
驅馳赴朔方。
兠鍪既焜燿，
寶劍生光芒。
良弓懸韎韐，
激矢藏縹囊。
仰天射鳬雁，
俯身射豺狼。
膂力已絶世，
捷黠誰能當。
邊風方慘冽，
壯士臨風僵。
躍馬入重圍，
生擒左賢王。
丈夫思報國，
安肯思故鄉。
裹屍誠所願，
毋然悲死傷。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00726","source_record_id":"CN-NT-CAT-00324","alias_record_ids":["CN-NT-CAT-00324"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%99%BD%E9%A6%AC%E7%AF%87_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '君馬黃', NULL, NULL, NULL, '君馬黃，
臣馬赤。
君馬馳驅，
臣馬辟易。
君馬登天閑，
臣馬伏槽櫪。
二馬同行，
一馬太息。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00727","source_record_id":"CN-NT-CAT-00325","alias_record_ids":["CN-NT-CAT-00325"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%90%9B%E9%A6%AC%E9%BB%83_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '臨髙臺', NULL, NULL, NULL, '臨髙臺，
望故鄉，
下有流水流湯湯。
羣草委腓萬木黃，
翩翩南雁來廻翔。
攬衣起徬徨，
美人不見兮斷我𠂻腸。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00728","source_record_id":"CN-NT-CAT-00326","alias_record_ids":["CN-NT-CAT-00326"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%87%A8%E9%AB%99%E8%87%BA_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '江南弄', NULL, NULL, NULL, '氷肌皓魄紅羅襦，
鬱金裙帶懸流蘇，
蓮舟蕩漾臨澄湖。
臨澄湖，
連臂歌，
歡不來，
將奈何。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00729","source_record_id":"CN-NT-CAT-00327","alias_record_ids":["CN-NT-CAT-00327"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%B1%9F%E5%8D%97%E5%BC%84_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '龍笛曲', NULL, NULL, NULL, '于闐玉管流哀音，
餘音寥亮水龍吟，
調繁指弱憂思深。
憂思深，
涕汍瀾，
懷逺道，
催清顔。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00730","source_record_id":"CN-NT-CAT-00328","alias_record_ids":["CN-NT-CAT-00328"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%BE%8D%E7%AC%9B%E6%9B%B2_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '採蓮曲', NULL, NULL, NULL, '蘭舟容與過橫塘，
步搖驚起雙鴛鴦，
羅裙帶濕生濃香。
生濃香，
紅汗滴，
坐中流，
奏龍笛。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00731","source_record_id":"CN-NT-CAT-00329","alias_record_ids":["CN-NT-CAT-00329"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%8E%A1%E8%93%AE%E6%9B%B2_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '逰女曲', NULL, NULL, NULL, '羅衣半褪飄金縷，
約束纎腰五雜組，
日暮採芳臨洛浦。
臨洛浦，
鮮明珠，
望交甫，
心踟蹰。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00732","source_record_id":"CN-NT-CAT-00330","alias_record_ids":["CN-NT-CAT-00330"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%80%B0%E5%A5%B3%E6%9B%B2_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '朝雲曲', NULL, NULL, NULL, '朝雲日日陽臺上，
晻曖迷茫開綺帳，
襄王一去勞相望。
勞相望，
夢難醒，
湘水緑，
湘山青。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00733","source_record_id":"CN-NT-CAT-00331","alias_record_ids":["CN-NT-CAT-00331"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%9C%9D%E9%9B%B2%E6%9B%B2_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '鳳笙曲', NULL, NULL, NULL, '纎指按節玉參差，
櫻唇緩吸聲遲遲，
吹儂無限心中悲。
心中悲，
望逺情，
何時吹，
雙鳳鳴。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00734","source_record_id":"CN-NT-CAT-00332","alias_record_ids":["CN-NT-CAT-00332"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%B3%B3%E7%AC%99%E6%9B%B2_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '春日白紵曲', NULL, '七言絶句', 7, '辛夷半落桃花開，
金羈寶瑟上春臺。
佳人倦倚闌乾曲，
兩兩黃鶯飛相逐。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00735","source_record_id":"CN-NT-CAT-00333","alias_record_ids":["CN-NT-CAT-00333"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%98%A5%E6%97%A5%E7%99%BD%E7%B4%B5%E6%9B%B2_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '秋日白紵曲', NULL, '七言絶句', 7, '庭槐初落秋氣深，
月中玉腕𢷬清碪。
東家倡婦恣行樂，
酒闌更説羅衣薄。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00736","source_record_id":"CN-NT-CAT-00334","alias_record_ids":["CN-NT-CAT-00334"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%A7%8B%E6%97%A5%E7%99%BD%E7%B4%B5%E6%9B%B2_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '烏棲曲', NULL, '七言古詩', 7, '髙樓四面栽楊栁，
白馬驪珂蹔回首。
玉壺美酒任君沽，
妾身十五已當壚。
㣲滅銀燈隔重幔，
宛轉嬌聲恣啼喚。
不辭今夕盡風流，
只愁明日見君羞。
帳中弱態含嬌嫵，
一夜為雲更為雨。
汝南雞啼天未明，
與君還盡片時情。
月銜半嶺燈將滅，
羅衫掩淚送君別。
入門獨自剔殘燈，
尋思無限夜來情。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00737","source_record_id":"CN-NT-CAT-00335","alias_record_ids":["CN-NT-CAT-00335"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%83%8F%E6%A0%96%E6%9B%B2_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '塞上曲', NULL, '五言古詩', 5, '將軍出北平，
匈奴爭遁走。
皷振天地昏，
令出風雷吼。
邊霜裂旌旗，
塞月寒刁鬥。
繫俘受降城，
屯兵井陘口。
歸來見至尊，
自獻單于首。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00738","source_record_id":"CN-NT-CAT-00336","alias_record_ids":["CN-NT-CAT-00336"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%A1%9E%E4%B8%8A%E6%9B%B2_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '白頭吟', NULL, '五言古詩', 5, '貌如雨中花，
節似霜中栢。
貌改節不移，
別君意悽惻。
妾心如女蘿，
君情如飛絮。
蘿生空纒綿，
絮飛何處去。
嫁君當紅顔，
辭君當白首。
請君看鏡中，
雙鬢何如舊。
死樹難再榮，
死灰難再熱。
寄語新懽人，
莫遣頭如雪。
含悲下中堂，
此情空脉脉。
君心能再回，
白頭應再黒。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00739","source_record_id":"CN-NT-CAT-00337","alias_record_ids":["CN-NT-CAT-00337"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%99%BD%E9%A0%AD%E5%90%9F_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '𢷬衣篇', NULL, '五言古詩', 5, '皎月入房帷，
凉風吹衣襟。
逰子逺行役，
少婦鳴清碪。
良夜既以永，
懷人益以深。
孤鴻唳天際，
促織吟堂隂。
餘亦別家久，
涕泣不能禁。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00740","source_record_id":"CN-NT-CAT-00338","alias_record_ids":["CN-NT-CAT-00338"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%F0%A2%B7%AC%E8%A1%A3%E7%AF%87_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '妾薄命', NULL, '五言古詩', 5, '南國有佳人，
容華世莫比。
嫁與東隣兒，
願言結生死。
良人輕別離，
匆匆辭故里。
朝醉閶闔門，
暮宿長安市。
新愛移平生，
恩情付流水。
欲促逺人歸，
裁書寄雙鯉。
遺之同心結，
兼以合歡被。
人匪金石堅，
容顔何足恃。
天涯君不歸，
河清難再俟。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00741","source_record_id":"CN-NT-CAT-00339","alias_record_ids":["CN-NT-CAT-00339"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%A6%BE%E8%96%84%E5%91%BD_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '有所思', NULL, '五言古詩', 5, '徙倚向花叢，
羅衣濕清露。
烏鵲隠茂林，
寒蟬抱髙樹。
焚香理素琴，
聊以抒心愫。
美人期不來，
中宵淚如注。
月色滿花隂，
花隂空竚立。
何以贈所驩，
悲歌聊當泣。
啾啾階蛩吟，
喔喔隣雞急。
幽會杳無期，
空令長太息。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00742","source_record_id":"CN-NT-CAT-00340","alias_record_ids":["CN-NT-CAT-00340"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%9C%89%E6%89%80%E6%80%9D_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-738b-4e16-8c9e', 0, '銅雀伎', NULL, '五言古詩', 5, '往事秦雲逝，
深恩漳水流。
月歸金鴈冷，
風至玉衣秋。
粉黛年年薄，
絃歌夜夜愁。
誰同漢武帝，
還向茂陵遊。
奉寢傳遺敎，
分香更繫情。
履猶明主跡，
絃是向時聲。
寂寞無新故，
榮華有重輕。
尚疑僊樂動，
別院夜相迎。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00743","source_record_id":"CN-NT-CAT-00341","alias_record_ids":["CN-NT-CAT-00341"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%8A%85%E9%9B%80%E4%BC%8E_(%E7%8E%8B%E4%B8%96%E8%B2%9E)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-738b-7acb-9053', 0, '銅雀伎二首', NULL, '五言古詩', 5, '掩涕辭金屋，
含情向白雲。
衣冠新卜道，
歌舞舊來羣。
貟枕無時覺，
哀猿終夜聞。
誰言妾薄命，
生死只從君。
漳河流日夜，
歌舞未能休。
艶色今誰妬，
餘香空自留。
朝雲不作雨，
陵樹早生秋。
滿目多疑塚，
君靈在此不。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00744","source_record_id":"CN-NT-CAT-00342","alias_record_ids":["CN-NT-CAT-00342"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%8A%85%E9%9B%80%E4%BC%8E%E4%BA%8C%E9%A6%96_(%E7%8E%8B%E7%AB%8B%E9%81%93)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-674e-5922-967d', 0, '銅雀伎', NULL, '五言律詩', 5, '帷飄雀臺上，
絃奏舞衣前。
羣悲一以望，
春草為誰妍。
芳歲銷蘭怨，
流塵集錦筵。
為問西陵道，
孰與漢家阡。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00745","source_record_id":"CN-NT-CAT-00343","alias_record_ids":["CN-NT-CAT-00343"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%8A%85%E9%9B%80%E4%BC%8E_(%E6%9D%8E%E5%A4%A2%E9%99%BD)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-6c6a-5ee3-6d0b', 0, '擬銅雀伎', NULL, '五言律詩', 5, '燕趙女如玉，
輕盈掌上身。
翠眉長不掃，
悵望西陵人。
酒闌歌舞罷，
臺榭坐生塵。
怨入漳河水，
悠悠秋復春。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00746","source_record_id":"CN-NT-CAT-00344","alias_record_ids":["CN-NT-CAT-00344"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%93%AC%E9%8A%85%E9%9B%80%E4%BC%8E_(%E6%B1%AA%E5%BB%A3%E6%B4%8B)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-80e1-61c9-9e9f', 0, '銅雀伎', NULL, '五言律詩', 5, '松栢西陵路，
君王不復遊。
高臺銅雀暮，
故苑石麟秋。
舞將羅袖歇，
歌倚繐帷愁。
浮雲渺天末，
漳水共悠悠。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00747","source_record_id":"CN-NT-CAT-00345","alias_record_ids":["CN-NT-CAT-00345"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%8A%85%E9%9B%80%E4%BC%8E_(%E8%83%A1%E6%87%89%E9%BA%9F)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '銅雀伎', NULL, '五言律詩', 5, '銅臺遺令在，
玉座主恩非。
舊曲流哀管，
餘香散舞衣。
繐帷空寂寞，
羅綺失光輝。
日日西陵望，
君王歸不歸。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00748","source_record_id":"CN-NT-CAT-00346","alias_record_ids":["CN-NT-CAT-00346"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%8A%85%E9%9B%80%E4%BC%8E_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f6d-5b6b-8cbd', 0, '銅雀伎', NULL, '五言律詩', 5, '高臺歌舞意，
無復望君憐。
寂寂西陵下，
深松枕墓田。
青青洛城雨，
北邙歌吹發。
鄴宮舊舞人，
春風生白髪。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00749","source_record_id":"CN-NT-CAT-00347","alias_record_ids":["CN-NT-CAT-00347"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%8A%85%E9%9B%80%E4%BC%8E_(%E5%BD%AD%E5%AD%AB%E8%B2%BD)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '詠美人觀畫', NULL, '五言律詩', 5, '國色看如畫，
丹青疑是眞。
誰能分麗質，
各欲競丰神。
江濱有兩艷，
下蔡見雙身。
只恐朱顔謝，
不及巻中人。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00750","source_record_id":"CN-NT-CAT-00348","alias_record_ids":["CN-NT-CAT-00348"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A0%E7%BE%8E%E4%BA%BA%E8%A7%80%E7%95%AB_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5289-5b50-7fec', 0, '老農', NULL, NULL, NULL, '山前有老農，
給我薪水役。
得錢徑沽酒，
醉卧山日夕。
忘形與之語，
妙理時見益。
志士多隠淪，
欲言原作墨丁，
據四庫本補慚未識。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00751","source_record_id":"CN-NT-CAT-00349","alias_record_ids":["CN-NT-CAT-00349"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%80%81%E8%BE%B2_(%E5%8A%89%E5%AD%90%E7%BF%AC)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '吳城覽古', NULL, '七言律詩', 7, '白雲猶繞舊王居，
獨對西風恨有餘。
百戰山河歸草莽，
千年陵寝總丘墟。
月明茂苑遊麋鹿，
花暗荒城弔闔廬。
況是異鄉多病客，
豈堪唫眺暫躊躇。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00752","source_record_id":"CN-NT-CAT-00351","alias_record_ids":["CN-NT-CAT-00351"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%90%B3%E5%9F%8E%E8%A6%BD%E5%8F%A4_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '塞下曲', NULL, '七言律詩', 7, '沙磧風髙敵騎侵，
將軍新戰賀蘭隂。
塞霜曉角降王淚，
漢月秋笳壯士心。
刀上洗瘢青血冷，
營前望氣白光沉。
旄頭未落邊烽急，
腸斷空閨戍婦碪。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00753","source_record_id":"CN-NT-CAT-00352","alias_record_ids":["CN-NT-CAT-00352"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%A1%9E%E4%B8%8B%E6%9B%B2_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '姑蘇懷古', NULL, '七言律詩', 7, '秋風吹送木蘭橈，
無那愁心逐暮潮。
響屧廊中歌舞散，
姑蘇臺上鹿麋驕。
東吳覇氣今俱盡，
西子香魂不可招。
半夜烏啼鐘欲動，
無情明月照楓橋。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00754","source_record_id":"CN-NT-CAT-00353","alias_record_ids":["CN-NT-CAT-00353"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%A7%91%E8%98%87%E6%87%B7%E5%8F%A4_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '聞警', NULL, '七言律詩', 7, '關山邉騎響蕭蕭，
司馬觀兵日度遼。
天上黑光久摩盪，
宮中黃屋太焚燒。
空揮涕涙憂時變，
難効涓涘答聖朝。
安得善言同宋璟，
冥冥氛祲一時銷。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00755","source_record_id":"CN-NT-CAT-00355","alias_record_ids":["CN-NT-CAT-00355"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%81%9E%E8%AD%A6_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '落花', NULL, '七言律詩', 7, '乍見清池映曉妝，
驚看池面貼殘芳。
武陵谿上春風暗，
杜曲園中夜雨狂。
緑葉成隂空自媚，
紅英落盡尚餘香。
含情最恨東君惡，
不向人間理斷腸。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00756","source_record_id":"CN-NT-CAT-00356","alias_record_ids":["CN-NT-CAT-00356"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%90%BD%E8%8A%B1_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '柳', NULL, '七言律詩', 7, '千絲萬縷鬭妖嬈，
和雨和煙陌上飄。
夜夜篴聲關塞路，
年年杯酒㶚陵橋。
隋堤㳺女輸濃黛，
楚國佳人鬭細腰。
只恐章臺春易老，
幾回攀折恨蕭條。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00757","source_record_id":"CN-NT-CAT-00357","alias_record_ids":["CN-NT-CAT-00357"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%9F%B3_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '花影', NULL, '七言律詩', 7, '芳英灼灼葉蓁蓁，
倒影雕欄態更新。
忽遇燈光成幻境，
倩將月色為傳神。
分明鏡裏看珠翠，
彷彿帷中見玉人。
世界隂晴元不定，
可憐生滅總非真。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00758","source_record_id":"CN-NT-CAT-00358","alias_record_ids":["CN-NT-CAT-00358"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%8A%B1%E5%BD%B1_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '夕陽', NULL, '七言律詩', 7, '羲馭難留忽已西，
東山猶帶一痕低。
能催古寺踈鐘起，
漸聴孤城畫角齊。
影入蘆汀羣鴈落，
光銜茅屋亂雞棲。
此時誰是銷魂者，
戍婦閨中最慘悽。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00759","source_record_id":"CN-NT-CAT-00359","alias_record_ids":["CN-NT-CAT-00359"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%A4%95%E9%99%BD_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '白鴈', NULL, '七言律詩', 7, '蹁躚刷羽度衡陽，
遙望還疑縞素妝。
起處蘆花飄岸渚，
低時殘雪㸃瀟湘。
帶來逺塞千山月，
呌落深林半夜霜。
影入薄雲看不見，
湖光漠漠楚天長。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00760","source_record_id":"CN-NT-CAT-00360","alias_record_ids":["CN-NT-CAT-00360"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%99%BD%E9%B4%88_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '弓', NULL, '七言律詩', 7, '誰挽烏號五石强，
由來猿臂可穿楊。
蛇疑杯裏終難釋，
鳥盡林中便已藏。
開處流星過絶塞，
掛時殘月在扶桑。
世間得失原無定，
尼父當年笑楚王。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00761","source_record_id":"CN-NT-CAT-00361","alias_record_ids":["CN-NT-CAT-00361"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%BC%93_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '萍', NULL, '七言律詩', 7, '有葉無根不用栽，
還疑水面長蒼苔。
遊魚吹浪重重亂，
彩鷁衝波兩兩開。
却得微風依岸泊，
不容明月入池來。
忽然一夜添新雨，
蹤跡飄零信可哀。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00762","source_record_id":"CN-NT-CAT-00362","alias_record_ids":["CN-NT-CAT-00362"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%90%8D_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '蝶', NULL, '七言律詩', 7, '傅粉嬌姿五色衣，
由來生性愛芳菲。
夜深栩栩夢中化，
日午雙雙花底飛。
偷得餘香過別院，
帶將春色入簾幃。
只愁荏苒韶光暮，
飄泊知從何處歸。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00763","source_record_id":"CN-NT-CAT-00363","alias_record_ids":["CN-NT-CAT-00363"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%9D%B6_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '老農', NULL, '七言律詩', 7, '容貌衰癯兩鬢華，
難將生計事汚邪。
手栽禾黍知多少，
眼見田園屬幾家。
時課兒孫勤耨穫，
閒從隣叟話桑麻。
昨朝扶杖過春社，
還祝甌窶欲滿車。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00764","source_record_id":"CN-NT-CAT-00364","alias_record_ids":["CN-NT-CAT-00364"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%80%81%E8%BE%B2_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '水簾', NULL, '七言律詩', 7, '潺潺千㸃響淙淙，
一片氷綃掛碧空。
日射恍疑金絡索，
月明如坐水晶宮。
神龍噴處珠盈貫，
玉女來時佩馭風。
十二闌乾遙騁望，
萬重山色總朦朧。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00765","source_record_id":"CN-NT-CAT-00365","alias_record_ids":["CN-NT-CAT-00365"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%B0%B4%E7%B0%BE_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '愛妾換馬', NULL, '七言律詩', 7, '雙眉顰蹙四蹄飜，
皂櫪無聲被不溫。
憔悴難忘當日寵，
悲鳴猶戀主人恩。
强隨夜月登妝閣，
愁逐秋風出塞垣。
金埒玉樓遙騁望，
幾多汗血幾啼痕。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00766","source_record_id":"CN-NT-CAT-00366","alias_record_ids":["CN-NT-CAT-00366"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%84%9B%E5%A6%BE%E6%8F%9B%E9%A6%AC_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '經古戰塲', NULL, '七言律詩', 7, '蕭條殘壘不勝悲，
此地曾經幾亂離。
恨血尚餘春草裏，
遊魂多出夕陽時。
瀟瀟寒雨聞刁鬥，
漠漠隂雲見羽旗。
滿路乾戈愁轉戰，
胡笳休向馬頭吹。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00767","source_record_id":"CN-NT-CAT-00367","alias_record_ids":["CN-NT-CAT-00367"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%B6%93%E5%8F%A4%E6%88%B0%E5%A1%B2_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '易水懷古', NULL, '七言律詩', 7, '一笑秦庭事已空，
蕭蕭寒氣動悲風。
飛霜枉購千金匕，
貫日猶懸百丈虹。
公子歌殘衣變白，
田光死去血流紅。
薊門零落咸陽火，
易水年年只向東。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00768","source_record_id":"CN-NT-CAT-00368","alias_record_ids":["CN-NT-CAT-00368"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%98%93%E6%B0%B4%E6%87%B7%E5%8F%A4_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '燕子樓', NULL, '七言律詩', 7, '舊日懽情委逝波，
空樓燈影恨如何。
一天夜月閒簫管，
十載春風罷綺羅。
松栢鎖煙愁思苦，
牡丹含雨淚痕多。
香銷粉歇歌塵散，
忍見雙雙燕子過。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00769","source_record_id":"CN-NT-CAT-00369","alias_record_ids":["CN-NT-CAT-00369"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%87%95%E5%AD%90%E6%A8%93_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '書懷', NULL, '七言律詩', 7, '嵗月蹉跎黯自驚，
此身雖在鬢毛更。
江湖故舊無消息，
童稚交遊半死生。
喜信空門縁漸老，
厭聞徃事為多情。
客中最是愁人處，
獨夜殘燈風雨聲。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00770","source_record_id":"CN-NT-CAT-00370","alias_record_ids":["CN-NT-CAT-00370"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%9B%B8%E6%87%B7_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '無題', NULL, '七言律詩', 7, '玉殞珠沉思悄然，
明中流淚暗相憐。
常圖蛺蝶花樓下，
記刺鴛鴦繡幙前。
祗有夢魂能結雨，
曾無心膽似非煙。
朱顔皓齒歸黃土，
脉脉空尋再世縁。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00771","source_record_id":"CN-NT-CAT-00371","alias_record_ids":["CN-NT-CAT-00371"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%84%A1%E9%A1%8C_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '別金陵', NULL, '五言律詩', 5, '人境元如夢，
兹逰真惘然。
一帆揚子月，
雙屐白門煙。
遇寺多留偈，
逢僧盡問禪。
獨餘千佛嶺，
待我再來縁。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00772","source_record_id":"CN-NT-CAT-00372","alias_record_ids":["CN-NT-CAT-00372"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%88%A5%E9%87%91%E9%99%B5_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '曉發', NULL, '五言律詩', 5, '枕上榜歌起，
溪中行侣稀。
纜牽煙縷細，
帆掛月痕微。
曙逐雞聲盡，
濤驚客夢歸。
沿洄三五里，
猶未見朝暉。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00773","source_record_id":"CN-NT-CAT-00373","alias_record_ids":["CN-NT-CAT-00373"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%9B%89%E7%99%BC_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '陷石堂', NULL, '五言律詩', 5, '縁溪下復登，
山色翠層層。
洞以水流闢，
石從雲壓崩。
落花魂卧草，
空樹腹吞藤。
漸覺非人境，
風光近武陵。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00774","source_record_id":"CN-NT-CAT-00374","alias_record_ids":["CN-NT-CAT-00374"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%99%B7%E7%9F%B3%E5%A0%82_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '偶成', NULL, '五言律詩', 5, '吟詠隨真性，
行藏聴自然。
因窮閒半世，
託病謝諸縁。
乞字人催債，
脩琴鋪索錢。
辛勤猶一事，
洗硯竹根邊。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00775","source_record_id":"CN-NT-CAT-00375","alias_record_ids":["CN-NT-CAT-00375"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%81%B6%E6%88%90_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '秋日偶成', NULL, '五言律詩', 5, '山翠夕陽天，
齋居息衆縁。
倦啼將暮鳥，
哀咽過秋蟬。
榻靜喧松雨，
窻疎納竹煙。
微吟多信步，
行到蓼花邊。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00776","source_record_id":"CN-NT-CAT-00376","alias_record_ids":["CN-NT-CAT-00376"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%A7%8B%E6%97%A5%E5%81%B6%E6%88%90_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '經廢寺', NULL, NULL, NULL, '寳殿莽蕭蕭，
殘僧宿敝寮。
壁餘昏後畫，
樹絶掛時瓢。
碑毁趺損，
梁荒䑕族驕。
聴經知識少，
馴虎度危橋。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00777","source_record_id":"CN-NT-CAT-00377","alias_record_ids":["CN-NT-CAT-00377"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%B6%93%E5%BB%A2%E5%AF%BA_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '不寐', NULL, '五言律詩', 5, '展轉懷鄉國，
愁心夜更繁。
猿聲煙外峽，
漁火水邊村。
屢醒無完夢，
頻啼有亂痕。
廿年嬰世網，
銷盡幾多魂。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00778","source_record_id":"CN-NT-CAT-00378","alias_record_ids":["CN-NT-CAT-00378"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E4%B8%8D%E5%AF%90_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '有感', NULL, '五言律詩', 5, '久雨防時歉，
囊空米價騰。
子錢殘嵗急，
官賦隔年徴。
薄劣明時棄，
疎慵末俗憎。
處籬同斥鷃，
未敢望鵾鵬。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00779","source_record_id":"CN-NT-CAT-00379","alias_record_ids":["CN-NT-CAT-00379"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%9C%89%E6%84%9F_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '擬古', NULL, '五言古詩', 5, '徙倚髙樓上，
西北多浮雲。
浮雲望不極，
妾淚徒紛紛。
丈夫思報國，
仗劍逺從軍。
十年遼水上，
生死不相聞。
洛陽有異卉，
灼灼生路傍。
顔色如朝霞，
百步聞馨香。
五陵多逰冶，
觀者如堵墻。
竟日歡不足，
秉燭飛羽觴。
涼秋降白露，
氣序回清商。
嗟哉此異卉，
倐忽無輝光。
容華不足恃，
歡愛靡故常。
因之感薄俗，
意緒重慘傷。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00780","source_record_id":"CN-NT-CAT-00380","alias_record_ids":["CN-NT-CAT-00380"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%93%AC%E5%8F%A4_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '詠荆軻', NULL, '五言古詩', 5, '荆卿一劍客，
擊築㳺燕都。
許身太子丹，
生死誓不渝。
文夫報知已，
何惜此㣲軀。
悲歌度易水，
慷慨自驅車。
匕首中銅柱，
非由劍術疎。
報秦雖不濟，
千載仰雄圖。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00781","source_record_id":"CN-NT-CAT-00381","alias_record_ids":["CN-NT-CAT-00381"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%92%8F%E8%8D%86%E8%BB%BB_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '薤露', NULL, '五言古詩', 5, '日出何杲杲，
薤露不長保。
人生在世間，
豈能長夀考。
穰穰陌上塵，
離離墳畔草。
殤子與彭籛，
胡然較遲早。
瞻彼薤露晞，
感歎傷懷抱。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00782","source_record_id":"CN-NT-CAT-00382","alias_record_ids":["CN-NT-CAT-00382"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%96%A4%E9%9C%B2_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '詠懷', NULL, '五言古詩', 5, '歳序如轉轂，
一去無還期。
形容久不逮，
臨鏡始嘆悲。
悠悠夢寐間，
覺寤何其遲。
處世三十年，
履厯多險巇。
世事古猶今，
此意當自知。
奈何㣲脆軀，
與俗争奔馳。
奔馳覺生累，
守靜性可怡。
老莊有明訓，
役役將何為。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00783","source_record_id":"CN-NT-CAT-00383","alias_record_ids":["CN-NT-CAT-00383"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%92%8F%E6%87%B7_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '感遇', NULL, '五言古詩', 5, '夫子且遁世，
結廬居青門。
山居絶塵鞅，
衆慮寡所營。
長嘯谷聲應，
撫琴薰風生。
雲流古洞濕，
雨過寒潭清。
年光自代謝，
草木隨枯榮。
且盡杯中酒，
遑圖身後名。
出門盡秋色，
策杖登寒山。
雲來幽徑迷，
風急衣裳單。
林深豺虎嘷，
洞古虬龍蟠。
路逺人煙絶，
日昃不得餐。
蒿藜蔽田野，
中心自悲酸。
嚱吁望絶巘，
始知行路難。
不如歸林臥，
長嘯賦猗蘭。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00784","source_record_id":"CN-NT-CAT-00384","alias_record_ids":["CN-NT-CAT-00384"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%84%9F%E9%81%87_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '田家雜興', NULL, '五言古詩', 5, '春風動郊墟，
村村事農務。
桑柘䕃比隣，
鶬鶊鳴髙樹。
訪舊入城稀，
持饁歸田暮。
雞犬識井閭，
牛羊諳村路。
此中寡所營，
悠然有眞趣。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00785","source_record_id":"CN-NT-CAT-00385","alias_record_ids":["CN-NT-CAT-00385"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%94%B0%E5%AE%B6%E9%9B%9C%E8%88%88_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '猛虎行', NULL, '五言古詩', 5, '上山采蘼蕪，
下山采蘼蕪。
采采猶未巳，
白日將崦嵫。
歸來逢猛虎，
咆哮當路隅。
徬徨何所之，
林莽多人居。
豈無桑間人，
輕薄同秋胡。
此身雖可噬，
此節安可渝。
甘心飼猛虎，
矢志同羅敷。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00786","source_record_id":"CN-NT-CAT-00386","alias_record_ids":["CN-NT-CAT-00386"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%8C%9B%E8%99%8E%E8%A1%8C_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '聽鶯曲', NULL, NULL, NULL, '條風淡蕩春將半，
倚欄忽聽鶯聲亂。
隔竹綿蠻別様啼，
遶林睍睆相呼喚。
相喚相呼不住聲，
聲聲偏動冶逰情。
王孫載酒青樓醉，
美女尋芳紫陌行。
青樓紫陌春風徧，
一種嬌聲千萬變。
彷彿秦筝出谷聞，
依稀羌笛隨風囀。
秦筝羌笛韻悠揚，
幾處歡娛幾斷腸。
閨中少婦悲征戍，
路上行人憶故鄉。
故鄉𣺌何許，
鶯聲何太苦。
征戍隔遼陽，
聞鶯空自傷。
鶯來鶯去自年年，
聽此啼聲倍可憐。
百年愁鬢聲中改，
九十春光舌上遷。
莫嘆韶華如轉轂，
愛鶯且賦聽鶯曲。
但得長聞栁外聲，
何辭頻進杯中醁。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00787","source_record_id":"CN-NT-CAT-00389","alias_record_ids":["CN-NT-CAT-00389"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%81%BD%E9%B6%AF%E6%9B%B2_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '送遠曲', NULL, '七言律詩', 7, '津亭下葉紛如雨，
客子逺㳺何處所。
悠悠一別無還期，
相對悲啼不能語。
此去山中經幾萬，
勸君惟有加餐飯。
須臾分手各東西，
猶聽前林征馬嘶。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00788","source_record_id":"CN-NT-CAT-00390","alias_record_ids":["CN-NT-CAT-00390"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%80%81%E9%81%A0%E6%9B%B2_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '老將行', NULL, '七言古詩', 7, '老夫元是良家子，
少年流落戎行裏。
能將一劍淨煙塵，
幾入重圍身不死。
纍纍金印肘間懸，
塞上馳驅五十年。
已羨功勲載盟府，
久看姓字書燕然。
一朝謝病歸巖壑，
門外蕭條可羅雀。
身經百戰未龍鍾，
猶向人前誇矍鑠。
寳劍年多鋒鍔銷，
櫪中老驥鳴蕭蕭。
戎衣掛壁成塵土，
舊日紅旗顔色凋。
一自投閒經幾載，
請纓壯志還應在。
遥望沙場願裹屍，
猶思銅柱標炎海。
鋒鏑今年去備邊，
連營烽火通甘泉。
多少材官俱束手，
無人賈勇能登先。
將軍聞此氣勃勃，
目眥裂盡冠衝髪。
便往投書獻至尊，
雄心誓欲探虎窟。
據鞍顧盼出轅門，
埀老還堪報主恩。
但令此去清沙漠，
不管金鎗臂上痕。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00789","source_record_id":"CN-NT-CAT-00391","alias_record_ids":["CN-NT-CAT-00391"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%80%81%E5%B0%87%E8%A1%8C_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '秋夜曲', NULL, '七言古詩', 7, '畫幕含春度清吹，
髙燒絳蠟金盤膩。
銅龍滴露夜聲沈，
老兎崩雲秋影墜。
銀筝斷續檀槽語，
紫霧迷濛罩金縷。
蟬衫麟帶委羅屏，
枕花濕透巫峰雨。
牽絲曉井啼烏急，
寒螿弔月香蘭泣。
紅光漸射菱花臺，
又拂嬌蛾寫春碧。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00790","source_record_id":"CN-NT-CAT-00392","alias_record_ids":["CN-NT-CAT-00392"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%A7%8B%E5%A4%9C%E6%9B%B2_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '寄衣曲', NULL, '七言古詩', 7, '流黃機上鴛鴦錦，
明滅疎燈照孤枕。
空閨冷月自娟娟，
絶塞金風何凜凜。
起視明河漏已殘，
沙塲遥望路漫漫。
羅幃錦帳人何在，
毳幙氊裘地更寒。
手剔殘燈取刀尺，
製得征衣寄征客。
去年寄去無回音，
此日無由識寛窄。
寛窄如今未可知，
幾回欲剪又遲疑。
金刀未下腸先斷，
弱線初縫淚自垂。
淚垂㸃㸃俱成血，
汚在征衣不能滅。
殷勤為拭衣上痕，
恐令孤客添愁絶。
掩淚裁衣逺寄將，
妾身不及此衣裳。
衣裳猶得親君體，
賤妾空居天一方。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00791","source_record_id":"CN-NT-CAT-00393","alias_record_ids":["CN-NT-CAT-00393"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%AF%84%E8%A1%A3%E6%9B%B2_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '征婦怨', NULL, '七言律詩', 7, '今年賊陷臨洮府，
殺死官軍何可數。
征夫塞外骨成山，
少婦閨中淚如雨。
死生消息總難知，
欲往招魂又自疑。
機中幾度聞嘶馬，
又恐夫歸投杼下。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00792","source_record_id":"CN-NT-CAT-00394","alias_record_ids":["CN-NT-CAT-00394"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%BE%81%E5%A9%A6%E6%80%A8_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '古別離', NULL, NULL, NULL, '君身如車輪，
去去無廻轍。
妾淚如井泉，
涓涓滴不竭。
歡愛能幾時，
傷哉此離別。
蕭蕭征馬向人嘶，
欲別未別心慘悽。
深閨不識天涯路，
但向門前看馬蹄。
送君試折長隄栁，
立馬躊蹰豈能久。
明年栁發今年枝，
還記今年送別時。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00793","source_record_id":"CN-NT-CAT-00395","alias_record_ids":["CN-NT-CAT-00395"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%8F%A4%E5%88%AB%E9%9B%A2_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '古戰場', NULL, NULL, NULL, '漢家將軍猛如虎，
手執長殳腰大斧。
白首從征恨數竒，
可憐性命輕如羽。
鼔聲死兮弓絶，
狼奔䑕竄無行伍。
良家百萬試鋒鋩，
枯骨如山委黃土。
燐火星星㸃白楊，
黃雲漠漠依邊樹。
千載猶聞戰血腥，
夜深不禁啼猿苦。
魑魅山魈當路號，
哀聲長亂黃昏雨。
逰魂難返玉門闗，
怨魄年年成杜宇。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00794","source_record_id":"CN-NT-CAT-00396","alias_record_ids":["CN-NT-CAT-00396"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%8F%A4%E6%88%B0%E5%A0%B4_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '築城詞', NULL, '七言古詩', 7, '丁夫抱杵城頭築，
朱顔少婦城邊哭。
哭聲未絶城已崩，
無數丁夫遭殺戮。
殺戮丁夫就此埋，
半為黃土半人骸。
長城未畢山東亂，
四海紛紛歸楚漢。
吁嗟吕政胡為乎，
亡秦乃在廢扶蘇。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00795","source_record_id":"CN-NT-CAT-00397","alias_record_ids":["CN-NT-CAT-00397"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%AF%89%E5%9F%8E%E8%A9%9E_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '去婦詞', NULL, '七言古詩', 7, '紅妝洗盡顔憔悴，
一片愁心幾行淚。
良人重色輕別離，
舊日恩情頓相棄。
含悲含怨出深閨，
宛轉躊躇更慘悽。
枝頭菡萏分連理，
枕上鴛鴦散並棲。
鴛鴦菡萏歸何處，
十載綢繆今別去。
往事翻同墜井瓶，
餘生却類飄風絮。
憶昔當年初嫁君，
明璫翠袖紅羅裙。
帳開綺閣連宵月，
夢遶巫山一段雲。
荏苒光隂如轉轂，
人情日久多飜覆。
薄命從來怨玉顔，
嬌姿一旦辭金屋。
萬轉千廻不下堂，
悲啼那忍別姑嫜。
君恩似水終難返，
妾意如膠詎敢忘。
心知別去難重見，
手把君衣苦留戀。
此生無計入君家，
芳魂願化孤飛燕。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00796","source_record_id":"CN-NT-CAT-00398","alias_record_ids":["CN-NT-CAT-00398"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%8E%BB%E5%A9%A6%E8%A9%9E_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '俠客行', NULL, '七言古詩', 7, '兩人市中相耳語，
欲報深讐誰敢去。
壯士聞之氣鬱陶，
平生俠烈同荆髙。
髪上指冠淚如雨，
借問君讐在何許。
一劍朝辭都市傍，
素車直指邯鄲路。
刺殺讐人函首歸，
争看頸血猶沾衣。
主人欲奉千金報，
問以姓名終不告。
辭君躍馬出都門，
君但報讐毋報恩。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00797","source_record_id":"CN-NT-CAT-00399","alias_record_ids":["CN-NT-CAT-00399"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E4%BF%A0%E5%AE%A2%E8%A1%8C_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '北邙行', NULL, NULL, NULL, '洛陽城外邙山麓，
舊哀呼新哭。
黃昏髑髏作人語，
白晝烏鳶攫人肉。
新墳古塜爭嵯峨，
世間人少北邙多。
北邙山中松柏樹，
聽盡車前薤露歌。
人生處世多辛苦，
賢愚貴賤同抔土。
不如歸去學還丹，
丹成白日生羽翰。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00798","source_record_id":"CN-NT-CAT-00400","alias_record_ids":["CN-NT-CAT-00400"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%8C%97%E9%82%99%E8%A1%8C_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '古怨', NULL, NULL, NULL, '當時初嫁君，
貌比楊花好。
今日與君離，
貌比楊花老。
楊衰能再榮，
妾貌終枯槁。
君如記妾舊容華，
但看明年楊白花。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00799","source_record_id":"CN-NT-CAT-00401","alias_record_ids":["CN-NT-CAT-00401"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%8F%A4%E6%80%A8_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-5f90-71a5', 0, '代閨人答輕薄少年', NULL, NULL, NULL, '妾本燕趙姿，
委身事君子。
憶昔深閨私語時，
指天誓日同生死。
一朝執㦸赴長安，
彼此恩情隔萬山。
經年去住無消息，
何處留連不肯還。
聞君日日耽㳺冶，
蹴踘鬬雞兼走馬。
醉裏常抛金彈丸，
狂來碎却珊瑚把。
自矜豪俊又繁華，
百萬黃金散狹邪。
昨宵趙女顔如玉，
今日燕姬色似花。
如花似玉争歌舞，
歡娛豈識淒涼苦。
樓上朝朝望白雲，
枕邊夜夜啼紅雨。
流年青鬢嘆蹉跎，
冷落深閨可奈何。
捲簾忽聽鶯聲老，
又是春光一度過。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00800","source_record_id":"CN-NT-CAT-00402","alias_record_ids":["CN-NT-CAT-00402"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E4%BB%A3%E9%96%A8%E4%BA%BA%E7%AD%94%E8%BC%95%E8%96%84%E5%B0%91%E5%B9%B4_(%E5%BE%90%E7%86%A5)","review_status":"auto-extracted","review_reasons":[]}')
)
INSERT INTO poems (
  poet_id, poem_no, volume, title_zh, title_ko, category, meter, body_zh,
  is_notable, status, quality, review_memo
)
SELECT
  p.id,
  COALESCE(existing_poem_count.max_poem_no, 0)
    + row_number() OVER (PARTITION BY p.id ORDER BY ip.title_zh, ip.body_zh)::integer,
  ip.volume::integer, ip.title_zh, ip.title_ko, ip.category, ip.meter::integer, ip.body_zh,
  TRUE, ip.status, ip.quality, ip.review_memo
FROM input_poems ip
JOIN poets p ON p.title_id = ip.poet_slug
LEFT JOIN LATERAL (
  SELECT max(poem_no) AS max_poem_no
  FROM poems
  WHERE poet_id = p.id
) existing_poem_count ON TRUE
WHERE NOT EXISTS (
  SELECT 1
  FROM poems existing
  WHERE existing.poet_id = p.id
    AND existing.title_zh = ip.title_zh
    AND existing.body_zh = ip.body_zh
);

UPDATE poets p
SET poem_count = sub.cnt
FROM (
  SELECT poet_id, count(*)::integer AS cnt
  FROM poems
  WHERE poet_id IN (SELECT id FROM poets WHERE title_id IN ('candidate-ming-5f90-71a5', 'candidate-ming-738b-4e16-8c9e', 'candidate-ming-738b-7acb-9053', 'candidate-ming-674e-5922-967d', 'candidate-ming-6c6a-5ee3-6d0b', 'candidate-ming-80e1-61c9-9e9f', 'candidate-ming-5f6d-5b6b-8cbd', 'candidate-song-5289-5b50-7fec'))
  GROUP BY poet_id
) sub
WHERE p.id = sub.poet_id;

-- Review counts before COMMIT when applying manually:
SELECT quality, status, count(*) FROM poems WHERE quality IN ('cnnt-auto') GROUP BY quality, status ORDER BY quality, status;
SELECT p.era_period, count(pm.id) FROM poets p JOIN poems pm ON pm.poet_id = p.id WHERE p.title_id IN ('candidate-ming-5f90-71a5', 'candidate-ming-738b-4e16-8c9e', 'candidate-ming-738b-7acb-9053', 'candidate-ming-674e-5922-967d', 'candidate-ming-6c6a-5ee3-6d0b', 'candidate-ming-80e1-61c9-9e9f', 'candidate-ming-5f6d-5b6b-8cbd', 'candidate-song-5289-5b50-7fec') GROUP BY p.era_period ORDER BY p.era_period;

ROLLBACK;
-- COMMIT;
