-- Generated by scripts/build_cn_translation_pipeline_staging.mjs
-- Part: 8/13
-- Purpose: stage CN pre-Tang and Song/Yuan/Ming poems into the JDS translation pipeline.
-- Translator decision: JDS backend=gemini model=gemini-2.5-flash-lite prompt=pipeline/translate/prompts/v5_full.txt.
-- Safety: inserts only missing poet slug + title_zh + body_zh rows. Default ending is ROLLBACK.

BEGIN;

WITH input_poets(slug, name_zh, name_ko, life_raw, era_period, country) AS (
  VALUES
    ('candidate-song-5f90-7167', '徐照', NULL, NULL, '宋', 'CN'),
    ('candidate-song-859b-5e2b-8463', '薛師董', NULL, NULL, '宋', 'CN'),
    ('candidate-song-7fc1-5377', '翁卷', NULL, NULL, '宋', 'CN'),
    ('candidate-song-8d99-5e2b-79c0', '趙師秀', NULL, NULL, '宋', 'CN'),
    ('candidate-song-5f90-74a3', '徐璣', NULL, NULL, '宋', 'CN'),
    ('candidate-song-9673-5085-826f', '陳傅良', NULL, NULL, '宋', 'CN'),
    ('candidate-song-767d-7389-87fe', '白玉蟾', NULL, NULL, '宋', 'CN'),
    ('candidate-song-845b-8d77-8015', '葛起耕', NULL, NULL, '宋', 'CN'),
    ('candidate-song-6234-654f', '戴敏', NULL, NULL, '宋', 'CN'),
    ('candidate-ming-6c88-660e-81e3', '沈明臣', NULL, NULL, '明', 'CN'),
    ('candidate-song-9127-6df1', '鄧深', NULL, NULL, '宋', 'CN'),
    ('candidate-song-5289-514b-838a', '劉克莊', NULL, NULL, '宋', 'CN'),
    ('candidate-song-9678-904a', '陸遊', NULL, NULL, '宋', 'CN'),
    ('candidate-song-6797-666f-7199', '林景熙', NULL, NULL, '宋', 'CN'),
    ('candidate-song-7f85-8207-4e4b', '羅與之', NULL, NULL, '宋', 'CN'),
    ('candidate-song-65bd-6a1e', '施樞', NULL, NULL, '宋', 'CN'),
    ('candidate-song-8d99-6c5d-9429', '趙汝鐩', NULL, NULL, '宋', 'CN'),
    ('candidate-song-8d99-5b5f-5805', '趙孟堅', NULL, NULL, '宋', 'CN'),
    ('candidate-song-8212-5dbd-7965', '舒嶽祥', NULL, NULL, '宋', 'CN'),
    ('candidate-song-91cb-6587-73e6', '釋文珦', NULL, NULL, '宋', 'CN'),
    ('candidate-song-859b-5b63-5ba3', '薛季宣', NULL, NULL, '宋', 'CN'),
    ('candidate-yuan-543e-4e18-884d', '吾丘衍', NULL, NULL, '元', 'CN'),
    ('candidate-yuan-8036-5f8b-9444', '耶律鑄', NULL, NULL, '元', 'CN'),
    ('candidate-ming-6bb7-594e', '殷奎', NULL, NULL, '明', 'CN'),
    ('candidate-ming-7d00-9035-5b9c', '紀逵宜', NULL, NULL, '明', 'CN'),
    ('candidate-song-738b-708e', '王炎', NULL, NULL, '宋', 'CN')
)
INSERT INTO poets (title_id, name_zh, name_ko, life_raw, era_period, poem_count)
SELECT slug, name_zh, name_ko, life_raw, era_period, 0
FROM input_poets
ON CONFLICT (title_id) DO UPDATE SET
  name_zh = EXCLUDED.name_zh,
  name_ko = COALESCE(EXCLUDED.name_ko, poets.name_ko),
  life_raw = COALESCE(EXCLUDED.life_raw, poets.life_raw),
  era_period = EXCLUDED.era_period;

WITH input_poems(poet_slug, volume, title_zh, title_ko, category, meter, body_zh, status, quality, review_memo) AS (
  VALUES
    ('candidate-song-5f90-7167', 0, '宿寺', NULL, NULL, NULL, '古殿清燈冷，
虛堂明本作廊。
葉掃風。
掩關人迹外，
得句佛香中。
鶴睡應無夢，
僧談必悟空。
坐驚窓欲曉，
片月在林東。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00561","source_record_id":"CN-NT-CAT-00144","alias_record_ids":["CN-NT-CAT-00144"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%AE%BF%E5%AF%BA_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '題江心寺', NULL, '五言律詩', 5, '兩寺今爲一，
僧多外國人。
流來天際水，
截斷世間塵。
鴉宿腥林徑，
龍歸損塔輪。
卻疑成片石，
曾坐謝公身。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00562","source_record_id":"CN-NT-CAT-00145","alias_record_ids":["CN-NT-CAT-00145"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%A1%8C%E6%B1%9F%E5%BF%83%E5%AF%BA_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '題桃花夫人廟', NULL, '五言律詩', 5, '一樹桃花發，
桃花即是君。
空祠臨野水，
何處覓行雲。
事迹樵人說，
爐香過客焚。
雨添碑上蘚，
難讀古時文。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00563","source_record_id":"CN-NT-CAT-00146","alias_record_ids":["CN-NT-CAT-00146"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%A1%8C%E6%A1%83%E8%8A%B1%E5%A4%AB%E4%BA%BA%E5%BB%9F_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '露', NULL, NULL, NULL, '立久衣襟潤，
空中氣結成。
光凝蘭葉膩，
冷逼鶴黃本作桂。
又覺爲霜近，
猶能向日明。
惟知漢宮內，
千尺有金莖。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00564","source_record_id":"CN-NT-CAT-00147","alias_record_ids":["CN-NT-CAT-00147"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%9C%B2_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '菊', NULL, '五言律詩', 5, '氣受一歲足，
千花極後芳。
蕊浮茶鼎沸，
色染道衣黃。
天上虛星落，
人間壽水香。
鄧州兵革外，
流種遍江鄉。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00565","source_record_id":"CN-NT-CAT-00148","alias_record_ids":["CN-NT-CAT-00148"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%8F%8A_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '子規', NULL, '五言律詩', 5, '羽類是遊魂，
哀多屬曙昏。
一時亡國恨，
千古向人言。
山竹已應裂，
野花猶更繁。
昔曾令杜甫，
再拜憶君尊。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00566","source_record_id":"CN-NT-CAT-00149","alias_record_ids":["CN-NT-CAT-00149"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%AD%90%E8%A6%8F_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '鷺鷥', NULL, '五言律詩', 5, '一點白如雪，
頂黏絲數莖。
沙邊行有跡，
空外過無聲。
高柳巢方穩，
危灘立不驚。
每看閑意思，
漁父是前生。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00567","source_record_id":"CN-NT-CAT-00150","alias_record_ids":["CN-NT-CAT-00150"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%B7%BA%E9%B7%A5_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '歸來', NULL, '五言律詩', 5, '歸來長獨坐，
誰更伴吾行。
不念爲生拙，
偏思得句清。
園晴秋菜少，
井涸夜泉生。
愛聽燈前雨，
松聲相雜鳴。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00568","source_record_id":"CN-NT-CAT-00151","alias_record_ids":["CN-NT-CAT-00151"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%AD%B8%E4%BE%86_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '漁家', NULL, NULL, NULL, '阿翁年紀老，
生計在綸絲。
野水無人占，
扁舟逐處移。
數鱗新柳串，
一笛小兒吹。
有酒人明本、顧本作全。
公卿要識誰。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00569","source_record_id":"CN-NT-CAT-00152","alias_record_ids":["CN-NT-CAT-00152"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%BC%81%E5%AE%B6_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '山中即事', NULL, NULL, NULL, '著履明本、顧本作屐。
上崔嵬，
呼兒注瓦杯。
千岑黃本作嶺。
經雨後，
一鴈帶秋來。
野艇乘潮發，
山園逐主開。
餘生落樵牧，
開卷明本、顧本作門巷。
少塵埃。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00570","source_record_id":"CN-NT-CAT-00153","alias_record_ids":["CN-NT-CAT-00153"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%B1%B1%E4%B8%AD%E5%8D%B3%E4%BA%8B_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '鴈', NULL, NULL, NULL, '今春北歸鴈，
秋至又南征。
冷避燕關雪，
暖逢湘水晴。
連行衝原作銜，
據黃本、明本、顧本改。
並食雜鷗行。
沙上無繒黃本作矰。
相呼一夜鳴。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00571","source_record_id":"CN-NT-CAT-00154","alias_record_ids":["CN-NT-CAT-00154"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%B4%88_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '蟬', NULL, '五言律詩', 5, '葉落無蟬在，
又隨林葉生。
不離荒苑處，
偏感異鄉情。
幽韻松風合，
枵腸竹露清。
無端溪鳥逐，
飛落地中行。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00572","source_record_id":"CN-NT-CAT-00155","alias_record_ids":["CN-NT-CAT-00155"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%9F%AC_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '登祝融峰', NULL, '五言律詩', 5, '祝融高莫比，
身到勝傳聞。
日動洞庭水，
風開衡嶽雲。
老僧冬離寺，
群狖夜歸墳。
後洞連方廣，
山頭路即分。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00573","source_record_id":"CN-NT-CAT-00156","alias_record_ids":["CN-NT-CAT-00156"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%99%BB%E7%A5%9D%E8%9E%8D%E5%B3%B0_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '送翁靈舒遊邊', NULL, NULL, NULL, '孤劍色磨青，
深謀祕鬼靈。
離山春值雪，
憂國夜觀星。
奏凱邊人悅，
翻營戰地腥。
期君歸幕下，
何石可書名明本、顧本作銘。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00574","source_record_id":"CN-NT-CAT-00157","alias_record_ids":["CN-NT-CAT-00157"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%80%81%E7%BF%81%E9%9D%88%E8%88%92%E9%81%8A%E9%82%8A_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '贈朱道士', NULL, '五言律詩', 5, '新營一間屋，
種柳是前春。
此地已逃俗，
何時可卜鄰。
吟詩能愈疾，
得酒自忘貧。
九十頭無雪，
多應笑野人。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00575","source_record_id":"CN-NT-CAT-00158","alias_record_ids":["CN-NT-CAT-00158"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%B4%88%E6%9C%B1%E9%81%93%E5%A3%AB_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '贈九華李丹士', NULL, NULL, NULL, '長記零陵郡，
共看江上峰。
平明本、顧本作一。
生輕世事，
幾度明本、顧本作處。
認仙蹤。
轉式驅雷電，
封泥伏虎龍。
三千三百里，
今日又相逢。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00576","source_record_id":"CN-NT-CAT-00159","alias_record_ids":["CN-NT-CAT-00159"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%B4%88%E4%B9%9D%E8%8F%AF%E6%9D%8E%E4%B8%B9%E5%A3%AB_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '贈不食姑', NULL, '五言律詩', 5, '衣以青爲色，
謂如天骨青。
近年全不食，
飲水自通靈。
心信生狂語，
清羸改俗形。
半空仙樂奏，
曾向靜中聽。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00577","source_record_id":"CN-NT-CAT-00160","alias_record_ids":["CN-NT-CAT-00160"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%B4%88%E4%B8%8D%E9%A3%9F%E5%A7%91_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '喜蔣德瞻還里', NULL, '五言律詩', 5, '長作湯村夢，
今來免所思。
丹靈年命永，
琴裂壁風吹。
開戶秋花發，
終經午飯遲。
嶽陽何日去，
後集要君詩。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00578","source_record_id":"CN-NT-CAT-00161","alias_record_ids":["CN-NT-CAT-00161"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%96%9C%E8%94%A3%E5%BE%B7%E7%9E%BB%E9%82%84%E9%87%8C_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '不寐', NULL, '五言律詩', 5, '擁衾多不寐，
吟思被愁分。
雪氣衝簾入，
鴻聲帶雨聞。
兒饑因廢學，
親沒未營墳。
何致貧如此，
肝腸痛莫雲。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00579","source_record_id":"CN-NT-CAT-00162","alias_record_ids":["CN-NT-CAT-00162"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E4%B8%8D%E5%AF%90_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '白石巖', NULL, NULL, NULL, '一石入遙天，
千峰疊在前。
人行不到處，
仙去未多年。
竇暗雲生像，
簷斜日照泉。
皇朝宣賜物，
弟子尚相明本、顧本作能。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00580","source_record_id":"CN-NT-CAT-00163","alias_record_ids":["CN-NT-CAT-00163"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%99%BD%E7%9F%B3%E5%B7%96_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '題薛景石瓜廬', NULL, '五言律詩', 5, '何地有瓜廬，
平湖四畝餘。
自鋤畦上草，
不放手中書。
人遠來求字，
童閑去釣魚。
山民山上住，
却羨水邊居。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00581","source_record_id":"CN-NT-CAT-00164","alias_record_ids":["CN-NT-CAT-00164"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%A1%8C%E8%96%9B%E6%99%AF%E7%9F%B3%E7%93%9C%E5%BB%AC_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '病中作', NULL, NULL, NULL, '一原作三，
據明本、顧本改。
行三步歇，
屋漏坐頻移。
妻欲藏茶鼎，
僧能施藥資。
鄰園梅盡發，
河岸草生遲。
天解憐貧病，
難令不作詩。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00582","source_record_id":"CN-NT-CAT-00165","alias_record_ids":["CN-NT-CAT-00165"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%97%85%E4%B8%AD%E4%BD%9C_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '漁者', NULL, '七言絶句', 7, '瑟瑟風吹鬢髮飛，
自將莎草補蓑衣。
小船撐入蘆花去，
家在溪邊多不歸。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00583","source_record_id":"CN-NT-CAT-00166","alias_record_ids":["CN-NT-CAT-00166"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%BC%81%E8%80%85_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '宮詞', NULL, '七言律詩', 7, '睡眼蒙茸帶宿酲，
起來階下探春晴。
滿身花露聽鶯久，
禁鼓重新打六更。
懶臨粧架索朱綿，
上得高臺失寶鈿。
內屋深屏多畫杏，
有誰獨喜畫雙蓮。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00584","source_record_id":"CN-NT-CAT-00167","alias_record_ids":["CN-NT-CAT-00167"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%AE%AE%E8%A9%9E_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '宮怨', NULL, '七言絶句', 7, '楊柳枝疎見月痕，
夜香燒了鎖宮門。
琵琶不有愁人聽，
誰識聲中是怨言。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00585","source_record_id":"CN-NT-CAT-00168","alias_record_ids":["CN-NT-CAT-00168"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%AE%AE%E6%80%A8_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '翫月', NULL, '五言古詩', 5, '初生如金鈎，
將滿如玉盤。
古人愛明月，
月色疑可餐。
賈島倚長杉，
精魂化蟾間。
李白捉皓色，
狂不如波瀾。
何爲梅山翁，
見月長興嘆。
月多照予愁，
未久先掩關。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00586","source_record_id":"CN-NT-CAT-00169","alias_record_ids":["CN-NT-CAT-00169"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%BF%AB%E6%9C%88_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '畏虎', NULL, '五言古詩', 5, '侯門無羆虎，
進者何趑趄。
主人畏客來，
有甚虎與羆。
彼此情不安，
逢迎反憂悲。
我愛田上翁，
面有無求姿。
不怨春作苦，
聯以歲晚期。
藜藿如羊棗，
豆粟兼晨炊。
西風作霜晴，
曉寒起呼兒。
大兒收橡實，
小兒拾松枝。
無求當自求，
勿用他人爲。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00587","source_record_id":"CN-NT-CAT-00170","alias_record_ids":["CN-NT-CAT-00170"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%95%8F%E8%99%8E_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '湘江曲', NULL, '五言絶句', 5, '湘江無潮水，
日夜一向流。
別心無彼此，
兩處各悠悠。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00588","source_record_id":"CN-NT-CAT-00171","alias_record_ids":["CN-NT-CAT-00171"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%B9%98%E6%B1%9F%E6%9B%B2_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '商人婦', NULL, '七言絶句', 7, '百尺檣竿過酒樓，
竹標雉尾信風頭。
高鬟粉項商人婦，
不識人間離別愁。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00589","source_record_id":"CN-NT-CAT-00172","alias_record_ids":["CN-NT-CAT-00172"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%95%86%E4%BA%BA%E5%A9%A6_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '昭君詞', NULL, '七言絶句', 7, '琵琶彈得是胡音，
上馬低蛾淚滴襟。
畫匠枉教延壽死，
相如作賦得黃金。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00590","source_record_id":"CN-NT-CAT-00173","alias_record_ids":["CN-NT-CAT-00173"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%98%AD%E5%90%9B%E8%A9%9E_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '促促詞', NULL, NULL, NULL, '促促復促促，
東家歡欲歌，
西家悲欲哭。
丈夫力耕長忍饑，
老婦勤織長無衣。
東家鋪兵不出戶，
父爲節級兒抄簿。
一年兩度請官衣，
每月請米一石五。
小兒作軍送文字，
旬日一輪怨辛苦。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00591","source_record_id":"CN-NT-CAT-00174","alias_record_ids":["CN-NT-CAT-00174"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E4%BF%83%E4%BF%83%E8%A9%9E_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-7167', 0, '莫愁曲', NULL, '五言絶句', 5, '莫愁石城住，
今來無莫愁。
只重石城水，
曾汎莫愁舟。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00592","source_record_id":"CN-NT-CAT-00176","alias_record_ids":["CN-NT-CAT-00176"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%8E%AB%E6%84%81%E6%9B%B2_(%E5%BE%90%E7%85%A7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-859b-5e2b-8463', 0, '秋風', NULL, '五言律詩', 5, '秋風有落枝，
天籟動塤箎。
鼓角山河壯，
襟懷歲月遲。
阮生狂一嘯，
漢武老多悲。
雖有秦歌激，
終堪理釣絲。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00593","source_record_id":"CN-NT-CAT-00178","alias_record_ids":["CN-NT-CAT-00178"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%A7%8B%E9%A2%A8_(%E8%96%9B%E5%B8%AB%E8%91%A3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-7fc1-5377', 0, '贈張亦', NULL, NULL, NULL, '興兵又罷兵，
策士恥無名。
閑西巖集作乍。
見秋風起，
猶生萬里情。
借窓臨水歇，
沽酒對花傾。
示我新詩卷，
如編衆西巖集作珠。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00594","source_record_id":"CN-NT-CAT-00179","alias_record_ids":["CN-NT-CAT-00179"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%B4%88%E5%BC%B5%E4%BA%A6_(%E7%BF%81%E5%8D%B7)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-8d99-5e2b-79c0', 0, '送薛子舒赴華亭船官', NULL, '五言律詩', 5, '竹籠盛書去，
遙知官事閒。
水程春有雨，
海岸曉無山。
奥理漸摩後，
清名䕶養間。
坐曹觀剡木，
意與易相關。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00595","source_record_id":"CN-NT-CAT-00180","alias_record_ids":["CN-NT-CAT-00180"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%80%81%E8%96%9B%E5%AD%90%E8%88%92%E8%B5%B4%E8%8F%AF%E4%BA%AD%E8%88%B9%E5%AE%98_(%E8%B6%99%E5%B8%AB%E7%A7%80)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-74a3', 0, '湘中', NULL, '五言律詩', 5, '舊說湘中事，
身來又可尋。
廟存虞帝迹，
江照楚臣心。
爲客人俱遠，
題名刻自深。
春迴洲渚綠，
遥望正沉吟。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00596","source_record_id":"CN-NT-CAT-00181","alias_record_ids":["CN-NT-CAT-00181"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%B9%98%E4%B8%AD_(%E5%BE%90%E7%92%A3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-74a3', 0, '喜雨', NULL, '五言律詩', 5, '自入春來旱，
祈求到夏中。
數朝人盡恐，
今夜雨須通。
雲氣昏猶散，
雷聲隠漸隆。
池魚先得活，
歡喜與予同。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00597","source_record_id":"CN-NT-CAT-00182","alias_record_ids":["CN-NT-CAT-00182"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%96%9C%E9%9B%A8_(%E5%BE%90%E7%92%A3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-74a3', 0, '不食姑', NULL, '五言律詩', 5, '惟誦天童咒，
飲泉能不饑。
只緣多自譽，
翻以致人疑。
賦質全如鶴，
謀生卻似龜。
綠華通籍後，
會報女仙知。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00598","source_record_id":"CN-NT-CAT-00183","alias_record_ids":["CN-NT-CAT-00183"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E4%B8%8D%E9%A3%9F%E5%A7%91_(%E5%BE%90%E7%92%A3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-74a3', 0, '題薛景石瓜廬', NULL, '五言律詩', 5, '近舍新爲圃，
澆鋤及晚凉。
因看瓜蔓吐，
識得道心長。
隔沼嘉蔬潔，
侵畦異草香。
小舟應買在，
門外是漁鄉。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00599","source_record_id":"CN-NT-CAT-00184","alias_record_ids":["CN-NT-CAT-00184"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%A1%8C%E8%96%9B%E6%99%AF%E7%9F%B3%E7%93%9C%E5%BB%AC_(%E5%BE%90%E7%92%A3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-74a3', 0, '夏日', NULL, NULL, NULL, '書疑當作晝。
困當檐立，
微風動鬢毛。
桐陰遮井暗，
鶯語出林高。
執熱思時雨，
如疲得美醪。
居然吟思起，
獨步幾周遭。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00600","source_record_id":"CN-NT-CAT-00185","alias_record_ids":["CN-NT-CAT-00185"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%A4%8F%E6%97%A5_(%E5%BE%90%E7%92%A3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-74a3', 0, '雨中', NULL, '五言律詩', 5, '雨來連幾夕，
滿漲一湖波。
苦似前時少，
毋嫌此日多。
砌荒蝸出舍，
屋漏燕移窠。
今歲翻成稔，
田塍亦産禾。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00601","source_record_id":"CN-NT-CAT-00186","alias_record_ids":["CN-NT-CAT-00186"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%9B%A8%E4%B8%AD_(%E5%BE%90%E7%92%A3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-74a3', 0, '送翁靈舒遊邊', NULL, '五言律詩', 5, '子向江淮去，
應懷計策新。
但須先審己，
然後可圖人。
戰野寒猶力，
邊城草不春。
曹劉若無競，
閑却卧龍身。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00602","source_record_id":"CN-NT-CAT-00187","alias_record_ids":["CN-NT-CAT-00187"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%80%81%E7%BF%81%E9%9D%88%E8%88%92%E9%81%8A%E9%82%8A_(%E5%BE%90%E7%92%A3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-74a3', 0, '初夏', NULL, '五言律詩', 5, '一雨臨初夏，
驚雷昨夜新。
地晴煙冉冉，
堤漲淥鱗鱗。
蘭麝銷衣潤，
珊瑚浄几塵。
牆陰舊無竹，
筍過謝東鄰。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00603","source_record_id":"CN-NT-CAT-00188","alias_record_ids":["CN-NT-CAT-00188"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%88%9D%E5%A4%8F_(%E5%BE%90%E7%92%A3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-74a3', 0, '宿寺', NULL, '五言律詩', 5, '古木山邊寺，
深松徑底風。
獨吟侵夜半，
清坐雜禪中。
殿靜燈光小，
經殘磬韻空。
不知清夢遠，
啼鳥在林東。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00604","source_record_id":"CN-NT-CAT-00189","alias_record_ids":["CN-NT-CAT-00189"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%AE%BF%E5%AF%BA_(%E5%BE%90%E7%92%A3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-74a3', 0, '霜', NULL, NULL, NULL, '詩鬢曉星星，
霜天似水清。
風當窓眼入，
冰向硯池生。
已瘦梅明本、顧本作花。
猶乾竹葉聲。
夜來天地潔，
惟是月華明。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00605","source_record_id":"CN-NT-CAT-00190","alias_record_ids":["CN-NT-CAT-00190"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%9C%9C_(%E5%BE%90%E7%92%A3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-74a3', 0, '山居', NULL, NULL, NULL, '柳竹藏花塢，
茅茨接草池。
開門驚燕子，
汲水得魚兒。
地僻春猶靜，
人閑日自明本、顧本作更。
山禽啼忽住，
飛起又相隨。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00606","source_record_id":"CN-NT-CAT-00191","alias_record_ids":["CN-NT-CAT-00191"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%B1%B1%E5%B1%85_(%E5%BE%90%E7%92%A3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-74a3', 0, '大龍湫', NULL, '五言律詩', 5, '瀑水數千尺，
何曾貼石流。
還疑眾山坼，
故使半空浮。
霧雨初相亂，
波濤忽自由。
道場從建後，
龍去任人遊。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00607","source_record_id":"CN-NT-CAT-00192","alias_record_ids":["CN-NT-CAT-00192"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%A4%A7%E9%BE%8D%E6%B9%AB_(%E5%BE%90%E7%92%A3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-74a3', 0, '寄舍弟', NULL, '五言律詩', 5, '寄問安仁弟，
弦歌又一年。
流來溪水遠，
清到縣門前。
故里人情樂，
新居物色鮮。
宦歸言話款，
正及早梅邊。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00608","source_record_id":"CN-NT-CAT-00193","alias_record_ids":["CN-NT-CAT-00193"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%AF%84%E8%88%8D%E5%BC%9F_(%E5%BE%90%E7%92%A3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-74a3', 0, '登滕王閣', NULL, '七言律詩', 7, '重重樓閣倚江乾，
岸草汀煙遠近間。
春水生時都是水，
西山青外別無山。
雲歸長若真人在，
風過猶疑帝子還。
自古舟船城下泊，
幾人來此望鄉關。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00609","source_record_id":"CN-NT-CAT-00194","alias_record_ids":["CN-NT-CAT-00194"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%99%BB%E6%BB%95%E7%8E%8B%E9%96%A3_(%E5%BE%90%E7%92%A3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-74a3', 0, '梅', NULL, '七言古詩', 7, '疎芳點點是春冰，
應笑浮華去不停。
石畔長來枝易老，
竹間瘦得萼全青。
孤高自愛香無色，
寂寞渾教影問形。
莫遣豐□種宮苑，
野橋流水最清泠。
是誰曾種白玻璃，
夐絶寒荒一點奇。
不厭壠頭千百樹，
最憐窓下兩三枝。
幽深真似離騷句，
枯健猶如賈島詩。
吟到月斜渾未已，
蕭蕭鬢影有風吹。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00610","source_record_id":"CN-NT-CAT-00195","alias_record_ids":["CN-NT-CAT-00195"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%A2%85_(%E5%BE%90%E7%92%A3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-74a3', 0, '酒', NULL, '七言律詩', 7, '才傾一盞碧澄澄，
自是山妻手法成。
不遣水多防味薄，
要令麴少得香清。
凉從荷葉風邊起，
煖向梅花月裏生。
世味總無如此味，
深知此味即淵明。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00611","source_record_id":"CN-NT-CAT-00196","alias_record_ids":["CN-NT-CAT-00196"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%85%92_(%E5%BE%90%E7%92%A3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-74a3', 0, '夜涼', NULL, '七言絶句', 7, '夜涼扶杖出山齋，
身似孤雲倚石崖。
吟就不知山月曉，
清風滿面落松釵。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00612","source_record_id":"CN-NT-CAT-00198","alias_record_ids":["CN-NT-CAT-00198"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%A4%9C%E6%B6%BC_(%E5%BE%90%E7%92%A3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-74a3', 0, '新涼', NULL, '七言絶句', 7, '水滿田疇稻葉齊，
日光穿樹曉煙低。
黃鶯也愛新涼好，
飛過青山影裏啼。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00613","source_record_id":"CN-NT-CAT-00199","alias_record_ids":["CN-NT-CAT-00199"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%96%B0%E6%B6%BC_(%E5%BE%90%E7%92%A3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-74a3', 0, '春晚', NULL, '七言絶句', 7, '午風庭院綠成衣，
春色方濃又欲歸。
蝌蚪散邊荷葉出，
酴醿香裏柳綿飛。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00614","source_record_id":"CN-NT-CAT-00200","alias_record_ids":["CN-NT-CAT-00200"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%98%A5%E6%99%9A_(%E5%BE%90%E7%92%A3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-74a3', 0, '新秋', NULL, '七言絶句', 7, '新秋一雨洗林關，
晚色清澄滿望間。
風靜白雲橫不斷，
山前又疊一重山。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00615","source_record_id":"CN-NT-CAT-00201","alias_record_ids":["CN-NT-CAT-00201"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%96%B0%E7%A7%8B_(%E5%BE%90%E7%92%A3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5f90-74a3', 0, '春雨', NULL, '七言律詩', 7, '斷橋橫落淺沙邊，
沙岸疎梅卧曉煙。
新雨漲溪三尺水，
漁翁來覓渡船錢。
柳著輕黃欲染衣，
汀沙漠漠草菲菲。
曉風吹斷寒煙碧，
無數鴛鴦溪上飛。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00616","source_record_id":"CN-NT-CAT-00203","alias_record_ids":["CN-NT-CAT-00203"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%98%A5%E9%9B%A8_(%E5%BE%90%E7%92%A3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-8d99-5e2b-79c0', 0, '白石巖', NULL, '七言絶句', 7, '誰炷清香禮少君，
數聲金磬夢中聞。
起來閑把青衣袖，
裹得欄乾一片雲。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00617","source_record_id":"CN-NT-CAT-00206","alias_record_ids":["CN-NT-CAT-00206"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%99%BD%E7%9F%B3%E5%B7%96_(%E8%B6%99%E5%B8%AB%E7%A7%80)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-9673-5085-826f', 0, '遊白石巖', NULL, '五言古詩', 5, '地向東南傾，
石際滄海立。
蛟鼉限波濤，
鷄犬得城邑。
居然通國望，
跋莫他山及。
道人獨有之，
置屋三四級。
幾看星月爛，
卻聽風雨急。
於今二百年，
我共冥鴻集。
晤語夕陽低，
對酒秋旻濕。
明朝江上舟，
避雨漁翁笠。
邂逅一俛仰，
此道可於邑。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00618","source_record_id":"CN-NT-CAT-00208","alias_record_ids":["CN-NT-CAT-00208"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%81%8A%E7%99%BD%E7%9F%B3%E5%B7%96_(%E9%99%B3%E5%82%85%E8%89%AF)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-767d-7389-87fe', 0, '白石巖', NULL, '七言律詩', 7, '平野巉然石一拳，
千崖萬岫翠相連。
鳥飛不到疑無路，
雲與齊高直接天。
下面仰看巖是屋，
上頭仍有玉爲泉。
李仙丹熟山魈遁，
尚有宸章寄紫煙。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00619","source_record_id":"CN-NT-CAT-00209","alias_record_ids":["CN-NT-CAT-00209"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E7%99%BD%E7%9F%B3%E5%B7%96_(%E7%99%BD%E7%8E%89%E8%9F%BE)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-845b-8d77-8015', 0, '樓上', NULL, NULL, NULL, '樓上何人奏玉簫，
數聲和月伴春宵原作霄，
據群賢集改。
斷腸喚起江南夢，
愁絶寒梅酒半銷。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00620","source_record_id":"CN-NT-CAT-00213","alias_record_ids":["CN-NT-CAT-00213"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%A8%93%E4%B8%8A_(%E8%91%9B%E8%B5%B7%E8%80%95)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-6234-654f', 0, '樓上', NULL, '七言律詩', 7, '終朝役役晚來閑，
識破浮生一夢間。
挈榼去沽深巷酒，
倚樓貪看夕陽山。
月臨江館人橫笛，
風折蘆花雁度關。
堪羨漁翁無檢束，
扁舟占斷白雲灣。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00621","source_record_id":"CN-NT-CAT-00214","alias_record_ids":["CN-NT-CAT-00214"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%A8%93%E4%B8%8A_(%E6%88%B4%E6%95%8F)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-6c88-660e-81e3', 0, '尋僧', NULL, NULL, NULL, '卧交知絶，
尋僧出野行。
岸花紛委露，
溪竹半侵萍。
力倦逢人歇，
林昏到寺明。
小橋斜處立，
波與夕陽平。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00622","source_record_id":"CN-NT-CAT-00217","alias_record_ids":["CN-NT-CAT-00217"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%B0%8B%E5%83%A7_(%E6%B2%88%E6%98%8E%E8%87%A3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-9127-6df1', 0, '夢回', NULL, '五言律詩', 5, '日日風吹雨，
秋深寒氣催。
簷聲中夜斷，
月色上窓來。
冷砌蟲吟穩，
幽屏蝶夢回。
明朝應露重，
晚菊正宜開。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00623","source_record_id":"CN-NT-CAT-00218","alias_record_ids":["CN-NT-CAT-00218"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%A4%A2%E5%9B%9E_(%E9%84%A7%E6%B7%B1)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-5289-514b-838a', 0, '夢回', NULL, NULL, NULL, '跳出槐安有底忙，
何須更待熟黃粱。
牙籤載返善和宅，
手板抽回政事堂。
效玉川生稱銳漢，
愛楊處士號憨郎。
山中豈不差岑寂，
猶勝人間臭腐腸馮本作場。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00624","source_record_id":"CN-NT-CAT-00219","alias_record_ids":["CN-NT-CAT-00219"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%A4%A2%E5%9B%9E_(%E5%8A%89%E5%85%8B%E8%8E%8A)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-9678-904a', 0, '夢回', NULL, '五言律詩', 5, '病骨便衾暖，
羈懷怯夢回。
鐘殘燈燼落，
香冷雨聲來。
老抱憂時志，
狂非濟世材。
明朝入冬假，
燒兔薦新醅。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00625","source_record_id":"CN-NT-CAT-00220","alias_record_ids":["CN-NT-CAT-00220"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%A4%A2%E5%9B%9E_(%E9%99%B8%E6%B8%B8)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-6797-666f-7199', 0, '夢回', NULL, '七言絶句', 7, '夢回荒館月籠秋，
何處砧聲喚客愁。
深夜無風蓮葉響，
水寒更有未眠鷗。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00626","source_record_id":"CN-NT-CAT-00221","alias_record_ids":["CN-NT-CAT-00221"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%A4%A2%E5%9B%9E_(%E6%9E%97%E6%99%AF%E7%86%99)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-7f85-8207-4e4b', 0, '夢迴', NULL, '五言律詩', 5, '酒薄難成醉，
輕寒襲破衾。
夢迴孤客枕，
聽徹草蟲吟。
寂莫三秋夜，
凄凉一片心。
山林與朝市，
底處豁愁襟。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00627","source_record_id":"CN-NT-CAT-00222","alias_record_ids":["CN-NT-CAT-00222"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%A4%A2%E8%BF%B4_(%E7%BE%85%E8%88%87%E4%B9%8B)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-65bd-6a1e', 0, '夢回', NULL, '七言絶句', 7, '銀漏迢迢箭緩傳，
夢回月在早梅邊。
小池凍合寒蘆折，
應是鴛鴦夜不眠。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00628","source_record_id":"CN-NT-CAT-00223","alias_record_ids":["CN-NT-CAT-00223"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%A4%A2%E5%9B%9E_(%E6%96%BD%E6%A8%9E)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-8d99-6c5d-9429', 0, '夢回', NULL, NULL, NULL, '春意已深寒未了，
夢回鬥帳房櫳悄。
五更五群賢集本作三。
點殘月銷，
山鳥一聲先破曉。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00629","source_record_id":"CN-NT-CAT-00224","alias_record_ids":["CN-NT-CAT-00224"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%A4%A2%E5%9B%9E_(%E8%B6%99%E6%B1%9D%E9%90%A9)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-8d99-5b5f-5805', 0, '夢回', NULL, '七言絶句', 7, '點點桃花短短牆，
雨聲徹夜響迴廊。
覺來蝴蝶家山夢，
一半分明一半忘。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00630","source_record_id":"CN-NT-CAT-00225","alias_record_ids":["CN-NT-CAT-00225"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%A4%A2%E5%9B%9E_(%E8%B6%99%E5%AD%9F%E5%A0%85)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-8212-5dbd-7965', 0, '夢回', NULL, '五言律詩', 5, '月上芙蓉浦，
船依杜若洲。
歲行人冉冉，
川永夢悠悠。
天地回青眼，
江山養白頭。
老生如朽木，
安識有悲秋。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00631","source_record_id":"CN-NT-CAT-00226","alias_record_ids":["CN-NT-CAT-00226"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%A4%A2%E5%9B%9E_(%E8%88%92%E5%B2%B3%E7%A5%A5)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-91cb-6587-73e6', 0, '夢回', NULL, '七言絶句', 7, '夢回四壁無人語，
高樹蕭蕭似有風。
獨起繞池行數匝，
萬山擎雪月明中。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00632","source_record_id":"CN-NT-CAT-00227","alias_record_ids":["CN-NT-CAT-00227"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%A4%A2%E5%9B%9E_(%E9%87%8B%E6%96%87%E7%8F%A6)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-859b-5b63-5ba3', 0, '夢回二首', NULL, NULL, NULL, '憶到梯雲梯雲，
走家坊名。
哀傷韡鄂叢。
舞鸞悲引鏡，
傷雁落空弓。
清夢回時雨，
繁聲發夏蟲。
情鍾正吾輩，
匡坐泣薰風。
吾宗鮮兄弟，
何事日飄零。
凋落皆鵷鳳，
相從謝鶺鴒。
世緣那可了，
魂夢也非寧。
屈指傷心事，
端如欲曙星。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00633","source_record_id":"CN-NT-CAT-00228","alias_record_ids":["CN-NT-CAT-00228"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%A4%A2%E5%9B%9E%E4%BA%8C%E9%A6%96_(%E8%96%9B%E5%AD%A3%E5%AE%A3)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-yuan-543e-4e18-884d', 0, '夢回', NULL, '七言絶句', 7, '夣裡看花錦繡城，
淺深桃杏五霞明。
覺來忍聽催花雨，
可是春風太有情。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00634","source_record_id":"CN-NT-CAT-00229","alias_record_ids":["CN-NT-CAT-00229"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%A4%A2%E5%9B%9E_(%E5%90%BE%E4%B8%98%E8%A1%8D)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-yuan-8036-5f8b-9444', 0, '夢廻', NULL, '七言絶句', 7, '恨別故人千里外，
夢回孤枕四更過。
軒窓何處無疏雨，
不似芭蕉葉上多。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00635","source_record_id":"CN-NT-CAT-00230","alias_record_ids":["CN-NT-CAT-00230"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%A4%A2%E5%BB%BB_(%E8%80%B6%E5%BE%8B%E9%91%84)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-6bb7-594e', 0, '夢回', NULL, '五言絶句', 5, '萬里家鄉半，
三秋信息稀。
心情春已去，
魂夢夜空歸。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00636","source_record_id":"CN-NT-CAT-00231","alias_record_ids":["CN-NT-CAT-00231"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%A4%A2%E5%9B%9E_(%E6%AE%B7%E5%A5%8E)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-ming-7d00-9035-5b9c', 0, '夢回作', NULL, '七言律詩', 7, '愁緒紛綸繞四圍，
夢醒似欲識天機。
人間啼笑誰真偽，
塵外行藏無是非。
花落烏衝春色散，
酒闌客帶月明歸。
齊州九點青煙在，
遼鶴何年故里飛。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00637","source_record_id":"CN-NT-CAT-00232","alias_record_ids":["CN-NT-CAT-00232"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E5%A4%A2%E5%9B%9E%E4%BD%9C_(%E7%B4%80%E9%80%B5%E5%AE%9C)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-yuan-8036-5f8b-9444', 0, '起夜來', NULL, '五言古詩', 5, '是處聲歌席，
一一凝塵埃。
羞掩合歡帳，
獨燭夜明苔。
徙倚立中庭，
候蟲一何哀。
滿天秋色裏，
鴈過黃金臺。
所願隨清風，
明月入君懷。
中心有勞結，
期以向時開。
穨想就珍簟，
遠出繞蘭堦。
美人來幾時，
知人起夜來。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00638","source_record_id":"CN-NT-CAT-00233","alias_record_ids":["CN-NT-CAT-00233"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E8%B5%B7%E5%A4%9C%E4%BE%86_(%E8%80%B6%E5%BE%8B%E9%91%84)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-yuan-8036-5f8b-9444', 0, '戰城南', NULL, NULL, NULL, '自來古戰塲，
多在長城南，
少在長城北。
茫茫白骨甸，
如何直接黃龍磧。
或雲是從漢武開西域，
耗折十萬衆，
博得善馬數十匹。
奮軍勢務鏖擊徃來誰，
洗兵赤河水猶赤。
終棄輪䑓地，
其地於中國。
失之且何損，
得之本無益。
歴計其所得，
皆不償所失。
雖下哀痛詔，
追悔將何及。
此是萬萬古，
華夏覆車轍。
底事夤縁其迄李唐，
競喜邊功好大矜英哲。
明皇不慮漁陽厄，
萬里孤軍征碎葉。
隻輪曽不返，
得無五情熱。
暴殄生靈塗草莾，
忍徇虗名為盛烈。
君不見世間人心固結，
是謂帝王真統業。
君不聞四海內有羙談，
至元天子平江南，
何曾漂杵與溺驂。
聖人有金城，
貴謀賤戰，
不戰屈人兵。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00639","source_record_id":"CN-NT-CAT-00235","alias_record_ids":["CN-NT-CAT-00235"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E6%88%B0%E5%9F%8E%E5%8D%97_(%E8%80%B6%E5%BE%8B%E9%91%84)","review_status":"auto-extracted","review_reasons":[]}'),
    ('candidate-song-738b-708e', 0, '門有車馬客', NULL, '五言古詩', 5, '烏鵲遶屋鳴，
有客停徵騑。
問客何自來，
君家寄家書。
攝衣起迎客，
開書多苦辭。
蕣花不長好，
玉顔亦易衰。
水行有卻流，
人行無反期。
置書拜謝客，
豈不心懐歸。
事君有明義，
不得顧所私。
作書附客返，
路逺幸勿遺。
上言重自愛，
下言長相思。
相思勿相怨，
自古多別離。', 'parsed', 'cnnt-auto', '{"queue_id":"CN-TR-00640","source_record_id":"CN-NT-CAT-00237","alias_record_ids":["CN-NT-CAT-00237"],"batch":"song-yuan-ming-auto","source_url":"https://zh.wikisource.org/wiki/%E9%96%80%E6%9C%89%E8%BB%8A%E9%A6%AC%E5%AE%A2_(%E7%8E%8B%E7%82%8E)","review_status":"auto-extracted","review_reasons":[]}')
)
INSERT INTO poems (
  poet_id, poem_no, volume, title_zh, title_ko, category, meter, body_zh,
  is_notable, status, quality, review_memo
)
SELECT
  p.id,
  COALESCE(existing_poem_count.max_poem_no, 0)
    + row_number() OVER (PARTITION BY p.id ORDER BY ip.title_zh, ip.body_zh)::integer,
  ip.volume::integer, ip.title_zh, ip.title_ko, ip.category, ip.meter::integer, ip.body_zh,
  TRUE, ip.status, ip.quality, ip.review_memo
FROM input_poems ip
JOIN poets p ON p.title_id = ip.poet_slug
LEFT JOIN LATERAL (
  SELECT max(poem_no) AS max_poem_no
  FROM poems
  WHERE poet_id = p.id
) existing_poem_count ON TRUE
WHERE NOT EXISTS (
  SELECT 1
  FROM poems existing
  WHERE existing.poet_id = p.id
    AND existing.title_zh = ip.title_zh
    AND existing.body_zh = ip.body_zh
);

UPDATE poets p
SET poem_count = sub.cnt
FROM (
  SELECT poet_id, count(*)::integer AS cnt
  FROM poems
  WHERE poet_id IN (SELECT id FROM poets WHERE title_id IN ('candidate-song-5f90-7167', 'candidate-song-859b-5e2b-8463', 'candidate-song-7fc1-5377', 'candidate-song-8d99-5e2b-79c0', 'candidate-song-5f90-74a3', 'candidate-song-9673-5085-826f', 'candidate-song-767d-7389-87fe', 'candidate-song-845b-8d77-8015', 'candidate-song-6234-654f', 'candidate-ming-6c88-660e-81e3', 'candidate-song-9127-6df1', 'candidate-song-5289-514b-838a', 'candidate-song-9678-904a', 'candidate-song-6797-666f-7199', 'candidate-song-7f85-8207-4e4b', 'candidate-song-65bd-6a1e', 'candidate-song-8d99-6c5d-9429', 'candidate-song-8d99-5b5f-5805', 'candidate-song-8212-5dbd-7965', 'candidate-song-91cb-6587-73e6', 'candidate-song-859b-5b63-5ba3', 'candidate-yuan-543e-4e18-884d', 'candidate-yuan-8036-5f8b-9444', 'candidate-ming-6bb7-594e', 'candidate-ming-7d00-9035-5b9c', 'candidate-song-738b-708e'))
  GROUP BY poet_id
) sub
WHERE p.id = sub.poet_id;

-- Review counts before COMMIT when applying manually:
SELECT quality, status, count(*) FROM poems WHERE quality IN ('cnnt-auto') GROUP BY quality, status ORDER BY quality, status;
SELECT p.era_period, count(pm.id) FROM poets p JOIN poems pm ON pm.poet_id = p.id WHERE p.title_id IN ('candidate-song-5f90-7167', 'candidate-song-859b-5e2b-8463', 'candidate-song-7fc1-5377', 'candidate-song-8d99-5e2b-79c0', 'candidate-song-5f90-74a3', 'candidate-song-9673-5085-826f', 'candidate-song-767d-7389-87fe', 'candidate-song-845b-8d77-8015', 'candidate-song-6234-654f', 'candidate-ming-6c88-660e-81e3', 'candidate-song-9127-6df1', 'candidate-song-5289-514b-838a', 'candidate-song-9678-904a', 'candidate-song-6797-666f-7199', 'candidate-song-7f85-8207-4e4b', 'candidate-song-65bd-6a1e', 'candidate-song-8d99-6c5d-9429', 'candidate-song-8d99-5b5f-5805', 'candidate-song-8212-5dbd-7965', 'candidate-song-91cb-6587-73e6', 'candidate-song-859b-5b63-5ba3', 'candidate-yuan-543e-4e18-884d', 'candidate-yuan-8036-5f8b-9444', 'candidate-ming-6bb7-594e', 'candidate-ming-7d00-9035-5b9c', 'candidate-song-738b-708e') GROUP BY p.era_period ORDER BY p.era_period;

ROLLBACK;
-- COMMIT;
