-- Generated by scripts/build_cn_translation_pipeline_staging.mjs
-- Part: 3/13
-- Purpose: stage CN pre-Tang and Song/Yuan/Ming poems into the JDS translation pipeline.
-- Translator decision: JDS backend=gemini model=gemini-2.5-flash-lite prompt=pipeline/translate/prompts/v5_full.txt.
-- Safety: inserts only missing poet slug + title_zh + body_zh rows. Default ending is ROLLBACK.

BEGIN;

WITH input_poets(slug, name_zh, name_ko, life_raw, era_period, country) AS (
  VALUES
    ('cnpreqin-3fcc3c660d5a7a4d', '佚名/詩經', NULL, NULL, '先秦', 'CN')
)
INSERT INTO poets (title_id, name_zh, name_ko, life_raw, era_period, poem_count)
SELECT slug, name_zh, name_ko, life_raw, era_period, 0
FROM input_poets
ON CONFLICT (title_id) DO UPDATE SET
  name_zh = EXCLUDED.name_zh,
  name_ko = COALESCE(EXCLUDED.name_ko, poets.name_ko),
  life_raw = COALESCE(EXCLUDED.life_raw, poets.life_raw),
  era_period = EXCLUDED.era_period;

WITH input_poems(poet_slug, volume, title_zh, title_ko, category, meter, body_zh, status, quality, review_memo) AS (
  VALUES
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '有狐', NULL, NULL, NULL, '有狐綏綏，在彼淇梁，心之憂矣，之子無裳。
有狐綏綏，在彼淇厲，心之憂矣，之子無帶。
有狐綏綏，在彼淇側，心之憂矣，之子無服。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00161","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-36-33-2d-6709-72d0-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6709-72d0","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-36-33-2d-6709-72d0-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6709-72d0"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%9C%89%E7%8B%90","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '木瓜', NULL, NULL, NULL, '投我以木瓜，報之以瓊琚，匪報也，永以為好也。
投我以木桃，報之以瓊瑤，匪報也，永以為好也。
投我以木李，報之以瓊玖，匪報也，永以為好也。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00162","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-36-34-2d-6728-74dc-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6728-74dc","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-36-34-2d-6728-74dc-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6728-74dc"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%9C%A8%E7%93%9C","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '黍離', NULL, NULL, NULL, '彼黍離離，彼稷之苗。行邁靡靡，中心搖搖。知我者，謂我心憂，不知我者，謂我何求。悠悠蒼天，此何人哉！
彼黍離離，彼稷之穗。行邁靡靡，中心如醉。知我者，謂我心憂，不知我者，謂我何求。悠悠蒼天，此何人哉！
彼黍離離，彼稷之實。行邁靡靡，中心如噎。知我者，謂我心憂，不知我者，謂我何求。悠悠蒼天，此何人哉！', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00163","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-36-35-2d-9ecd-96e2-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9ecd-96e2","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-36-35-2d-9ecd-96e2-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9ecd-96e2"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%BB%8D%E9%9B%A2","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '君子于役', NULL, NULL, NULL, '君子于役，不知其期。曷至哉？雞棲于塒，日之夕矣，羊牛下來。君子于役，如之何勿思！
君子于役，不日不月。曷其有佸？雞棲于桀，日之夕矣，羊牛下括。君子于役，苟無飢渴。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00164","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-36-36-2d-541b-5b50-4e8e-5f79-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-541b-5b50-4e8e-5f79","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-36-36-2d-541b-5b50-4e8e-5f79-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-541b-5b50-4e8e-5f79"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%90%9B%E5%AD%90%E4%BA%8E%E5%BD%B9","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '君子陽陽', NULL, NULL, NULL, '君子陽陽，左執簧，右招我由房。其樂只且。
君子陶陶，左執翿，右招我由敖。其樂只且。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00165","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-36-37-2d-541b-5b50-967d-967d-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-541b-5b50-967d-967d","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-36-37-2d-541b-5b50-967d-967d-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-541b-5b50-967d-967d"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%90%9B%E5%AD%90%E9%99%BD%E9%99%BD","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '揚之水', NULL, NULL, NULL, '揚之水，不流束薪。彼其之子，不與我戍申。懷哉懷哉！曷月予還歸哉！
揚之水，不流束楚。彼其之子，不與我戍甫。懷哉懷哉！曷月予還歸哉！
揚之水，不流束蒲。彼其之子，不與我戍許。懷哉懷哉！曷月予還歸哉！
揚之水，不流束楚，終鮮兄弟，維予與女，無信人之言，人實迋女。
揚之水，不流束薪，終鮮兄弟，維予二人，無信人之言，人實不信！
揚之水，白石鑿鑿，素衣朱襮，從子于沃，既見君子，雲何不樂。
揚之水，白石皓皓，素衣朱繡，從子于鵠，既見君子，雲何其憂。
揚之水，白石粼粼，我聞有命，不敢以告人！', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00166","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-36-38-2d-63da-4e4b-6c34-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-63da-4e4b-6c34","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-36-38-2d-63da-4e4b-6c34-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-63da-4e4b-6c34","CN-CLASSIC-73-68-69-6a-69-6e-67-2d-39-32-2d-63da-4e4b-6c34-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-63da-4e4b-6c34","CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-31-36-2d-63da-4e4b-6c34-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-63da-4e4b-6c34"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%8F%9A%E4%B9%8B%E6%B0%B4","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '中谷有蓷', NULL, NULL, NULL, '中谷有蓷，暵其乾矣。有女仳離，嘅其嘆矣。嘅其嘆矣！遇人之艱難矣！
中谷有蓷，暵其脩矣。有女仳離，條其歗矣。條其歗矣！遇人之不淑矣！
中谷有蓷，暵其濕矣。有女仳離，啜其泣矣。啜其泣矣！何嗟及矣！', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00167","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-36-39-2d-4e2d-8c37-6709-84f7-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-4e2d-8c37-6709-84f7","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-36-39-2d-4e2d-8c37-6709-84f7-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-4e2d-8c37-6709-84f7"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E4%B8%AD%E8%B0%B7%E6%9C%89%E8%93%B7","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '兔爰', NULL, NULL, NULL, '有兔爰爰，雉離于羅。我生之初，尚無為。我生之後，逢此百罹，尚寐無吪？
有兔爰爰，雉離于罦。我生之初，尚無造。我生之後，逢此百憂，尚寐無覺？
有兔爰爰，雉離于罿。我生之初，尚無庸。我生之後，逢此百凶，尚寐無聦！', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00168","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-37-30-2d-5154-7230-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5154-7230","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-37-30-2d-5154-7230-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5154-7230"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%85%94%E7%88%B0","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '葛藟', NULL, NULL, NULL, '緜緜葛藟，在河之滸。終遠兄弟，謂他人父。謂他人父，亦莫我顧。
緜緜葛藟，在河之涘。終遠兄弟，謂他人母。謂他人母，亦莫我有。
緜緜葛藟，在河之漘。終遠兄弟，謂他人昆。謂他人昆，亦莫我聞。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00169","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-37-31-2d-845b-85df-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-845b-85df","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-37-31-2d-845b-85df-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-845b-85df"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E8%91%9B%E8%97%9F","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '采葛', NULL, NULL, NULL, '彼采葛兮，一日不見，如三月兮。
彼采蕭兮，一日不見，如三秋兮。
彼采艾兮，一日不見，如三歲兮。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00170","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-37-32-2d-91c7-845b-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-91c7-845b","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-37-32-2d-91c7-845b-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-91c7-845b"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%87%87%E8%91%9B","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '大車', NULL, NULL, NULL, '大車檻檻，毳衣如菼。豈不爾思，畏子不敢。
大車啍啍，毳衣如璊。豈不爾思，畏子不奔。
穀則異室，死則同穴。謂予不信，有如皦日。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00171","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-37-33-2d-5927-8eca-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5927-8eca","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-37-33-2d-5927-8eca-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5927-8eca"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%A4%A7%E8%BB%8A","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '丘中有麻', NULL, NULL, NULL, '丘中有麻，彼留子嗟。彼留子嗟，將其來施施。
丘中有麥，彼留子國。彼留子國，將其來食。
丘中有李，彼留之子。彼留之子，貽我佩玖。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00172","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-37-34-2d-4e18-4e2d-6709-9ebb-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-4e18-4e2d-6709-9ebb","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-37-34-2d-4e18-4e2d-6709-9ebb-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-4e18-4e2d-6709-9ebb"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E4%B8%98%E4%B8%AD%E6%9C%89%E9%BA%BB","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '緇衣', NULL, NULL, NULL, '緇衣之宜兮，敝，予又改為兮。適子之館兮，還，予授子之粲兮。
緇衣之好兮，敝，予又改造兮。適子之館兮，還，予授子之粲兮。
緇衣之蓆兮，敝，予又改作兮。適子之館兮，還，予授子之粲兮。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00173","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-37-35-2d-7dc7-8863-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7dc7-8863","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-37-35-2d-7dc7-8863-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7dc7-8863"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E7%B7%87%E8%A1%A3","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '將仲子', NULL, NULL, NULL, '將仲子兮，無踰我里，無折我樹杞。豈敢愛之？畏我父母。仲可懷也，父母之言，亦可畏也。
將仲子兮，無踰我牆，無折我樹桑。豈敢愛之？畏我諸兄。仲可懷也，諸兄之言，亦可畏也。
將仲子兮，無踰我園，無折我樹檀。豈敢愛之？畏人之多言。仲可懷也，人之多言，亦可畏也。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00174","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-37-36-2d-5c07-4ef2-5b50-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5c07-4ef2-5b50","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-37-36-2d-5c07-4ef2-5b50-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5c07-4ef2-5b50"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%B0%87%E4%BB%B2%E5%AD%90","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '叔于田', NULL, NULL, NULL, '叔于田，巷無居人。豈無居人，不如叔也。洵美且仁。
叔于狩，巷無飲酒。豈無飲酒，不如叔也。洵美且好。
叔適野，巷無服馬。豈無服馬，不如叔也。洵美且武。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00175","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-37-37-2d-53d4-4e8e-7530-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-53d4-4e8e-7530","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-37-37-2d-53d4-4e8e-7530-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-53d4-4e8e-7530"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%8F%94%E4%BA%8E%E7%94%B0","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '大叔于田', NULL, NULL, NULL, '叔于田，乘乘馬。執轡如組，兩驂如舞。叔在藪，火烈具舉，襢裼暴虎，獻于公所。將叔無狃，戒其傷女。
叔于田，乘乘黃。兩服上襄，兩驂鴈行。叔在藪，火烈具揚。叔善射忌，又良御忌，抑磬控忌，抑縱送忌。
叔于田，乘乘鴇。兩服齊首，兩驂如手。叔在藪，火烈具阜。叔馬慢忌，叔發罕忌，抑釋掤忌，抑鬯弓忌。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00176","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-37-38-2d-5927-53d4-4e8e-7530-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5927-53d4-4e8e-7530","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-37-38-2d-5927-53d4-4e8e-7530-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5927-53d4-4e8e-7530"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%A4%A7%E5%8F%94%E4%BA%8E%E7%94%B0","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '清人', NULL, NULL, NULL, '清人在彭，駟介旁旁。二矛重英，河上乎翱翔。
清人在消，駟介麃麃。二矛重喬，河上乎逍遙。
清人在軸，駟介陶陶。左旋右抽，中軍作好。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00177","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-37-39-2d-6e05-4eba-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6e05-4eba","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-37-39-2d-6e05-4eba-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6e05-4eba"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%B8%85%E4%BA%BA","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '羔裘', NULL, NULL, NULL, '羔裘如濡，洵直且侯。彼其之子，舍命不渝。
羔裘豹飾，孔武有力。彼其之子，邦之司直。
羔裘晏兮，三英粲兮。彼其之子，邦之彥兮。
羔裘豹袪，自我人居居。豈無他人？維子之故。
羔裘豹褎，自我人究究。豈無他人？維子之好。
羔裘逍遙，狐裘以朝。豈不爾思，勞心忉忉。
羔裘翱翔，狐裘在堂。豈不爾思，我心憂傷。
羔裘如膏，日出有曜。豈不爾思，中心是悼。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00178","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-38-30-2d-7f94-88d8-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7f94-88d8","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-38-30-2d-7f94-88d8-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7f94-88d8","CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-32-30-2d-7f94-88d8-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7f94-88d8","CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-34-36-2d-7f94-88d8-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7f94-88d8"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E7%BE%94%E8%A3%98","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '遵大路', NULL, NULL, NULL, '遵大路兮，摻執子之袪兮。無我惡兮，不寁故也。
遵大路兮，摻執子之手兮。無我魗兮，不寁好也。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00179","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-38-31-2d-9075-5927-8def-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9075-5927-8def","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-38-31-2d-9075-5927-8def-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9075-5927-8def"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%81%B5%E5%A4%A7%E8%B7%AF","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '女曰鷄鳴', NULL, NULL, NULL, '女曰鷄鳴，士曰昧旦。子興視夜，明星有爛。將翱將翔，弋鳧與鴈。
弋言加之，與子宜之。宜言飲酒，與子偕老。琴瑟在御，莫不靜好。
知子之來之，雜佩以贈之。知子之順之，雜佩以問之。知子之好之，雜佩以報之。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00180","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-38-32-2d-5973-66f0-9dc4-9cf4-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5973-66f0-9dc4-9cf4","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-38-32-2d-5973-66f0-9dc4-9cf4-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5973-66f0-9dc4-9cf4"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%A5%B3%E6%9B%B0%E9%B7%84%E9%B3%B4","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '有女同車', NULL, NULL, NULL, '有女同車，顏如舜華，將翱將翔，佩玉瓊琚，彼美孟姜，洵美且都。
有女同行，顏如舜英，將翱將翔，佩玉將將，彼美孟姜，德音不忘。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00181","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-38-33-2d-6709-5973-540c-8eca-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6709-5973-540c-8eca","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-38-33-2d-6709-5973-540c-8eca-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6709-5973-540c-8eca"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%9C%89%E5%A5%B3%E5%90%8C%E8%BB%8A","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '山有扶蘇', NULL, NULL, NULL, '山有扶蘇，隰有荷華。不見子都，乃見狂且。
山有喬松，隰有遊龍。不見子充，乃見狡童。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00182","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-38-34-2d-5c71-6709-6276-8607-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5c71-6709-6276-8607","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-38-34-2d-5c71-6709-6276-8607-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5c71-6709-6276-8607"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%B1%B1%E6%9C%89%E6%89%B6%E8%98%87","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '蘀兮', NULL, NULL, NULL, '蘀兮蘀兮，風其吹女。叔兮伯兮，倡予和女。
蘀兮蘀兮，風其漂女。叔兮伯兮，倡予要女。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00183","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-38-35-2d-8600-516e-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-8600-516e","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-38-35-2d-8600-516e-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-8600-516e"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E8%98%80%E5%85%AE","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '狡童', NULL, NULL, NULL, '彼狡童兮，不與我言兮，維子之故，使我不能餐兮。
彼狡童兮，不與我食兮，維子之故，使我不能息兮。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00184","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-38-36-2d-72e1-7ae5-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-72e1-7ae5","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-38-36-2d-72e1-7ae5-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-72e1-7ae5"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E7%8B%A1%E7%AB%A5","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '褰裳', NULL, NULL, NULL, '子惠思我，褰裳涉溱。子不我思，豈無他人？狂童之狂也且！
子惠思我，褰裳涉洧。子不我思，豈無他士？狂童之狂也且！', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00185","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-38-37-2d-8930-88f3-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-8930-88f3","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-38-37-2d-8930-88f3-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-8930-88f3"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E8%A4%B0%E8%A3%B3","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '丰', NULL, NULL, NULL, '子之丰兮，俟我乎巷兮。悔予不送兮。
子之昌兮，俟我乎堂兮。悔予不將兮。
衣錦褧衣，裳錦褧裳。叔兮伯兮，駕予與行。
裳錦褧裳，衣錦褧衣。叔兮伯兮，駕予與歸。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00186","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-38-38-2d-4e30-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-4e30","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-38-38-2d-4e30-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-4e30"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E4%B8%B0","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '東門之墠', NULL, NULL, NULL, '東門之墠，茹藘在阪。其室則邇，其人甚遠。
東門之栗，有踐家室。豈不爾思？子不我即。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00187","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-38-39-2d-6771-9580-4e4b-58a0-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6771-9580-4e4b-58a0","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-38-39-2d-6771-9580-4e4b-58a0-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6771-9580-4e4b-58a0"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%9D%B1%E9%96%80%E4%B9%8B%E5%A2%A0","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '風雨', NULL, NULL, NULL, '風雨淒淒，雞鳴喈喈。既見君子，雲胡不夷。
風雨瀟瀟，雞鳴膠膠。既見君子，雲胡不瘳。
風雨如晦，雞鳴不已。既見君子，雲胡不喜。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00188","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-39-30-2d-98a8-96e8-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-98a8-96e8","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-39-30-2d-98a8-96e8-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-98a8-96e8"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%A2%A8%E9%9B%A8","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '子衿', NULL, NULL, NULL, '青青子衿，悠悠我心。縱我不往，子寧不嗣音。
青青子佩，悠悠我思。縱我不往，子寧不來。
挑兮達兮，在城闕兮。一日不見，如三月兮。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00189","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-39-31-2d-5b50-887f-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5b50-887f","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-39-31-2d-5b50-887f-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5b50-887f"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%AD%90%E8%A1%BF","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '出其東門', NULL, NULL, NULL, '出其東門，有女如雲。雖則如雲，匪我思存。縞衣綦巾，聊樂我員。
出其闉闍，有女如荼。雖則如荼，匪我思且。縞衣茹藘，聊可與娛。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00190","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-39-33-2d-51fa-5176-6771-9580-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-51fa-5176-6771-9580","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-39-33-2d-51fa-5176-6771-9580-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-51fa-5176-6771-9580"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%87%BA%E5%85%B6%E6%9D%B1%E9%96%80","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '野有蔓草', NULL, NULL, NULL, '野有蔓草，零露漙兮。有美一人，清揚婉兮。邂逅相遇，適我願兮。
野有蔓草，零露瀼瀼。有美一人，婉如清揚。邂逅相遇，與子偕臧。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00191","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-39-34-2d-91ce-6709-8513-8349-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-91ce-6709-8513-8349","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-39-34-2d-91ce-6709-8513-8349-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-91ce-6709-8513-8349"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%87%8E%E6%9C%89%E8%94%93%E8%8D%89","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '溱洧', NULL, NULL, NULL, '溱與洧，方渙渙兮。士與女，方秉蕑兮。女曰觀乎，士曰既且。且往觀乎，洧之外，洵訏且樂。維士與女，伊其相謔。贈之以勺藥。
溱與洧，瀏其清矣。士與女，殷其盈矣。女曰觀乎，士曰既且。且往觀乎，洧之外，洵訏且樂。維士與女，伊其將謔。贈之以勺藥。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00192","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-39-35-2d-6eb1-6d27-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6eb1-6d27","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-39-35-2d-6eb1-6d27-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6eb1-6d27"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%BA%B1%E6%B4%A7","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '雞鳴', NULL, NULL, NULL, '雞既鳴矣，朝既盈矣。匪雞則鳴，蒼蠅之聲。
東方明矣，朝既昌矣。匪東方則明，月出之光。
蟲飛薨薨，甘與子同夢。會且歸矣，無庶予子憎！', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00193","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-39-36-2d-96de-9cf4-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-96de-9cf4","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-39-36-2d-96de-9cf4-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-96de-9cf4"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%9B%9E%E9%B3%B4","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '還', NULL, NULL, NULL, '子之還兮，遭我乎峱之閒兮。並驅從兩肩兮，揖我謂我儇兮。
子之茂兮，遭我乎峱之道兮。並驅從兩牡兮，揖我謂我好兮。
子之昌兮，遭我乎峱之陽兮。並驅從兩狼兮，揖我謂我臧兮。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00194","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-39-37-2d-9084-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9084","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-39-37-2d-9084-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9084"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%82%84","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '著', NULL, NULL, NULL, '俟我於著乎而，充耳以素乎而，尚之以瓊華乎而。
俟我於庭乎而，充耳以青乎而，尚之以瓊瑩乎而。
俟我於堂乎而，充耳以黃乎而，尚之以瓊英乎而。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00195","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-39-38-2d-8457-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-8457","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-39-38-2d-8457-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-8457"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E8%91%97","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '東方之日', NULL, NULL, NULL, '東方之日兮，彼姝者子，在我室兮，在我室兮，履我即兮。
東方之月兮，彼姝者子，在我闥兮，在我闥兮，履我發兮。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00196","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-39-39-2d-6771-65b9-4e4b-65e5-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6771-65b9-4e4b-65e5","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-39-39-2d-6771-65b9-4e4b-65e5-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6771-65b9-4e4b-65e5"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%9D%B1%E6%96%B9%E4%B9%8B%E6%97%A5","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '東方未明', NULL, NULL, NULL, '東方未明，顛倒衣裳。顛之倒之，自公召之。
東方未晞，顛倒裳衣。倒之顛之，自公令之。
折柳樊圃，狂夫瞿瞿。不能辰夜，不夙則莫。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00197","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-30-30-2d-6771-65b9-672a-660e-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6771-65b9-672a-660e","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-30-30-2d-6771-65b9-672a-660e-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6771-65b9-672a-660e"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%9D%B1%E6%96%B9%E6%9C%AA%E6%98%8E","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '南山', NULL, NULL, NULL, '南山崔崔，雄狐綏綏。魯道有蕩，齊子由歸。既曰歸止，曷又懷止！
葛屨五兩，冠緌雙止。魯道有蕩，齊子庸止。既曰庸止，曷又從止！
蓺麻如之何？衡從其畝。取妻如之何？必告父母，既曰告止，曷又鞠止！
析薪如之何？匪斧不克。取妻如之何？匪媒不得，既曰得止，曷又極止！', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00198","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-30-31-2d-5357-5c71-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5357-5c71","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-30-31-2d-5357-5c71-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5357-5c71"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%8D%97%E5%B1%B1","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '甫田', NULL, NULL, NULL, '無田甫田，維莠驕驕。無思遠人，勞心忉忉。
無田甫田，維莠桀桀。無思遠人，勞心怛怛。
婉兮孌兮，緫角丱兮。未幾見兮，突而弁兮。
倬彼甫田，歲取十千。我取其陳，食我農人，自古有年。
今適南畝，或耘或耔。黍稷薿薿。攸介攸止，烝我髦士。
以我齊明，與我犧羊，以社以方。
我田既臧，農夫之慶。琴瑟擊鼓，以御田祖。
以祈甘雨，以介我稷黍，以穀我士女。
曾孫來止，以其婦子，饁彼南畝。
田畯至喜，攘其左右，嘗其旨否。
禾易長畝，終善且有。曾孫不怒，農夫克敏。
曾孫之稼，如茨如梁，曾孫之庾，如坻如京。
乃求千斯倉，乃求萬斯箱，黍稷稻粱。
農夫之慶，報以介福，萬壽無疆。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00199","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-30-32-2d-752b-7530-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-752b-7530","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-30-32-2d-752b-7530-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-752b-7530","CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-31-37-2d-752b-7530-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-752b-7530"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E7%94%AB%E7%94%B0","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '盧令', NULL, NULL, NULL, '盧令令，其人美且仁。
盧重環，其人美且鬈。
盧重鋂，其人美且偲。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00200","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-30-33-2d-76e7-4ee4-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-76e7-4ee4","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-30-33-2d-76e7-4ee4-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-76e7-4ee4"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E7%9B%A7%E4%BB%A4","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '敝笱', NULL, NULL, NULL, '敝笱在梁，其魚魴鰥。齊子歸止，其從如雲。
敝笱在梁，其魚魴鱮。齊子歸止，其從如雨。
敝笱在梁，其魚唯唯。齊子歸止，其從如水。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00201","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-30-34-2d-655d-7b31-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-655d-7b31","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-30-34-2d-655d-7b31-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-655d-7b31"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%95%9D%E7%AC%B1","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '載驅', NULL, NULL, NULL, '載驅薄薄，簟茀朱鞹。魯道有蕩，齊子發夕。
四驪濟濟，垂轡濔濔。魯道有蕩，齊子豈弟。
汶水湯湯，行人彭彭。魯道有蕩，齊子翱翔。
汶水滔滔，行人儦儦。魯道有蕩，齊子遊敖。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00202","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-30-35-2d-8f09-9a45-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-8f09-9a45","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-30-35-2d-8f09-9a45-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-8f09-9a45"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E8%BC%89%E9%A9%85","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '猗嗟', NULL, NULL, NULL, '猗嗟昌兮！頎而長兮。抑若揚兮，美目揚兮。巧趨蹌兮。射則臧兮。
猗嗟名兮！美目清兮。儀既成兮，終日射侯，不出正兮，展我甥兮。
猗嗟孌兮！清揚婉兮。舞則選兮，射則貫兮，四矢反兮，以禦亂兮。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00203","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-30-36-2d-7317-55df-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7317-55df","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-30-36-2d-7317-55df-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7317-55df"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E7%8C%97%E5%97%9F","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '葛屨', NULL, NULL, NULL, '糾糾葛屨，可以履霜。摻摻女手，可以縫裳。要之襋之，好人服之。
好人提提，宛然左辟。佩其象揥。維是褊心，是以為刺。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00204","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-30-37-2d-845b-5c68-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-845b-5c68","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-30-37-2d-845b-5c68-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-845b-5c68"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E8%91%9B%E5%B1%A8","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '汾沮洳', NULL, NULL, NULL, '彼汾沮洳，言采其莫。彼其之子，美無度；美無度，殊異乎公路。
彼汾一方，言采其桑。彼其之子，美如英；美如英，殊異乎公行。
彼汾一曲，言采其藚。彼其之子，美如玉；美如玉，殊異乎公族。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00205","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-30-38-2d-6c7e-6cae-6d33-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6c7e-6cae-6d33","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-30-38-2d-6c7e-6cae-6d33-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6c7e-6cae-6d33"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%B1%BE%E6%B2%AE%E6%B4%B3","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '園有桃', NULL, NULL, NULL, '園有桃，其實之殽。心之憂矣，我歌且謠。不知我者，謂我士也驕。彼人是哉，子曰何其？心之憂矣！其誰知之？其誰知之？蓋亦勿思！
園有棘，其實之食。心之憂矣，聊以行國。不我知者，謂我士也罔極。彼人是哉，子曰何其？心之憂矣！其誰知之？其誰知之？蓋亦勿思！', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00206","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-30-39-2d-5712-6709-6843-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5712-6709-6843","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-30-39-2d-5712-6709-6843-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5712-6709-6843"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%9C%92%E6%9C%89%E6%A1%83","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '陟岵', NULL, NULL, NULL, '陟彼岵兮，瞻望父兮。父曰：「嗟予子！行役夙夜無已。上慎旃哉，猶來無止！」
陟彼屺兮，瞻望母兮。母曰：「嗟予季！行役夙夜無寐。上慎旃哉！猶來無棄！」
陟彼岡兮，瞻望兄兮。兄曰：「嗟予弟！行役夙夜必偕。上慎旃哉！猶來無死！」', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00207","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-31-30-2d-965f-5cb5-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-965f-5cb5","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-31-30-2d-965f-5cb5-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-965f-5cb5"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%99%9F%E5%B2%B5","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '十畝之間', NULL, NULL, NULL, '十畝之間兮，桑者閑閑兮。行與子還兮。
十畝之外兮，桑者泄泄兮。行與子逝兮。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00208","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-31-31-2d-5341-755d-4e4b-9593-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5341-755d-4e4b-9593","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-31-31-2d-5341-755d-4e4b-9593-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5341-755d-4e4b-9593"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%8D%81%E7%95%9D%E4%B9%8B%E9%96%93","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '伐檀', NULL, NULL, NULL, '坎坎伐檀兮，寘之河之乾兮，河水清且漣猗。不稼不穡，胡取禾三百廛兮！不狩不獵，胡瞻爾庭有縣貆兮。彼君子兮，不素餐兮。
坎坎伐輻兮，寘之河之側兮，河水清且直猗。不稼不穡，胡取禾三百億兮！不狩不獵，胡瞻爾庭有縣特兮。彼君子兮，不素食兮。
坎坎伐輪兮，寘之河之漘兮，河水清且淪猗。不稼不穡，胡取禾三百囷兮！不狩不獵，胡瞻爾庭有縣鶉兮。彼君子兮，不素飧兮。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00209","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-31-32-2d-4f10-6a80-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-4f10-6a80","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-31-32-2d-4f10-6a80-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-4f10-6a80"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E4%BC%90%E6%AA%80","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '碩鼠', NULL, NULL, NULL, '碩鼠碩鼠，無食我黍！三歲貫女，莫我肯顧。逝將去女，適彼樂土。樂土樂土，爰得我所。
碩鼠碩鼠，無食我麥！三歲貫女，莫我肯德。逝將去女，適彼樂國。樂國樂國，爰得我直。
碩鼠碩鼠，無食我苗！三歲貫女，莫我肯勞。逝將去女，適彼樂郊。樂郊樂郊，誰之永號。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00210","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-31-33-2d-78a9-9f20-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-78a9-9f20","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-31-33-2d-78a9-9f20-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-78a9-9f20"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E7%A2%A9%E9%BC%A0","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '蟋蟀', NULL, NULL, NULL, '蟋蟀在堂，歲聿其莫。今我不樂，日月其除。無已大康，職思其居。好樂無荒，良士瞿瞿。
蟋蟀在堂，歲聿其逝。今我不樂，日月其邁。無已大康，職思其外。好樂無荒，良士蹶蹶。
蟋蟀在堂，役車其休。今我不樂，日月其慆。無已大康，職思其憂。好樂無荒，良士休休。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00211","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-31-34-2d-87cb-87c0-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-87cb-87c0","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-31-34-2d-87cb-87c0-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-87cb-87c0"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E8%9F%8B%E8%9F%80","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '山有樞', NULL, NULL, NULL, '山有樞，隰有榆。子有衣裳，弗曳弗婁。子有車馬，弗馳弗驅。宛其死矣，他人是愉。
山有栲，隰有杻。子有廷內，弗洒弗埽。子有鐘鼓，弗鼓弗考。宛其死矣，他人是保。
山有漆，隰有栗。子有酒食，何不日鼓瑟？且以喜樂，且以永日。宛其死矣，他人入室。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00212","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-31-35-2d-5c71-6709-6a1e-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5c71-6709-6a1e","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-31-35-2d-5c71-6709-6a1e-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5c71-6709-6a1e"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%B1%B1%E6%9C%89%E6%A8%9E","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '椒聊', NULL, NULL, NULL, '椒聊之實，蕃衍盈升。彼其之子，碩大無朋。椒聊且！遠條且！
椒聊之實，蕃衍盈匊。彼其之子，碩大且篤。椒聊且！遠條且！', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00213","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-31-37-2d-6912-804a-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6912-804a","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-31-37-2d-6912-804a-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6912-804a"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%A4%92%E8%81%8A","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '綢繆', NULL, NULL, NULL, '綢繆束薪，三星在天。今夕何夕？見此良人！子兮子兮！如此良人何！
綢繆束芻，三星在隅。今夕何夕？見此邂逅！子兮子兮！如此邂逅何！
綢繆束楚，三星在戶。今夕何夕？見此粲者！子兮子兮！如此粲者何！', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00214","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-31-38-2d-7da2-7e46-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7da2-7e46","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-31-38-2d-7da2-7e46-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7da2-7e46"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E7%B6%A2%E7%B9%86","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '杕杜', NULL, NULL, NULL, '有杕之杜，其葉湑湑。獨行踽踽，豈無他人？不如我同父，嗟行之人，胡不比焉？人無兄弟，胡不佽焉？
有杕之杜，其葉菁菁。獨行睘睘，豈無他人？不如我同姓，嗟行之人，胡不比焉？人無兄弟，胡不佽焉？
有杕之杜，有睆其實。王事靡盬，繼嗣我日。日月陽止，女心傷止，征夫遑止。
有杕之杜，其葉萋萋。王事靡盬，我心傷悲。卉木萋止，女心悲止，征夫歸止。
陟彼北山，言采其杞。王事靡盬，憂我父母。檀車幝幝，四牡痯痯，征夫不遠。
匪載匪來，憂心孔疚。期逝不至，而多為恤。卜筮偕止，會言近止，征夫邇止。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00215","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-31-39-2d-6755-675c-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6755-675c","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-31-39-2d-6755-675c-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6755-675c","CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-36-39-2d-6755-675c-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6755-675c"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%9D%95%E6%9D%9C","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '鴇羽', NULL, NULL, NULL, '肅肅鴇羽，集于苞栩。王事靡盬，不能蓺稷黍。父母何怙？悠悠蒼天，曷其有所。
肅肅鴇翼，集于苞棘。王事靡盬，不能蓺黍稷。父母何食？悠悠蒼天，曷其有極。
肅肅鴇行，集于苞桑。王事靡盬，不能蓺稻粱。父母何嘗？悠悠蒼天，曷其有常。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00216","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-32-31-2d-9d07-7fbd-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9d07-7fbd","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-32-31-2d-9d07-7fbd-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9d07-7fbd"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%B4%87%E7%BE%BD","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '無衣', NULL, NULL, NULL, '豈曰無衣七兮、不如子之衣、安且吉兮。
豈曰無衣六兮、不如子之衣、安且燠兮。
豈曰無衣、與子同袍。
王於興師、脩我戈矛、與子同仇。
豈曰無衣、與子同澤。
王於興師、脩我矛戟、與子偕作。
豈曰無衣、與子同裳。
王於興師、脩我甲兵、與子偕行。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00217","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-32-32-2d-7121-8863-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7121-8863","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-32-32-2d-7121-8863-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7121-8863","CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-33-33-2d-7121-8863-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7121-8863"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E7%84%A1%E8%A1%A3","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '有杕之杜', NULL, NULL, NULL, '有杕之杜，生于道左。彼君子兮，噬肯適我。中心好之，曷飲食之。
有杕之杜，生于道周。彼君子兮，噬肯來遊。中心好之，曷飲食之。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00218","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-32-33-2d-6709-6755-4e4b-675c-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6709-6755-4e4b-675c","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-32-33-2d-6709-6755-4e4b-675c-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6709-6755-4e4b-675c"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%9C%89%E6%9D%95%E4%B9%8B%E6%9D%9C","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '葛生', NULL, NULL, NULL, '葛生蒙楚，蘞蔓于野。予美亡此，誰與獨處。
葛生蒙棘，蘞蔓于域。予美亡此，誰與獨息。
角枕粲兮，錦衾爛兮。予美亡此，誰與獨旦。
夏之日，冬之夜。百歲之後，歸于其居。
冬之夜，夏之日。百歲之後，歸于其室。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00219","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-32-34-2d-845b-751f-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-845b-751f","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-32-34-2d-845b-751f-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-845b-751f"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E8%91%9B%E7%94%9F","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '采苓', NULL, NULL, NULL, '采苓采苓，首陽之巔。人之為言，苟亦無信。舍旃舍旃，苟亦無然。人之為言，胡得焉！
采苦采苦，首陽之下。人之為言，苟亦無與。舍旃舍旃，苟亦無然。人之為言，胡得焉！
采葑采葑，首陽之東。人之為言，苟亦無從。舍旃舍旃，苟亦無然。人之為言，胡得焉！', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00220","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-32-35-2d-91c7-82d3-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-91c7-82d3","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-32-35-2d-91c7-82d3-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-91c7-82d3"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%87%87%E8%8B%93","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '車鄰', NULL, NULL, NULL, '有車鄰鄰，有馬白顛。未見君子，寺人之令。
阪有漆，隰有栗。既見君子，並坐鼓瑟。今者不樂，逝者其耋。
阪有桑，隰有楊。既見君子，並坐鼓簧。今者不樂，逝者其亡。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00221","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-32-36-2d-8eca-9130-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-8eca-9130","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-32-36-2d-8eca-9130-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-8eca-9130"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E8%BB%8A%E9%84%B0","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '駟驖', NULL, NULL, NULL, '駟驖孔阜，六轡在手。公之媚子，從公于狩。
奉時辰牡，辰牡孔碩。公曰左之，舍拔則獲。
遊于北園，四馬既閑。輶車鸞鑣，載獫歇驕。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00222","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-32-37-2d-99df-9a56-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-99df-9a56","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-32-37-2d-99df-9a56-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-99df-9a56"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%A7%9F%E9%A9%96","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '小戎', NULL, NULL, NULL, '小戎俴收，五楘梁輈，遊環脅驅，陰靷鋈續，文茵暢轂，駕我騏馵。言念君子，溫其如玉。在其板屋，亂我心曲。
四牡孔阜，六轡在手，騏駵是中，騧驪是驂，龍盾之合，鋈以觼軜。言念君子，溫其在邑。方何為期，胡然我念之。
俴駟孔羣，厹矛鋈錞，蒙伐有苑，虎韔鏤膺，交韔二弓，竹閉緄縢。言念君子，載寢載興。厭厭良人，秩秩德音。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00223","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-32-38-2d-5c0f-620e-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5c0f-620e","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-32-38-2d-5c0f-620e-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5c0f-620e"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%B0%8F%E6%88%8E","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '蒹葭', NULL, NULL, NULL, '蒹葭蒼蒼，白露為霜。所謂殹人，在水弌方。溯違從之，道阻且長。溯違從之，宛在水之中央。
蒹葭萋萋，白露未晞。所謂殹人，在水之溦。溯違從之，道阻且躋。 .
溯違從之，道阻且右。溯違從之，宛在水之中。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00224","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-32-39-2d-84b9-846d-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-84b9-846d","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-32-39-2d-84b9-846d-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-84b9-846d"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E8%92%B9%E8%91%AD","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '終南', NULL, NULL, NULL, '終南何有，有條有梅。君子至止，錦衣狐裘。顏如渥丹，其君也哉。
終南何有，有紀有堂。君子至止，黻衣繡裳。佩玉將將，壽考不亡。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00225","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-33-30-2d-7d42-5357-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7d42-5357","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-33-30-2d-7d42-5357-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7d42-5357"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E7%B5%82%E5%8D%97","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '黃鳥', NULL, NULL, NULL, '交交黃鳥，止于棘。
誰從穆公？子車奄息。維此奄息，百夫之特。
臨其穴，惴惴其慄。
彼蒼者天，殲我良人！如可贖兮，人百其身。
交交黃鳥，止于桑。
誰從穆公？子車仲行。維此仲行，百夫之防。
臨其穴，惴惴其慄。
彼蒼者天，殲我良人！如可贖兮，人百其身。
交交黃鳥，止于楚。
誰從穆公？子車鍼虎。維此鍼虎，百夫之禦。
臨其穴，惴惴其慄。
彼蒼者天，殲我良人！如可贖兮，人百其身。
黃鳥黃鳥，無集于穀，無啄我粟。
此邦之人，不我肯穀。言旋言歸，復我邦族。
黃鳥黃鳥，無集于桑，無啄我粱。
此邦之人，不可與明。言旋言歸，復我諸兄。
黃鳥黃鳥，無集于栩，無啄我黍。
此邦之人，不可與處。言旋言歸，復我諸父。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00226","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-33-31-2d-9ec3-9ce5-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9ec3-9ce5","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-33-31-2d-9ec3-9ce5-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9ec3-9ce5","CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-39-33-2d-9ec3-9ce5-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9ec3-9ce5"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%BB%83%E9%B3%A5","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '晨風', NULL, NULL, NULL, '鴥彼晨風，鬱彼北林，未見君子，憂心欽欽，如何如何，忘我實多。
山有苞櫟，隰有六駮，未見君子，憂心靡樂，如何如何，忘我實多。
山有苞棣，隰有樹檖，未見君子，憂心如醉，如何如何，忘我實多。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00227","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-33-32-2d-6668-98a8-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6668-98a8","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-33-32-2d-6668-98a8-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6668-98a8"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%99%A8%E9%A2%A8","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '渭陽', NULL, NULL, NULL, '我送舅氏，曰至渭陽。何以贈之，路車乘黃。
我送舅氏，悠悠我思。何以贈之，瓊瑰玉佩。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00228","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-33-34-2d-6e2d-967d-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6e2d-967d","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-33-34-2d-6e2d-967d-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6e2d-967d"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%B8%AD%E9%99%BD","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '權輿', NULL, NULL, NULL, '於我乎，夏屋渠渠，今也每食無餘。于嗟乎！不承權輿。
於我乎，每食四簋，今也每食不飽。于嗟乎！不承權輿。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00229","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-33-35-2d-6b0a-8f3f-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6b0a-8f3f","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-33-35-2d-6b0a-8f3f-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6b0a-8f3f"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%AC%8A%E8%BC%BF","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '宛丘', NULL, NULL, NULL, '子之湯兮，宛丘之上兮，洵有情兮，而無望兮。
坎其擊鼓，宛丘之下，無冬無夏，值其鷺羽。
坎其擊缶，宛丘之道，無冬無夏，值其鷺翿。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00230","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-33-36-2d-5b9b-4e18-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5b9b-4e18","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-33-36-2d-5b9b-4e18-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5b9b-4e18"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%AE%9B%E4%B8%98","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '東門之枌', NULL, NULL, NULL, '東門之枌，宛丘之栩。子仲之子，婆娑其下。
穀旦于差，南方之原。不績其麻，市也婆娑。
穀旦于逝，越以鬷邁。視爾如荍，貽我握椒。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00231","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-33-37-2d-6771-9580-4e4b-678c-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6771-9580-4e4b-678c","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-33-37-2d-6771-9580-4e4b-678c-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6771-9580-4e4b-678c"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%9D%B1%E9%96%80%E4%B9%8B%E6%9E%8C","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '衡門', NULL, NULL, NULL, '衡門之下，可以棲遲。泌之洋洋，可以樂飢。
豈其食魚，必河之魴。豈其取妻，必齊之姜。
豈其食魚，必河之鯉。豈其取妻，必宋之子。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00232","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-33-38-2d-8861-9580-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-8861-9580","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-33-38-2d-8861-9580-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-8861-9580"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E8%A1%A1%E9%96%80","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '東門之池', NULL, NULL, NULL, '東門之池，可以漚麻。彼美淑姬，可與晤歌。
東門之池，可以漚紵。彼美淑姬，可與晤語。
東門之池，可以漚菅。彼美淑姬，可與晤言。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00233","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-33-39-2d-6771-9580-4e4b-6c60-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6771-9580-4e4b-6c60","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-33-39-2d-6771-9580-4e4b-6c60-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6771-9580-4e4b-6c60"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%9D%B1%E9%96%80%E4%B9%8B%E6%B1%A0","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '東門之楊', NULL, NULL, NULL, '東門之楊，其葉牂牂。昏以為期，明星煌煌。
東門之楊，其葉肺肺。昏以為期，明星晢晢。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00234","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-34-30-2d-6771-9580-4e4b-694a-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6771-9580-4e4b-694a","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-34-30-2d-6771-9580-4e4b-694a-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6771-9580-4e4b-694a"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%9D%B1%E9%96%80%E4%B9%8B%E6%A5%8A","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '墓門', NULL, NULL, NULL, '墓門有棘，斧以斯之。夫也不良，國人知之。知而不已，誰昔然矣。
墓門有梅，有鴞萃止。夫也不良，歌以誶之。訊予不顧，顛倒思予。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00235","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-34-31-2d-5893-9580-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5893-9580","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-34-31-2d-5893-9580-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5893-9580"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%A2%93%E9%96%80","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '防有鵲巢', NULL, NULL, NULL, '防有鵲巢，邛有旨苕。誰侜予美，心焉忉忉。
中唐有甓，邛有旨鷊。誰侜予美，心焉惕惕。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00236","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-34-32-2d-9632-6709-9d72-5de2-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9632-6709-9d72-5de2","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-34-32-2d-9632-6709-9d72-5de2-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9632-6709-9d72-5de2"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%98%B2%E6%9C%89%E9%B5%B2%E5%B7%A2","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '月出', NULL, NULL, NULL, '月出皎兮，佼人僚兮，舒窈糾兮，勞心悄兮。
月出皓兮，佼人懰兮，舒懮受兮，勞心慅兮。
月出照兮，佼人燎兮，舒夭紹兮，勞心慘兮。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00237","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-34-33-2d-6708-51fa-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6708-51fa","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-34-33-2d-6708-51fa-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6708-51fa"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%9C%88%E5%87%BA","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '株林', NULL, NULL, NULL, '胡為乎株林？從夏南。匪適株林，從夏南。
駕我乘馬，說于株野。乘我乘駒，朝食于株。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00238","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-34-34-2d-682a-6797-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-682a-6797","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-34-34-2d-682a-6797-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-682a-6797"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%A0%AA%E6%9E%97","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '澤陂', NULL, NULL, NULL, '彼澤之陂，有蒲與荷。有美一人，傷如之何。寤寐無為，涕泗滂沱。
彼澤之陂，有蒲與蕑。有美一人，碩大且卷。寤寐無為，中心悁悁。
彼澤之陂，有蒲菡萏。有美一人，碩大且儼。寤寐無為，輾轉伏枕。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00239","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-34-35-2d-6fa4-9642-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6fa4-9642","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-34-35-2d-6fa4-9642-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6fa4-9642"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%BE%A4%E9%99%82","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '素冠', NULL, NULL, NULL, '庶見素冠兮，棘人欒欒兮，勞心慱慱兮。
庶見素衣兮，我心傷悲兮，聊與子同歸兮。
庶見素韠兮，我心蘊結兮，聊與子如一兮。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00240","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-34-37-2d-7d20-51a0-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7d20-51a0","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-34-37-2d-7d20-51a0-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7d20-51a0"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E7%B4%A0%E5%86%A0","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}')
)
INSERT INTO poems (
  poet_id, poem_no, volume, title_zh, title_ko, category, meter, body_zh,
  is_notable, status, quality, review_memo
)
SELECT
  p.id,
  COALESCE(existing_poem_count.max_poem_no, 0)
    + row_number() OVER (PARTITION BY p.id ORDER BY ip.title_zh, ip.body_zh)::integer,
  ip.volume::integer, ip.title_zh, ip.title_ko, ip.category, ip.meter::integer, ip.body_zh,
  TRUE, ip.status, ip.quality, ip.review_memo
FROM input_poems ip
JOIN poets p ON p.title_id = ip.poet_slug
LEFT JOIN LATERAL (
  SELECT max(poem_no) AS max_poem_no
  FROM poems
  WHERE poet_id = p.id
) existing_poem_count ON TRUE
WHERE NOT EXISTS (
  SELECT 1
  FROM poems existing
  WHERE existing.poet_id = p.id
    AND existing.title_zh = ip.title_zh
    AND existing.body_zh = ip.body_zh
);

UPDATE poets p
SET poem_count = sub.cnt
FROM (
  SELECT poet_id, count(*)::integer AS cnt
  FROM poems
  WHERE poet_id IN (SELECT id FROM poets WHERE title_id IN ('cnpreqin-3fcc3c660d5a7a4d'))
  GROUP BY poet_id
) sub
WHERE p.id = sub.poet_id;

-- Review counts before COMMIT when applying manually:
SELECT quality, status, count(*) FROM poems WHERE quality IN ('cnpt-shijing') GROUP BY quality, status ORDER BY quality, status;
SELECT p.era_period, count(pm.id) FROM poets p JOIN poems pm ON pm.poet_id = p.id WHERE p.title_id IN ('cnpreqin-3fcc3c660d5a7a4d') GROUP BY p.era_period ORDER BY p.era_period;

ROLLBACK;
-- COMMIT;
