-- Generated by scripts/build_cn_translation_pipeline_staging.mjs
-- Part: 2/13
-- Purpose: stage CN pre-Tang and Song/Yuan/Ming poems into the JDS translation pipeline.
-- Translator decision: JDS backend=gemini model=gemini-2.5-flash-lite prompt=pipeline/translate/prompts/v5_full.txt.
-- Safety: inserts only missing poet slug + title_zh + body_zh rows. Default ending is ROLLBACK.

BEGIN;

WITH input_poets(slug, name_zh, name_ko, life_raw, era_period, country) AS (
  VALUES
    ('cnhan-4d1c052feb6f7223', '佚名', NULL, NULL, '兩漢', 'CN'),
    ('cnhan-43b38ccd5d1e93f0', '無名氏/漢樂府', NULL, NULL, '兩漢', 'CN'),
    ('cnhan-4c77569df016009b', '蔡琰', NULL, NULL, '兩漢', 'CN'),
    ('cnhan-aa408a3758d7e916', '諸葛亮', NULL, NULL, '兩漢', 'CN'),
    ('cnpreqin-d9cfb1495fcebc18', '屈原', NULL, '約前340-前278', '先秦', 'CN'),
    ('cnpreqin-3fcc3c660d5a7a4d', '佚名/詩經', NULL, NULL, '先秦', 'CN')
)
INSERT INTO poets (title_id, name_zh, name_ko, life_raw, era_period, poem_count)
SELECT slug, name_zh, name_ko, life_raw, era_period, 0
FROM input_poets
ON CONFLICT (title_id) DO UPDATE SET
  name_zh = EXCLUDED.name_zh,
  name_ko = COALESCE(EXCLUDED.name_ko, poets.name_ko),
  life_raw = COALESCE(EXCLUDED.life_raw, poets.life_raw),
  era_period = EXCLUDED.era_period;

WITH input_poems(poet_slug, volume, title_zh, title_ko, category, meter, body_zh, status, quality, review_memo) AS (
  VALUES
    ('cnhan-4d1c052feb6f7223', 0, '古詩十九首', NULL, NULL, NULL, '驅車上東門 遙望郭北墓
白楊何蕭蕭 松柏夾廣路
下有陳死人 杳杳即長暮
潛寐黃泉下 千載永不寤
浩浩陰陽移 年命如朝露
人生忽如寄 壽無金石固
萬歲更相送 聖賢莫能度
服食求神仙 多為藥所誤
不如飲美酒 被服紈與素', 'parsed', 'cnpt-comp', '{"queue_id":"CN-TR-00081","source_record_id":"CN-PRETANG-CACHED-HAN-53e4-8a69-5341-4e5d-9996-2d-4f5a-540d","alias_record_ids":["CN-PRETANG-CACHED-HAN-53e4-8a69-5341-4e5d-9996-2d-4f5a-540d"],"batch":"pre-tang-first-tranche","source_url":"https://zh.wikisource.org/wiki/%E9%A9%85%E8%BB%8A%E4%B8%8A%E6%9D%B1%E9%96%80","review_status":"needs-review","review_reasons":["standalone-page-reuse"]}'),
    ('cnhan-4d1c052feb6f7223', 0, '古詩十九首', NULL, NULL, NULL, '去者日以疎 生者日以親
出郭門直視 但見丘與墳
古墓犁為田 松栢摧為薪
白楊多悲風 蕭蕭愁殺人
思還故里閭 欲歸道無因', 'parsed', 'cnpt-comp', '{"queue_id":"CN-TR-00082","source_record_id":"CN-PRETANG-CACHED-HAN-53e4-8a69-5341-4e5d-9996-2d-4f5a-540d","alias_record_ids":["CN-PRETANG-CACHED-HAN-53e4-8a69-5341-4e5d-9996-2d-4f5a-540d"],"batch":"pre-tang-first-tranche","source_url":"https://zh.wikisource.org/wiki/%E5%8E%BB%E8%80%85%E6%97%A5%E4%BB%A5%E7%96%8E","review_status":"needs-review","review_reasons":["standalone-page-reuse"]}'),
    ('cnhan-4d1c052feb6f7223', 0, '古詩十九首', NULL, NULL, NULL, '生年不滿百，常懷千歲憂。
晝短苦夜長，何不秉燭遊！
為樂當及時，何能待來茲？
愚者愛惜費，但為後世嗤。
仙人王子喬，難可與等期。', 'parsed', 'cnpt-comp', '{"queue_id":"CN-TR-00083","source_record_id":"CN-PRETANG-CACHED-HAN-53e4-8a69-5341-4e5d-9996-2d-4f5a-540d","alias_record_ids":["CN-PRETANG-CACHED-HAN-53e4-8a69-5341-4e5d-9996-2d-4f5a-540d"],"batch":"pre-tang-first-tranche","source_url":"https://zh.wikisource.org/wiki/%E7%94%9F%E5%B9%B4%E4%B8%8D%E6%BB%BF%E7%99%BE","review_status":"needs-review","review_reasons":["standalone-page-reuse","uncertain-author-or-text-marker"]}'),
    ('cnhan-4d1c052feb6f7223', 0, '古詩十九首', NULL, NULL, NULL, '凜凜歲雲暮 螻蛄夕鳴悲
涼風率已厲 遊子寒無衣
錦衾遺洛浦 同袍與我違
獨宿累長夜 夢想見容輝
良人惟古歡 枉駕惠前綏
願得常巧笑 攜手同車歸
既來不須臾 又不處重闈
亮無晨風翼 焉能凌風飛
眄睞以適意 引領遙相睎
徙倚懷感傷 垂涕沾雙扉', 'parsed', 'cnpt-comp', '{"queue_id":"CN-TR-00084","source_record_id":"CN-PRETANG-CACHED-HAN-53e4-8a69-5341-4e5d-9996-2d-4f5a-540d","alias_record_ids":["CN-PRETANG-CACHED-HAN-53e4-8a69-5341-4e5d-9996-2d-4f5a-540d"],"batch":"pre-tang-first-tranche","source_url":"https://zh.wikisource.org/wiki/%E5%87%9C%E5%87%9C%E6%AD%B2%E4%BA%91%E6%9A%AE","review_status":"needs-review","review_reasons":["standalone-page-reuse"]}'),
    ('cnhan-43b38ccd5d1e93f0', 0, '枯鱼过河泣', NULL, '五言絶句', NULL, '枯魚過河泣
何時悔復及
作書與魴鱮
相教慎出入', 'parsed', 'cnpt-comp', '{"queue_id":"CN-TR-00085","source_record_id":"CN-PRETANG-CACHED-HAN-67af-9c7c-8fc7-6cb3-6ce3-2d-7121-540d-6c0f-2f-6f22-6a02-5e9c","alias_record_ids":["CN-PRETANG-CACHED-HAN-67af-9c7c-8fc7-6cb3-6ce3-2d-7121-540d-6c0f-2f-6f22-6a02-5e9c"],"batch":"pre-tang-first-tranche","source_url":"https://zh.wikisource.org/wiki/%E6%9E%AF%E9%AD%9A%E9%81%8E%E6%B2%B3%E6%B3%A3_(%E5%8F%A4%E8%BE%AD)","review_status":"needs-review","review_reasons":["standalone-page-reuse"]}'),
    ('cnhan-43b38ccd5d1e93f0', 0, '戰城南', NULL, NULL, NULL, '戰城南，死郭北，野死不葬鳥可食。
為我謂鳥：「且為客豪，野死諒不葬，腐肉安能去子逃？」
水深激激，蒲葦冥冥。梟騎戰鬥死，駑馬裴徊鳴。
梁築室，何以南？何以北？
禾黍不獲君何食？願為忠臣安可得？
思子良臣，良臣誠可思。
朝行出攻，暮不夜歸。', 'parsed', 'cnpt-comp', '{"queue_id":"CN-TR-00086","source_record_id":"CN-PRETANG-CACHED-HAN-6230-57ce-5357-2d-7121-540d-6c0f-2f-6f22-6a02-5e9c","alias_record_ids":["CN-PRETANG-CACHED-HAN-6230-57ce-5357-2d-7121-540d-6c0f-2f-6f22-6a02-5e9c"],"batch":"pre-tang-first-tranche","source_url":"https://zh.wikisource.org/wiki/%E6%88%B0%E5%9F%8E%E5%8D%97_(%E4%BD%9A%E5%90%8D)","review_status":"needs-review","review_reasons":["standalone-page-reuse","uncertain-author-or-text-marker"]}'),
    ('cnhan-4c77569df016009b', 0, '悲憤詩', NULL, NULL, NULL, '漢季失權柄，董卓亂天常，志欲圖篡弒，先害諸賢良。逼迫遷舊邦，擁主以自彊。海內興義師，欲共討不祥。卓眾來東下，金甲耀日光。平土人脆弱，來兵皆胡羌。獵野圍城邑，所向悉破亡。斬截無孑遺，尸骸相撐拒。馬邊懸男頭，馬後載婦女。長驅西入關，迥路險且阻。還顧邈冥冥，肝脾為爛腐。所略有萬計，不得令屯聚。或有骨肉俱，欲言不敢語。失意幾微間，輒言斃降虜：「要當以亭刃，我曹不活汝！」豈敢惜性命？不堪其詈罵。或便加棰杖，毒痛參並下。旦則號泣行，夜則悲吟坐。欲死不能得，欲生無一可。彼蒼者何辜，乃遭此厄禍？
邊荒與華異，人俗少義理。處所多霜雪，胡風春夏起。翩翩吹我衣，肅肅入我耳。感時念父母，哀嘆無終已。
有客從外來，聞之常歡喜。迎問其消息，輒復非鄉里。邂逅徼時願，骨肉來迎己。己得自解免，當復棄兒子。天屬綴人心，念別無會期。存亡永乖隔，不忍與之辭。兒前抱我頸，問母欲何之？「人言母當去，豈復有還時？阿母常仁惻，今何更不慈？我尚未成人，奈何不顧思？」見此崩五內，恍惚生狂痴。號泣手撫摩，當發復回疑。
兼有同時輩，相送告離別。慕我獨得歸，哀叫聲摧裂。馬為立踟躕，車為不轉轍。觀者皆歔欷，行路亦嗚咽。
去去割情戀，遄征日遐邁。悠悠三千里，何時復交會？念我出腹子，胸臆為摧敗。既至家人盡，又復無中外。城郭為山林，庭宇生荊艾。白骨不知誰，縱橫莫覆蓋。出門無人聲，豺狼號且吠。煢煢對孤景，怛吒詫靡肝肺。登高遠眺望，神魂忽飛逝，奄若壽命盡。旁人相寬大，為復彊視息，雖生何聊賴？
託命於新人，竭心自勖勵。流離成鄙賤，常恐復捐廢。人生幾何時，懷憂終年歲！', 'parsed', 'cnpt-comp', '{"queue_id":"CN-TR-00087","source_record_id":"CN-PRETANG-CACHED-HAN-60b2-61a4-8a69-2d-8521-7430","alias_record_ids":["CN-PRETANG-CACHED-HAN-60b2-61a4-8a69-2d-8521-7430"],"batch":"pre-tang-first-tranche","source_url":"https://zh.wikisource.org/wiki/%E6%82%B2%E6%86%A4%E8%A9%A9_(%E8%94%A1%E7%90%B0)","review_status":"needs-review","review_reasons":["standalone-page-reuse","uncertain-author-or-text-marker"]}'),
    ('cnhan-43b38ccd5d1e93f0', 0, '有所思', NULL, NULL, NULL, '有所思，乃在大海南。何用問遺君？雙珠玳瑁簪，用玉紹繚之。聞君有他心，拉雜摧燒之。摧燒之，當風揚其灰。從今以往，勿復相思。相思與君絶！雞鳴狗吠，兄嫂當知之。秋風肅肅晨風颸，東方須臾高知之。', 'parsed', 'cnpt-comp', '{"queue_id":"CN-TR-00088","source_record_id":"CN-PRETANG-CACHED-HAN-6709-6240-601d-2d-7121-540d-6c0f-2f-6f22-6a02-5e9c","alias_record_ids":["CN-PRETANG-CACHED-HAN-6709-6240-601d-2d-7121-540d-6c0f-2f-6f22-6a02-5e9c"],"batch":"pre-tang-first-tranche","source_url":"https://zh.wikisource.org/wiki/%E6%A8%82%E5%BA%9C%E8%A9%A9%E9%9B%86/016%E5%8D%B7","review_status":"needs-review","review_reasons":["standalone-page-reuse","short-text","uncertain-author-or-text-marker"]}'),
    ('cnhan-43b38ccd5d1e93f0', 0, '東門行', NULL, NULL, NULL, '出東門，不顧歸。來入門，悵欲悲。盎中無鬥儲，還視桁上無懸衣。拔劍出門去，兒女牽衣啼。他家但願富貴，賤妾與君共餔糜。共餔糜，上用倉浪天故，下為黃口小兒。今時清廉，難犯教言，君復自愛莫為非。今時清廉，難犯教言，君復自愛，莫為非。行！吾去為遲，平慎行，望君歸。
出東門，不顧歸。來入門，悵欲悲。盎中無鬥米儲，還視架上無懸衣。拔劍東門去，舍中兒母牽衣啼。他家但願富貴，賤妾與君共餔糜。上用倉浪天故，下當用此黃口兒。今非，咄！行！吾去為遲，白髮時下難久居。', 'parsed', 'cnpt-comp', '{"queue_id":"CN-TR-00089","source_record_id":"CN-PRETANG-CACHED-HAN-6771-9580-884c-2d-7121-540d-6c0f-2f-6f22-6a02-5e9c","alias_record_ids":["CN-PRETANG-CACHED-HAN-6771-9580-884c-2d-7121-540d-6c0f-2f-6f22-6a02-5e9c"],"batch":"pre-tang-first-tranche","source_url":"https://zh.wikisource.org/wiki/%E6%A8%82%E5%BA%9C%E8%A9%A9%E9%9B%86/037%E5%8D%B7","review_status":"needs-review","review_reasons":["standalone-page-reuse"]}'),
    ('cnhan-43b38ccd5d1e93f0', 0, '西門行', NULL, NULL, NULL, '出西門，步念之。今日不作樂，當待何時？夫為樂，為樂當及時。何能坐愁怫鬱，當復待來茲。飲醇酒，炙肥牛，請呼心所歡，可用解愁憂。人生不滿百，常懷千歲憂。晝短而夜長，何不秉燭遊。自非仙人王子喬，計會壽命難與期。自非仙人王子喬，計會壽命難與期。人壽非金石，年命安可期。貪財愛惜費，但為後世嗤。
出西門，步念之，今日不作樂，當待何時？逮為樂，逮為樂，當及時。何能愁怫鬱，當復待來茲。釀美酒，炙肥牛，請呼心所歡，可用解憂愁。人生不滿百，常懷千歲憂。晝短苦夜長，何不秉燭遊。遊行去去如雲除，弊車贏馬為自儲。', 'parsed', 'cnpt-comp', '{"queue_id":"CN-TR-00090","source_record_id":"CN-PRETANG-CACHED-HAN-897f-9580-884c-2d-7121-540d-6c0f-2f-6f22-6a02-5e9c","alias_record_ids":["CN-PRETANG-CACHED-HAN-897f-9580-884c-2d-7121-540d-6c0f-2f-6f22-6a02-5e9c"],"batch":"pre-tang-first-tranche","source_url":"https://zh.wikisource.org/wiki/%E6%A8%82%E5%BA%9C%E8%A9%A9%E9%9B%86/037%E5%8D%B7","review_status":"needs-review","review_reasons":["standalone-page-reuse","uncertain-author-or-text-marker"]}'),
    ('cnhan-43b38ccd5d1e93f0', 0, '陌上桑', NULL, NULL, NULL, '日出東南隅，照我秦氏樓。秦氏有好女，自名為羅敷。羅敷憙蠶桑，采桑城南隅。青絲為籠係，桂枝為籠鉤。頭上倭墮髻，耳中明月珠。緗綺為下裙，紫綺為上襦。行者見羅敷，下擔捋髭須；少年見羅敷，脫帽著肖頭。耕者忘其犁，鋤者忘其鋤。來歸相怒怨，但坐觀羅敷。使君從南來，五馬立踟躕。使君遣吏往，問是誰家姝？秦氏有好女，自名為羅敷。羅敷年幾何？二十尚不足，十五頗有餘。使君謝羅敷：「寧可共載不？」羅敷前置辭：「使君一何愚！使君自有婦，羅敷自有夫。」東方千餘騎，夫婿居上頭。何用識夫婿，白馬從驪駒。青絲係馬尾，黃金絡馬頭。腰中鹿盧劍，可直千萬餘。十五府小史，二十朝大夫。三十侍中郎，四十專城居。為人潔白皙，鬑々頗有須。盈盈公府步，冉冉府中趨。坐中數千人，皆言夫婿殊。', 'parsed', 'cnpt-comp', '{"queue_id":"CN-TR-00091","source_record_id":"CN-PRETANG-CACHED-HAN-964c-4e0a-6851-2d-7121-540d-6c0f-2f-6f22-6a02-5e9c","alias_record_ids":["CN-PRETANG-CACHED-HAN-964c-4e0a-6851-2d-7121-540d-6c0f-2f-6f22-6a02-5e9c"],"batch":"pre-tang-first-tranche","source_url":"https://zh.wikisource.org/wiki/%E6%A8%82%E5%BA%9C%E8%A9%A9%E9%9B%86/028%E5%8D%B7","review_status":"needs-review","review_reasons":["standalone-page-reuse","short-text","uncertain-author-or-text-marker"]}'),
    ('cnhan-43b38ccd5d1e93f0', 0, '相逢行', NULL, NULL, NULL, '相逢狹路間，道隘不容車。不知何年少，夾轂問君家。君家誠易知，易知復難忘。黃金為君門，白玉為君堂。堂上置樽酒，作使邯鄲倡。中庭生桂樹，華燈何煌煌。兄弟兩三人，中子為侍郎。五日一來歸，道上自生光。黃金絡馬頭，觀者盈道傍。入門時左顧，但見雙鴛鴦。鴛鴦七十二，羅列自成行。音聲何雍雍，鶴鳴東西廂。大婦織綺羅，中婦織流黃。小婦無所為，挾瑟上高堂。丈人且安坐，調絲方未央。', 'parsed', 'cnpt-comp', '{"queue_id":"CN-TR-00092","source_record_id":"CN-PRETANG-CACHED-HAN-76f8-9022-884c-2d-7121-540d-6c0f-2f-6f22-6a02-5e9c","alias_record_ids":["CN-PRETANG-CACHED-HAN-76f8-9022-884c-2d-7121-540d-6c0f-2f-6f22-6a02-5e9c"],"batch":"pre-tang-first-tranche","source_url":"https://zh.wikisource.org/wiki/%E6%A8%82%E5%BA%9C%E8%A9%A9%E9%9B%86/034%E5%8D%B7","review_status":"needs-review","review_reasons":["standalone-page-reuse","short-text"]}'),
    ('cnhan-43b38ccd5d1e93f0', 0, '隴西行', NULL, NULL, NULL, '天上何所有，歷歷種白榆。桂樹夾道生，青龍對道隅。鳳凰鳴啾啾，一母將九雛。顧視世間人，為樂甚獨殊。好婦出迎客，顏色正敷愉。伸腰再拜跪，問客平安不。請客北堂上，坐客氈氍毹。清白各異樽，酒上正華疏。酌酒持與客，客言主人持。卻略再拜跪，然後持一杯。談笑未及竟，左顧敕中廚。促令辦粗飯，慎莫使稽留。廢禮送客出，盈盈府中趨。送客亦不遠，足不過門樞。取婦得如此，齊姜亦不如。健婦持門戶，一勝一丈夫。', 'parsed', 'cnpt-comp', '{"queue_id":"CN-TR-00093","source_record_id":"CN-PRETANG-CACHED-HAN-96b4-897f-884c-2d-7121-540d-6c0f-2f-6f22-6a02-5e9c","alias_record_ids":["CN-PRETANG-CACHED-HAN-96b4-897f-884c-2d-7121-540d-6c0f-2f-6f22-6a02-5e9c"],"batch":"pre-tang-first-tranche","source_url":"https://zh.wikisource.org/wiki/%E6%A8%82%E5%BA%9C%E8%A9%A9%E9%9B%86/037%E5%8D%B7","review_status":"needs-review","review_reasons":["standalone-page-reuse","short-text"]}'),
    ('cnhan-aa408a3758d7e916', 0, '梁甫吟', NULL, NULL, NULL, '步出齊城門，遙望蕩陰裏。里中有三墓，累累正相似。問是誰家墓，田彊、古冶子。力能排南山，文能絶地紀。一朝被讒言，二桃殺三士。誰能為此謀？國相齊晏子。', 'parsed', 'cnpt-comp', '{"queue_id":"CN-TR-00094","source_record_id":"CN-PRETANG-CACHED-HAN-6881-752b-541f-2d-8af8-845b-4eae","alias_record_ids":["CN-PRETANG-CACHED-HAN-6881-752b-541f-2d-8af8-845b-4eae"],"batch":"pre-tang-first-tranche","source_url":"https://zh.wikisource.org/wiki/%E6%A8%82%E5%BA%9C%E8%A9%A9%E9%9B%86/041%E5%8D%B7","review_status":"needs-review","review_reasons":["standalone-page-reuse","short-text","uncertain-author-or-text-marker"]}'),
    ('cnhan-43b38ccd5d1e93f0', 0, '悲歌', NULL, NULL, NULL, '悲歌可以當泣，遠望可以當歸。思念故鄉，鬱鬱累累。欲歸家無人，欲渡河無船，心思不能言，腸中車輪轉。', 'parsed', 'cnpt-comp', '{"queue_id":"CN-TR-00095","source_record_id":"CN-PRETANG-CACHED-HAN-60b2-6b4c-2d-7121-540d-6c0f-2f-6f22-6a02-5e9c","alias_record_ids":["CN-PRETANG-CACHED-HAN-60b2-6b4c-2d-7121-540d-6c0f-2f-6f22-6a02-5e9c"],"batch":"pre-tang-first-tranche","source_url":"https://zh.wikisource.org/wiki/%E6%A8%82%E5%BA%9C%E8%A9%A9%E9%9B%86/062%E5%8D%B7","review_status":"needs-review","review_reasons":["standalone-page-reuse","short-text"]}'),
    ('cnpreqin-d9cfb1495fcebc18', 0, '九歌', NULL, NULL, NULL, '東皇太一
吉日兮辰良，穆將愉兮上皇。
撫長劍兮玉珥，璆鏘鳴兮琳琅。
瑤席兮玉瑱，盍將把兮瓊芳。
蕙肴蒸兮蘭藉，奠桂酒兮椒漿。
揚枹兮拊鼓，疏緩節兮安歌，陳竽瑟兮浩倡。
靈偃蹇兮姣服，芳菲菲兮滿堂。
五音紛兮繁會，君欣欣兮樂康。
雲中君
浴蘭湯兮沐芳，華采衣兮若英。
靈連蜷兮既留，爛昭昭兮未央。
蹇將憺兮壽宮，與日月兮齊光。
龍駕兮帝服，聊翱遊兮周章。
靈皇皇兮既降，猋遠舉兮雲中。
覽冀州兮有餘，橫四海兮焉窮。
思夫君兮太息，極勞心兮憧憧。
大司命
廣開兮天門，紛吾乘兮玄雲。
令飄風兮先驅，使涷雨兮灑塵。
君迴翔兮以下，踰空桑兮從女。
紛總總兮九州，何壽夭兮在予！
高飛兮安翔，乘清氣兮御陰陽。
吾與君兮齋速，導帝之兮九坑。
靈衣兮被被，玉佩兮陸離。
壹陰兮壹陽，衆莫知兮餘所為。
折疏麻兮瑤華，將以遺兮離居。
老冉冉兮既極，不寖近兮愈疏。
乘龍兮轔轔，高駝兮沖天。
結桂枝兮延竚，羌愈思兮愁人。
愁人兮柰何，願若今兮無虧。
固人命兮有當，孰離合兮可為？
少司命
秋蘭兮麋蕪，羅生兮堂下。
綠葉兮素華，芳菲菲兮襲予。
夫人自有兮美子，蓀何以兮愁苦！
秋蘭兮青青，綠葉兮紫莖。
滿堂兮美人，忽獨與餘兮目成。
入不言兮出不辭，乘回風兮載雲旗。
悲莫悲兮生別離，樂莫樂兮新相知。
荷衣兮蕙帶，儵而來兮忽而逝。
夕宿兮帝郊，君誰須兮雲之際？
與女沐兮咸池，晞女髮兮陽之阿。
望美人兮未來，臨風怳兮浩歌。
孔蓋兮翠旍，登九天兮撫彗星。
竦長劍兮擁幼艾，蓀獨宜兮為民正。
東君
暾將出兮東方，照吾檻兮扶桑。
撫餘馬兮安驅，夜晈晈兮既明。
駕龍輈兮乘雷，載雲旗兮委蛇。
長太息兮將上，心低佪兮顧懷。
羌聲色兮娛人，觀者憺兮忘歸。
緪瑟兮交鼓，簫鍾兮瑤簴，
鳴箎兮吹竽，思靈保兮賢姱。
翾飛兮翠曾，展詩兮會舞。
應律兮合節，靈之來兮蔽日。
青雲衣兮白霓裳，舉長矢兮射天狼。
操餘弧兮反淪降，援北鬥兮酌桂漿。
撰餘轡兮高駝翔，杳冥冥兮以東行。
湘君
君不行兮夷猶，蹇誰留兮中洲？
美要眇兮宜修，沛吾乘兮桂舟。
令沅湘兮無波，使江水兮安流！
望夫君兮未來，吹參差兮誰思！
駕飛龍兮北征，邅吾道兮洞庭。
薜荔柏兮蕙綢，蓀橈兮蘭旌。
望涔陽兮極浦，橫大江兮揚靈。
揚靈兮未極，女嬋媛兮為餘太息。
橫流涕兮潺湲，隱思君兮陫側。
桂櫂兮蘭枻，斲冰兮積雪。
采薜荔兮水中，搴芙蓉兮木末。
心不同兮媒勞，恩不甚兮輕絶。
石瀨兮淺淺，飛龍兮翩翩。
交不忠兮怨長，期不信兮告餘以不閒。
鼂騁騖兮江臯，夕弭節兮北渚。
鳥次兮屋上，水周兮堂下。
捐餘玦兮江中，遺餘佩兮醴浦。
采芳洲兮杜若，將以遺兮下女。
旹不可兮再得，聊逍遙兮容與。
湘夫人
帝子降兮北渚，目眇眇兮愁予。
嫋嫋兮秋風，洞庭波兮木葉下。
登白薠兮騁望，與佳期兮夕張。
鳥何萃兮蘋中，罾何為兮木上。
沅有芷兮醴有蘭，思公子兮未敢言。
荒忽兮遠望，觀流水兮潺湲。
麋何食兮庭中？蛟何為兮水裔？
朝馳餘馬兮江臯，夕濟兮西澨。
聞佳人兮召予，將騰駕兮偕逝。
築室兮水中，葺之兮荷蓋。
蓀壁兮紫壇，播芳椒兮成堂。
桂棟兮蘭橑，辛夷楣兮葯房。
罔薜荔兮為帷，擗蕙櫋兮既張。
白玉兮為鎮，疏石蘭兮為芳。
芷葺兮荷屋，繚之兮杜衡。
合百草兮實庭，建芳馨兮廡門。
九嶷繽兮並迎，靈之來兮如雲。
捐餘袂兮江中，遺餘褋兮醴浦。
搴汀洲兮杜若，將以遺兮遠者。
時不可兮驟得，聊逍遙兮容與。
河伯
與女遊兮九河，衝風起兮橫波。
乘水車兮荷蓋，駕兩龍兮驂螭。
登崑崙兮四望，心飛揚兮浩蕩。
日將暮兮悵忘歸，惟極浦兮寤懷。
魚鱗屋兮龍堂，紫貝闕兮朱宮。
靈何為兮水中，乘白黿兮逐文魚。
與女遊兮河之渚，流澌紛兮將來下。
子交手兮東行，送美人兮南浦。
波滔滔兮來迎，魚鱗鱗兮媵予。
山鬼
若有人兮山之阿，被薜荔兮帶女羅。
既含睇兮又宜笑，子慕予兮善窈窕。
乘赤豹兮從文狸，辛夷車兮結桂旗。
被石蘭兮帶杜衡，折芳馨兮遺所思。
餘處幽篁兮終不見天，路險難兮獨後來。
表獨立兮山之上，雲容容兮而在下。
杳冥冥兮羌晝晦，東風飄兮神靈雨。
留靈脩兮憺忘歸，歲既晏兮孰華予。
采三秀兮於山間，石磊磊兮葛蔓蔓。
怨公子兮悵忘歸，君思我兮不得閒。
山中人兮芳杜若，飲石泉兮蔭松柏，君思我兮然疑作。
靁填填兮雨冥冥，猿啾啾兮狖夜鳴。
風颯颯兮木蕭蕭，思公子兮徒離憂。
國殤
操吳戈兮被犀甲，車錯轂兮短兵接。
旌蔽日兮敵若雲，矢交墜兮士爭先。
凌餘陣兮躐餘行，左驂殪兮右刃傷。
霾兩輪兮縶四馬，援玉枹兮擊鳴鼓。
天時懟兮威靈怒，嚴殺盡兮棄原野。
出不入兮往不反，平原忽兮路超遠。
帶長劍兮挾秦弓，首身離兮心不懲。
誠既勇兮又以武，終剛強兮不可凌。
身既死兮神以靈，魂魄毅兮為鬼雄。
禮魂
成禮兮會鼓，傳芭兮代舞，姱女倡兮容與。
春蘭兮秋菊，長無絶兮終古。', 'parsed', 'cnpt-chuci', '{"queue_id":"CN-TR-00096","source_record_id":"CN-CLASSIC-63-68-75-63-69-2d-32-2d-4e5d-6b4c-2d-5c48-539f-2d-4e5d-6b4c","alias_record_ids":["CN-CLASSIC-63-68-75-63-69-2d-32-2d-4e5d-6b4c-2d-5c48-539f-2d-4e5d-6b4c"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E4%B9%9D%E6%AD%8C","review_status":"needs-review","review_reasons":["classic-index-work","chuci"]}'),
    ('cnpreqin-d9cfb1495fcebc18', 0, '天問', NULL, NULL, NULL, '曰：遂古之初，誰傳道之？上下未形，何由考之？冥昭瞢闇，誰能極之？馮翼惟像，何以識之？明明闇闇，惟時何爲？陰陽三合，何本何化？圜則九重，孰營度之？惟兹何功，孰初作之？斡維焉繫？天極焉加？八柱何當，東南何虧？九天之際，安放安屬？隅隈多有，誰知其數？天何所沓，十二焉分？日月安屬，列星安陳？出自湯谷，次于蒙汜。自明及晦，所行幾里？夜光何德，死則又育？厥利維何，而顧菟在腹？女岐無合，夫焉取九子？伯強何處，惠氣安在？何闔而晦，何開而明？角宿未旦，曜靈安藏？
不任汩鴻，師何以尚之？僉曰：何憂？何不課而行之？鴟龜曳銜，鮌何聽焉？順欲成功，帝何刑焉？永遏在羽山，夫何三年不施？伯禹愎鮌，夫何以變化？纂就前緒，遂成考功。何續初繼業，而厥謀不同？洪泉極深，何以窴之？地方九則，何以墳之？河海應龍，何盡何歷？鮌何所營，禹何所成？康回馮怒，墬何故以東南傾？九州安錯，川谷何洿？東流不溢，孰知其故？東西南北，其脩孰多？南北順㯐，其衍幾何？崑崙縣圃，其凥安在？增城九重，其高幾里？四方之門，其誰從焉？西北辟啓，何氣通焉？
日安不到，燭龍何照？羲和之未揚，若華何光？何所冬暖，何所夏寒？焉有石林，何獸能言？焉有虬龍，負熊以遊？雄虺九首，儵忽焉在？何所不死，長人何守？靡蓱九衢，枲華安居？一蛇吞象，厥大何如？黑水、玄趾，三危安在？延年不死，壽何所止？鯪魚何所，鬿堆焉處？羿焉彃日，烏焉解羽？
禹之力獻功，降省下土四方。焉得彼嵞山女，而通之於台桑？閔妃匹合，厥身是繼。胡維嗜不同味，而快鼂飽？啓代益作後，卒然離蠥。何啓惟憂，而能拘是達〈逸〉？皆歸䠶𥷴，而無害厥躬。何後益作革，而禹播降？啓棘〈陟〉賓商，九辯、九歌。何勤子屠母，而死分竟地？帝降夷羿，革孽夏民。胡䠶夫河伯，而妻彼雒嬪？馮珧利決，封豨是䠶。何獻蒸肉之膏，而後帝不若？浞娶純狐，眩妻爰謀？何羿之䠶革，而交吞揆之？阻窮西征，巖何越焉？化爲黃熊，巫何活焉？咸播秬黍，莆雚是營。何由並投，而鮌疾〈息〉脩盈？白蜺嬰茀〈門簾〉，胡爲此堂？安得夫良藥，不能固藏？天式從橫，陽離爰〈受〉死？大鳥何鳴，夫焉喪厥體？蓱號起雨，何以興之？撰體協脅，鹿何膺之？鼇戴山抃，何以安之？釋舟陵行，何以遷之？惟澆在戶，何求于嫂？何少康逐犬，而顛隕厥首？女歧縫裳，而館同爰止。何顛易厥首，而親以逢殆？湯謀易旅，何以厚之？覆舟斟尋，何道取之？桀伐蒙〈岷〉山，何所得焉？妺嬉何肆〈咎〉，湯何殛焉？
舜閔〈文〉在家，父何以鱞？堯不姚告，二女何親？厥萌在初，何所億焉？璜臺十成，誰所極焉？登立爲帝，孰道尚之？女媧有體，孰制匠之？舜服厥弟，終然爲害。何肆犬體，而厥身不危敗？吳獲迄古，南嶽是止。孰期去斯，得兩男子？緣〈臇〉鵠飾玉，後帝是饗。何承謀夏桀，終以滅喪？帝乃降觀，下逢伊摯。何條〈逐〉放致罰，而黎服大說？簡狄在臺嚳何宜？玄鳥致貽。女何喜？該秉季德，厥父是臧。胡終弊于有扈，牧夫牛羊？乾協時舞，何以懷之？平脅曼膚，何以肥之？有扈牧豎，雲何而逢？擊牀先出，其命何從？恒秉季德，焉得夫樸牛？何往營班祿，不但還〈轉〉來？昏微遵迹，有狄不寧？何繁鳥萃棘，負子肆情？眩弟竝淫，危害厥兄。何變化以作詐，後嗣而逢長？成湯東巡，有莘爰極。何乞彼小臣，而吉妃是得？水濱之木，得彼小子。夫何惡之，媵有莘之婦？湯出重泉，夫何辠尤？不勝心伐帝，夫誰使挑之？
會鼂爭〈請〉盟，何踐吾〈許〉期？蒼鳥羣飛，孰使萃之？到擊紂躬，叔旦不嘉。何親揆發足，周之命以咨嗟？授殷天下，其位安施？反成乃亡，其罪伊何？爭遣伐器，何以行之？竝驅擊翼，何以將之？昭後成遊，南土爰底。厥利惟何，逢彼白雉？穆王巧梅〈訏謀〉，夫何爲周流？環理天下，夫何索求？妖夫曳衒，何號于市？周幽誰誅，焉得夫褒姒？天命反側，何罰何佑？齊桓九會，卒然身殺。彼王紂之躬，孰使亂惑？何惡輔弼，讒諂是服？比乾何逆，而抑沈之？雷開阿順，而賜封之？何聖人之一德，卒其異方？梅伯受醢，箕子詳狂。稷維元子，帝何竺之？投之於冰上，鳥何燠之？何馮弓挾矢，殊能將之？既驚帝切激，何逢長之？伯昌號衰，秉鞭作牧。何令徹彼岐社，命有殷國？遷藏就岐何能依？殷有惑婦何所譏？受賜兹醢，西伯上告。何親就上帝罰，殷之命以不救？師望在肆，昌何識？鼓刀揚聲，後何喜？武發殺殷何所悒？載尸集戰何所急？伯林雉經，維其何故？何感天抑墬，夫誰畏懼？皇天集命，惟何戒之？受禮天下，又使至代之？初湯臣摯，後茲〈使〉承輔。何卒官湯，尊食宗緒？勳闔夢生，少離散亡。何壯武厲，能流厥嚴？彭鏗斟雉帝何饗？受壽永多，夫何久長？中央共牧後何怒？𧒒蛾微命力何固？驚女采薇鹿何祐？北至回水萃何喜？兄有噬犬弟何欲？易之以百兩卒無祿？
薄暮雷電歸何憂？厥嚴不奉帝何求？伏匿穴處爰何雲？荆勳作師夫何長？悟過改更我又何言？吳光爭國，（何）久餘是勝。何環穿自閭社丘陵，是淫是蕩？爰出子文，吾告堵敖以不長？何試上自予，忠名彌彰？', 'parsed', 'cnpt-chuci', '{"queue_id":"CN-TR-00097","source_record_id":"CN-CLASSIC-63-68-75-63-69-2d-33-2d-5929-554f-2d-5c48-539f-2d-5929-554f","alias_record_ids":["CN-CLASSIC-63-68-75-63-69-2d-33-2d-5929-554f-2d-5c48-539f-2d-5929-554f"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E5%A4%A9%E5%95%8F","review_status":"needs-review","review_reasons":["classic-index-work","chuci"]}'),
    ('cnpreqin-d9cfb1495fcebc18', 0, '遠遊', NULL, NULL, NULL, '悲時俗之迫阨兮，願輕舉而遠遊。質菲薄而無因兮，焉託乘而上浮？遭沈濁而汙穢兮，獨鬱結其誰語！夜耿耿而不寐兮，魂焭焭而至曙。
惟天地之無窮兮，哀人生之長勤。往者餘弗及兮，來者吾不聞。步徙倚而遥思兮，怊惝怳而乖懷。意荒忽而流蕩兮，心愁悽而增悲。神儵忽而不反兮，形枯槁而獨留。內惟省以端操兮，求正氣之所由。漠虛靜以恬愉兮，澹無爲而自得。
聞赤松之清塵兮，願承風乎遺則。貴真人之休德兮，美往世之登仙。與化去而不見兮，名聲著而日延。奇傅說之託辰星兮，羨韓衆之得一。形穆穆以浸遠兮，離人羣而遁逸。因氣變而遂曾舉兮，忽神奔而鬼怪。時髣髴以遥見兮，精晈晈以往來。絶氛埃而淑尤兮，終不反其故都。免衆患而不懼兮，世莫知其所如。
恐天時之代序兮，耀靈曄而西征。微霜降而下淪兮，悼芳草之先零。聊仿佯而逍遥兮，永歷年而無成。誰可與玩斯遺芳兮，晨向風而舒情。高陽邈以遠兮，餘將焉所程。
重曰：春秋忽其不淹兮，奚久留此故居？軒轅不可攀援兮，吾將從王喬而娛戲。餐六氣而飲沆瀣兮，漱正陽而含朝霞。保神明之清澄兮，精氣入而麤穢除。順凱風以從遊兮，至南巢而壹息。見王子而宿之兮，審壹氣之和德。
曰：道可受兮，不可傳。其小無內兮，其大無垠。無滑而䰟兮，彼將自然。壹氣孔神兮，於中夜存。虛以待之兮，無爲之先。庶類以成兮，此德之門。
聞至貴而遂徂兮，忽乎吾將行。仍羽人於丹丘兮，留不死之舊鄉。朝濯髮於湯谷兮，夕晞餘身兮九陽。吸飛泉之微液兮，懷琬琰之華英。玉色頩以脕顏兮，精醇粹而始壯。質銷鑠以汋約兮，神要眇以淫放。嘉南州之炎德兮，麗桂樹之冬榮。山蕭條而無獸兮，野寂漠其無人。載營魄而登霞兮，掩浮雲而上征。命天閽其開關兮，排閶闔而望予。召豐隆使先導兮，問大微之所居。集重陽入帝宮兮，造旬始而觀清都。
朝發軔於太儀兮，夕始臨乎於微閭。屯餘車之萬乘兮，紛溶與而並馳。駕八龍之婉婉兮，載雲旗之逶蛇。建雄虹之采旄兮，五色雜而炫燿。服偃蹇以𠇓昂兮，驂連蜷以驕驁。騎膠葛以雜亂兮，斑漫衍而方行。撰餘轡而正策兮，吾將過乎句芒。歷太皓以右轉兮，前飛廉以啓路。陽杲杲其未光兮，淩天地以徑度。風伯爲餘先驅兮，氛埃辟而清涼。鳳皇翼其承旂兮，遇蓐收乎西皇。擥彗星㠯爲旍兮，舉鬥柄以爲麾。叛陸離其上下兮，遊驚霧之流波。旹曖曃其曭莽兮，召玄武而奔屬。後文昌使掌行兮，選署衆神以並轂。路曼曼其脩遠兮，徐弭節而高厲。左雨師使徑侍兮，右雷公以爲衛。欲度世以忘歸兮，意姿睢㠯担撟。內欣欣而自美兮，聊媮娛以自樂。涉青雲以汎濫遊兮，忽臨睨夫舊鄉。僕夫懷餘心悲兮，邊馬顧而不行。思舊故以想像兮，長太息而掩涕。氾容與而遐舉兮，聊抑志而自弭。指炎神而直馳兮，吾將往乎南疑。
覽方外之荒忽兮，沛罔象而自浮。祝融戒而還衡兮，騰告鸞鳥迎宓妃。張咸池奏承雲兮，二女御九韶歌。使湘靈鼓瑟兮，令海若舞馮夷。玄螭蟲象並出進兮，形蟉虬而逶蛇。雌蜺便娟㠯增撓兮，鸞鳥軒翥而翔飛。音樂博衍無終極兮，焉乃逝以俳佪。舒並節以馳騖兮，逴絶垠乎寒門。軼迅風於清源兮，從顓頊乎增冰。歷玄冥以邪徑兮，乘間維以反顧。召黔嬴而見之兮，爲餘先乎平路。經營四荒兮，周流六漠。上至列𡙇兮，降望大壑。下崢嶸而無地兮，上寥廓而無天。視儵忽而無見兮，聽惝怳而無聞。超無爲以至清兮，與泰初而爲鄰。', 'parsed', 'cnpt-chuci', '{"queue_id":"CN-TR-00098","source_record_id":"CN-CLASSIC-63-68-75-63-69-2d-35-2d-9060-904a-2d-5c48-539f-2d-695a-8fad-2f-9060-904a","alias_record_ids":["CN-CLASSIC-63-68-75-63-69-2d-35-2d-9060-904a-2d-5c48-539f-2d-695a-8fad-2f-9060-904a"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E6%A5%9A%E8%BE%AD/%E9%81%A0%E9%81%8A","review_status":"needs-review","review_reasons":["classic-index-work","chuci"]}'),
    ('cnpreqin-d9cfb1495fcebc18', 0, '卜居', NULL, NULL, NULL, '屈原既放三年，不得復見，竭知盡忠，而蔽鄣於讒。心煩慮亂，不知所從。往見太卜鄭詹尹曰：「餘有所疑，願因先生決之。」詹尹乃端策拂龜，曰：「君將何以教之？」屈原曰：「吾寧悃悃欵欵，樸以忠乎？將送往勞來，斯無窮乎？寧誅鋤草茅，以力耕乎？將遊大人，以成名乎？寧正言不諱，以危身乎？將從俗富貴，以媮生乎？寧超然高舉，㠯保真乎？將哫訾栗斯，喔咿儒兒，以事婦人乎？寧廉潔正直，以自清乎？將突梯滑稽，如脂如韋，以潔楹乎？寧昂昂若千里之駒乎？將氾氾若水中之鳧乎？與波上下，偷以全吾軀乎？寧與騏驥亢軛乎？將隨駑馬之迹乎？寧與黃鵠比翼乎？將與雞鶩爭食乎？此孰吉孰凶？何去何從？世溷濁而不清，蟬翼爲重，千鈞爲輕；黃鐘毀棄，瓦釜雷鳴；讒人高張，賢士無名。吁嗟默默兮，誰知吾之廉貞！」詹尹乃釋策而謝曰：「夫尺有所短，寸有所長；物有所不足，智有所不明；數有所不逮，神有所不通。用君之心，行君之意，龜策誠不能知事。」', 'parsed', 'cnpt-chuci', '{"queue_id":"CN-TR-00099","source_record_id":"CN-CLASSIC-63-68-75-63-69-2d-36-2d-535c-5c45-2d-5c48-539f-2d-535c-5c45-20-28-5c48-539f-29","alias_record_ids":["CN-CLASSIC-63-68-75-63-69-2d-36-2d-535c-5c45-2d-5c48-539f-2d-535c-5c45-20-28-5c48-539f-29"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E5%8D%9C%E5%B1%85_(%E5%B1%88%E5%8E%9F)","review_status":"needs-review","review_reasons":["classic-index-work","chuci"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '關雎', NULL, NULL, NULL, '關關雎鳩，在河之洲。
窈窕淑女，君子好逑。
參差荇菜，左右流之。
窈窕淑女，寤寐求之。
求之不得，寤寐思服。
悠哉悠哉，輾轉反側。
參差荇菜，左右采之。
窈窕淑女，琴瑟友之。
參差荇菜，左右芼之。
窈窕淑女，鐘鼓樂之。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00100","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-2d-95dc-96ce-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-95dc-96ce","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-2d-95dc-96ce-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-95dc-96ce"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%97%9C%E9%9B%8E","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '葛覃', NULL, NULL, NULL, '葛之覃兮，施于中谷，維葉萋萋，黃鳥于飛，集于灌木，其鳴喈喈。
葛之覃兮，施于中谷，維葉莫莫，是刈是濩，為絺為綌，服之無斁。
言告師氏，言告言歸，薄汙我私，薄澣我衣，害澣害否，歸寧父母。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00101","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-2d-845b-8983-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-845b-8983","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-2d-845b-8983-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-845b-8983"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E8%91%9B%E8%A6%83","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '卷耳', NULL, NULL, NULL, '采采卷耳，不盈頃筐，嗟我懷人，寘彼周行。
陟彼崔嵬，我馬虺隤，我姑酌彼金罍，維以不永懷。
陟彼高岡，我馬玄黃，我姑酌彼兕觥，維以不永傷。
陟彼砠矣，我馬瘏矣，我僕痡矣，雲何吁矣。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00102","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-33-2d-5377-8033-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5377-8033","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-33-2d-5377-8033-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5377-8033"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%8D%B7%E8%80%B3","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '樛木', NULL, NULL, NULL, '南有樛木，葛藟纍之，樂只君子，福履綏之。
南有樛木，葛藟荒之，樂只君子，福履將之。
南有樛木，葛藟縈之，樂只君子，福履成之。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00103","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-34-2d-6a1b-6728-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6a1b-6728","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-34-2d-6a1b-6728-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6a1b-6728"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%A8%9B%E6%9C%A8","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '螽斯', NULL, NULL, NULL, '螽斯羽，詵詵兮，宜爾子孫，振振兮！
螽斯羽，薨薨兮，宜爾子孫，繩繩兮！
螽斯羽，揖揖兮，宜爾子孫，蟄蟄兮！', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00104","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-35-2d-87bd-65af-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-87bd-65af","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-35-2d-87bd-65af-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-87bd-65af"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E8%9E%BD%E6%96%AF","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '桃夭', NULL, NULL, NULL, '桃之夭夭，灼灼其華，之子于歸，宜其室家。
桃之夭夭，有蕡其實，之子于歸，宜其家室。
桃之夭夭，其葉蓁蓁，之子于歸，宜其家人。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00105","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-36-2d-6843-592d-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6843-592d","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-36-2d-6843-592d-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6843-592d"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%A1%83%E5%A4%AD","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '兔罝', NULL, NULL, NULL, '肅肅兔罝，椓之丁丁，赳赳武夫，公侯乾城。
肅肅兔罝，施于中逵，赳赳武夫，公侯好仇。
肅肅兔罝，施于中林，赳赳武夫，公侯腹心。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00106","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-37-2d-5154-7f5d-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5154-7f5d","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-37-2d-5154-7f5d-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5154-7f5d"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%85%94%E7%BD%9D","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '芣苢', NULL, NULL, NULL, '采采芣苢，薄言采之，采采芣苢，薄言有之。
采采芣苢，薄言掇之，采采芣苢，薄言捋之。
采采芣苢，薄言袺之，采采芣苢，薄言襭之。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00107","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-38-2d-82a3-82e2-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-82a3-82e2","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-38-2d-82a3-82e2-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-82a3-82e2"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E8%8A%A3%E8%8B%A2","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '漢廣', NULL, NULL, NULL, '南有喬木，不可休息；漢有遊女，不可求思，漢之廣矣，不可泳思，江之永矣，不可方思。
翹翹錯薪，言刈其楚，之子于歸，言秣其馬，漢之廣矣，不可泳思，江之永矣，不可方思。
翹翹錯薪，言刈其蔞，之子于歸，言秣其駒，漢之廣矣，不可泳思，江之永矣，不可方思。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00108","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-39-2d-6f22-5ee3-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6f22-5ee3","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-39-2d-6f22-5ee3-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6f22-5ee3"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%BC%A2%E5%BB%A3","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '汝墳', NULL, NULL, NULL, '遵彼汝墳，伐其條枚，未見君子，惄如調飢。
遵彼汝墳，伐其條肄，既見君子，不我遐棄。
魴魚赬尾，王室如燬，雖則如燬，父母孔邇。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00109","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-30-2d-6c5d-58b3-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6c5d-58b3","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-30-2d-6c5d-58b3-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6c5d-58b3"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%B1%9D%E5%A2%B3","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '麟之趾', NULL, NULL, NULL, '麟之趾，振振公子，于嗟麟兮。
麟之定，振振公姓，于嗟麟兮。
麟之角，振振公族，于嗟麟兮。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00110","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-31-2d-9e9f-4e4b-8dbe-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9e9f-4e4b-8dbe","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-31-2d-9e9f-4e4b-8dbe-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9e9f-4e4b-8dbe"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%BA%9F%E4%B9%8B%E8%B6%BE","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '鵲巢', NULL, NULL, NULL, '維鵲有巢，維鳩居之，之子于歸，百兩御之。
維鵲有巢，維鳩方之，之子于歸，百兩將之。
維鵲有巢，維鳩盈之，之子于歸，百兩成之。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00111","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-32-2d-9d72-5de2-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9d72-5de2","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-32-2d-9d72-5de2-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9d72-5de2"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%B5%B2%E5%B7%A2","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '采蘩', NULL, NULL, NULL, '于以采蘩，于沼于沚，于以用之，公侯之事。
于以采蘩，于澗之中，于以用之，公侯之宮。
被之僮僮，夙夜在公，被之祁祁，薄言還歸。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00112","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-33-2d-91c7-8629-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-91c7-8629","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-33-2d-91c7-8629-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-91c7-8629"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%87%87%E8%98%A9","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '草蟲', NULL, NULL, NULL, '喓喓草蟲，趯趯阜螽，未見君子，憂心忡忡，亦既見止，亦既覯止，我心則降。
陟彼南山，言采其蕨，未見君子，憂心惙惙，亦既見止，亦既覯止，我心則說。
陟彼南山，言采其薇，未見君子，我心傷悲，亦既見止，亦既覯止，我心則夷。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00113","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-34-2d-8349-87f2-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-8349-87f2","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-34-2d-8349-87f2-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-8349-87f2"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E8%8D%89%E8%9F%B2","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '采蘋', NULL, NULL, NULL, '于以采蘋？南澗之濱，于以采藻？于彼行潦。
于以盛之？維筐及筥，于以湘之？維錡及釜。
于以奠之？宗室牖下，誰其尸之？有齊季女。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00114","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-35-2d-91c7-860b-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-91c7-860b","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-35-2d-91c7-860b-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-91c7-860b"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%87%87%E8%98%8B","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '甘棠', NULL, NULL, NULL, '蔽芾甘棠，勿翦勿伐，召伯所茇。
蔽芾甘棠，勿翦勿敗，召伯所憇。
蔽芾甘棠，勿翦勿拜，召伯所說。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00115","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-36-2d-7518-68e0-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7518-68e0","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-36-2d-7518-68e0-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7518-68e0"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E7%94%98%E6%A3%A0","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '行露', NULL, NULL, NULL, '厭浥行露，豈不夙夜，謂行多露。
誰謂雀無角？何以穿我屋？誰謂女無家？何以速我獄？雖速我獄，室家不足。
誰謂鼠無牙？何以穿我墉？誰謂女無家？何以速我訟？雖速我訟，亦不女從。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00116","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-37-2d-884c-9732-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-884c-9732","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-37-2d-884c-9732-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-884c-9732"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E8%A1%8C%E9%9C%B2","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '羔羊', NULL, NULL, NULL, '羔羊之皮，素絲五紽，退食自公，委蛇委蛇。
羔羊之革，素絲五緎，委蛇委蛇，自公退食。
羔羊之縫，素絲五緫，委蛇委蛇，退食自公。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00117","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-38-2d-7f94-7f8a-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7f94-7f8a","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-38-2d-7f94-7f8a-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7f94-7f8a"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E7%BE%94%E7%BE%8A","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '殷其靁', NULL, NULL, NULL, '殷其靁，在南山之陽，何斯違斯，莫敢或遑，振振君子，歸哉歸哉。
殷其靁，在南山之側，何斯違斯，莫敢遑息，振振君子，歸哉歸哉。
殷其靁，在南山之下，何斯違斯，莫或遑處，振振君子，歸哉歸哉。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00118","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-39-2d-6bb7-5176-9741-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6bb7-5176-9741","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-31-39-2d-6bb7-5176-9741-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6bb7-5176-9741"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%AE%B7%E5%85%B6%E9%9D%81","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '摽有梅', NULL, NULL, NULL, '摽有梅，其實七兮，求我庶士，迨其吉兮。
摽有梅，其實三兮，求我庶士，迨其今兮。
摽有梅，頃筐塈之，求我庶士，迨其謂之。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00119","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-30-2d-647d-6709-6885-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-647d-6709-6885","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-30-2d-647d-6709-6885-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-647d-6709-6885"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%91%BD%E6%9C%89%E6%A2%85","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '小星', NULL, NULL, NULL, '嘒彼小星，三五在東，肅肅宵征，夙夜在公，寔命不同。
嘒彼小星，維參與昴，肅肅宵征，抱衾與裯，寔命不猶。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00120","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-31-2d-5c0f-661f-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5c0f-661f","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-31-2d-5c0f-661f-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5c0f-661f"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%B0%8F%E6%98%9F","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '江有汜', NULL, NULL, NULL, '江有汜，之子歸，不我以，不我以，其後也悔。
江有渚，之子歸，不我與，不我與，其後也處。
江有沱，之子歸，不我過，不我過，其嘯也歌。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00121","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-32-2d-6c5f-6709-6c5c-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6c5f-6709-6c5c","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-32-2d-6c5f-6709-6c5c-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6c5f-6709-6c5c"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%B1%9F%E6%9C%89%E6%B1%9C","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '野有死麕', NULL, NULL, NULL, '野有死麕，白茅包之，有女懷春，吉士誘之。
林有樸樕，野有死鹿，白茅純束，有女如玉。
舒而脫脫兮，無感我帨兮，無使尨也吠。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00122","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-33-2d-91ce-6709-6b7b-9e95-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-91ce-6709-6b7b-9e95","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-33-2d-91ce-6709-6b7b-9e95-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-91ce-6709-6b7b-9e95"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%87%8E%E6%9C%89%E6%AD%BB%E9%BA%95","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '何彼穠矣', NULL, NULL, NULL, '何彼穠矣，唐棣之華，曷不肅雝，王姬之車。
何彼穠矣，華如桃李，平王之孫，齊侯之子。
其釣維何，維絲伊緡，齊侯之子，平王之孫。
何：驚歎詞。何其。
穠：猶戎戎也。（《羣經治要》卷三）或作襛、茙。戎戎，形容大。此處作形容詞形容後面的唐棣之華。
唐棣：栘也。（《羣經治要》卷三），一名常棣、棠棣、鬱李。今名鬱李。
華：花。
肅，敬也。（《羣經治要》卷三）
雝，和也。（《羣經治要》卷三）
曷，何也。（《羣經治要》卷三）
車：按王先謙考證，此天子、大夫嫁娶時留車反馬之禮。女方嫁至男方時所乘之車，到達後歸屬於男方家庭，但所用之馬則要退還給女方。
華如桃李：比喻鬱李的華茂盛如桃李一般。
平：按鄭玄《毛詩傳》；平，正也。正王，正統的君主。此處非周平王。
伊：同維。維、伊皆語詞，無意義。
緡：魚線。釣魚用的線。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00123","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-34-2d-4f55-5f7c-7a60-77e3-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-4f55-5f7c-895b-77e3","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-34-2d-4f55-5f7c-7a60-77e3-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-4f55-5f7c-895b-77e3"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E4%BD%95%E5%BD%BC%E8%A5%9B%E7%9F%A3","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '騶虞', NULL, NULL, NULL, '彼茁者葭，壹發五豝，于嗟乎騶虞。
彼茁者蓬，壹發五豵，于嗟乎騶虞。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00124","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-35-2d-9a36-865e-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9a36-865e","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-35-2d-9a36-865e-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9a36-865e"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%A8%B6%E8%99%9E","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '柏舟', NULL, NULL, NULL, '汎彼柏舟，在彼中河，髧彼兩髦，實維我儀，之死矢靡它，母也天只，不諒人只。
汎彼柏舟，在彼河側，髧彼兩髦，實維我特，之死矢靡慝，母也天只，不諒人只。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00125","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-36-2d-67cf-821f-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-67cf-821f","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-36-2d-67cf-821f-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-67cf-821f","CN-CLASSIC-73-68-69-6a-69-6e-67-2d-34-35-2d-67cf-821f-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-67cf-821f"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%9F%8F%E8%88%9F","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '綠衣', NULL, NULL, NULL, '綠兮衣兮，綠衣黃裏，心之憂矣，曷維其已。
綠兮衣兮，綠衣黃裳，心之憂矣，曷維其亡。
綠兮絲兮，女所治兮，我思古人，俾無訧兮。
絺兮綌兮，淒其以風，我思古人，實獲我心。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00126","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-37-2d-7da0-8863-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7da0-8863","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-37-2d-7da0-8863-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7da0-8863"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E7%B6%A0%E8%A1%A3","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '燕燕', NULL, NULL, NULL, '燕燕于飛，差池其羽，之子于歸，遠送于野，瞻望弗及，泣涕如雨。
燕燕于飛，頡之頏之，之子于歸，遠于將之，瞻望弗及，佇立以泣。
燕燕于飛，下上其音，之子于歸，遠送于南，瞻望弗及，實勞我心。
仲氏任只，其心塞淵，終溫且惠，淑慎其身，先君之思，以勗寡人。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00127","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-38-2d-71d5-71d5-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-71d5-71d5","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-38-2d-71d5-71d5-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-71d5-71d5"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E7%87%95%E7%87%95","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '日月', NULL, NULL, NULL, '日居月諸，照臨下土，乃如之人兮，逝不古處，胡能有定，寧不我顧。
日居月諸，下土是冒，乃如之人兮，逝不相好，胡能有定，寧不我報。
日居月諸，出自東方，乃如之人兮，德音無良，胡能有定，俾也可忘。
日居月諸，東方自出，父兮母兮，畜我不卒，胡能有定，報我不述。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00128","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-39-2d-65e5-6708-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-65e5-6708","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-39-2d-65e5-6708-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-65e5-6708"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%97%A5%E6%9C%88","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '終風', NULL, NULL, NULL, '終風且暴，顧我則笑，謔浪笑敖，中心是悼。
終風且霾，惠然肯來，莫往莫來，悠悠我思。
終風且曀，不日有曀，寤言不寐，願言則嚏。
曀曀其陰，虺虺其靁，寤言不寐，願言則懷。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00129","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-33-30-2d-7d42-98a8-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7d42-98a8","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-33-30-2d-7d42-98a8-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7d42-98a8"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E7%B5%82%E9%A2%A8","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '擊鼓', NULL, NULL, NULL, '擊鼓其鏜，踴躍用兵，土國城漕，我獨南行。
從孫子仲，平陳與宋，不我以歸，憂心有忡。
爰居爰處，爰喪其馬，于以求之，于林之下。
死生契闊，與子成說，執子之手，與子偕老。
于嗟闊兮，不我活兮，于嗟洵兮，不我信兮。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00130","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-33-31-2d-64ca-9f13-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-64ca-9f13","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-33-31-2d-64ca-9f13-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-64ca-9f13"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%93%8A%E9%BC%93","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '凱風', NULL, NULL, NULL, '凱風(1)自南，吹彼棘心(2)，棘心夭夭(3)，母氏劬勞。
凱風自南，吹彼棘薪(4)，母氏聖善(5)，我無令(6)人。
爰(7)有寒泉，在浚(8)之下，有子七人，母氏勞苦。
睍睆(9)黃鳥，載(10)好其音，有子七人，莫慰母心。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00131","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-33-32-2d-51f1-98a8-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-51f1-98a8","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-33-32-2d-51f1-98a8-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-51f1-98a8"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%87%B1%E9%A2%A8","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '雄雉', NULL, NULL, NULL, '雄雉于飛，泄泄其羽，我之懷矣，自詒伊阻。
雄雉于飛，下上其音，展矣君子，實勞我心。
瞻彼日月，悠悠我思，道之雲遠，曷雲能來。
百爾君子，不知德行，不忮不求，何用不臧。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00132","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-33-33-2d-96c4-96c9-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-96c4-96c9","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-33-33-2d-96c4-96c9-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-96c4-96c9"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%9B%84%E9%9B%89","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '匏有苦葉', NULL, NULL, NULL, '匏有苦葉，濟有深涉，深則厲，淺則揭。
有瀰濟盈，有鷕雉鳴，濟盈不濡軓，雉鳴求其牡。
雝雝鳴鴈，旭日始旦，士如歸妻，迨冰未泮。
招招舟子，人涉卬否，人涉卬否，卬須我友。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00133","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-33-34-2d-530f-6709-82e6-8449-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-530f-6709-82e6-8449","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-33-34-2d-530f-6709-82e6-8449-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-530f-6709-82e6-8449"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%8C%8F%E6%9C%89%E8%8B%A6%E8%91%89","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '谷風', NULL, NULL, NULL, '習習谷風，以陰以雨。黽勉同心，不宜有怒。
采葑采菲，無以下體？德音莫違，及爾同死。
行道遲遲，中心有違。不遠伊邇，薄送我畿。
誰謂荼苦，其甘如薺。宴爾新昏，如兄如弟。
涇以渭濁，湜湜其沚。宴爾新昏，不我屑以。
毋逝我梁，毋發我笱。我躬不閱，遑恤我後。
就其深矣，方之舟之。就其淺矣，泳之遊之。
何有何亡，黽勉求之。凡民有喪，匍匐救之。
不我能慉，反以我為讎。既阻我德，賈用不售。
昔育恐育鞫，及爾顛覆。既生既育，比予于毒。
我有旨蓄，亦以御冬。宴爾新昏，以我御窮。
有洸有潰，既詒我肄。不念昔者，伊餘來塈。
習習谷風，維風及雨。
將恐將懼，維予與女。
將安將樂，女轉棄予。
習習谷風，維風及頹。
將恐將懼，寘予于懷。
將安將樂，棄予如遺。
習習谷風，維山崔嵬。
無草不死，無木不萎。
忘我大德，思我小怨。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00134","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-33-35-2d-8c37-98a8-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-8c37-98a8","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-33-35-2d-8c37-98a8-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-8c37-98a8","CN-CLASSIC-73-68-69-6a-69-6e-67-2d-32-30-37-2d-8c37-98a8-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-8c37-98a8"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E8%B0%B7%E9%A2%A8","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '式微', NULL, NULL, NULL, '式微式微，胡不歸？微君之故，胡為乎中露？
式微式微，胡不歸？微君之躬，胡為乎泥中？', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00135","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-33-36-2d-5f0f-5fae-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5f0f-5fae","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-33-36-2d-5f0f-5fae-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5f0f-5fae"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%BC%8F%E5%BE%AE","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '旄丘', NULL, NULL, NULL, '旄丘之葛兮，何誕之節兮，叔兮伯兮，何多日也。
何其處也，必有與也，何其久也，必有以也。
狐裘蒙戎，匪車不東，叔兮伯兮，靡所與同。
瑣兮尾兮，流離之子，叔兮伯兮，褎如充耳。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00136","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-33-37-2d-65c4-4e18-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-65c4-4e18","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-33-37-2d-65c4-4e18-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-65c4-4e18"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%97%84%E4%B8%98","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '簡兮', NULL, NULL, NULL, '簡兮簡兮，方將萬舞，日之方中，在前上處，碩人俁俁，公庭萬舞。
有力如虎，執轡如組，左手執籥，右手秉翟，赫如渥赭，公言錫爵。
山有榛，隰有苓，雲誰之思，西方美人，彼美人兮，西方之人兮。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00137","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-33-38-2d-7c21-516e-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7c21-516e","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-33-38-2d-7c21-516e-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7c21-516e"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E7%B0%A1%E5%85%AE","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '泉水', NULL, NULL, NULL, '毖彼泉水，亦流于淇，有懷于衞，靡日不思，孌彼諸姬，聊與之謀。
出宿于泲，飲餞于禰，女子有行，遠父母兄弟，問我諸姑，遂及伯姊。
出宿于乾，飲餞于言，載脂載舝，還車言邁，遄臻于衞，不瑕有害。
我思肥泉，茲之永歎，思須與漕，我心悠悠，駕言出遊，以寫我憂。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00138","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-33-39-2d-6cc9-6c34-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6cc9-6c34","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-33-39-2d-6cc9-6c34-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6cc9-6c34"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%B3%89%E6%B0%B4","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '北門', NULL, NULL, NULL, '出自北門，憂心殷殷，終窶且貧，莫知我艱，已焉哉，天實為之，謂之何哉。
王事適我，政事一埤益我，我入自外，室人交徧讁我，已焉哉，天實為之，謂之何哉。
王事敦我，政事一埤遺我，我入自外，室人交徧摧我，已焉哉，天實為之，謂之何哉。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00139","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-34-30-2d-5317-9580-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5317-9580","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-34-30-2d-5317-9580-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5317-9580"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%8C%97%E9%96%80","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '北風', NULL, NULL, NULL, '北風其涼，雨雪其雱，
惠而好我，攜手同行，【韻：雱行】
其虛其邪，既亟只且。
北風其喈，雨雪其霏，
惠而好我，攜手同歸，【韻：霏歸】
其虛其邪，既亟只且。
莫赤匪狐，莫黑匪烏，
惠而好我，攜手同車，【韻：烏車】
其虛其邪，既亟只且。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00140","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-34-31-2d-5317-98a8-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5317-98a8","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-34-31-2d-5317-98a8-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5317-98a8"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%8C%97%E9%A2%A8","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '靜女', NULL, NULL, NULL, '靜女其姝，俟我於城隅，愛而不見，搔首踟躕。
靜女其孌，貽我彤管，彤管有煒，說懌女美。
自牧歸荑，洵美且異，匪女之為美，美人之貽。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00141","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-34-32-2d-975c-5973-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-975c-5973","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-34-32-2d-975c-5973-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-975c-5973"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%9D%9C%E5%A5%B3","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '新臺', NULL, NULL, NULL, '新臺有泚，河水瀰瀰，燕婉之求，蘧篨不鮮。
新臺有洒，河水浼浼，燕婉之求，蘧篨不殄。
魚網之設，鴻則離之，燕婉之求，得此戚施。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00142","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-34-33-2d-65b0-81fa-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-65b0-81fa","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-34-33-2d-65b0-81fa-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-65b0-81fa"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%96%B0%E8%87%BA","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '二子乘舟', NULL, NULL, NULL, '二子乘舟，汎汎其景，願言思子，中心養養。
二子乘舟，汎汎其逝，願言思子，不瑕有害。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00143","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-34-34-2d-4e8c-5b50-4e58-821f-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-4e8c-5b50-4e58-821f","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-34-34-2d-4e8c-5b50-4e58-821f-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-4e8c-5b50-4e58-821f"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E4%BA%8C%E5%AD%90%E4%B9%98%E8%88%9F","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '牆有茨', NULL, NULL, NULL, '牆有茨，不可埽也，中冓之言，不可道也，所可道也，言之醜也。
牆有茨，不可襄也，中冓之言，不可詳也，所可詳也，言之長也。
牆有茨，不可束也，中冓之言，不可讀也，所可讀也，言之辱也。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00144","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-34-36-2d-7246-6709-8328-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7246-6709-8328","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-34-36-2d-7246-6709-8328-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7246-6709-8328"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E7%89%86%E6%9C%89%E8%8C%A8","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '君子偕老', NULL, NULL, NULL, '君子偕老，副笄六珈，委委佗佗，如山如河，象服是宜，子之不淑，雲如之何。
玼兮玼兮，其之翟也，鬒髮如雲，不屑髢也，玉之瑱也，象之揥也，揚且之晳也，胡然而天也，胡然而帝也。
瑳兮瑳兮，其之展也，蒙彼縐絺，是紲袢也，子之清揚，揚且之顏也，展如之人兮，邦之媛也。
呂氏曰：「首章之末雲『子之不淑，雲如之何』，責之也；二章之末雲『胡然而天也，胡然而帝也』，問之也；三章之末雲『展如之人兮，邦之媛也』，惜之也。辭益惋而意益深矣。」', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00145","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-34-37-2d-541b-5b50-5055-8001-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-541b-5b50-5055-8001","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-34-37-2d-541b-5b50-5055-8001-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-541b-5b50-5055-8001"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%90%9B%E5%AD%90%E5%81%95%E8%80%81","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '桑中', NULL, NULL, NULL, '爰采唐矣，沬之鄉矣，雲誰之思，美孟姜矣，期我乎桑中，要我乎上宮，送我乎淇之上矣。
爰采麥矣，沬之北矣，雲誰之思，美孟弋矣，期我乎桑中，要我乎上宮，送我乎淇之上矣。
爰采葑矣，沬之東矣，雲誰之思，美孟庸矣，期我乎桑中，要我乎上宮，送我乎淇之上矣。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00146","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-34-38-2d-6851-4e2d-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6851-4e2d","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-34-38-2d-6851-4e2d-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6851-4e2d"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%A1%91%E4%B8%AD","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '鶉之奔奔', NULL, NULL, NULL, '鶉之奔奔，鵲之彊彊，人之無良，我以為兄。
鵲之彊彊，鶉之奔奔，人之無良，我以為君。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00147","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-34-39-2d-9d89-4e4b-5954-5954-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9d89-4e4b-5954-5954","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-34-39-2d-9d89-4e4b-5954-5954-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-9d89-4e4b-5954-5954"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E9%B6%89%E4%B9%8B%E5%A5%94%E5%A5%94","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '定之方中', NULL, NULL, NULL, '定之方中，作于楚宮，揆之以日，作于楚室，樹之榛栗，椅桐梓漆，爰伐琴瑟。
升彼虛矣，以望楚矣，望楚與堂，景山與京，降觀于桑，卜雲其吉，終然允臧。
靈雨既零，命彼倌人，星言夙駕，說于桑田，匪直也人，秉心塞淵，騋牝三千。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00148","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-35-30-2d-5b9a-4e4b-65b9-4e2d-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5b9a-4e4b-65b9-4e2d","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-35-30-2d-5b9a-4e4b-65b9-4e2d-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5b9a-4e4b-65b9-4e2d"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%AE%9A%E4%B9%8B%E6%96%B9%E4%B8%AD","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '蝃蝀', NULL, NULL, NULL, '蝃蝀在東，莫之敢指，女子有行，遠父母兄弟。
朝隮于西，崇朝其雨，女子有行，遠兄弟父母。
乃如之人也，懷昏姻也，大無信也，不知命也。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00149","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-35-31-2d-8743-8740-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-8743-8740","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-35-31-2d-8743-8740-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-8743-8740"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E8%9D%83%E8%9D%80","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '相鼠', NULL, NULL, NULL, '相鼠有皮，人而無儀，人而無儀，不死何為。
相鼠有齒，人而無止，人而無止，不死何俟。
相鼠有體，人而無禮，人而無禮，胡不遄死。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00150","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-35-32-2d-76f8-9f20-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-76f8-9f20","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-35-32-2d-76f8-9f20-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-76f8-9f20"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E7%9B%B8%E9%BC%A0","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '乾旄', NULL, NULL, NULL, '孑孑乾旄，在浚之郊，素絲紕之，良馬四之，彼姝者子，何以畀之。
孑孑乾旟，在浚之都，素絲組之，良馬五之，彼姝者子，何以予之。
孑孑乾旌，在浚之城，素絲祝之，良馬六之，彼姝者子，何以告之。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00151","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-35-33-2d-4e7e-65c4-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5e72-65c4","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-35-33-2d-4e7e-65c4-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-5e72-65c4"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E5%B9%B2%E6%97%84","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '載馳', NULL, NULL, NULL, '載馳載驅，歸唁衞侯，驅馬悠悠，言至于漕，大夫跋涉，我心則憂。
既不我嘉，不能旋反，視爾不臧，我思不遠。
既不我嘉，不能旋濟，視爾不臧，我思不閟。
陟彼阿丘，言采其蝱，女子善懷，亦各有行，許人尤之，衆穉且狂。
我行其野，芃芃其麥，控于大邦，誰因誰極，大夫君子，無我有尤，百爾所思，不如我所之。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00152","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-35-34-2d-8f09-99b3-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-8f09-99b3","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-35-34-2d-8f09-99b3-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-8f09-99b3"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E8%BC%89%E9%A6%B3","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '淇奧', NULL, NULL, NULL, '瞻彼淇奧，綠竹猗猗，有匪君子，如切如磋，如琢如磨，瑟兮僩兮，赫兮咺兮，有匪君子，終不可諼兮。
瞻彼淇奧，綠竹青青，有匪君子，充耳琇瑩，會弁如星，瑟兮僩兮，赫兮咺兮，有匪君子，終不可諼兮。
瞻彼淇奧，綠竹如簀，有匪君子，如金如錫，如圭如璧，寬兮綽兮，倚重較兮，善戲謔兮，不為虐兮。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00153","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-35-35-2d-6dc7-5967-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6dc7-5967","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-35-35-2d-6dc7-5967-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6dc7-5967"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%B7%87%E5%A5%A7","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '考槃', NULL, NULL, NULL, '考槃在澗，碩人之寬，獨寐寤言，永矢弗諼。
考槃在阿，碩人之薖，獨寐寤歌，永矢弗過。
考槃在陸，碩人之軸，獨寐寤宿，永矢弗告。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00154","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-35-36-2d-8003-69c3-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-8003-69c3","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-35-36-2d-8003-69c3-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-8003-69c3"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E8%80%83%E6%A7%83","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '碩人', NULL, NULL, NULL, '碩人其頎，衣錦褧衣，齊侯之子，衛侯之妻，東宮之妹，邢侯之姨，譚公維私。
手如柔荑，膚如凝脂，領如蝤蠐，齒如瓠犀，螓首蛾眉，巧笑倩兮，美目盻兮。
碩人敖敖，說于農郊，四牡有驕，朱幩鑣鑣，翟茀以朝，大夫夙退，無使君勞。
河水洋洋，北流活活，施罛濊濊，鱣鮪發發，葭菼揭揭，庶姜孽孽，庶士有朅。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00155","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-35-37-2d-78a9-4eba-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-78a9-4eba","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-35-37-2d-78a9-4eba-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-78a9-4eba"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E7%A2%A9%E4%BA%BA","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '氓', NULL, NULL, NULL, '氓之蚩蚩，抱布貿絲。匪來貿絲，來即我謀。送子涉淇，至于頓丘。匪我愆期，子無良媒。將子無怒，秋以為期。
乘彼垝垣，以望復關。不見復關，泣涕漣漣。既見復關，載笑載言。爾卜爾筮，體無咎言。以爾車來，以我賄遷。
桑之未落，其葉沃若。于嗟鳩兮，無食桑葚。于嗟女兮，無與士耽。士之耽兮，猶可說也。女之耽兮，不可說也。
桑之落矣，其黃而隕。自我徂爾，三歲食貧。淇水湯湯，漸車帷裳。女也不爽，士貳其行。士也罔極，二三其德。
三歲為婦，靡室勞矣。夙興夜寐，靡有朝矣。言既遂矣，至于暴矣。兄弟不知，咥其笑矣。靜言思之，躬自悼矣。
及爾偕老，老使我怨。淇則有岸，隰則有泮。總角之宴，言笑晏晏。信誓旦旦，不思其反。反是不思，亦已焉哉。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00156","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-35-38-2d-6c13-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6c13","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-35-38-2d-6c13-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6c13"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%B0%93","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '竹竿', NULL, NULL, NULL, '籊籊竹竿，以釣于淇，豈不爾思，遠莫致之。
泉源在左，淇水在右，女子有行，遠兄弟父母。
淇水在右，泉源在左，巧笑之瑳，佩玉之儺。
淇水滺滺，檜楫松舟，駕言出遊，以寫我憂。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00157","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-35-39-2d-7af9-7aff-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7af9-7aff","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-35-39-2d-7af9-7aff-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-7af9-7aff"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E7%AB%B9%E7%AB%BF","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '芄蘭', NULL, NULL, NULL, '芄蘭之支，童子佩觿，雖則佩觿，能不我知，容兮遂兮，垂帶悸兮。
芄蘭之葉，童子佩韘，雖則佩韘，能不我甲，容兮遂兮，垂帶悸兮。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00158","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-36-30-2d-8284-862d-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-8284-862d","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-36-30-2d-8284-862d-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-8284-862d"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E8%8A%84%E8%98%AD","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '河廣', NULL, NULL, NULL, '誰謂河廣，一葦杭之，誰謂宋遠，跂予望之。
誰謂河廣，曾不容刀，誰謂宋遠，曾不崇朝。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00159","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-36-31-2d-6cb3-5ee3-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6cb3-5ee3","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-36-31-2d-6cb3-5ee3-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-6cb3-5ee3"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E6%B2%B3%E5%BB%A3","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}'),
    ('cnpreqin-3fcc3c660d5a7a4d', 0, '伯兮', NULL, NULL, NULL, '伯兮朅兮，邦之桀兮。伯也執殳，爲王前驅。
自伯之東，首如飛蓬。豈無膏沐？誰適爲容！
其雨其雨，杲杲出日。願言思伯，甘心首疾。
焉得諼草？言樹之背。願言思伯。使我心痗。', 'parsed', 'cnpt-shijing', '{"queue_id":"CN-TR-00160","source_record_id":"CN-CLASSIC-73-68-69-6a-69-6e-67-2d-36-32-2d-4f2f-516e-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-4f2f-516e","alias_record_ids":["CN-CLASSIC-73-68-69-6a-69-6e-67-2d-36-32-2d-4f2f-516e-2d-4f5a-540d-2f-8a69-7d93-2d-8a69-7d93-2f-4f2f-516e"],"batch":"pre-tang-classic-index","source_url":"https://zh.wikisource.org/wiki/%E8%A9%A9%E7%B6%93/%E4%BC%AF%E5%85%AE","review_status":"needs-review","review_reasons":["classic-index-work","shijing"]}')
)
INSERT INTO poems (
  poet_id, poem_no, volume, title_zh, title_ko, category, meter, body_zh,
  is_notable, status, quality, review_memo
)
SELECT
  p.id,
  COALESCE(existing_poem_count.max_poem_no, 0)
    + row_number() OVER (PARTITION BY p.id ORDER BY ip.title_zh, ip.body_zh)::integer,
  ip.volume::integer, ip.title_zh, ip.title_ko, ip.category, ip.meter::integer, ip.body_zh,
  TRUE, ip.status, ip.quality, ip.review_memo
FROM input_poems ip
JOIN poets p ON p.title_id = ip.poet_slug
LEFT JOIN LATERAL (
  SELECT max(poem_no) AS max_poem_no
  FROM poems
  WHERE poet_id = p.id
) existing_poem_count ON TRUE
WHERE NOT EXISTS (
  SELECT 1
  FROM poems existing
  WHERE existing.poet_id = p.id
    AND existing.title_zh = ip.title_zh
    AND existing.body_zh = ip.body_zh
);

UPDATE poets p
SET poem_count = sub.cnt
FROM (
  SELECT poet_id, count(*)::integer AS cnt
  FROM poems
  WHERE poet_id IN (SELECT id FROM poets WHERE title_id IN ('cnhan-4d1c052feb6f7223', 'cnhan-43b38ccd5d1e93f0', 'cnhan-4c77569df016009b', 'cnhan-aa408a3758d7e916', 'cnpreqin-d9cfb1495fcebc18', 'cnpreqin-3fcc3c660d5a7a4d'))
  GROUP BY poet_id
) sub
WHERE p.id = sub.poet_id;

-- Review counts before COMMIT when applying manually:
SELECT quality, status, count(*) FROM poems WHERE quality IN ('cnpt-comp', 'cnpt-chuci', 'cnpt-shijing') GROUP BY quality, status ORDER BY quality, status;
SELECT p.era_period, count(pm.id) FROM poets p JOIN poems pm ON pm.poet_id = p.id WHERE p.title_id IN ('cnhan-4d1c052feb6f7223', 'cnhan-43b38ccd5d1e93f0', 'cnhan-4c77569df016009b', 'cnhan-aa408a3758d7e916', 'cnpreqin-d9cfb1495fcebc18', 'cnpreqin-3fcc3c660d5a7a4d') GROUP BY p.era_period ORDER BY p.era_period;

ROLLBACK;
-- COMMIT;
