#!/usr/bin/env node
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');
const INPUT = resolve(ROOT, 'docs/spec/cn-non-tang-tranche1.records.v1.json');
const OUT = resolve(ROOT, 'docs/spec/cn-non-tang-tranche1.jds-upsert.sql');

const { records } = JSON.parse(readFileSync(INPUT, 'utf8'));
const poets = uniqueBy(records.map((record) => ({
  slug: record.jdsCandidate.poet.slug,
  name_zh: record.jdsCandidate.poet.name_zh,
  name_ko: record.jdsCandidate.poet.name_ko,
  life_raw: record.jdsCandidate.poet.life_raw,
  era_period: record.jdsCandidate.poet.era_period,
  country: 'CN',
})), (poet) => poet.slug);

const poemRows = records.map((record, index) => ({
  poet_slug: record.jdsCandidate.poet.slug,
  poem_no: index + 1,
  title_zh: record.jdsCandidate.poem.title_zh,
  title_ko: record.jdsCandidate.poem.title_ko,
  category: record.jdsCandidate.poem.category,
  meter: record.jdsCandidate.poem.meter,
  body_zh: record.jdsCandidate.poem.body_zh,
  translation_ko: record.translation.translationKoOwned,
  commentary_ko: record.translation.commentaryKoOwned,
  is_notable: true,
  status: record.jdsCandidate.poem.status,
  quality: 'cn-tranche1',
  country: 'CN',
}));

const sql = `-- Generated by scripts/build_cn_non_tang_tranche1_jds_sql.mjs
-- Purpose: stage CN non-Tang tranche 1 into jds before Supabase hansi_curated_* sync.
-- Safety: poems are inserted only when the same poet slug + title_zh + body_zh is absent.
-- Default ending is ROLLBACK. Change the final ROLLBACK to COMMIT only after reviewing counts.

BEGIN;

WITH input_poets(slug, name_zh, name_ko, life_raw, era_period, country) AS (
  VALUES
${poets.map((poet) => `    (${sqlValue(poet.slug)}, ${sqlValue(poet.name_zh)}, ${sqlValue(poet.name_ko)}, ${sqlValue(poet.life_raw)}, ${sqlValue(poet.era_period)}, ${sqlValue(poet.country)})`).join(',\n')}
)
INSERT INTO poets (slug, name_zh, name_ko, life_raw, era_period, country, poem_count)
SELECT slug, name_zh, name_ko, life_raw, era_period, country, 0
FROM input_poets
ON CONFLICT (slug) DO UPDATE SET
  name_zh = EXCLUDED.name_zh,
  name_ko = EXCLUDED.name_ko,
  life_raw = EXCLUDED.life_raw,
  era_period = EXCLUDED.era_period,
  country = EXCLUDED.country;

WITH input_poems(poet_slug, poem_no, title_zh, title_ko, category, meter, body_zh, translation_ko, commentary_ko, is_notable, status, quality, country) AS (
  VALUES
${poemRows.map((poem) => `    (${sqlValue(poem.poet_slug)}, ${sqlValue(poem.poem_no)}, ${sqlValue(poem.title_zh)}, ${sqlValue(poem.title_ko)}, ${sqlValue(poem.category)}, ${sqlValue(poem.meter)}, ${sqlValue(poem.body_zh)}, ${sqlValue(poem.translation_ko)}, ${sqlValue(poem.commentary_ko)}, ${sqlValue(poem.is_notable)}, ${sqlValue(poem.status)}, ${sqlValue(poem.quality)}, ${sqlValue(poem.country)})`).join(',\n')}
)
INSERT INTO poems (
  poet_id, poem_no, title_zh, title_ko, category, meter, body_zh,
  translation_ko, commentary_ko, is_notable, status, quality, country
)
SELECT
  p.id, ip.poem_no, ip.title_zh, ip.title_ko, ip.category, ip.meter, ip.body_zh,
  ip.translation_ko, ip.commentary_ko, ip.is_notable, ip.status, ip.quality, ip.country
FROM input_poems ip
JOIN poets p ON p.slug = ip.poet_slug
WHERE NOT EXISTS (
  SELECT 1
  FROM poems existing
  WHERE existing.poet_id = p.id
    AND existing.title_zh = ip.title_zh
    AND existing.body_zh = ip.body_zh
);

UPDATE poets p
SET poem_count = sub.cnt
FROM (
  SELECT poet_id, count(*)::integer AS cnt
  FROM poems
  WHERE poet_id IN (SELECT id FROM poets WHERE slug IN (${poets.map((poet) => sqlValue(poet.slug)).join(', ')}))
  GROUP BY poet_id
) sub
WHERE p.id = sub.poet_id;

-- Review counts before COMMIT when applying manually:
SELECT era_period, count(*) FROM poets WHERE slug IN (${poets.map((poet) => sqlValue(poet.slug)).join(', ')}) GROUP BY era_period ORDER BY era_period;
SELECT p.slug, count(pm.id) FROM poets p LEFT JOIN poems pm ON pm.poet_id = p.id WHERE p.slug IN (${poets.map((poet) => sqlValue(poet.slug)).join(', ')}) GROUP BY p.slug ORDER BY p.slug;

ROLLBACK;
-- COMMIT;
`;

mkdirSync(resolve(ROOT, 'docs/spec'), { recursive: true });
writeFileSync(OUT, sql);

console.log(`wrote ${OUT}`);
console.log(JSON.stringify({ poets: poets.length, poems: poemRows.length }, null, 2));

function sqlValue(value) {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'number') return String(value);
  if (typeof value === 'boolean') return value ? 'TRUE' : 'FALSE';
  return `'${String(value).replace(/'/g, "''")}'`;
}

function uniqueBy(items, selector) {
  const seen = new Set();
  const out = [];
  for (const item of items) {
    const key = selector(item);
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(item);
  }
  return out;
}
