#!/usr/bin/env node
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');
const INPUT = resolve(ROOT, 'docs/spec/cn-pre-tang-first-tranche.db-dry-run.v1.json');
const OUT = resolve(ROOT, 'docs/spec/cn-pre-tang-first-tranche.jds-upsert.sql');

const dryRun = JSON.parse(readFileSync(INPUT, 'utf8'));
const poets = dryRun.jdsUpsertCandidates?.poets ?? [];
const poems = dryRun.jdsUpsertCandidates?.poems ?? [];

const sql = `-- Generated by scripts/build_cn_pre_tang_first_tranche_jds_sql.mjs
-- Purpose: stage CN pre-Tang first tranche into jds before Supabase hansi_curated_* sync.
-- Safety: poems are inserted only when the same poet slug + title_zh + body_zh is absent.
-- Default ending is ROLLBACK. Change the final ROLLBACK to COMMIT only after reviewing counts.

BEGIN;

WITH input_poets(slug, name_zh, name_ko, life_raw, era_period, country) AS (
  VALUES
${poets.map((poet) => `    (${sqlValue(poet.slug)}, ${sqlValue(poet.name_zh)}, ${sqlValue(poet.name_ko)}, ${sqlValue(poet.life_raw)}, ${sqlValue(poet.era_period)}, ${sqlValue(poet.country)})`).join(',\n')}
)
INSERT INTO poets (slug, name_zh, name_ko, life_raw, era_period, country, poem_count)
SELECT slug, name_zh, name_ko, life_raw, era_period, country, 0
FROM input_poets
ON CONFLICT (slug) DO UPDATE SET
  name_zh = EXCLUDED.name_zh,
  name_ko = EXCLUDED.name_ko,
  life_raw = EXCLUDED.life_raw,
  era_period = EXCLUDED.era_period,
  country = EXCLUDED.country;

WITH input_poems(poet_slug, title_zh, title_ko, category, body_zh, translation_ko, commentary_ko, status, quality, country, source_record_id, source_url) AS (
  VALUES
${poems.map((poem) => `    (${sqlValue(poem.poet_slug)}, ${sqlValue(poem.title_zh)}, ${sqlValue(poem.title_ko)}, ${sqlValue(poem.category)}, ${sqlValue(poem.body_zh)}, ${sqlValue(poem.translation_ko)}, ${sqlValue(poem.commentary_ko)}, ${sqlValue(poem.status)}, ${sqlValue(poem.quality)}, ${sqlValue(poem.country)}, ${sqlValue(poem.source_record_id)}, ${sqlValue(poem.source_url)})`).join(',\n')}
)
INSERT INTO poems (
  poet_id, poem_no, title_zh, title_ko, category, body_zh,
  translation_ko, commentary_ko, is_notable, status, quality, country
)
SELECT
  p.id,
  COALESCE(existing_poem_count.max_poem_no, 0)
    + row_number() OVER (PARTITION BY p.id ORDER BY ip.title_zh)::integer,
  ip.title_zh, ip.title_ko, ip.category, ip.body_zh,
  ip.translation_ko, ip.commentary_ko, TRUE, ip.status, ip.quality, ip.country
FROM input_poems ip
JOIN poets p ON p.slug = ip.poet_slug
LEFT JOIN LATERAL (
  SELECT max(poem_no) AS max_poem_no
  FROM poems
  WHERE poet_id = p.id
) existing_poem_count ON TRUE
WHERE NOT EXISTS (
  SELECT 1
  FROM poems existing
  WHERE existing.poet_id = p.id
    AND existing.title_zh = ip.title_zh
    AND existing.body_zh = ip.body_zh
);

UPDATE poets p
SET poem_count = sub.cnt
FROM (
  SELECT poet_id, count(*)::integer AS cnt
  FROM poems
  WHERE poet_id IN (SELECT id FROM poets WHERE slug IN (${poets.map((poet) => sqlValue(poet.slug)).join(', ')}))
  GROUP BY poet_id
) sub
WHERE p.id = sub.poet_id;

-- Review counts before COMMIT when applying manually:
SELECT era_period, count(*) FROM poets WHERE slug IN (${poets.map((poet) => sqlValue(poet.slug)).join(', ')}) GROUP BY era_period ORDER BY era_period;
SELECT p.slug, count(pm.id) FROM poets p LEFT JOIN poems pm ON pm.poet_id = p.id WHERE p.slug IN (${poets.map((poet) => sqlValue(poet.slug)).join(', ')}) GROUP BY p.slug ORDER BY p.slug;

ROLLBACK;
-- COMMIT;
`;

mkdirSync(resolve(ROOT, 'docs/spec'), { recursive: true });
writeFileSync(OUT, sql);

console.log(`wrote ${OUT}`);
console.log(JSON.stringify({ poets: poets.length, poems: poems.length }, null, 2));

function sqlValue(value) {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'number') return String(value);
  if (typeof value === 'boolean') return value ? 'TRUE' : 'FALSE';
  return `'${String(value).replace(/'/g, "''")}'`;
}
